language: node_js
node_js:
  - '10'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn check-all
  - yarn build
  - yarn e2e-ci
after_success:
  - travis_wait yarn ndla-scripts now-travis
cache:
  yarn: true
  directories:
    - '~/.npm'
    - '~/.cache'
    - '.eslintcache'
  install:
    - yarn install --frozen-lockfile
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: HP0d1hQG2MCGvo4KF3YUdLxPjGei41UBgqMBhxVVPtyqm2twKOoH0ZaNz7HaMUZzGwLJ54O0I5ohWCM3E9nGBZFZj4fuqTTf9VQV1ig0B85DUKkT21ru2LxVqTDQQ2Md9sPIThZcviu3D11yD8tRnUl54/uV2/SH6mXw5BNimxipKLxKASQTroRxIsuAvNs72xEvKvE/ijNBlayXs9Vek9SuqTaTyS5WHvnO2hbtqrDYckqORmSVOa8TtMOeyz77ilOU7aqp+HrRgkB8xlyUOVmyod6EvU27IugunkwAAPQJLHNCoa/Dm3AFzj6ZMtyJet+e3/j2LPyN/92AcZMsz3IxFTxnZq0PhbpVSoVQbMVoIcFuV6c1kNTYEJY6B2dNhkBMvHGqq32z2XdX0EA4kJEihlMvI0jwsbYaBtcOXN/92HXqwM97LR2KKEseQGpbErM1aoWrzT0gWaU8IJ+RlPYzs016Nr33gE1Tmpk3UHh9jyBaWeIgbSxAVg1SWmI5B5iFnQm5tHiyJsH6+uGhJ08HniPqeIuKQpN5FEQ/ux8VpqMa+XqGLMauQdndDLz5DeAilTf8q4GH0HSv4I1UkwmIgpKeDBjmBe7H73rF1g+4uTkuxRd2irB/iEt+Infw+R0y55tRKsoP/b57ROGyZClzfpObbdwYNrvUPbQM91c=
env:
  global:
    - secure: gxKlTJ490qaj588wxI3M9J3FKNe2mVNJdyMnFa3P78mlLtKuDYHQ1rmr3FOzng/Hy91DgMYzazBGFoKK8uaU1y7cKogHhbL+mWYOiQ6FJ9ezNZOJAzEVffvkyEPYakanaHZnWS3BWLJcMIER/AIWCgs/7alur3Cj+wzvJdm2X8cX+Jf3c9G7hKm0UajIEQqwWS8BU3judl2h524+ANsSgk2LBRSQc0g25UYlOkMSTKg9wjZSJvwPQs/ykWNf9+MHZaNk4Rk/fdYtXnYkOU5lLPUMg1G5eQ5bUvqbSc1X5Tl3Jk0z0d09V1LIlVydT/PwQ6oQStUQFg+yPU59egOM5scM0H0sso5b8pdRwGjnV2mWQOBvDPWJHDYWOPJa52SjcO6XKYeZfJtt4+PbGOlj1r3viGE2MWZRrd2mG5qSdW30ZAA7Tc5qvc9BrBkgFUSNcQtR0cBCKaS37x33VbJL1bLY3bAlbHbDhaFEMcXDzRanVu/Xbc/Hso7MQVOIoGMwLb1V581bGXf1CjalpAJ1QzWXj+dHFO48Li0hPocAcEpHCIUhoGbYC5ey2Rqa4mOV1f7AtUnyp3xz38xln1IFsEHyiR3LBHTeulLZXgPBYoOeARUjOlASqiRlKnTHtZnJe1bXPbKq52U1kreBBrqgvEIf04a0AEc4iSqQ4sViYts=
