language: node_js
node_js:
- '8'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- yarn test
- yarn build
after_script:
- travis_wait yarn ndla-scripts now-travis
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: HP0d1hQG2MCGvo4KF3YUdLxPjGei41UBgqMBhxVVPtyqm2twKOoH0ZaNz7HaMUZzGwLJ54O0I5ohWCM3E9nGBZFZj4fuqTTf9VQV1ig0B85DUKkT21ru2LxVqTDQQ2Md9sPIThZcviu3D11yD8tRnUl54/uV2/SH6mXw5BNimxipKLxKASQTroRxIsuAvNs72xEvKvE/ijNBlayXs9Vek9SuqTaTyS5WHvnO2hbtqrDYckqORmSVOa8TtMOeyz77ilOU7aqp+HrRgkB8xlyUOVmyod6EvU27IugunkwAAPQJLHNCoa/Dm3AFzj6ZMtyJet+e3/j2LPyN/92AcZMsz3IxFTxnZq0PhbpVSoVQbMVoIcFuV6c1kNTYEJY6B2dNhkBMvHGqq32z2XdX0EA4kJEihlMvI0jwsbYaBtcOXN/92HXqwM97LR2KKEseQGpbErM1aoWrzT0gWaU8IJ+RlPYzs016Nr33gE1Tmpk3UHh9jyBaWeIgbSxAVg1SWmI5B5iFnQm5tHiyJsH6+uGhJ08HniPqeIuKQpN5FEQ/ux8VpqMa+XqGLMauQdndDLz5DeAilTf8q4GH0HSv4I1UkwmIgpKeDBjmBe7H73rF1g+4uTkuxRd2irB/iEt+Infw+R0y55tRKsoP/b57ROGyZClzfpObbdwYNrvUPbQM91c=
env:
  global:
  - secure: Qv7QOQoAjPHUTKfNUs+Y7G3SCL18iV1Wu5kqKV6Sq/17lNsyTkeLPwbl2Ggryeby4hNR4DZlu31gUCGS7VkVMfUS27IoU7ODmzeY1k+d6g6cL2ZbIsS0m9cnWyvp+B82cq96RHWWxO07i7Fe58X+y//lY/w8UnTmEomj1ZgAoQAytfRXWquZXkVvVunp3j6xZfevG6LFzixUZtUz+XEVPqRlPQ1PdokSW0HAF+EyUriCKEHey3JbjMf8zaXsc14PpGZaY8uhDzO6OUisBsLkzbrRFStAKSrZdtXwlPHHVBHnARnqQBGE7XpQ7bEVVcJvYTuoAo8TwpakxHhVpyHbwscCb1VFTDCefe0qJYLr2upwy6G7tRKpzaBF66n1dHyPLtx2PerNmWBSXZH0MDwd0rQqb+t94vZxHdMR5cuXNPCBJOeL3x5Y/ruwlQh45x238d5BpbOM0TiVwkbb8w6v9EB9cyQByu5m1QuQKjqUpOT5CLussVQRhCVGCzcGURBjQ25eKvi0Y+f0xdxmLJ9+t2quUuSz1icw8UshyIw52eKF4rsoEimn//y27PqWs8Tkuxt6JDRPNPVf2c6qSkW1lmtjUDPNWXyU87cRQApuylkxh5NwxYkRXowxYLp0XsAfhjCraYP4jVHacUCwcOtKqN0872HXQOG8tJcTyJw6ZBI=
  - secure: AZmJ4t85RNHY9hhsK/2LYMEw2daJPqOLkOgGEhWlfoEDvswL0z+r9qbRt/q09HJSEenXWBYAw9BFp3Q8xY5kx3ZkYiP5XsaG2TM32RpwHu7wRiXaxDyjCPBT4WMYhJppnsfl1xVZrnGiYFSqUv3vcuqdwMIHkn9JUvRTUYxQDKIkmjwmhG5sNejuB/rA/ftzWGKmf+YLNfXFjUHMqgk5Za9J9xZ+H857hIFilFuD7fwyjREnNvpbWUux/+Z2OgJwmurlrsbEi04fYFHqn9sfBq3gP3/WMzTMoH8XRkzFphfQTxig1oDPnHEjbf/Fl7hPegR+F4FhoaPYFhJLszWogDYzM4SnYHdyHWP9mC/8hKZA3nW/ArXNb7GuflxnA5mHoxOM2k69yNBnqPOcrkWksvtRFklIPNk/K/lqgsFB8R7lrCSEG9CVETG7cYimWCbMoFoCqB0lPEO0ek3JvvgV3+r+adzc4DA7aZ8mN6CpMcuT5SWncS6VQVYXkFjdClnNrpFA1VKcRfarK0KS5+H0DY1jvTY7eb2xWBNNsNEU1M3AW2WZxMnwD4/BOXUl4zIA2P6bx822XD1Dry8zxXeqUbywj0z/VkJl5FATWW6N0YsR1wVroN/dxNfQSrH+FhT//ND49Pmj1fIthMbyyIVvJWk7iAdRn0lmx+D5NPMGB9w=
