export default [
  {
    tags: [
      'access control',
      'activity',
      'addiction',
      'adjective',
      'advertisement',
      'advertising',
      'advertising photography',
      'afghanistan',
      'africa',
      'al-andalus',
      'alarm system',
      'an enemy of the people',
      'antenna',
      'aquaculture',
      'aquafarming',
      'asia',
      'attention demanding work',
      'audio production',
      'audio recording',
      'author',
      'automated',
      'availability',
      'avledning',
      'balance',
      'baroque',
      'barrier',
      'bear',
      'belief',
      'bha',
      'bilingualism',
      'blog',
      'blogs',
      'boccaccio',
      'bop',
      'brainstorming',
      'brand building',
      'break',
      'bright',
      'broadcasting act',
      'buoyancy',
      'camera movement',
      'camera settings',
      'cased hole',
      'cement',
      'censorship',
      'chainsaw',
      'channel',
      'china',
      'chores',
      'christianity',
      'circulating pressure',
      'classical antiquity',
      'clay',
      'coding',
      'color theory',
      'colour',
      'colours',
      'comic strip',
      'communication',
      'communication model',
      'communication process',
      'communications adviser',
      'comparison',
      'compensating',
      'completion',
      'completionfluid',
      'composition',
      'composition principle',
      'compression',
      'computer and electronic systems',
      'concrete',
      'construction documentation',
      'contactor',
      'contemporaneously',
      'contents',
      'continuity',
      'contrast',
      'cooling',
      'copyright',
      'copyright act',
      'creation myths',
      'creative',
      'creative commons',
      'creativity',
      'cultural history',
      'dante',
      'debate',
      'decameron',
      'declaration of conformity',
      'decoration',
      'democracy',
      'derrick',
      'deviated well',
      'digital media',
      'direction of rotation',
      'discussion',
      'documentary',
      'dokumnetasjon',
      'dorothe engelbretsdotter',
      'drama',
      'dramaturgy',
      'draw-work',
      'drill bit',
      'drill collar',
      'drill pipe',
      'drill string',
      'drillers method',
      'drilling',
      'drilling module',
      'drilling mud',
      'drilling problem',
      'editor program',
      'emoji',
      'emoticons',
      'empire',
      'enlightenment',
      'entry',
      'epic',
      'epic poem',
      'epic text',
      'essay',
      'ethics',
      'exchange programme',
      'exercise',
      'exploration',
      'eyeflap',
      'fairy tale',
      'falling objects',
      'family saga',
      'feature film',
      'field development',
      'file formats',
      'film',
      'film analysis',
      'film production',
      'final inspection',
      'finite verb',
      'first aid',
      'flex joint',
      'floating vessel',
      'foreign language',
      'foreign languages',
      'forestry',
      'form',
      'form contrast',
      'formats',
      'fotograferinf',
      'freedom of expression',
      'freedom of speech',
      'friction stress',
      'friends',
      'friendship',
      'gantt',
      'gas cap',
      'gas injection',
      'genre',
      'geology',
      'german',
      'germany',
      'god',
      'grafisk design',
      'graphic design',
      'group',
      'gypsum',
      'health worker',
      'heat',
      'heave compensating',
      'heavy weight drill pipe',
      'heimskringla',
      'hell',
      'historiical sources',
      'hoax',
      'hobby',
      'homecinema',
      'hot work',
      'hse',
      'hse plan',
      'hse work',
      'html5',
      'humanism and the renaissance',
      'hunt',
      'hydraulic',
      'hydraulics',
      'hydrostatic pressure',
      'hymn',
      'hymn writer',
      'ibop',
      'ice',
      'idea development',
      'identity',
      'identity formation',
      'image',
      'imperial era',
      'implementation',
      'india',
      'infographic',
      'information activity',
      'installation',
      'installation guide',
      'instrument',
      'instruments',
      'interior designer',
      'internet',
      'interview',
      'intrior',
      'introduction',
      'johannes vermeer',
      'journalism',
      'journalist',
      'krosstog',
      'language history',
      'language learning',
      'late middle ages',
      'lateral',
      'laws',
      'layout',
      'legend',
      'leisure',
      'lense',
      'letter to the editor',
      'lifting expertise',
      'light',
      'lighting',
      'lightning',
      'linguistic',
      'literary analysis',
      'log assembly',
      'logging',
      'lower completion',
      'ludvig holberg',
      'lwd',
      'main system',
      'maintenance',
      'manufacturing process',
      'manuscript',
      'marketing',
      'marketing act',
      'marketing communication',
      'martin luther',
      'material list',
      'measurement',
      'media',
      'media communication',
      'media design',
      'media development',
      'media ethics',
      'media expression',
      'media habits',
      'media history',
      'media industry',
      'media occupations',
      'media policy',
      'media power',
      'media production',
      'media stories',
      'media survey',
      'media use',
      'meeting invitation',
      'mental health',
      'message',
      'microphone',
      'middle ages',
      'mobile phone',
      'mobile use',
      'mother tongue',
      'motion',
      'movable equipment',
      'moving pictures',
      'mud',
      'mud lab',
      'music taste',
      'musician',
      'mythology',
      'nation building',
      'national identity',
      'need',
      'news',
      'news reporting',
      'news values',
      'newspaper',
      'nonfiction',
      'norm',
      'norse literature',
      'north america',
      'norwegian continental shelf',
      'norwegian film history',
      'norwegian history',
      'noun',
      'numbers',
      'objective',
      'offshore',
      'oil and gas',
      'oil production',
      'open hole',
      'oppgave',
      'oral',
      'outlet',
      'overhead crane',
      'p of influence',
      'painting',
      'past participle',
      'perforating',
      'petroleum',
      'petter dass',
      'phone number',
      'photo production',
      'photo reportage',
      'photography',
      'pipe elevator',
      'pipe handling',
      'pipeline',
      'planning',
      'platform',
      'podcast',
      'poem analysis',
      'pollution act',
      'portfolio',
      'portrait',
      'positioning',
      'post',
      'press conference',
      'press release',
      'pressure drop',
      'pressure force',
      'pressure gradient',
      'pressure support',
      'privacy',
      'procedure',
      'procedures',
      'process plants',
      'processing',
      'processing equipment',
      'production',
      'production part',
      'production processes',
      'production test',
      'production well',
      'profession',
      'programming',
      'public awareness campaign',
      'publication',
      'pulp fiction',
      'pump system',
      'radio',
      'radiospot',
      'railway',
      'ramrig',
      'regulation',
      'remotely operated',
      'renaissance',
      'reported undesirable event',
      'reputation building',
      'reservoir',
      'reservoir drive',
      'reservoir pressure',
      'responsibility',
      'return sludge line therapy',
      'review',
      'rig',
      'riser',
      'risk',
      'risk assessment',
      'risk matrix',
      'safety training',
      'saktekster',
      'salmon louse',
      'sand production',
      'scale',
      'school',
      'sealing rock',
      'search strategies',
      'second language',
      'secure',
      'securing personell',
      'sedimentary rocks',
      'sender',
      'separation of powers principle',
      'shaker system',
      'short story',
      'signaling',
      'sky',
      'slipjoint',
      'smartphone',
      'snorri sturlason',
      'social',
      'soil',
      'sound',
      'source',
      'source criticism',
      'south america',
      'statistics',
      'storage cell',
      'story',
      'storyboards',
      'storytelling',
      'stuck pipe',
      'student production',
      'subjectively',
      'subsea installation',
      'subsea template',
      'surface systems',
      'tankers',
      'tanks',
      'target group',
      'teaching',
      'technical text',
      'teenager',
      'television',
      'tell',
      'tempelriddar',
      'text production',
      'textile',
      'the divine comedy',
      'the dream poem',
      'the fourth estate',
      'the icelandic sagas',
      'the norwegian project',
      'the roman empire',
      'the working environment act',
      'theater',
      'thermal management',
      'thomas kingo',
      'tin',
      'to present oneselv',
      'tool',
      'top drive',
      'train',
      'training',
      'traps',
      'tree',
      'tree felling',
      'tv news',
      'typography',
      'unit',
      'universal design',
      'use of sources',
      'use of the voice',
      'user experience',
      'user manual',
      'value',
      'verb',
      'verb tense',
      'verbal communication',
      'verbal language',
      'verification',
      'vhf',
      'video camera',
      'video production',
      'viking age',
      'vocational course',
      'wall newspaper',
      'war',
      'water injection',
      'web development',
      'web ethics',
      'web page',
      'web search',
      'web site',
      'web troll',
      'website',
      'well control',
      'well flow test',
      'well killing method',
      'well logging',
      'well problem',
      'wellcontrol',
      'wife',
      'william shakespeare',
      'work permission',
      'writing process',
      'writing tools',
      'written',
      'ww2',
      'youth',
    ],
    language: 'en',
  },
  {
    tags: [
      'adgangskontroll',
      'adjektiv',
      'afghanistan',
      'afrika',
      'aktivitet',
      'akvakultur',
      'al-andalus',
      'alarmanlegg',
      'andre verdenskrig',
      'andrespråk',
      'anleggsdokumentasjon',
      'anmeldelse',
      'ansvar',
      'antenne',
      'antenneutstyr',
      'antikken',
      'arbeid i høyde',
      'arbeidsmiljøforskriftene',
      'arbeidsmiljøloven',
      'arbeidstillatelse',
      'asia',
      'athen',
      'automatisert',
      'avhengighet',
      'avis',
      'avisand',
      'avlede',
      'avledning',
      'avsender',
      'avsetning',
      'avviksbrønn',
      'balanse',
      'barokk',
      'barrierer',
      'behov',
      'betong',
      'betongfag',
      'betongfaget',
      'bevegelig utstyr',
      'bevegelse',
      'bilde',
      'bildemanus',
      'bildeproduksjon',
      'bilder',
      'bilderedigering',
      'bjørn',
      'blogg',
      'boccaccio',
      'bop',
      'borekronen',
      'boremodul',
      'boreproblem',
      'borerør',
      'boreslam',
      'borestreng',
      'boretårn',
      'borevæske',
      'boring',
      'brudd',
      'brukeropplevelse',
      'bruksanvisning',
      'brønnbygging',
      'brønndrepingsmetode',
      'brønnkontroll',
      'brønnlogging',
      'brønnsikring',
      'brønntest',
      'budskap',
      'bunnhullsutstyr',
      'bystat',
      'bøyelasting',
      'conquistadorene',
      'creative commons',
      'dante',
      'data- og elektronikksystemer',
      'datainnsamling',
      'debatt',
      'dekameronen',
      'dekor',
      'demokrati',
      'den fjerde statsmakt',
      'den guddommelige komedie',
      'det norske prosjektet',
      'digitale medier',
      'diktanalyse',
      'diskusjon',
      'dokumentar',
      'dokumentasjon',
      'dokumnetasjon',
      'dorothe engelbretsdotter',
      'drama',
      'dramaturgi',
      'draumkvedet',
      'dreieretningsvender',
      'drillers metode',
      'drivmekanismer',
      'elektrisk installasjon',
      'elevproduksjon',
      'emoji',
      'emoticons',
      'en folkefiende',
      'enhet',
      'entring',
      'episk',
      'episk tekst',
      'erosjon',
      'essay',
      'etikk',
      'europeere',
      'eventyr',
      'fagtekst',
      'fallende gjenstander',
      'farge',
      'fargelære',
      'farger',
      'fastkjørt borestreng',
      'feller',
      'feltutbygging',
      'filformater',
      'film',
      'filmanalyse',
      'filmproduksjon',
      'finitte verb',
      'fiskeoppdrett',
      'fjernoperert',
      'fjernsyn',
      'fleksibelt ledd',
      'flytende installasjon',
      'fordelingsskap',
      'forfatter',
      'form',
      'formater',
      'formelement',
      'formkontrast',
      'formuttrykk',
      'forskrift',
      'fortelle',
      'forteller',
      'fortellermåte',
      'fortelleteknikk',
      'fortelling',
      'forurensningsloven',
      'fotografering',
      'fotografi',
      'fotoreportasje',
      'fremmedspråk',
      'friksjonstrykk',
      'fritid',
      'fritt ord',
      'førstehjelp',
      'førstespråk',
      'gantt',
      'gassinjeksjon',
      'gasskappe',
      'geologi',
      'gips',
      'gjennomføring',
      'grafisk design',
      'grafisk utforming',
      'grunnord',
      'gruppe',
      'gud',
      'hatsve',
      'havbunnsanlegg',
      'havbunnsramme',
      'heimskringla',
      'heisespill',
      'hellas',
      'helsefagarbeider',
      'heltedikt',
      'helvete',
      'himmel',
      'historiske kilder',
      'hiv kompensering',
      'hjemmekino',
      'hms',
      'hms-arbeid',
      'hms-kultur',
      'hms-plan',
      'hobby',
      'holdningskampanje',
      'hovedsystem',
      'html5',
      'hullproblem',
      'humanisme og renessanse',
      'husarbeid',
      'hydraulikk',
      'hydraulikkanlegg',
      'hydrostatisk trykk',
      'høymiddelalderen',
      'iberia',
      'ibop',
      'identitet',
      'identitetsdannelse',
      'idémyldring',
      'idéutvikling',
      'igangsetting',
      'imperium',
      'india',
      'indianere',
      'infografikk',
      'informasjonsarbeid',
      'informasjonsvirksomhet',
      'innhold',
      'innretningsforskriften',
      'instalasjon',
      'installasjon',
      'installasjonsveiledning',
      'interiør',
      'interiørkonsulent',
      'internett',
      'internettside',
      'intervju',
      'introduksjon',
      'is',
      'islendingesagaene',
      'jakt',
      'jernbane',
      'johannes vermeer',
      'jord',
      'journalist',
      'journalistikk',
      'kamerabevegelser',
      'kamerainnstilling',
      'kanal',
      'keisertiden',
      'kilde',
      'kildebruk',
      'kildekritikk',
      'kina',
      'klasseromsaktivitet',
      'klemfare',
      'koding',
      'kommunikasjon',
      'kommunikasjonsbransjen',
      'kommunikasjonsmodell',
      'kommunikasjonsprosess',
      'kommunikasjonsprosessen',
      'kommunikasjonsrådgivar',
      'kompensering',
      'komplettering',
      'kompletteringsvæske',
      'komposisjonsprinsipp',
      'kompresjon',
      'kone',
      'kongens nei',
      'konkurranse',
      'kontaktor',
      'kontinuitet',
      'kontrast',
      'korstog',
      'kreativ',
      'kreativitet',
      'krig',
      'kringkastingsloven',
      'kristendom',
      'kulturhistorie',
      'kulturmøter',
      'kåseri',
      'laboratorieforsøk',
      'lagercelle',
      'lakselus',
      'layout',
      'leire',
      'leserinnlegg',
      'leting',
      'levende bilder',
      'limtre',
      'linse',
      'litterær analyse',
      'loggestreng',
      'logging',
      'lover',
      'ludvig holberg',
      'lwd',
      'lyd',
      'lydopptak',
      'lydproduksjon',
      'lys',
      'lyssetting',
      'lysstyring',
      'læringssti',
      'løftekompetanse',
      'maktfordelingsprinsipp',
      'maleri',
      'manus',
      'markedsføring',
      'markedsføringsloven',
      'markedskommunikasjon',
      'martin luther',
      'materialliste',
      'media',
      'mediebransjen',
      'mediebruk',
      'mediedesign',
      'medieetikk',
      'mediehistorie',
      'mediehistorier',
      'mediekommunikasjon',
      'mediemakt',
      'mediepolitikk',
      'medieproduksjon',
      'mediestruktur',
      'medieundersøkelse',
      'medieuttrykk',
      'medieutvikling',
      'medievaner',
      'medieyrker',
      'merkevarebygging',
      'middelalderen',
      'mikrofon',
      'mobilbruk',
      'mobiltelefon',
      'morsmål',
      'motorsag',
      'multilateral brønn',
      'muntlig',
      'musiker',
      'musikksjanger',
      'musikksmak',
      'mytologi',
      'målgruppe',
      'måling',
      'møteinnkalling',
      'møtereferat',
      'nasjonal identitet',
      'nasjonsbygging',
      'nedkjøling',
      'nedre komplettering',
      'nettdesign',
      'nettetikk',
      'nettroll',
      'nettside',
      'nettsted',
      'nettsøk',
      'njaevie',
      'nord-amerika',
      'norge',
      'norm',
      'norrøn litteratur',
      'norsk filmhistorie',
      'norsk historie',
      'norsk sokkel',
      'norsok',
      'novelle',
      'nyhet',
      'nyhetsformidling',
      'nyhetskriterier',
      'objektiv',
      'offshore',
      'olje og gass',
      'oljeproduksjon',
      'omdømmebygging',
      'oppdrift',
      'oppdriftselement',
      'oppgave',
      'opphavsrett',
      'opplysningstida',
      'opplæring',
      'oppmerksomhetskrevende arbeid',
      'overflatesystemer',
      'oversjøisk ekspansjon',
      'oversjøisk handel',
      'p for påvirkning',
      'pavestaten',
      'perfektum partisipp',
      'perforering',
      'perforert brønn',
      'personvern',
      'petroleum',
      'petroleumsloven',
      'petter dass',
      'planlegging',
      'plattform',
      'pls',
      'pluskvam perfektum',
      'podkast',
      'polis',
      'portefølje',
      'portrett',
      'posisjonering',
      'presentere seg',
      'pressekonferanse',
      'pressemakt',
      'pressemelding',
      'produksjon',
      'produksjonsanlegg',
      'produksjonsbrønn',
      'produksjonsdel',
      'produksjonsprosess',
      'produksjonsprosesser',
      'produksjonstest',
      'programmering',
      'prosedyre',
      'prosedyrer',
      'prosessanlegg',
      'prosessering',
      'prosessutstyr',
      'psykisk helse',
      'publikasjon',
      'publisere',
      'pulp fiction',
      'pumpesystem',
      'radio',
      'radiospot',
      'rammeforskriftene',
      'ramrig',
      'redigeringsprogram',
      'reklame',
      'reklameformater',
      'reklamefotografi',
      'renessanse',
      'rensefisk',
      'reservoar',
      'reservoarkomplettering',
      'reservoartrykk',
      'returslambehandling',
      'rigg',
      'risiko',
      'risikoanalyse',
      'risikomatrise',
      'risikotiltak',
      'risikovurdering',
      'roma',
      'romerriket',
      'rovhtege',
      'ruh',
      'rød sone',
      'rørfeste',
      'rørhåndtering',
      'rørledning',
      'saajve',
      'saajvesjø',
      'sagn',
      'sakprosa',
      'saktekster',
      'salme',
      'salmedikter',
      'samfunnsansvar',
      'samfunnsforhold',
      'samisk fortellertradisjon',
      'sammenligning',
      'sammensetting',
      'samsvarserklæring',
      'sandproblem',
      'sedimentære bergarter',
      'seismikk',
      'sement',
      'sementeringsutstyr',
      'senmiddelalder',
      'sensur',
      'shakersystem',
      'sidebrønn',
      'sideoppsett',
      'signalanlegg',
      'sikker jobb analyse',
      'sikkerhetskurs',
      'sikre',
      'sikring av personell',
      'sirkulasjonstrykk',
      'sjanger',
      'skapelsesmyter',
      'skjema',
      'skjønnlitteratur',
      'skogbruk',
      'skole',
      'skriftlig',
      'skriveprosess',
      'skriveverktøy',
      'skylappjenta',
      'slam',
      'slamlab',
      'sluttkontroll',
      'smarte brønner',
      'smarttelefon',
      'snorre sturlason',
      'sola',
      'sparta',
      'spillefilm',
      'språkhistorie',
      'språklige virkemidler',
      'språklæring',
      'stallo',
      'statistikk',
      'statsutvikling',
      'stemmebruk',
      'sterk',
      'stigerør',
      'stikkontakt',
      'styringsforskriften',
      'subjektiv',
      'substantiv',
      'søkestrategier',
      'sør-amerika',
      'takbergart',
      'tall',
      'tanker',
      'tankskip',
      'teater',
      'tegneserie',
      'teknologiutvikling',
      'tekstil',
      'tekstproduksjon',
      'telefonnummer',
      'teleskopledd',
      'tempelridder',
      'tenåring',
      'testtag autolagret',
      'testtag1',
      'testtag2',
      'thomas kingo',
      'tilgjengelighet',
      'tinn',
      'tog',
      'top drive',
      'tospråklighet',
      'traverskran',
      'tre',
      'trefelling',
      'tro',
      'trykkfall',
      'trykkgradient',
      'trykkontroll',
      'trykkstøtte',
      'tunge borerør',
      'tv',
      'tv-nyheter',
      'typografi',
      'tysk',
      'tyskere',
      'tyskland',
      'ulagret tagg',
      'undervisning',
      'ungdom',
      'universell utforming',
      'utforskning',
      'utvekslingsprogram',
      'vanninjeksjon',
      'varme',
      'varmestyring',
      'varmt arbeid',
      'vedlikehold',
      'veggavis',
      'vektrør',
      'venner',
      'vennskap',
      'verb',
      'verbal kommunikasjon',
      'verbalt språk',
      'verbtid',
      'verdi',
      'verifikasjon',
      'verktøy',
      'verktøyferdighet',
      'vhf',
      'videokamera',
      'videoproduksjon',
      'vikingtiden',
      'virkemiddel',
      'virkemidler',
      'webutvikling',
      'william shakespeare',
      'yrke',
      'yrkesfag',
      'ytringsfrihet',
      'åndsverkloven',
      'åpent hull',
      'ættesaga',
      'ættesamfunn',
      'øvelse',
    ],
    language: 'nb',
  },
  {
    tags: [
      'adjektiv',
      'afghanistan',
      'afrika',
      'aktivitet',
      'akvakultur',
      'al-andalus',
      'alarmanlegg',
      'andre verdskrig',
      'andrespråk',
      'anleggsdokumentasjon',
      'ansvar',
      'antenne',
      'antenneutstyr',
      'antikken',
      'arbeidsmiljølova',
      'arbeidstillatelse',
      'asia',
      'athen',
      'avhengigheit',
      'avis',
      'avisand',
      'avsendar',
      'balanse',
      'barokk',
      'behov',
      'betong',
      'betongfag',
      'betongfaget',
      'bilete',
      'biletmanus',
      'biletproduksjon',
      'bjørn',
      'blogg',
      'boccaccio',
      'bodskap',
      'bop',
      'boreslam',
      'boring',
      'brot',
      'brukaroppleving',
      'bruksrettleiing',
      'bystat',
      'conquistadorane',
      'dante',
      'debatt',
      'dekameronen',
      'dekor',
      'demokrati',
      'den fjerde statsmakta',
      'den guddommelege komedien',
      'digitale medium',
      'diskusjon',
      'dokumentar',
      'dokumentasjon',
      'dorothe engelbretsdotter',
      'drama',
      'dramaturgi',
      'draumkvedet',
      'dreieretningsvendar',
      'eining',
      'elektrisk installasjon',
      'elevproduksjon',
      'emoji',
      'emoticons',
      'episk',
      'episk tekst',
      'essay',
      'etikk',
      'europearar',
      'eventyr',
      'farge',
      'fargelære',
      'filformat',
      'film',
      'filmanalyse',
      'filmproduksjon',
      'fiskeoppdrett',
      'fjernsyn',
      'fordelingsskap',
      'forfattar',
      'form',
      'format',
      'formelement',
      'formuttrykk',
      'forskrift',
      'forteljeteknikk',
      'forteljing',
      'fotografering',
      'fotografi',
      'fotoreportasje',
      'fritid',
      'fritt ord',
      'gantt',
      'gips',
      'gjennomføring',
      'grafisk design',
      'grafisk utforming',
      'gruppe',
      'gud',
      'heimekino',
      'heimskringla',
      'hellas',
      'helsefagarbeidar',
      'heltedikt',
      'helvete',
      'himmel',
      'historiske kjelder',
      'hms',
      'hms-arbeid',
      'hmt-plan',
      'hobby',
      'holdningskampanje',
      'html5',
      'humanisme og renessanse',
      'husarbeid',
      'hydraulikk',
      'hydraulikkanlegg',
      'høgmellomalderen',
      'iberia',
      'identitet',
      'identitetsdanning',
      'idémyldring',
      'idéutvikling',
      'igangsetjing',
      'imperium',
      'india',
      'indianarar',
      'infografikk',
      'informasjonsarbeid',
      'informasjonsverksemd',
      'innhald',
      'instalasjon',
      'installasjon',
      'installasjonsrettleiing',
      'interiør',
      'interiørkonsulent',
      'internett',
      'internettside',
      'intervju',
      'introduksjon',
      'is',
      'islendingesogene',
      'jakt',
      'jernbane',
      'johannes vermeer',
      'jord',
      'journalist',
      'journalistikk',
      'kamerainnstilling',
      'kamerarørsler',
      'kanal',
      'keisartida',
      'kina',
      'kjelde',
      'kjeldebruk',
      'kjeldekritikk',
      'klasseromsaktivitet',
      'koding',
      'kommunikasjon',
      'kommunikasjonsbransjen',
      'kommunikasjonsmodell',
      'kommunikasjonsprosess',
      'kommunikasjonsprosessen',
      'kommunikasjonsrådgjevar',
      'komposisjonsprinsipp',
      'kompresjon',
      'kone',
      'kongens nei',
      'konkurranse',
      'kontaktor',
      'kontinuitet',
      'kontrast',
      'kreativ',
      'krig',
      'kringkastingslova',
      'kristendom',
      'krosstog',
      'kulturhistorie',
      'kulturmøte',
      'kåseri',
      'laboratorieforsøk',
      'lakselus',
      'layout',
      'leire',
      'lesarinnlegg',
      'levande bilete',
      'limtre',
      'linse',
      'litterær analyse',
      'logging',
      'lover',
      'ludvig holberg',
      'lyd',
      'lydopptak',
      'lydproduksjon',
      'lys',
      'lyssetjing',
      'lysstyring',
      'læringssti',
      'maktfordelingsprinsipp',
      'manus',
      'marknadsføring',
      'marknadsføringslova',
      'martin luther',
      'materialliste',
      'media',
      'mediebransjen',
      'mediebruk',
      'mediedesign',
      'medieetikk',
      'mediehistorie',
      'mediekommunikasjon',
      'mediemakt',
      'mediepolitikk',
      'medieproduksjon',
      'mediestruktur',
      'medieundersøking',
      'medieuttrykk',
      'medieutvikling',
      'medievanar',
      'medieyrke',
      'mellomalderen',
      'mikrofon',
      'mobilbruk',
      'mobiltelefon',
      'motorsag',
      'munnleg',
      'musiker',
      'mytologi',
      'måleri',
      'målgruppe',
      'måling',
      'nasjonal identitet',
      'nasjonsbygging',
      'nedkjøling',
      'nettdesign',
      'nettetikk',
      'nettroll',
      'nettside',
      'nettstad',
      'nettsøk',
      'nord-amerika',
      'noreg',
      'norm',
      'norrøn litteratur',
      'norsk filmhistorie',
      'norsk historie',
      'novelle',
      'nyheit',
      'nyheitsformidling',
      'nyheitskriterium',
      'objektiv',
      'offshore',
      'omdømmebygging',
      'omtale',
      'oppdrift',
      'oppgåve',
      'opphavsrett',
      'opplysningstida',
      'opplæring',
      'oversjøisk ekspansjon',
      'oversjøisk handel',
      'pavestaten',
      'personvern',
      'petroleum',
      'petter dass',
      'planlegging',
      'plattform',
      'pls',
      'podkast',
      'polis',
      'portrett',
      'presentere seg',
      'pressekonferanse',
      'pressemakt',
      'pressemelding',
      'produksjon',
      'produksjonsbrønn',
      'produksjonsprosess',
      'programmering',
      'prosedyre',
      'prosedyrer',
      'psykisk helse',
      'publikasjon',
      'publisere',
      'pulp fiction',
      'radio',
      'radiospot',
      'redigeringsprogram',
      'reinsefisk',
      'reklame',
      'reklamefotografi',
      'renessanse',
      'risikoanalyse',
      'risikotiltak',
      'risikovurdering',
      'roma',
      'romarriket',
      'rørledning',
      'sakprosa',
      'salme',
      'salmediktar',
      'samfunnsansvar',
      'samfunnstilhøve',
      'samsvarserklæring',
      'segn',
      'seinmellomalder',
      'sensur',
      'signalanlegg',
      'sikre',
      'sjanger',
      'skjema',
      'skogbruk',
      'skriftleg',
      'skule',
      'slam',
      'sluttkontroll',
      'smarttelefon',
      'snorre sturlason',
      'sparta',
      'spelefilm',
      'språkhistorie',
      'statistikk',
      'statsutvikling',
      'stemmebruk',
      'stigerøyr',
      'subjektiv',
      'substantiv',
      'sør-amerika',
      'tankskip',
      'teater',
      'teknologiutvikling',
      'tekstil',
      'telefonnummer',
      'tempelridder',
      'tenåring',
      'thomas kingo',
      'tilgjengelegheit',
      'tinn',
      'tog',
      'tre',
      'trefelling',
      'tro',
      'tv',
      'typografi',
      'tysk',
      'tyskerar',
      'tyskland',
      'undervisning',
      'ungdom',
      'universell utforming',
      'utforsking',
      'utvekslingsprogram',
      'varme',
      'varmestyring',
      'varmt arbeid',
      'vedlikehald',
      'veggavis',
      'venleik',
      'venner',
      'verb',
      'verbal kommunikasjon',
      'verbalt språk',
      'verbtid',
      'verdi',
      'verifikasjon',
      'verkemiddel',
      'verktøy',
      'verktøyferdigheit',
      'videokamera',
      'videoproduksjon',
      'vikingtida',
      'webutvikling',
      'william shakespeare',
      'yrke',
      'yrkesfag',
      'ytringsfridom',
      'åndsverklova',
      'åtgangskontroll',
      'ættesaga',
      'ættesamfunn',
      'øving',
    ],
    language: 'nn',
  },
  {
    tags: [
      '中国',
      '动词',
      '手机',
      '爱好',
    ],
    language: 'zh',
  },
  {
    tags: [
      'aamhtese-prosa',
      'aamhtese-tjaalegh',
      'adjektijvh',
      'ammes-gïele',
      'biejjie',
      'bïerne',
      'digkiedimmie',
      'draama',
      'dïjre',
      'epihke',
      'epihke tjaalegh',
      'essay',
      'faage-tjaalege',
      'filme',
      'govlesadteme',
      'guektiengïelen-voete',
      'guvvie',
      'guvvie-raajroe',
      'guvvieh',
      'gåmma',
      'gïeleviehkie-dïrregh',
      'hatsve',
      'heamture',
      'ietnien-gïele',
      'jaahkoe',
      'jupmele',
      'kontraste',
      'kååserije',
      'laavenjasse',
      'lohkeme-tjaalege',
      'maadth-baakoe',
      'mobijle-telefovne',
      'mubpien-gïele',
      'njaalmeldh',
      'njaevie',
      'novella',
      'perfektume partisihpe',
      'raadijove',
      'rovhtege',
      'saajve',
      'saajve-jaevrie',
      'saemien soptsestimmie-vuekie',
      'seerkedh',
      'seerkeme',
      'sjangere',
      'sjugniedimmie-soptsesh',
      'skuvle',
      'soptsese',
      'soptsestidh',
      'soptsestimmie-vuekie',
      'soptsestæjja',
      'staaloe',
      'substantijvh',
      'teatere',
      'tjaaleldh',
      'tjiehpies-lidteratuvre',
      'tjoeje',
      'tjåanghkoe-gohtjedimmie',
      'tjåanghkoe-referaate',
      'vaajese',
      'veaksehke',
      'verbe-tïjje',
      'verbh',
      'viehkie-dïrrege',
      'viehkie-vierhtieh',
      'viertiestimmie',
      'vijreme',
      'voestes-gïele',
    ],
    language: 'se',
  },
  {
    tags: [
      'abhängigkeit',
      'adjektiv',
      'aktivität',
      'aktivitäten im klassenzimmer',
      'aufklärung',
      'austauschprogramm',
      'beruf',
      'deutsch',
      'deutschland',
      'diskussion',
      'emoji',
      'emoticons',
      'erzählung',
      'farben',
      'fernsehen',
      'film',
      'freizeit',
      'fremdsprachen',
      'freunde',
      'freundschaft',
      'gemälde',
      'gruppe',
      'handy',
      'handynutzung',
      'hausarbeit',
      'himmel',
      'hobby',
      'indien',
      'infografik',
      'inhalt',
      'internet',
      'interview',
      'jugendliche',
      'kommunikation',
      'laut',
      'martin luther',
      'musiker',
      'musikgenre',
      'mündlich',
      'nomen',
      'schriftlich',
      'schule',
      'sich vorstellen',
      'smartphone',
      'statistik',
      'teenager',
      'telefonnummer',
      'unterricht',
      'verb',
      'zahlen',
      'übung',
    ],
    language: 'de',
  },
];
