/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Production system - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Learning resource ${titleTemplate}`,
    createTopicArticlePage: `Topic ${titleTemplate}`,
    createSubjectpage: `Subjectpage ${titleTemplate}`,
    agreementPage: `Agreement ${titleTemplate}`,
    welcomePage: `Frontpage ${titleTemplate}`,
    structurePage: `Structure ${titleTemplate}`,
    audioUploaderPage: `Audio ${titleTemplate}`,
    imageUploaderPage: `Image ${titleTemplate}`,
    loginPage: `Login ${titleTemplate}`,
    logoutPage: `Logout ${titleTemplate}`,
    ndlaFilmPage: `NDLA Film ${titleTemplate}`,
    podcastUploaderPage: `Podcast episode ${titleTemplate}`,
    podcastSeriesPage: `Podcast series ${titleTemplate}`,
    h5pPage: `H5P ${titleTemplate}`,
    search: {
      'podcast-series': `Search podcast series ${titleTemplate}`,
      audio: `Search audio files ${titleTemplate}`,
      concept: `Search concepts ${titleTemplate}`,
      content: `Search content ${titleTemplate}`,
      image: `Search images ${titleTemplate}`,
    },
  },
  meta: {
    description: 'Norwegian Digital Learning Arena, Open Educational Resources',
  },
  menu: {
    title: 'Menu',
  },
  dropdown: {
    numberHits: `Search returned {{hits}} hits`,
    searching: 'Searching...',
    create: 'Create new',
    isSelectedItem: 'Added',
  },
  dialog: {
    close: 'Close',
    title: 'Title',
    audio: {
      rulesForUse: 'Rules for use of audio',
    },
    learnAboutLicenses: 'Learn more about open licenses',
    source: 'Source',
  },
  license: {
    heading: 'Howto reuse content',
    tabs: {
      text: 'Text',
      images: 'Images',
      audio: 'Audio',
      video: 'Video',
    },
    images: {
      heading: 'How to use images from the article',
      description: 'Remember to copy the text to be attached to the image where you use it.',
      rules: 'Rules for use of image:',
      source: 'Source',
      title: 'Title',
    },
    text: {
      heading: 'How to use text from the article',
      description: 'The article may be composed of several different texts, which are listed here.',
      rules: 'Rules for use of text:',
      published: 'Published',
    },
    audio: {
      heading: 'How to use audio files from the article',
      description: 'Remember to copy the text to be attached to the audio where you use it.',
      rules: 'Rules for use of audio file:',
    },
    video: {
      heading: 'How to use videos from the article',
      description: 'Remember to copy the text to be attached to the video where you use it.',
      rules: 'Rules for use of audio file:',
    },
    learnMore: 'Learn more about open licenses',
    copyTitle: 'Copy reference',
    embed: 'Embed',
    embedCopied: 'Copied embed code!',
    hasCopiedTitle: 'Copied!',
    download: 'Download',
  },
  language: {
    en: 'English',
    nb: 'Norwegian - Bokmål',
    nn: 'Norwegian - Nynorsk',
    se: 'Sami',
    sma: 'Southern Sami',
    unknown: 'Unknown',
    de: 'German',
    empty: 'No languages left',
    change: 'Change to {{language}} version',
  },
  welcomePage: {
    addSearch: 'Add new search',
    deleteSavedSearch: 'Delete saved search',
    deleteSearch: 'Delete search',
    emptyLastUsed: 'Empty last edited list',
    emptySavedSearch: 'No saved searches',
    guidelines: 'Guidelines',
    mustBeSearch: 'Link must be a search url',
    lastUsed: 'Last edited',
    savedSearch: 'Saved searches',
    saveSearch: 'Save search',
  },
  searchPage: {
    header: {
      content: 'Search for content',
      audio: 'Search for audio files',
      image: 'Search for images',
      concept: 'Search for concepts',
      'podcast-series': 'Search for podcast series',
    },
    searchButton: 'Search',
    emptyButton: 'Empty',
    title: 'Title',
    language: 'Language',
    contentNoHits: 'Your search - {{query}} - did not match any content.',
    'podcast-seriesNoHits': 'Your search - {{query}} - did not match any content.',
    conceptNoHits: 'Your search - {{query}} - did not match any concept.',
    audioNoHits: 'Your search - {{query}} - did not match any audio files.',
    imageNoHits: 'Your search - {{query}} - did not match any images.',
    pageSize: '{{pageSize}} hits per page',
    totalCount: 'Total results',
    highlights: {
      title: 'Search hits',
      content: 'Search hits from content',
      tags: 'Search hits from tags',
      embedAttributes: 'Search hits from embedded elements',
      notes: 'Search hits from version log',
      previousVersionsNotes: 'Search hits from version log',
    },
  },
  articleType: {
    'topic-article': 'Topic',
    standard: 'Subject matter',
  },
  subNavigation: {
    learningPath: 'Learningpath',
    learningPathLink: 'Go to learningpath',
    subjectMatter: 'Subject matter',
    detailSearch: 'Detail search',
    topicArticle: 'Create new topic',
    learningResource: 'Learning resource',
    image: 'New image',
    audio: 'New Audiofile',
    podcast: 'New Podcast episode',
    podcastSeries: 'New Podcast series',
    agreement: 'New Agreement',
    structure: 'Structure',
    searchContent: 'Search content',
    searchAudio: 'Search audio',
    searchPodcastSeries: 'Search series',
    searchImage: 'Search image',
    searchConcepts: 'Search concepts',
    film: 'Edit NDLA film',
    h5p: 'Edit H5P',
    newConcept: 'Create new concept',
    newSubject: 'Create new subject',
  },
  logo: {
    altText: 'The Norwegian Digital Learning Arena',
  },
  siteNav: {
    chooseSubject: 'Choose Subject',
    search: 'Search',
    login: 'Login',
  },
  loginFailure: {
    errorMessage: 'Sorry. Login failed.',
    loginLink: 'Click to try again.',
    userNotRegistered:
      'We did not recognize your email address. Did you use the correct email address?',
  },
  loginProviders: {
    description: 'Log in with',
  },
  logoutProviders: {
    localLogout: 'Log out from production system',
    or: 'eller',
    federatedLogout: 'Log out of all providers',
    description: 'N.B. All providers include the identityprovider (Google or Facebook).',
  },
  searchForm: {
    placeholder: 'Search articles',
    types: {
      conceptQuery: 'Search for concept',
      contentQuery: 'Search for content',
      audioQuery: 'Search for audio files',
      podcastSeriesQuery: 'Search for podcast series',
      imageQuery: 'Search for images',
      language: 'Select language',
      users: 'Select editor',
      subjects: 'Select subject',
      resourceTypes: 'Select resource type',
      status: 'Select status',
      audio: 'Select audio file type',
    },
    tagType: {
      query: 'Query',
      subjects: 'Subject',
      language: 'Language',
      users: 'Editor',
      resourceTypes: 'Resource type',
      status: 'Status',
    },
    btn: 'Search',
    empty: 'Empty',
    articleType: {
      all: 'All',
      standard: 'Standard',
      learningResource: 'Learning resource',
      topicArticle: 'Topic description',
      image: 'Image',
      audio: 'Audio',
    },
    audioType: {
      standard: 'Audio',
      podcast: 'Podcast',
    },
    order: 'Rekkefølge',
    asc: 'Ascending',
    desc: 'Descending',
    sorting: 'Sorting',
    sort: {
      id: 'Id',
      relevance: 'Relevance',
      title: 'Title',
      lastUpdated: 'Last updated',
    },
    resultError: 'Something went wrong with type: {{type}}',
  },
  subjectsPage: {
    subjects: 'Subjects',
  },
  subjectPage: {
    topics: 'Topics',
  },
  editMarkup: {
    linkTitle: 'Go to HTML editor',
    title: 'HTML editor',
    subTitle: 'Edit article with HTML',
    fetchError:
      'An error occurred while loding an article into the HTML editor. Go back or try to reload the page.',
    saveError: 'An error occurred while saving article changes.',
    helpMessage: {
      tooltip: 'About the HTML editor',
      paragraph1:
        'It is possible to format the HTML code by pressing F1 and then selecting Format. Note that this could lead to changes in whitespace (indentations, linebreaks and spaces) when saving. Feel free to use the preview feature rapidly. Saving using ctrl+s also works.',
      paragraph2:
        'To minimize potential problems with formatting and to secure consistent HTML, the same transformations as in the regular editor is applied. This means that illegal code is attempted to be corrected. Linebreaks are removed when saving and are therefore ignored',
    },
  },
  imageSearch: {
    placeholder: 'Search images',
    buttonTitle: 'Search',
    useImage: 'Use image',
    noTitle: 'No title',
    noResultsText: 'No images found. Would you like to upload a new image?',
    noResultsButtonText: 'Upload image',
  },
  videoSearch: {
    searchPlaceholder: 'Search videos',
    searchButtonTitle: 'Search',
    loadMoreVideos: 'Load more videos',
    noResults: 'No videos found',
    addVideo: 'Use video',
    previewVideo: 'Preview',
    publishedDate: 'Published date',
    duration: 'Duration',
    interactioncount: 'Views',
  },
  mathEditor: {
    editMath: 'Edit Math',
    preview: 'Preview',
    continue: 'You might have unsaved changes in the math editor. Do you want to continue?',
  },
  code: {
    continue: 'You might have unsaved changes in the code editor. Do you want to continue?',
  },
  h5pElement: {
    fetchError: 'Sorry, an error occurd while loading the H5P client.',
  },
  displayOembed: {
    errorMessage: 'An error occurd when displaying oEmbed.',
    notSupported: 'oEmbed of type {{type}} and provider {{provider}} is not supported.',
  },
  audioSearch: {
    searchPlaceholder: 'Search in audio files',
    searchButtonTitle: 'Search',
    useAudio: 'Chose audio',
    noResults: 'No audio files found',
    noTitle: 'No title',
  },
  conceptSearch: {
    searchPlaceholder: 'Search in concepts',
    searchButtonTitle: 'Search',
    noResults: 'No concepts found',
    noTitle: 'No title',
    noContent: 'No content',
  },
  searchTypes: {
    content: 'Content',
    audio: 'Audio',
    image: 'Image',
    concept: 'Concepts',
    'podcast-series': 'Series',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element of type {{type}} will be deleted on save.',
  },
  conceptpageForm: {
    articlesTitle: 'Related Articles',
    articlesSubtitle: 'Articles',
    changeOrder: 'Change order',
    removeArticle: 'Remove article',
  },
  subjectpageForm: {
    title: 'Subject',
    about: 'About subject',
    description: 'Description',
    metadata: 'Metadata',
    addBanner: 'Choose banner image',
    changeBanner: 'Change banner image',
    editorsChoices: 'Editor choices from the subject',
    articles: 'Articles',
    addArticle: 'Add article',
    removeArticle: 'Remove article',
    missingVisualElement: 'Visual element is required',
  },
  filterform: {
    title: 'Filter',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Image title',
      video: 'Video title',
      brightcove: 'Video title',
      external: 'Content title',
      h5p: 'H5P title',
    },
    visualElementCopyright: 'Origin',
    removeVisualElement: 'Remove element',
    info: {
      lastUpdated: 'Last updated: ',
    },
    title: 'Topic',
    fields: {
      caption: {
        label: {
          image: 'Video caption',
          brightcove: 'Video caption',
          external: 'Content caption',
        },
        placeholder: {
          image: 'Image caption',
          brightcove: 'Video caption',
          external: 'Content caption',
        },
      },
      alt: {
        label: 'Alt-text',
        placeholder: 'Alt-text',
      },
    },
  },
  footnoteForm: {
    title: 'Title',
    year: 'Year',
    authors: 'Author',
  },
  linkForm: {
    href: 'Link',
    text: 'Text',
  },
  audioForm: {
    title: 'audio file',
  },
  podcastSeriesForm: {
    title: 'Podcast series',
    alreadyPartOfSeries: 'Part of another series',
    description: 'Description',
  },
  podcastForm: {
    title: 'Podcast episode',
    fields: {
      header: 'Header',
      introduction: 'Introduction',
      coverPhoto: 'Image',
      coverPhotoAltText: 'Alt-text',
      manuscript: 'Text version',
      series: 'Series',
    },
    information: {
      partOfSeries: 'This podcast is a part of the series',
      removeSeries: 'Remove Series',
      noSeries: 'This podcast is not a part of any series',
    },
  },
  imageEditor: {
    remove: {
      crop: 'Remove crop',
      focalPoint: 'Remove focal point',
    },
  },
  imageForm: {
    title: 'Image',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Image title',
      copyright: 'Copyright',
      change: 'Change meta image',
    },
    title: 'Learning resource',
    validation: {
      missingEmbedData:
        'One or more included video, image, or audio elements is missing caption or alternative text.',
    },
    fields: {
      rightAside: {
        title: 'Right column',
        moveContent: 'Move content into the text',
        delete: 'Delete right aside',
      },
      footnotes: {
        edition: 'Edition',
        publisher: 'Publisher',
      },
    },
  },
  editorToolbar: {
    bold: 'Bold\n({{ctrl}}+b)',
    bulletedList: 'Bulleted list\n({{ctrl}}+l)',
    code: 'Inline code\n({{ctrl}}+k)',
    codeblock: 'Code',
    concept: 'Concept\n({{ctrl}}+alt+c)',
    footnote: 'Footnote\n({{ctrl}}+alt+f)',
    headingOne: 'Heading 1',
    headingThree: 'Heading 3\n({{ctrl}}+3)',
    headingTwo: 'Heading 2\n({{ctrl}}+2)',
    italic: 'Italic\n({{ctrl}}+i)',
    letterList: 'Letter list\n({{ctrl}}+alt+a)',
    link: 'Link\n({{ctrl}}+alt+l)',
    mathml: 'Math\n({{ctrl}}+m)',
    numberedList: 'Numbered list\n({{ctrl}}+alt+1)',
    quote: 'Quote\n({{ctrl}}+alt+b)',
    sub: 'Subscript\n({{ctrl}}+alt+s)',
    sup: 'Superscript\n({{ctrl}}+alt+h)',
    twoColumnList: 'Two-column list',
    underlined: 'Underlined',
  },
  editorBlockpicker: {
    heading: 'Add',
    actions: {
      block: 'Section',
      factAside: 'Factbox',
      table: 'Table',
      bodybox: 'Text in frame',
      details: 'Expandable box',
      image: 'Image',
      video: 'Video',
      audio: 'Audio',
      h5p: 'H5P',
      url: 'Resource from link',
      related: 'Related content',
      file: 'File',
      code: 'Codeblock',
      podcast: 'Podcast episode',
    },
  },
  form: {
    metadataSection: 'Metadata',
    contentSection: 'Content',
    workflowSection: 'Version log and notes',
    taxonomySection: 'Taxonomy',
    copyrightSection: 'License and authors',
    articleSection: 'Articles',
    podcastSection: 'Podcast information',
    podcastSeriesSection: 'Podcast series',
    podcastEpisodesSection: 'Episodes',
    podcastEpisodesTypeName: 'Podcasts',
    inlineEdit: 'Inline editor',
    save: 'Save',
    saveAsNewVersion: 'Save as new version',
    saveAndPublish: 'Save and publish',
    saveDraft: 'Save draft',
    saveTax: 'Save taxonomy',
    saving: 'Saving...',
    choose: 'Choose',
    saved: 'Saved ',
    feil: 'There are still errors.',
    copy: 'copy',
    saveAsCopySuccess: 'New article saved',
    preview: {
      button: 'Preview',
    },
    name: {
      title: 'Title',
      slatetitle: 'Title',
      aboutTitle: 'Title',
      introduction: 'Ingress',
      creators: 'Creators',
      rightsholders: 'Rightsholders',
      processors: 'Processors',
      tags: 'Tags',
      license: 'License',
      origin: 'Origin',
      audioFile: 'Audio file',
      content: 'Content',
      notes: 'Notes',
      metaDescription: 'Meta description',
      metaImageAlt: 'Alt-text',
      alttext: 'Alt-text',
      caption: 'Caption',
      imageFile: 'Imagefile',
      visualElement: 'Visual element',
      visualElementObject: 'Visual element',
      visualElementCaption: 'Caption',
      visualElementAlt: 'Alt-text',
      validFrom: 'Valid from',
      validTo: 'Valid to',
      description: 'Content',
      conceptContent: 'Description',
      grepCodes: 'Curriculum connection',
      desktopBanner: 'Desktop banner',
      mobileBanner: 'Mobile banner',
      concepts: 'Concepts',
      relatedContent: 'Related content',
      subjects: 'Subject',
      header: 'Header',
      manuscript: 'Text version',
      coverPhotoId: 'Meta image',
    },
    previewProductionArticle: {
      button: 'Compare draft and article',
      article: 'Published version',
      draft: 'Draft',
    },
    previewLanguageArticle: {
      button: 'Compare language versions',
      title: 'Draft on {{language}}',
    },
    previewNewWindow: 'Preview in a new window',
    contributor: {
      add: 'Add',
    },
    detailBox: {
      changeTitle: 'Change title',
      placeholder: 'Short summary',
    },
    mustSaveFirst: 'You must save your changes first',
    abort: 'Abort',
    edit: 'Edit',
    remove: 'Remove',
    validate: 'Validate',
    publish: 'Publish',
    savedOk: 'Saved OK',
    publishedOk: 'Published OK',
    validationOk: 'No validation errors found',
    createdOk: 'Created OK',
    addNewImage: 'Add new image',
    addNewAudio: 'Add new audio',
    notes: {
      heading: 'Notes',
      add: 'Add new note',
      remove: 'Remove note',
      warning: 'A note must contain text',
      areHere: 'You are here',
      published: 'Published',
      history: {
        user: 'User',
        time: 'When',
        status: 'Status',
        heading: 'Notes history',
        note: 'Note',
        empty: 'No notes',
      },
    },
    updated: {
      label: 'Updated date',
    },
    published: {
      label: 'Published date',
      reset: 'Reset date',
    },
    updatePublished: 'Update published date',
    editImage: 'Edit image',
    editOriginalImage: 'Edit orginal image',
    editAudio: 'Edit audio',
    editPodcast: 'Edit podcast',
    resetToProd: {
      button: 'Reset to prod',
      modal: 'Do you want to reset the draft as it is on the ndla frontpage?',
      success: 'Content is reset, press save to save changes',
    },
    resetToVersion: 'Reset to version',
    previewVersion: 'See version',
    variant: {
      create: 'Create variant',
      translate: 'Translate to Nynorsk',
    },
    remainingCharacters: 'Max {{maxLength}} characters and you have {{remaining}} remaining.',
    title: {
      label: 'Title',
    },
    introduction: {
      label: 'Introduction',
    },
    metaImage: {
      copyright: 'Copyright',
      change: 'Change meta image',
      title: 'Meta image',
      imageTitle: 'Image title',
      label: 'Meta image',
      helpLabel: 'What is a meta image?',
      add: 'Choose meta image',
      remove: 'Remove meta image',
    },
    availability: {
      everyone: 'Everyone',
      teacher: 'Teachers',
      student: 'Students',
      label: 'Availability',
      description: 'Who the article is intended for:',
    },
    markdown: {
      button: 'Click to view markdown',
      helpLabel: 'What is markdown?',
    },
    visualElement: {
      title: 'Add visual element',
      label: 'Visual element',
      video: 'Video search',
      image: 'Image search',
      imageUpload: 'Upload image',
      h5p: 'H5P',
    },
    concept: {
      create: 'Create concept',
      addText: 'Choose a concept and press "connect to topic", or',
      edit: 'Edit concept',
      addConcept: 'Add existing concept',
      removeConcept: 'Remove concept',
      source: 'Source',
      subjects: 'Only subjects marked as explanation subjects will be displayed in the list.',
    },
    workflow: {
      title: 'Status',
      change: 'Change status',
      qualityAssurance: 'Quality assurance',
      saveAsNew: 'Make copy',
      deleteLanguageVersion: {
        button: 'Delete language version',
        title: 'Delete language version',
        modal: 'Are you sure that you want to delete this language version?',
      },
      statusInfoTooltip: 'Whats the difference between statuses?',
      statusLabel: 'Status',
      published: 'There exists a published version of this item.',
      multipleTaxonomy: 'The article has multiple entries in taxonomy.',
    },
    status: {
      new: 'New - unsaved',
      new_language: 'New language - unsaved',
      created: 'Created',
      imported: 'Imported',
      draft: 'Draft',
      proposal: 'Proposal',
      user_test: 'User test',
      awaiting_quality_assurance: 'Quality assurance',
      queued_for_language: 'Queued for language',
      translated: 'Language done',
      quality_assured: 'Ready for publishing',
      queued_for_publishing: 'Queued for publishing',
      quality_assured_delayed: 'Ready for publishing-delayed',
      queued_for_publishing_delayed: 'Queue for publishing-delayed',
      published: 'Published',
      has_published: 'Has published version',
      unlisted: 'Link shared',
      unpublished: 'Unpublished',
      awaiting_unpublishing: 'Awaiting unpublishing',
      awaiting_archiving: 'Delayed archivation',
      archived: 'Deleted',
      actions: {
        DRAFT: 'Draft',
        PROPOSAL: 'Proposal',
        USER_TEST: 'User test',
        AWAITING_QUALITY_ASSURANCE: 'To Quality assurance',
        QUEUED_FOR_LANGUAGE: 'Queued for language',
        TRANSLATED: 'Language done',
        QUALITY_ASSURED: 'Ready for publishing',
        QUEUED_FOR_PUBLISHING: 'Queue for publishing',
        QUALITY_ASSURED_DELAYED: 'Ready for publishing-delayed',
        QUEUED_FOR_PUBLISHING_DELAYED: 'Queue for publishing-delayed',
        PUBLISHED: 'Publish',
        AWAITING_UNPUBLISHING: 'Queue for unpublishing',
        UNPUBLISHED: 'Unpublish',
        ARCHIVED: 'Delete',
        AWAITING_ARCHIVING: 'Delayed archivation',
      },
      learningpath_statuses: {
        private: 'Draft',
        published: 'Public',
        unlisted: 'Link shared',
        submitted: 'Requested publication',
      },
    },
    validDate: {
      label: 'Valid date',
      from: {
        label: 'Valid from',
        placeholder: 'From date',
      },
      to: {
        label: 'Valid to',
        placeholder: 'To date',
      },
    },
    content: {
      label: 'Content',
      placeholder: 'Write here...',
      figure: {
        notSupported: 'Media type {{mediaType}} is not supported.',
        confirmDelete: 'Are you sure that you will delete this figure?',
      },
      relatedArticle: {
        placeholder: 'Search for title',
        urlPlaceholder: 'Url',
        titlePlaceholder: 'Title',
        urlLocation: 'Webpage at {{domain}}',
        invalidArticle: 'Invalid article',
        addExternal: 'Add external article',
        removeExternal: 'Delete external article',
        changeExternal: 'Edit external article',
        searchExternal: 'Write the title and url of the external article',
      },
      concept: {
        remove: 'Remove concept',
        choose: 'Choose concept',
      },
      link: {
        goTo: 'Go to',
        insert: 'Insert link',
        update: 'Update link',
        change: 'Change',
        remove: 'Remove link',
        href: 'Link',
        newTab: 'Open link in new tab',
        text: 'Text',
        addTitle: 'Add link',
        changeTitle: 'Change link',
        required: 'Link is required',
        invalid: 'Invalid link',
        preview: 'Preview link',
        unSupported: 'Content in link is not supported',
        newUrlResource: 'New resource',
        changeUrlResource: 'Edit resource: {{type}}',
        description:
          'Links to ndla-resources are handled by the system and are displayed correct on {{url}}. Ndla-resources are shown with blue background and external links with yellow.',
      },
      footnote: {
        title: 'Title',
        year: 'Year',
        authors: {
          label: 'Author',
          description: 'Required with at least one author.',
          createOption: 'Create new author',
        },
        edition: 'Edition',
        publisher: 'Publisher',
        addTitle: 'Add footnote',
        editTitle: 'Edit footnote',
        removeFootnote: 'Remove footnote',
      },
      table: {
        'row-remove': 'Remove row',
        'row-add': 'Add row',
        'column-add': 'Add column',
        'column-remove': 'Remove column',
        'table-remove': 'Remove table',
      },
    },
    tags: {
      label: 'Tags',
      helpLabel: 'What is a tag?',
      description: '3 tags is required.',
      createOption: 'Create new tag',
      searchPlaceholder: 'Search for tags',
    },
    categories: {
      label: 'List and filters',
      description: 'Format: list:filter1:filter2',
      searchPlaceholder: 'Search for lists',
    },
    grepCodes: {
      label: 'Competences and core elements',
      placeholder: 'Type code',
      description:
        'Type in codes using the format K(E/M) or TT followed by one or more digits. Ex. KE137, KM2255, TT2. Non existing codes will not be created. Separate multiple codes with comma. Texts will be displayed in norwegian here but will be shown correct in frontend.',
    },
    resourceTypes: {
      label: 'Resource type and properties',
      placeholder: 'Add property',
    },
    subjects: {
      label: 'Subjects',
      searchPlaceholder: 'Search for subjects',
      placeholder: 'Add subjects',
    },
    topics: {
      label: 'Topics',
      placeholder: 'Add topic',
      primaryTopic: 'Primary topic',
      sharedTopic: 'Shared topic',
      setPrimaryTopic: 'Set as primary topic',
      RGTooltip: 'Choose between Core(K) or Supplementary(T)',
    },
    metaDescription: {
      label: 'Meta description',
      helpLabel: 'What is a meta description?',
      description: 'The description will be viewable in search.',
    },
    agreement: {
      label: 'Connect to agreement',
      helpLabel: 'What is an agreement?',
      placeholder: 'Search for agreement',
    },
    rightsholders: {
      label: 'Rightsholder',
      labelRemove: 'Remove',
      placeholder: 'Type name of rightholder',
      createOption: 'Add new rightsholder',
    },
    processors: {
      label: 'Processor',
      labelRemove: 'Remove',
      placeholder: 'Type name of processor',
      createOption: 'Add new processor',
    },
    creators: {
      label: 'Creator',
      labelRemove: 'Remove',
      placeholder: 'Type name of creator',
      createOption: 'Add new creator',
      description: 'Required with at least one creator.',
    },
    license: {
      label: 'License',
      helpLabel: 'What is a license?',
      choose: 'Choose a license',
    },
    origin: {
      label: 'Origin',
    },
    caption: {
      label: 'Caption',
      placeholder: 'Caption',
    },
    image: {
      file: 'Image',
      save: 'Save image',
      editImage: 'Edit image',
      removeImage: 'Remove image',
      alignment: {
        left: 'Left aligned',
        right: 'Right aligned',
        center: 'Large centered',
      },
      sizes: {
        xsmall: 'Size: Tiny',
        small: 'Size: Small',
        medium: 'Size: Medium',
        fullwidth: 'Size: Large',
      },
      crop: 'Crop image',
      focalPoint: 'Set focalpoint',
      alt: {
        label: 'Alt-text',
        placeholder: 'Alt-text',
        noText: 'WCAG requires alt-text.',
      },
      caption: {
        label: 'Image caption',
        placeholder: 'Image caption',
      },
      dragdrop: {
        main: 'Drag and drop',
        sub: 'or click to upload image',
        ariaLabel: 'Drag and drop or click to upload image',
      },
      byline: {
        show: 'Show byline',
        hide: 'Hide byline',
      },
    },
    video: {
      caption: {
        label: 'Video caption',
        placeholder: 'Video caption',
      },
      remove: 'Remove video',
      save: 'Save video',
      time: {
        start: 'Start',
        stop: 'Stop',
        hms: 'h:m:s',
      },
      brightcove: 'Open in Brightcove',
      toLinkedVideo: 'Switch to interpreted video',
      fromLinkedVideo: 'Switch back to original video',
      linkedVideoButton: 'IV',
    },
    audio: {
      file: 'Audio file',
      title: {
        label: 'Audio title',
        placeholder: 'Audio title',
      },
      manuscript: 'Text version',
      caption: {
        label: 'Audio caption',
        placeholder: 'Audio caption',
      },
      remove: 'Remove audio',
      sound: 'Audio',
      speech: 'Speech',
      dragdrop: {
        main: 'Drag and drop',
        sub: 'or click to upload image',
        ariaLabel: 'Drag and drop or click to upload image',
      },
    },
    podcast: {
      remove: 'Remove podcast',
    },
    external: {
      title: 'external',
      edit: 'Edit {{type}} element',
      remove: 'Remove {{type}} element',
    },
    related: {
      title: 'Related content',
      subtitle: 'Drag article to change the order',
      showMore: 'Show more related content',
      showLess: 'Show less',
    },
    file: {
      label: 'Files',
      file: {
        label: 'File',
      },
      alt: {
        label: 'Alt text',
        placeholder: 'Alt text',
      },
      download: 'Download:',
      title: {
        label: 'File title',
        placeholder: 'File title',
      },
      addFile: 'Add file',
      removeList: 'Remove file list',
      placeholder: 'Filename',
      changeName: 'Change name',
      changeOrder: 'Change the order',
      removeFile: 'Remove file',
      missingFileTooltip:
        'This file does not seem to exist on the server. It might have been deleted from another article.',
      missingFilename: 'File type is not supported',
      dragdrop: {
        main: 'Drag and drop',
        sub: 'or click to upload file(s)',
        ariaLabel: 'Drag and drop or click to upload file(s)',
        noFilesAdded: 'No files are added',
      },
      showPdf: 'Show expanded',
      showPdfTooltip: 'Show expanded PDF in article',
    },
    article: {
      label: 'Article',
      add: 'Add article',
    },
    learningpathConnections: {
      sectionTitle: 'Uses of the article in learningpaths',
      title: 'Learningpaths containing this article',
    },
    embedConnections: {
      type: {
        image: 'image',
        audio: 'audio file',
      },
      sectionTitleArticle: 'Articles containing the {{resource}}',
      sectionTitleConcept: 'Concepts containing the {{resource}}',
      title: 'Uses of the {{resource}}',
      info: {
        image: 'Uses of the image in articles and/or concepts',
        audio: 'Uses of the audio file in articles',
      },
      notInUse: 'No uses of the {{resource}} in articles and/or concepts were found',
      articles: '1 article',
      articles_plural: '{{count}} articles',
      concepts: '1 concept',
      concepts_plural: '{{count}} concepts',
    },
    relatedConcepts: {
      placeholder: 'Search for title',
      articlesTitle: 'Concepts',
      changeOrder: 'Change order',
      removeArticle: 'Remove concept',
    },
    relatedContent: {
      placeholder: 'Search for title',
      articlesTitle: 'Content',
      changeOrder: 'Change order',
      removeArticle: 'Remove content',
      addExternal: 'Add external article',
      link: {
        missingTitle: 'Missing title',
        missingUrl: 'Url must start with http:// or https://',
        titlePlaceholder: 'Title',
        urlPlaceholder: 'https://example.com',
        addLink: 'Add',
      },
    },
    section: {
      remove: 'Remove section',
    },
  },
  validation: {
    isRequired: '{{label}} is required.',
    isNumeric: '{{label}} must contain digits.',
    bothFields: 'One {{labelLowerCase}} must contain all fields.',
    url: '{{label}} must contain a valid link.',
    urlOrNumber: '{{label}} must contain a valid link or article-id.',
    dateBeforeInvalid: '{{label}} can not be after {{afterLabel}}.',
    dateAfterInvalid: '{{label}} can not be before {{beforeLabel}}.',
    maxLength: '{{label}} must not have more than {{maxLength}} characters.',
    minLength: '{{length}} must have at least {{minLength}} characters.',
    minItems: '{{label}} must have at least one {{labelLowerCase}}.',
    minItems_plural: '{{label}} must have at least {{count}} unique {{labelLowerCase}}.',
    noEmptyNote: 'A note cannot be empty',
    grepCodes:
      'The code format is wrong. The correct format is K(E/M) or TT followed by one or more digits. Ex. KE137, KM2255, TT2.',
    podcastImageShape: 'A meta image must have equal height and width.',
    podcastImageSize: 'A meta image must be between 1400 and 3000 pixels wide.',
  },
  errorMessage: {
    title: 'Oops, something went wrong',
    description: 'Sorry, an error occurd.',
    back: 'Back',
    goToFrontPage: 'Go to frontpage',
    invalidUrl: 'Invalid url',
    noArticleInProd: 'No article found in prod',
    taxonomy: 'There was a problem loading taxonomy',
    unsavedTaxonomy:
      'You have unsaved changes. Press cancel again if you are sure you want to continue.',
    auth0:
      'Authentication error. Press cancel to take care of any changes you have made before logging in again. The following error message came from auth0: {{message}}',
    statusCode: {
      409: 'This article has already been updated. Keep what you have changed and reload the page to save.',
    },
    grepCodes: 'The following codes have wrong format or does not exist, and will not be added: ',
  },
  notFound: {
    description: 'The page cannot be found',
  },
  forbiddenPage: {
    description: 'You do not have access to this page',
  },
  alertModal: {
    notSaved: 'Document is not saved, do you want to continue?',
    needToRefresh:
      'Someone have saved the same article while you were editing. You need to copy your changes manually and refresh the page',
    continue: 'Continue',
    delete: 'Delete',
    confirm: 'Confirm',
    loginAgain: 'Login again',
  },
  taxonomy: {
    editStructure: 'Edit structure',
    editSubjectpage: 'Edit subjectpage',
    addSubject: 'Add new subject',
    addExistingTopic: 'Move existing topic here',
    newSubject: 'New Subject',
    existingTopic: 'Existing topic',
    newTopic: 'New topic',
    resources: 'Resources',
    errorMessage: 'An error occurred',
    addTopic: 'Add topic',
    changeName: 'Change name',
    topicSettings: 'Topic settings',
    subjectSettings: 'Subject settings',
    linkSettings: 'Link',
    setPrimary: 'Set as primary link',
    addResource: 'Add resource',
    removeResource: 'Remove resource from topic',
    searchResource: 'Search for resource',
    searchArticle: 'Search for topic article',
    confirmDeleteTopic: 'Are you sure you want to delete this topic?',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Note! This is a different resource type: ',
    noResources: 'No resources found',
    addTopicDescription: 'Change topic description',
    confirmSetPrimary: 'Do you want to make this the main location?',
    removeLink: 'Remove link',
    jumpToResources: 'Jump to resources',
    copyResources: 'Reuse resources from topic',
    copyAndCloneResources: 'Copy and clone resources from topic',
    favorites: 'Show favorites',
    publish: {
      button: 'Publish all',
      waiting: 'Publishing resourses',
      done: 'Resources published',
      error: 'The following resources were not published:',
    },
    info: {
      title: 'Information',
      subTitle: 'Id and visibility for the element',
    },
    resource: {
      confirmDelete:
        'Do you want to delete the resource from this folder? This will not affect the placement other places',
      copyError:
        'An error occurred while copying resources. Double check the copied resources and try to fix deficiencies manually, or delete the copied resources and try to copy again',
      addResourceConflict: 'The resource you attempted to add already exists on the topic.',
    },
    resourceTypes: {
      title: 'Content type',
      subTitle: 'What content type does this resource have?',
      placeholder: 'Select content type',
    },
    topics: {
      title: 'Topic connections',
      topicPlacement: 'Topcic placement',
      subTitle: 'Where in the taxonomy should this resource be?',
      subTitleTopic: 'Where in the taxonomy should the topic description be?',
      filestructureButton: 'Create a topic connection',
      filestructureHeading: 'Select a topic connection',
      filestructureClose: 'Close',
      addNewTopic: 'Add new topic',
      addNewSubTopic: 'Add new sub topic',
      addedTopic: 'Added to taxonomy',
      disconnectedTaxonomyWarning: 'Invalid topic connection',
    },
    grepCodes: {
      edit: 'Edit grep codes',
      empty: 'No existing grep codes',
      addNew: 'Add new grep code',
    },
    missingResourceType: 'Missing resource type',
    metadata: {
      customFields: {
        alterFields: 'Add/change metadata',
        addField: 'New metadata field',
        languagePlaceholder: 'Ndla.no interface language',
        explanationSubject: 'Explanation Subject',
        resourceGroupPlaceholder: 'Grouping of resources',
        RGTooltip: 'Show resources Grouped or Ungrouped',
      },
    },
  },
  notions: {
    edit: 'Edit notions',
    closeNotion: 'Close notion dialog',
  },
  contextTypes: {
    topic: 'Topic',
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: 'Slideshow',
      slideshowTitle: 'Movies on slideshow',
      slideshowSubTitle: 'on frontpage',
      movieGroupHeader: 'Movies themes',
      addMovieToSlideshow: 'Add movie to slideshow',
      addMovieToGroup: 'Add a movie to "{{name}}"',
      editMovieGroupName: 'Change the names on this movie group',
      deleteMovieGroup: 'Delete "{{name}}"',
      moveMovieGroupUp: 'Move up',
      moveMovieGroupDown: 'Move down',
      changeOrder: 'Change order',
      removeMovieFromGroup: 'Remove movie from group',
      removeMovieFromSlideshow: 'Remove movie from slideshow',
      createThemeGroup: 'Create new movie group',
      saveNameChanges: 'Save changes',
      cancel: 'Cancel',
      editGroupTitle: 'Change the name(s) in this movie group:',
      newGroupTitle: 'What shall we call the new movie group?',
      notFound: 'We can not find metadata for this movie...',
    },
  },
  modal: {
    closeModal: 'Close',
  },
  conceptform: {
    title: 'Concept',
  },
  editorFooter: {
    buttonLabel: 'Quality ensurance',
    heading: 'Quality ensurance:',
    changeStatus: 'Change status',
    back: 'Go back',
    inputHeader: 'Your note',
    inputHelperText: 'Short note',
    cancelLabel: 'Cancel',
    saveLabel: 'Change status and save draft',
    warningSaveWithoutComment: 'Note is missing',
    newStatusPrefix: 'New status:',
    statusLabel: 'Status:',
    changeHeader: 'Changes',
    saveAsNew: 'Save as copy',
  },
  metadata: {
    visible: 'is visible',
    notVisible: 'is not visible',
    changeVisibility: 'Change visibility',
  },
};

export default phrases;
