/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = "- Production system - NDLA";

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Learning resource ${titleTemplate}`,
    createTopicArticlePage: `Topic ${titleTemplate}`,
    createSubjectpage: `Subjectpage ${titleTemplate}`,
    createFrontPageArticePage: `About-NDLA article ${titleTemplate}`,
    agreementPage: `Agreement ${titleTemplate}`,
    welcomePage: `Frontpage ${titleTemplate}`,
    structurePage: `Structure ${titleTemplate}`,
    programmePage: `Programmes ${titleTemplate}`,
    versionsPage: `Versions ${titleTemplate}`,
    audioUploaderPage: `Audio ${titleTemplate}`,
    imageUploaderPage: `Image ${titleTemplate}`,
    loginPage: `Login ${titleTemplate}`,
    logoutPage: `Logout ${titleTemplate}`,
    ndlaFilmPage: `NDLA Film ${titleTemplate}`,
    podcastUploaderPage: `Podcast episode ${titleTemplate}`,
    podcastSeriesPage: `Podcast series ${titleTemplate}`,
    h5pPage: `H5P ${titleTemplate}`,
    nodeDiffPage: `Compare Nodes ${titleTemplate}`,
    editFrontpage: "Edit front page",
    comparePage: `Compare versions ${titleTemplate}`,
    notFoundPage: `Not found ${titleTemplate}`,
    search: {
      "podcast-series": `Search podcast series ${titleTemplate}`,
      audio: `Search audio files ${titleTemplate}`,
      concept: `Search concepts ${titleTemplate}`,
      content: `Search content ${titleTemplate}`,
      image: `Search images ${titleTemplate}`,
    },
    learningpath: {
      new: `Create learning path ${titleTemplate}`,
      edit: `Edit learning path ${titleTemplate}`,
      preview: `Preview learning path ${titleTemplate}`,
      stepSamples: `External learning step samples ${titleTemplate}`,
    },
  },
  meta: {
    description: "Norwegian Digital Learning Arena, Open Educational Resources",
  },
  menu: {
    title: "Menu",
  },
  dropdown: {
    numberHits: `Search returned {{hits}} hits`,
    searching: "Searching...",
    create: "Create new",
    isSelectedItem: "Added",
  },
  dialog: {
    close: "Close",
    title: "Title",
    audio: {
      rulesForUse: "Rules for use of audio",
    },
    learnAboutLicenses: "Learn more about open licenses",
    source: "Source",
  },
  license: {
    heading: "Howto reuse content",
    tabs: {
      text: "Text",
      images: "Images",
      audio: "Audio",
      video: "Video",
    },
    images: {
      heading: "How to use images from the article",
      description: "Remember to copy the text to be attached to the image where you use it.",
      rules: "Rules for use of image:",
      source: "Source",
      title: "Title",
    },
    text: {
      heading: "How to use text from the article",
      description: "The article may be composed of several different texts, which are listed here.",
      rules: "Rules for use of text:",
      published: "Published",
    },
    audio: {
      heading: "How to use audio files from the article",
      description: "Remember to copy the text to be attached to the audio where you use it.",
      rules: "Rules for use of audio file:",
    },
    video: {
      heading: "How to use videos from the article",
      description: "Remember to copy the text to be attached to the video where you use it.",
      rules: "Rules for use of audio file:",
    },
    learnMore: "Learn more about open licenses",
    copyTitle: "Copy reference",
    embed: "Embed",
    embedCopied: "Copied embed code!",
    hasCopiedTitle: "Copied!",
    download: "Download",
  },
  languages: {
    // Adds to list from frontend-packages
    ar: "Arabic",
    la: "Latin",
    no: "Norwegian",
    so: "Somali",
    ti: "Tigrinya",
    und: "Undetermined",
    ukr: "Ukranian",
    prs: "Dari",
    san: "Sanskrit",
    heb: "Hebrew",
    pli: "Pali",
    change: "Change to {{language}} version",
    none: "Language",
  },
  // WARNING: Some of these symbols contain special unicode characters that look like normal characters.
  // Make sure not to accidentally change them!
  symbols: {
    "½": "One half",
    "¼": "One quarter",
    "¾": "Three quarters",
    "²": "Squared",
    "³": "Cubed",
    "©": "Copyright",
    "™": "Trademark",
    "°": "Degrees",
    "¥": "Yen",
    "‑": "Hard hyphen",
    "–": "N-dash",
    " ": "Non breaking space",
    "§": "Section",
    "¿": "Inverted questionmark",
    α: "Alpha",
    β: "Beta",
    γ: "Gamma",
    "±": "Plus/minus",
    "→": "Right arrow",
  },
  welcomePage: {
    lastFavorited: "Last favorited resource: ",
    addSearch: "Add new search",
    deleteSavedSearch: "Delete saved search",
    noHitsSavedSearch: "No hits in your saved searches",
    deleteSearch: "Delete search",
    noArticles: "Empty resource list ...",
    emptyLastUsed: "Empty last edited list ...",
    emptyConcepts: "Empty concept list ...",
    emptyRevision: "No matching resources that need revision ...",
    emptySavedSearch: "No saved searches",
    guidelines: "Guidelines",
    mustBeSearch: "Link must be a search url",
    lastUsed: "Last edited",
    lastUsedDescription: "Your recently edited resources",
    lastUsedConcepts: "Your recently edited concepts",
    savedSearch: "Saved searches",
    saveSearch: "Save search",
    chooseSubject: "Choose subjects",
    chooseFavoriteSubject: "Choose favorite subjects",
    chooseTopic: "Choose topics",
    errorMessage: "Failed to retrieve data",
    goToSearch: "Go to search",
    revision: "Revision",
    revisionDescription: "Resources with a revision date within 365 days",
    revisionDate: "Revision date",
    welcomeText: "to ED",
    updated: "Updated",
    primaryConnection: "Only show resources with primary connection to my favorite subjects",
    primaryConnectionLabel: "Only show primary connection",
    prioritizedLabel: "Only show prioritized",
    lmaSubjects: "LMA-subjects",
    daSubjects: "DA-subjects",
    saSubjects: "SA-subjects",
    favoriteSubjects: "Favorite subjects",
    lmaSubjectsHeading: "Production flow in LMA-subjects",
    daSubjectsHeading: "Production flow in DA-subjects",
    saSubjectsHeading: "Production flow in SA-subjects",
    favoriteSubjectsHeading: "Production flow in favorite subjects",
    lmaSubjectsDescription: "Distribution of where resources in your LMA-subjects is in the workflow",
    daSubjectsDescription: "Distribution of where resources in your DA-subjects is in the workflow",
    saSubjectsDescription: "Distribution of where resources in your SA-subjects is in the workflow",
    favoriteSubjectsDescription:
      "Distribution of where resources in your favorite subjects is in the workflow. Archived subjects are not included",
    noResultsLMASubjects: "The following statuses will not be shown",
    count: "Count",
    countResponsible: "Responsible count",
    pagination: {
      resources: "resources",
      concepts: "concepts",
      workList: "Pages containing {{ resourceType }} where you are responsible",
      lastUsed: "Pages containing your last edited {{ resourceType }}",
      revisionView: "Pages containing expiring resources for your {{ group }}",
      subjectView: "Pages containing statistics for your {{ group }}",
    },
    workList: {
      heading: "My tasks",
      description: "Resources where you are responsible",
      title: "Title",
      status: "Status",
      contentType: "Content type",
      primarySubject: "Primary subject",
      topicRelation: "Topic relation",
      date: "Assigned",
      ariaLabel: "Overview of my tasks and concepts",
      conceptDescription: "Concepts where you are responsible",
      conceptSubject: "Concept subject",
      sortAsc: "Sort ascending",
      sortDesc: "Sort descending",
      pickPageSize: "Choose the number of rows",
      numberOfRows: "Number of rows",
      onHold: "On hold",
      onHoldHeading: "Resources on hold",
      onHoldDescription: "Resources on hold where you are responsible",
      onHoldFilter: "Do not count on hold",
      loading: "Loading...",
    },
    subjectView: {
      lma: "Subject view LMA-subjects",
      da: "Subject view DA-subjects",
      sa: "Subject view SA-subjects",
      favorites: "Subject view favorite subjects",
      description: "Overview of statistics related to resources in your subjects",
      heart: "Hearts",
      heartDescription: "Number of favorited resources",
      flow: "In flow",
      flowDescription: "Number of resources in flow",
      old: "Outdated",
      oldDescription: "Number of resources that have not been revised in over 5 years",
      revision: "Revisions",
      revisionDescription: "Number of resources with expired revision date",
      published: "Published",
      publishedDescription: "Number of published resources",
    },
    revisionView: {
      lma: "Revisions in LMA subjects",
      sa: "Revisions in SA subjects",
      da: "Revisions in DA subjects",
      favorites: "Revisions in favorite subjects",
    },
    welcomeBack: "Welcome",
    listLabels: {
      worklist: "Resource types",
      lastUsed: "Resource types",
      subjectView: "Subject types",
      revisionView: "Subject types",
      articleStatuses: "Subject types",
    },
  },
  updateCodesPage: {
    title: "Update curriculum codes",
    description:
      "Convert grep-codes from outdated curricula to the corresponding grep-codes for new curricula. This updates all articles that have associated competency goals and core elements from outdated curricula, in both published and unpublished versions. The articles do not need to be modified afterward for the new grep-codes to become visible.",
    buttonText: "Update",
    error: "Something went wrong while updating grep-codes",
  },
  searchPage: {
    search: "Søk",
    header: {
      content: "Search for content",
      audio: "Search for audio files",
      image: "Search for images",
      concept: "Search for concepts",
      "podcast-series": "Search for podcast series",
    },
    activeFilters: "Active filters",
    searchButton: "Search",
    emptyButton: "Empty",
    title: "Title",
    language: "Language",
    contentNoHits: "Your search - {{query}} - did not match any content.",
    "podcast-seriesNoHits": "Your search - {{query}} - did not match any content.",
    conceptNoHits: "Your search - {{query}} - did not match any concept.",
    audioNoHits: "Your search - {{query}} - did not match any audio files.",
    imageNoHits: "Your search - {{query}} - did not match any images.",
    pageSize: "{{pageSize}} hits per page",
    hitsSelectLabel: "Number of hits per page",
    totalCount: "Total results",
    highlights: {
      title: "Search hits",
      content: "Search hits from content",
      tags: "Search hits from tags",
      embedAttributes: "Search hits from embedded elements",
      notes: "Search hits from version log",
      previousVersionsNotes: "Search hits from version log",
    },
    save: {
      alreadyExist: "Search has already been saved.",
      fetchFailed: "Could not get load saved searches.",
      other: "Save failed.",
    },
  },
  taxonomyResourceType: {
    resource: "Resource",
    topic: "Topic",
  },
  articleType: {
    "topic-article": "Topic",
    "frontpage-article": "About-NDLA article",
    standard: "Subject matter",
  },
  subNavigation: {
    listTitle: {
      create: "Create",
      edit: "Edit",
      admin: "Admin",
      external: "External systems",
    },
    media: "Media",
    learningPath: "Learningpath",
    learningPathLink: "Learningpaths",
    brightcoveLink: "Brightcove",
    detailSearch: "Detail search",
    learningResource: "Learning resource",
    image: "Image",
    audio: "Audio file",
    podcast: "Podcast episode",
    podcastSeries: "Podcast series",
    agreement: "New Agreement",
    structure: "Structure",
    programme: "Programmes",
    taxonomyVersions: "Taxonomy Versions",
    searchContent: "Search content",
    searchAudio: "Search audio",
    searchPodcastSeries: "Search series",
    searchImage: "Search image",
    searchConcepts: "Search concepts",
    film: "NDLA film",
    h5p: "Edlib H5P",
    newConcept: "Concept",
    newGloss: "Gloss",
    newSubject: "Create new subject",
    newFrontpageArticle: "About-NDLA article",
    frontpage: "NDLA frontpage",
    updateCodes: "Update curriculum codes",
    learningStepSamples: "External learning step samples",
  },
  logo: {
    altText: "The Norwegian Digital Learning Arena",
  },
  siteNav: {
    chooseSubject: "Choose Subject",
    search: "Search",
    login: "Login",
  },
  loginFailure: {
    errorMessage: "Sorry. Login failed.",
    loginLink: "Click to try again.",
    userNotRegistered: "We did not recognize your email address. Did you use the correct email address?",
  },
  loginProviders: {
    description: "Log in with",
  },
  logoutProviders: {
    localLogout: "Log out from production system",
    or: "eller",
    federatedLogout: "Log out of all providers",
    description: "N.B. All providers include the identityprovider (Google or Facebook).",
  },
  searchForm: {
    placeholder: "Search articles",
    searchTypes: "Search types",
    types: {
      conceptQuery: "Search for concept",
      glossQuery: "Search for gloss",
      contentQuery: "Search for content",
      audioQuery: "Search for audio files",
      "podcast-seriesQuery": "Search for podcast series",
      imageQuery: "Search for images",
      language: "Select language",
      users: "Select editor",
      "model-released": "Select model released",
      subjects: "Select subject",
      "resource-types": "Select resource type",
      status: "Select status",
      "draft-status": "Select status",
      "audio-type": "Select audio file type",
      "concept-type": "Select concept type",
      license: "Select license",
      "revision-date-from": "Revisiondate from",
      "revision-date-to": "Revisiondate to",
      "exclude-revision-log": "Exclude revision log",
      "responsible-ids": "Select responsible",
      "filter-inactive": "Include archived subjects",
    },
    tagType: {
      query: "Search:",
      subjects: "Subject: {{value}}",
      language: "Language: $(languages.{{value}})",
      users: "Editor: {{value}}",
      "resource-types": "Resource type: {{value}}",
      status: "Status: $t(form.status.{{value}})",
      "draft-status": "Status: $t(form.status.{{value}})",
      "audio-type": "Audio file type: {{value}}",
      "concept-type": "Concept type: {{value}}",
      license: "License: {{value}}",
      "model-released": "Model released: {{value}}",
      "revision-date-from": "Revisiondate from: {{value}}",
      "revision-date-to": "Revisiondate to: {{value}}",
      "exclude-revision-log": "Revision log excluded",
      "responsible-ids": "Responsible: {{value}}",
      "filter-inactive": "Archived subjects included",
      inactive: "Showing {{value}} images",
    },
    btn: "Search",
    empty: "Empty",
    articleType: {
      all: "All",
      standard: "Standard",
      learningResource: "Learning resource",
      topicArticle: "Topic description",
      image: "Image",
      audio: "Audio",
    },
    audioType: {
      standard: "Audio",
      podcast: "Podcast",
    },
    conceptType: {
      concept: "Concept",
      gloss: "Gloss",
    },
    order: "Rekkefølge",
    asc: "Ascending",
    desc: "Descending",
    sorting: "Sorting",
    sort: {
      id: "Id",
      relevance: "Relevance",
      title: "Title",
      lastUpdated: "Last updated",
      revisionDate: "Next revision",
      favorited: "Favorite marks",
      published: "Last revised",
    },
    resultError: "Something went wrong with type: {{type}}",
    favourites: "My favourite subjects",
    LMASubjects: "My LMA-subjects",
    SASubjects: "My SA-subjects",
    DASubjects: "My DA-subjects",
    archivedIncluded: "Archived subjects included",
    error: "Something went wrong with the search",
    conceptSubject: "Concept subject: {{name}}",
    multiTaxonomy: "{{count}} placements in taxonomy",
  },
  subjectsPage: {
    subjects: "Subjects",
  },
  subjectPage: {
    topics: "Topics",
  },
  editMarkup: {
    linkTitle: "Go to HTML editor",
    title: "HTML editor",
    previewDialogTitle: "Preview article",
    subTitle: "Edit article with HTML",
    back: "Back",
    fetchError: "An error occurred while loding an article into the HTML editor. Go back or try to reload the page.",
    saveError: "An error occurred while saving article changes.",
    helpMessage: {
      tooltip: "About the HTML editor",
      paragraph1:
        "It is possible to format the HTML code by pressing F1 and then selecting Format. Note that this could lead to changes in whitespace (indentations, linebreaks and spaces) when saving. Feel free to use the preview feature rapidly. Saving using ctrl+s also works.",
      paragraph2:
        "To minimize potential problems with formatting and to secure consistent HTML, the same transformations as in the regular editor is applied. This means that illegal code is attempted to be corrected. Linebreaks are removed when saving and are therefore ignored",
    },
  },
  imageSearch: {
    modelReleased: {
      yes: "Model released",
      no: "Not model released",
      "not-applicable": "Not applicable",
      "not-set": "Not set",
    },
    inactive: {
      false: "Active",
      true: "Inactive",
    },
    placeholder: "Search images",
    buttonTitle: "Search",
    useImage: "Use image",
    metaImageCheckboxLabel: "Set as meta image",
    visualElementCheckboxLabel: "Set as visual element",
    noTitle: "No title",
    noResultsText: "No images found. Would you like to upload a new image?",
    noResultsButtonText: "Upload image",
  },
  videoSearch: {
    searchPlaceholder: "Search videos",
    searchButtonTitle: "Search",
    loadMoreVideos: "Load more videos",
    noResults: "No videos found",
    addVideo: "Use video",
    previewVideo: "Preview",
    publishedDate: "Published date",
    duration: "Duration",
    interactioncount: "Views",
    is360Video: "VR video",
  },
  mathEditor: {
    editMath: "Edit Math",
    preview: "Preview",
    continue: "You might have unsaved changes in the math editor. Do you want to continue?",
  },
  code: {
    continue: "You might have unsaved changes in the code editor. Do you want to continue?",
  },
  h5pElement: {
    fetchError: "Sorry, an error occurd while loading the H5P client.",
  },
  displayOembed: {
    errorMessage: "An error occurd when displaying oEmbed.",
    notSupported: "oEmbed of type {{type}} and provider {{provider}} is not supported.",
  },
  audioSearch: {
    searchPlaceholder: "Search in audio files",
    searchButtonTitle: "Search",
    useAudio: "Chose audio",
    noResults: "No audio files found",
    noTitle: "No title",
  },
  conceptSearch: {
    searchPlaceholder: "Search in concepts",
    searchButtonTitle: "Search",
    noResults: "No concepts found",
    noTitle: "No title",
    noContent: "No content",
    listLabel: "Options",
  },
  searchTypes: {
    content: "Content",
    audio: "Audio",
    image: "Image",
    concept: "Concepts",
    "podcast-series": "Series",
  },
  noEmbedMessage: {
    deleteOnSave: "Element of type {{type}} will be deleted on save.",
  },
  conceptpageForm: {
    articlesTitle: "Related Articles",
    articlesSubtitle: "Articles",
    changeOrder: "Change order",
    removeArticle: "Remove article",
  },
  subjectpageForm: {
    title: "Subject",
    about: "About subject",
    description: "Description",
    metadata: "Metadata",
    addBanner: "Choose banner image",
    changeBanner: "Change banner image",
    editorsChoices: "Editor choices from the subject",
    articles: "Articles",
    addArticle: "Add article",
    removeArticle: "Remove article",
    missingVisualElement: "Visual element is required",
    subjectlinks: "Subject links",
    addSubject: "Add subject",
    moveSubject: "Drag and drop",
    removeSubject: "Remove subject",
    connectedTo: "Common programme subject with",
    buildsOn: "Builds on",
    leadsTo: "Leads to",
  },
  programmepageForm: {
    title: "Programme",
  },
  topicArticleForm: {
    visualElementTitle: {
      image: "Image title",
      video: "Video title",
      brightcove: "Video title",
      external: "Content title",
      h5p: "H5P title",
    },
    visualElementCopyright: "Origin",
    removeVisualElement: "Remove element",
    info: {
      lastUpdated: "Last revised",
    },
    title: "Topic",
    fields: {
      caption: {
        label: {
          image: "Video caption",
          brightcove: "Video caption",
          external: "Content caption",
        },
        placeholder: {
          image: "Image caption",
          brightcove: "Video caption",
          external: "Content caption",
        },
      },
      alt: {
        label: "Alt-text",
        placeholder: "Alt-text",
      },
    },
    validation: {
      containsContent: "Only topics in multidisciplinary subjects (case) can have text in the content field.",
      illegalResource: "Topic articles should only have image as visual element.",
    },
  },
  agreementForm: {
    title: {
      create: "Agreement",
      update: "Agreement",
    },
    fields: {
      title: {
        label: "Agreement title",
        placeholder: "Agreement title",
      },
      content: {
        label: "Agreement content",
        placeholder: "Agreement content",
      },
    },
  },
  footnoteForm: {
    title: "Title",
    year: "Year",
    authors: "Author",
  },
  linkForm: {
    href: "Link",
    text: "Text",
  },
  audioForm: {
    title: "audio file",
  },
  podcastSeriesForm: {
    title: "Podcast series",
    alreadyPartOfSeries: "Part of another series",
    description: "Description",
    rss: "Rss feed",
    adminError: "You don't have access to create or update podcast series.",
    hasRSS: "Activate RSS-feed for this series",
  },
  podcastForm: {
    title: "Podcast episode",
    fields: {
      header: "Header",
      introduction: "Introduction",
      coverPhoto: "Image",
      coverPhotoAltText: "Alt-text",
      manuscript: "Text version",
      series: "Series",
    },
    information: {
      partOfSeries: "This podcast is a part of the series",
      removeSeries: "Remove Series",
      noSeries: "This podcast is not a part of any series",
    },
  },
  imageEditor: {
    editImage: "Edit image",
    remove: {
      crop: "Remove crop",
      focalPoint: "Remove focal point",
    },
  },
  imageForm: {
    title: "Image",
    copyImageTitle: "Upload image as copy",
    copyDescription: "Upload an image with the same information as the current image",
    fields: {
      inactive: {
        label: "Inactive",
      },
    },
  },
  contactBlockForm: {
    title: "Contact block",
    edit: "Edit contact block",
    delete: "Remove contact block",
    background: {
      subtle: "Subtle",
      moderate: "Moderate",
      strong: "Strong",
    },
  },
  frontpageArticleForm: {
    title: "About-NDLA article",
    validation: {
      illegalSlug: "Use of illegal characters in permalink! Legal characters are numbers and letters, plus dashes.",
    },
    isFrontpageArticle: {
      toggleArticle: "Wide editor",
    },
  },
  gridForm: {
    title: "Grid",
    background: {
      white: "White",
      transparent: "Transparent",
      gray: "Gray",
    },
    setSticky: "Lock content to adjacent grid cell",
    unsetSticky: "Unlock content from adjacent grid cell",
  },
  gridCellForm: {
    edit: "Edit grid cell",
  },
  pitchForm: {
    title: "Edit pitch",
    languageExplanation: "Choose language for screen readers",
    sizes: {
      normal: "Normal",
      large: "Large",
    },
  },
  learningResourceForm: {
    metaImage: {
      title: "Image title",
      copyright: "Copyright",
      change: "Change meta image",
    },
    title: "Learning resource",
    validation: {
      missingEmbedData: "One or more included video, image, or audio elements is missing caption or alternative text.",
    },
    fields: {
      footnotes: {
        edition: "Edition",
        publisher: "Publisher",
      },
    },
  },
  keyFigureForm: {
    title: "Key figure",
    edit: "Edit key figure",
  },
  qualityEvaluationForm: {
    title: "Quality evaluation",
    unavailable: "Not specified",
    dialogTitle: "Update quality evaluation",
    description:
      "Provide a quality assessment of the {{ resource }} with a description of the chosen rating. The scale is as follows: 1 = outstanding, 2 = very good, 3 = OK, 4 = should be fixed, 5 = needs to be fixed.",
    edit: "Edit quality evaluation",
    delete: "Delete",
    note: "Note",
    article: "article",
    topicArticle: "full topic article",
    needsRevision: "Quality evaluated to grade 5",
    error: "An error occured while updating taxonomy",
    disabled: "Resources without taxonomy cannot be evaluated",
    warning:
      "The revision note is set automatically when the quality rating is set to 5. The article will have unsaved changes.",
  },
  editorToolbar: {
    bold: "Bold\n({{ctrl}}+b)",
    "bulleted-list": "Bulleted list\n({{ctrl}}+l)",
    code: "Inline code\n({{ctrl}}+k)",
    "code-block": "Code",
    "concept-inline": "Concept\n({{ctrl}}+alt+c)",
    "gloss-inline": "Gloss\n({{ctrl}}+alt+g)",
    "comment-inline": "Comment\n({{ctrl}}+alt+e)",
    footnote: "Footnote\n({{ctrl}}+alt+f)",
    language: `Language`,
    noneLanguage: "None",
    "normal-text-value": "Normal",
    "heading-1-value": "Heading 1",
    "heading-2-value": "Heading 2",
    "heading-3-value": "Heading 3",
    "heading-4-value": "Heading 4",
    "normal-text": "Normal",
    "heading-1": "Heading 1",
    "heading-2": "Heading 2\n({{ctrl}}+2)",
    "heading-3": "Heading 3\n({{ctrl}}+3)",
    "heading-4": "Heading 4\n({{ctrl}}+4)",
    italic: "Italic\n({{ctrl}}+i)",
    span: "Language\n(alt+l)",
    "letter-list": "Letter list\n({{ctrl}}+alt+a)",
    "content-link": "Link\n({{ctrl}}+alt+l)",
    mathml: "Math\n({{ctrl}}+m)",
    "numbered-list": "Numbered list\n({{ctrl}}+alt+1)",
    quote: "Quote\n({{ctrl}}+alt+b)",
    sub: "Subscript\n({{ctrl}}+alt+s)",
    sup: "Superscript\n({{ctrl}}+alt+h)",
    twoColumnList: "Two-column list",
    underlined: "Underlined",
    "definition-list": "Definition list\n({{ctrl}}+alt+d)",
    left: "Left aligned",
    center: "Center aligned",
    right: "Right aligned",
    rephrase: "Rephrase",
    symbol: "Symbol\n({{ctrl}}+alt+y)",
    disabled: {
      "comment-inline": "Comment can only overlap text",
    },
  },
  editorBlockpicker: {
    open: "Open menu ({{ctrl}}+Enter)",
    close: "Close menu",
    heading: "Add",
    tooltip: "Read our guidelines for using {{ type }}",
    actions: {
      block: "Section",
      factAside: "Factbox",
      table: "Table",
      framedContent: "Text in frame",
      details: "Expandable box",
      image: "Image",
      video: "Video",
      audio: "Audio",
      h5p: "H5P",
      url: "Resource from link",
      related: "Related content",
      file: "File",
      code: "Codeblock",
      podcast: "Podcast episode",
      conceptList: "Concept list",
      concept: "Concept",
      keyFigure: "Key figure",
      contactBlock: "Contact block",
      pitch: "Pitch",
      grid: "Grid",
      campaignBlock: "Kampanjeblokk",
      linkBlockList: "Link block",
      gloss: "Gloss",
      disclaimer: "Accessability disclaimer",
      comment: "Comment",
    },
  },
  form: {
    createNew: "Unsaved {{type}}",
    metadataSection: "Metadata",
    contentSection: "Content",
    workflowSection: "Version log and notes",
    taxonomySection: "Taxonomy",
    copyrightSection: "License and authors",
    articleSection: "Articles",
    podcastSection: "Podcast information",
    podcastSeriesSection: "Podcast series",
    podcastEpisodesSection: "Episodes",
    podcastEpisodesTypeName: "Podcasts",
    inlineEdit: "Inline editor",
    save: "Save",
    saveAsNewVersion: "Save as new version",
    saveAndPublish: "Save and publish",
    saveDraft: "Save draft",
    saveTax: "Save taxonomy",
    saving: "Saving...",
    saveSearch: "Save search",
    alreadySaved: "Saved",
    choose: "Choose",
    saved: "Saved ",
    feil: "There are still errors.",
    copy: "copy",
    saveAsCopySuccess: "New article saved",
    openAll: "Open all",
    hideAll: "Hide all",
    unpublishedChanges: "(Changed since last publish)",
    unpublishedConcepts: "The article contains unpublished concepts",
    moveContent: "Move content into the text",
    open: "Open",
    close: "Close",
    comment: {
      comment: "Comment",
      hide: "Hide comment",
      hideComments: "Hide comments",
      showComments: "Show comments",
      show: "Show comment",
      commentField: "Comment field",
      solve: "The comment is marked as unresolved. Mark as solved",
      unresolve: "The comment is marked as resolved. Mark as unresolved",
    },
    preview: {
      button: "Preview",
    },
    resize: "Resize",
    slug: {
      label: "Permalink",
      edit: "Edit permalink",
    },
    name: {
      title: "Title",
      aboutTitle: "Title",
      slug: "Permalink",
      introduction: "Ingress",
      creators: "Creators",
      rightsholders: "Rightsholders",
      processors: "Processors",
      contributors: "Contributor",
      tags: "Tags",
      license: "License",
      origin: "Origin",
      audioFile: "Audio file",
      content: "Content",
      conceptContent: "Description",
      notes: "Notes",
      metaDescription: "Meta description",
      metaImageAlt: "Alt-text",
      alttext: "Alt-text",
      caption: "Caption",
      imageFile: "Imagefile",
      visualElement: "Visual element",
      visualElementCaption: "Caption",
      visualElementAlt: "Alt-text",
      validFrom: "Valid from",
      validTo: "Valid to",
      description: "Content",
      grepCodes: "Curriculum connection",
      desktopBannerId: "Wide subject page image",
      mobileBannerId: "Narrow subject page image",
      concepts: "Concepts",
      learningpaths: "Learning paths",
      relatedContent: "Related content",
      subjects: "Subject",
      header: "Header",
      manuscript: "Text version",
      coverPhotoId: "Meta image",
      revisions: "Revisions",
      name: "Name",
      subtitle: "Subtitle",
      email: "Email",
      jobTitle: "Job title",
      author: "Author",
      language: "Language",
      link: "Link",
      size: "Size",
      columns: "Columns",
      border: "Show border",
      background: "Background",
      contentType: "Content type",
      linkText: "Link text",
      titleLanguage: "Title language",
      descriptionlanguage: "Description language",
      url: "Link",
      date: "Date",
      sides: "Image side",
      transcription: "Transcription",
      type: "Type",
      text: "Comment",
      grade: "Grade",
      note: "Note",
      files: "File upload",
      code: "Code",
      disclaimer: "Accessibility",
    },
    previewProductionArticle: {
      button: "Compare current version with last published version",
      buttonDisabled: "The article content is identical to the last published version",
      version: "Version {{revision}}",
      current: "Current version",
      published: "Published version",
      article: "Article",
      enableDiff: "Highlight differences",
      diffInfo:
        "Highlights the differences in the unpublished version. Deleted text will be marked in red, changed text in yellow and new text in green. Images and block elements will be displayed with a frame around them, but the display may be somewhat incomplete for some elements.",
    },
    previewLanguageArticle: {
      button: "Compare language versions",
      title: "Draft on {{language}}",
    },
    previewNewWindow: "Preview in a new window",
    contributor: {
      add: "Add",
    },
    mustSaveFirst: "You must save your changes first",
    abort: "Abort",
    edit: "Edit",
    remove: "Remove",
    validate: "Validate",
    publish: "Publish",
    savedOk: "Saved OK",
    publishedOk: "Published OK",
    validationOk: "No validation errors found",
    createdOk: "Created OK",
    addNewImage: "Add new image",
    addNewAudio: "Add new audio",
    notes: {
      heading: "Notes",
      add: "Add new note",
      remove: "Remove note",
      warning: "A note must contain text",
      areHere: "You are here",
      published: "Published",
      placeholder: "Write a note",
      history: {
        user: "User",
        time: "When",
        status: "Status",
        heading: "Notes history",
        note: "Note",
        empty: "No notes",
      },
    },
    updated: {
      label: "Updated date",
    },
    published: {
      label: "Published date",
      reset: "Reset date",
    },
    updatePublished: "Update published date",
    editImage: "Edit image",
    editOriginalImage: "Edit orginal image",
    editAudio: "Edit audio",
    editOriginalAudio: "Edit orginal audio",
    editPodcast: "Edit podcast",
    editH5p: "Edit H5P",
    resetToProd: {
      success: "Content is reset, press save to save changes",
    },
    resetToVersion: "Reset to version",
    previewVersion: "Compare with published",
    variant: {
      create: "Create variant",
      translate: "Translate to Nynorsk",
    },
    remainingCharacters: "Max {{maxLength}} characters and you have {{remaining}} remaining.",
    title: {
      label: "Title",
    },
    introduction: {
      label: "Introduction",
    },
    metaImage: {
      copyright: "Copyright",
      change: "Change meta image",
      title: "Meta image",
      imageTitle: "Image title",
      label: "Meta image",
      helpLabel: "What is a meta image?",
      add: "Choose meta image",
      remove: "Remove meta image",
    },
    availability: {
      everyone: "Everyone",
      teacher: "Teachers",
      label: "Availability",
      description: "Who the article is intended for:",
    },
    modelReleased: {
      label: "Model released",
      yes: "Yes",
      no: "No",
      "not-applicable": "Not applicable",
      "not-set": "Not set",
      description: "Whether the image is model released or not:",
    },
    visualElement: {
      title: "Add visual element",
      label: "Visual element",
      helpLabel: "Information about visual element",
      video: "Video search",
      image: "Image search",
      imageUpload: "Upload image",
      h5p: "H5P",
      description:
        "A visual element can be set differently for each language. If a visual element does not exist, it will be automatically retrieved from another language.",
    },
    visualElementPicker: {
      h5p: "H5P",
      url: "New resource",
      video: "Video",
      image: "Image",
    },
    concept: {
      create: "Create concept",
      edit: "Edit concept",
      remove: "Remove concept",
      source: "Source",
      markdown: "The field supports markdown. Use the format [Text](https://url) to create a link.",
      subjects: "Only subjects marked as explanation subjects will be displayed in the list.",
    },
    gloss: {
      create: "Create gloss",
      edit: "Edit gloss",
      remove: "Remove gloss",
      removeExample: "Remove example",
      source: "Source",
      markdown: "The field supports markdown. Use the format [Text](https://url) to create a link.",
      subjects: "Only subjects marked as explanation subjects will be displayed in the list.",
      gloss: "Gloss in target language",
      originalLanguage: "Original language",
      wordClass: "Word class",
      glossHeading: "Gloss and word class",
      transcriptions: "Transcriptions",
      transcription: "Transcription",
      romanization: "Romanization",
      example: "Example",
      language: "Language",
      languageVariant: "Language variant",
      add: "Add {{label}}",
      choose: "Choose {{label}}",
      languageMissingFields: "All fields for a language must be filled out.",
      exampleMissingFields: "An example entry must include all fields.",
      glossMissingFields: "A gloss entry must include all fields.",
      transcriptionMissingFields: "A transcription cannot be empty.",
      editExamples: "Edit examples",
      editExamplesHeading: "Choose example sentences and languages",
      editExamplesLanguage: "Choose the languages to display on the gloss",
      displayOnGloss: "Show this example",
      titleSection: "Norwegian translation",
      audio: {
        helperText: "Add audio from audio-api to the gloss.",
        button: "Add audio",
      },
      examples: {
        title: "Examples of gloss usage",
        description: "Add relevant examples of gloss usage",
        exampleOnIndex: "Example {{index}}",
        exampleOnLanguage: `Example {{index}} in {{language}}`,
        exampleTextLabel: `Example text in {{language}} for example {{index}}`,
        removeLanguageVariant: "Remove example {{index}} in {{language}}",
        remove: "Remove example {{index}}",
      },
    },
    conceptList: {
      edit: "Edit concept list",
      remove: "Remove concept list",
    },
    workflow: {
      title: "Status",
      change: "Change status",
      qualityAssurance: "Quality assurance",
      saveAsNew: "Make copy",
      deleteLanguageVersion: {
        button: "Delete {{languageVersion}} version",
        title: "Delete language version",
        dialog: "Are you sure that you want to delete this language version?",
      },
      statusInfoTooltip: "Whats the difference between statuses?",
      statusLabel: "Status",
      published: "There exists a published version of this item.",
      multipleTaxonomy: "The article has multiple entries in taxonomy.",
      currentStatus: "Current status: {{ status }}.",
      expiration: {
        warn: "One of the revisions expires soon (Must be revised before {{date}}).",
        expired: "One of the revisions has expired (Expired {{date}}).",
      },
      deleteComment: {
        title: "Delete comment",
        dialog: "Are you sure you want to delete this comment? It can`t be restored.",
        button: "Delete",
      },
      addComment: {
        createdBy: "Created by",
        warn: "Remember to add a comment",
        description: "You have changed responsible without adding a comment!",
        add: "Add new comment",
        label: "Write down comment",
      },
      updateComment: "Update comment",
      deleteCurrentRevision: {
        buttonLabel: "Delete",
        buttonLabelDirty: "Cannot delete revision with unsaved changes",
        buttonLabelPublished: "Cannot delete revision with (partially) published changes",
        dialogTitle: "Delete current revision",
        dialogText: "Are you sure you want to delete the current revision? It cannot be restored.",
        dialogCancel: "Cancel",
        dialogConfirm: "Delete",
      },
    },
    status: {
      new: "New - unsaved",
      new_language: "New language - unsaved",
      created: "Created",
      planned: "Planned",
      in_progress: "In progress",
      external_review: "External review",
      internal_review: "Internal review",
      quality_assurance: "Quality assurance desk",
      language: "Language",
      for_approval: "For approval LMA",
      end_control: "End control",
      imported: "Imported",
      draft: "Draft",
      proposal: "Proposal",
      user_test: "User test",
      awaiting_quality_assurance: "Quality assurance",
      queued_for_language: "Queued for language",
      translated: "Language done",
      quality_assured: "Ready for publishing",
      queued_for_publishing: "Queued for publishing",
      quality_assured_delayed: "Ready for publishing-delayed",
      queued_for_publishing_delayed: "Queue for publishing-delayed",
      publish_delayed: "Publish-delayed",
      published: "Published",
      has_published: "Has published version",
      unlisted: "Link shared",
      unpublished: "Unpublished",
      awaiting_unpublishing: "Awaiting unpublishing",
      awaiting_archiving: "Delayed archivation",
      archived: "Deleted",
      republish: "For republishing",
      sum: "Total",
      private: "Private",
      ready_for_sharing: "Ready for sharing",
      deleted: "Deleted",
      actions: {
        PLANNED: "Planned",
        IN_PROGRESS: "In progress",
        EXTERNAL_REVIEW: "External review",
        INTERNAL_REVIEW: "Internal review",
        QUALITY_ASSURANCE: "Quality assurance",
        LANGUAGE: "Language",
        FOR_APPROVAL: "For approval LMA",
        END_CONTROL: "End control",
        DRAFT: "Draft",
        PROPOSAL: "Proposal",
        USER_TEST: "User test",
        AWAITING_QUALITY_ASSURANCE: "To Quality assurance",
        QUEUED_FOR_LANGUAGE: "Queued for language",
        TRANSLATED: "Language done",
        QUALITY_ASSURED: "Ready for publishing",
        QUEUED_FOR_PUBLISHING: "Queue for publishing",
        QUALITY_ASSURED_DELAYED: "Ready for publishing-delayed",
        QUEUED_FOR_PUBLISHING_DELAYED: "Queue for publishing-delayed",
        PUBLISH_DELAYED: "Publish-delayed",
        PUBLISHED: "Published",
        AWAITING_UNPUBLISHING: "Queue for unpublishing",
        UNPUBLISHED: "Unpublished",
        ARCHIVED: "Deleted",
        AWAITING_ARCHIVING: "Delayed archivation",
        REPUBLISH: "For republishing",
      },
      learningpath_statuses: {
        private: "In progress",
        published: "Published",
        unlisted: "Link shared",
        submitted: "Requested publication",
      },
    },
    validDate: {
      label: "Valid date",
      from: {
        label: "Valid from",
        placeholder: "From date",
      },
      to: {
        label: "Valid to",
        placeholder: "To date",
      },
    },
    content: {
      label: "Content",
      placeholder: "Write here...",
      figure: {
        notSupported: "Media type {{mediaType}} is not supported.",
      },
      relatedArticle: {
        placeholder: "Search for title",
        urlPlaceholder: "Url",
        titlePlaceholder: "Title",
        urlLocation: "Webpage at {{domain}}",
        invalidArticle: "Invalid article",
        addExternal: "Add external article",
        removeExternal: "Delete external article",
        changeExternal: "Edit external article",
        searchExternal: "Write the title and url of the external article",
        listLabel: "Options",
      },
      conceptList: {
        subjectMissing: "Subject missing: {{subjectId}}",
      },
      concept: {
        remove: "Remove concept",
        choose: "Choose concept",
      },
      gloss: {
        remove: "Remove gloss",
        choose: "Choose gloss",
      },
      link: {
        name: "Name",
        domains: "Url",
        validDomains: "Valid domains",
        goTo: "Go to",
        insert: "Insert link",
        update: "Update link",
        change: "Change",
        remove: "Remove link",
        href: "Link",
        newTab: "Open link in new tab",
        text: "Text",
        addTitle: "Add link",
        changeTitle: "Change link",
        required: "Link is required",
        invalid: "Invalid link",
        preview: "Preview link",
        unSupported: "Content in link is not supported",
        newUrlResource: "New resource",
        changeUrlResource: "Edit resource: {{type}}",
        fullscreen: "Open in new window",
        description:
          "Links to ndla-resources are handled by the system and are displayed correct on {{url}}. Internal resources are shown with purple background and external links with blue.",
      },
      footnote: {
        title: "Title",
        year: "Year",
        authors: {
          label: "Author",
          description: "Required with at least one author.",
          createOption: "Create new author",
        },
        edition: "Edition",
        publisher: "Publisher",
        addTitle: "Add footnote",
        editTitle: "Edit footnote",
        removeFootnote: "Remove footnote",
      },
      table: {
        "row-remove": "Remove row",
        "row-add": "Add row",
        "column-add": "Add column",
        "column-remove": "Remove column",
        "table-remove": "Remove table",
        colgroups: "Colgroups",
        colgroupTitle: "Colgroups to adjust width",
        colgroupInfo: "Example: ",
        "edit-colgroups": "Edit colgroups",
        "enable-header": "Enable title column",
        "disable-header": "Disable title column",
        addHeader: "Add title row",
        "column-left": "Left align column",
        "column-center": "Center align column",
        "column-right": "Right align column",
        row: "row",
        column: "column",
      },
      normalizedOnLoad:
        "This article contains old html-code, changed by the editor. This means that you will have to republish the resource even if you only have changed metadata or grep-codes.",
      symbol: {
        title: "Insert symbol",
        insert: "Insert",
      },
    },
    tags: {
      label: "Tags",
      helpLabel: "What is a tag?",
      description: "3 tags is required.",
      createOption: "Create new tag",
      searchPlaceholder: "Search for tags",
    },
    grepCodes: {
      label: "Competences and core elements",
      placeholder: "Type code",
      description:
        "Type in codes using the correct format ({{ codes }}) followed by one or more digits. Non existing codes will not be created. Separate multiple codes with comma. Texts will be displayed in norwegian here but will be shown correct in frontend. You can also filter on learningplan codes.",
      expired: "This code is no longer active",
    },
    articleDisclaimer: {
      title: "Information about availability for the entire article",
      description:
        "Enter what is challenging about the content of the article. You can also add links to alternative content. Templates have been prepared for this. Check these <0>here</0> before using the component.",
    },
    resourceTypes: {
      label: "Resource type and properties",
      placeholder: "Add property",
    },
    subjects: {
      label: "Subjects",
      searchPlaceholder: "Search for subjects",
      placeholder: "Add subjects",
    },
    topics: {
      label: "Topics",
      placeholder: "Add topic",
      primaryTopic: "Primary topic",
      sharedTopic: "Shared topic",
      setPrimaryTopic: "Set as primary topic",
      RGTooltip: "Choose between Core(K) or Supplementary(T)",
    },
    metaDescription: {
      label: "Meta description",
      helpLabel: "What is a meta description?",
      description: "The description will be viewable in search.",
    },
    articleSummary: {
      label: "Summary",
      description: "AI generated summary of the article. Will not be saved.",
    },
    agreement: {
      label: "Connect to agreement",
      helpLabel: "What is an agreement?",
      placeholder: "Search for agreement",
    },
    rightsholders: {
      label: "Rightsholder",
      labelRemove: "Remove",
      placeholder: "Type name of rightholder",
      createOption: "Add new rightsholder",
    },
    processors: {
      label: "Processor",
      labelRemove: "Remove",
      placeholder: "Type name of processor",
      createOption: "Add new processor",
    },
    creators: {
      label: "Creator",
      labelRemove: "Remove",
      placeholder: "Type name of creator",
      createOption: "Add new creator",
      description: "Required with at least one creator.",
    },
    contributors: {
      label: "Contributors",
    },
    license: {
      label: "License",
      helpLabel: "What is a license?",
      choose: "Choose a license",
    },
    responsible: {
      label: "Responsible",
      choose: "Choose a responsible",
      noResults: "No results",
      noResponsible: "No responsible",
      revisionDate: "Amount approaching revision date",
      error: "Something went wrong when updating responsible",
    },
    origin: {
      label: "Origin",
    },
    processed: {
      label: "Processed",
      description: "The content has been processed",
      disabledCause: "The processed field can only be set when origin is defined",
    },
    image: {
      file: "Image",
      save: "Save image",
      editImage: "Edit image",
      removeImage: "Remove image",
      alignment: {
        left: "Left aligned",
        right: "Right aligned",
        center: "Large centered",
      },
      sizes: {
        xsmall: "Size: Tiny",
        small: "Size: Small",
        medium: "Size: Medium",
        fullwidth: "Size: Large",
      },
      crop: "Crop image",
      aspect: {
        "4_3": "4:3",
        "3_4": "3:4",
        "16_9": "16:9",
        square: "Square",
        none: "Free form",
      },
      focalPoint: "Set focalpoint",
      alt: {
        label: "Alt-text",
        placeholder: "Alt-text",
        noText: "WCAG requires alt-text for images that are not decorative.",
      },
      caption: {
        label: "Image caption",
        placeholder: "Image caption",
        hide: "Hide caption",
      },
      fileUpload: {
        description: "Drag and drop or click to upload image",
        button: "Add",
        genericError: "Image upload failed",
        tooLargeError: "Image is too large",
        fileTypeInvalidError: "The file type is not supported",
      },
      byline: {
        show: "Show byline",
        hide: "Hide byline",
      },
      isDecorative: "This image is decorative in this context",
      showBorder: "Show image border",
    },
    video: {
      caption: {
        label: "Video caption",
        placeholder: "Video caption",
      },
      remove: "Remove video",
      save: "Save video",
      editVideo: "Edit video",
      time: {
        start: "Start",
        stop: "Stop",
        hms: "h:m:s",
      },
      brightcove: "Open in Brightcove",
      toLinkedVideo: "Switch to interpreted video",
      fromLinkedVideo: "Switch back to original video",
      linkedVideoButton: "IV",
    },
    h5p: {
      remove: "Remove H5P",
      copy: "Copy H5P",
      copyError: "Failed to copy H5P",
      metadata: {
        alttext: "Alt-text",
        save: "Save",
        cancel: "Cancel",
        edit: "Edit H5P metadata",
        description: "The metadata is stored in the article and will not affect the original H5P.",
      },
    },
    audio: {
      file: "Audio file",
      title: {
        label: "Audio title",
        placeholder: "Audio title",
      },
      manuscript: "Text version",
      caption: {
        label: "Audio caption",
        placeholder: "Audio caption",
      },
      edit: "Edit audio",
      remove: "Remove audio",
      chooseAudioType: "Choose audio type",
      sound: "Audio",
      speech: "Speech",
      fileUpload: {
        description: "Drag and drop or click to upload audio",
        button: "Add",
        genericError: "Audio upload failed",
        fileTypeInvalidError: "The file type is not supported",
      },
      copiedFrom:
        "Audio file will be copied from {{language}}. Click the delete icon to remove it and upload a new file.",
      info: {
        multipleFiles: "You can upload different audio files for each language.",
        changeFile: "Changes made to a language will not alter the other languages.",
        newLanguage: "When adding a new language, an audio file from an existing language will be suggested.",
        deleteFiles: "Audio files will only be deleted when not used in any language.",
      },
      dialog: {
        header: "Audio files",
        label: "Audio file information",
      },
    },
    podcast: {
      remove: "Remove podcast",
    },
    external: {
      title: "external",
      edit: "Edit {{type}} element",
      remove: "Remove {{type}} element",
    },
    related: {
      title: "Related content",
      subtitle: "Drag article to change the order",
      showMore: "Show more related content",
      showLess: "Show less",
    },
    file: {
      label: "Files",
      file: {
        label: "File",
      },
      alt: {
        label: "Alt text",
        placeholder: "Alt text",
      },
      download: "Download:",
      title: {
        label: "File title",
        placeholder: "File title",
      },
      addFile: "Add file",
      removeList: "Remove file list",
      placeholder: "Filename",
      changeName: "Change name",
      changeOrder: "Change the order",
      removeFile: "Remove file",
      missingFileTooltip:
        "This file does not seem to exist on the server. It might have been deleted from another article.",
      missingFilename: "File type is not supported",
      fileUpload: {
        description: "Drag and drop or click to upload file(s)",
        button: "Add",
        genericError: "File upload failed",
        fileTypeInvalidError: "The file type is not supported",
        tooManyError: "Maximum 5 files can be uploaded at once",
      },
      showPdf: "Show expanded",
      showPdfTooltip: "Show expanded PDF in article",
    },
    article: {
      label: "Article",
      add: "Add article",
    },
    learningpathConnections: {
      sectionTitle: "Uses of the article in learningpaths",
      title: "Learningpaths containing this article",
    },
    linkConnections: {
      title: "Subjects/topics linking to this article",
    },
    myNdla: {
      noFavorites: "No one has favorited the resource.",
      numFavorites: "The resource has been favorited {{num}} times.",
    },
    embedConnections: {
      type: {
        image: "image",
        audio: "audio file",
        concept: "concept",
        gloss: "gloss",
        article: "article",
      },
      sectionTitleArticle: "Articles containing the {{resource}}",
      sectionTitleConcept: "Concepts containing the {{resource}}",
      title: "Uses of the {{resource}}",
      info: {
        image: "Uses of the image in articles and/or concepts",
        audio: "Uses of the audio file in articles",
        concept: "Uses of the concept in articles",
        gloss: "Uses of the gloss in articles",
        article: "Uses of the article in other articles",
      },
      articles_one: "1 article",
      articles_other: "{{count}} articles",
      concepts_one: "1 concept/gloss",
      concepts_other: "{{count}} concepts/glosses",
    },
    relatedConcepts: {
      placeholder: "Search for title",
      articlesTitle: "Concepts",
      changeOrder: "Change order",
      removeArticle: "Remove concept",
    },
    relatedContent: {
      placeholder: "Search for title",
      articlesTitle: "Content",
      changeOrder: "Change order",
      removeArticle: "Remove content",
      addExternal: "Add external article",
      link: {
        missingTitle: "Missing title",
        missingUrl: "Url must start with http:// or https://",
        titlePlaceholder: "Title",
        urlPlaceholder: "https://example.com",
        addLink: "Add",
      },
    },
    section: {
      remove: "Remove section",
    },
    revisions: {
      add: "New revision",
      remove: "Remove revision",
      revisionNumber: "Revision {{number}}",
      description:
        "Revisions requires a description and an expiration date for the article. The switch marks whether a revision is performed or not. Remember that a revised article must be republished.",
      datePickerTooltip: "The date the article expires if the revision is not marked as revised.",
      reminder: "Remember to check if the revision you now have performed requires republishing.",
      switchTooltip: "Whether the article is revised or not.",
      inputPlaceholder: "Description of the revision",
      deleteTooltip: "Remove this revision",
    },
    disclaimer: {
      edit: "Edit accessibility information",
      title: "Universal design - information in continuous text",
      description:
        "Write down what the problem with the component is. Templates have been prepared for this. Check these <0>here</0> before using the component.",
      editorHeader: "Information about accessibility for individual components",
    },
    copyright: {
      title: "Edit license",
      edit: "Edit license",
      add: "Add licensed content",
    },
  },
  validation: {
    isRequired: "{{label}} is required.",
    isNumeric: "{{label}} must contain digits.",
    bothFields: "One {{labelLowerCase}} must contain all fields.",
    url: "{{label}} must contain a valid link.",
    urlOrNumber: "{{label}} must contain a valid link or article-id.",
    dateBeforeInvalid: "{{label}} can not be after {{afterLabel}}.",
    dateAfterInvalid: "{{label}} can not be before {{beforeLabel}}.",
    maxLength: "{{label}} must not have more than {{maxLength}} characters.",
    minLength: "{{length}} must have at least {{minLength}} characters.",
    minItems_one: "{{label}} must have at least one {{labelLowerCase}}.",
    minItems_other: "{{label}} must have at least {{count}} unique {{labelLowerCase}}.",
    noEmptyNote: "A note cannot be empty",
    noEmptyRevision: "A description cannot be empty",
    noLicenseWithoutCopyrightHolder: "A license cannot be added without providing at least one copyright holder.",
    maxSizeExceeded: "The file you are trying to upload is too large. Max size: {{maxSize}}. File size: {{fileSize}}.",
    grepCodes:
      "The code format is wrong. The correct format is K(E/M) or TT followed by one or more digits. Ex. KE137, KM2255, TT2.",
    podcastImageShape: "A meta image must have equal height and width.",
    podcastImageSize: "A meta image must be between 1400 and 3000 pixels wide.",
    unfinishedRevision: "You must have at least one planned revision.",
    missingRevision: "There must be at least one revision.",
    email: "The email address is not valid.",
    learningpathMustBeStandalone: "The learning path content type cannot be combined with other content types.",
  },
  errorMessage: {
    title: "Oops, something went wrong",
    description: "Sorry, an error occurd.",
    back: "Back",
    goToFrontPage: "Go to frontpage",
    invalidUrl: "Invalid url",
    noArticleInProd: "No article found in prod",
    taxonomy: "There was a problem loading taxonomy",
    versionSelect: "This article does not exist in the selected version",
    errorWhenFetchingTaxonomyArticle: "There was a problem fetching the underlying article",
    unsavedTaxonomy: "You have unsaved changes. Press reset again if you are sure you want to continue.",
    auth0: "Authentication error. Press cancel to take care of any changes you have made before logging in again.",
    statusCode: {
      409: "This article has already been updated. Keep what you have changed and reload the page to save.",
    },
    grepCodes: "The following codes have wrong format or does not exist, and will not be added: ",
    errorOnSave: "Something went wrong when saving the article.",
    genericError: "Something went wrong, the action could not be completed.",
    missingResourceType: "The resource must have at least one resource type.",
    missingTaxTitle: "Not in taxonomy!",
    missingTax:
      "Articles and topics cannot be saved without being placed in the taxonomy. Update the taxonomy block and save again.",
    invalidTopicPlacements: "Topics without placement in taxonomy",
    invalidTopicPlacementsDescription:
      "The nodes that end up here could have children. They have ended up here because they have been detached from their parent.",
    noTaxNode:
      "This resource does not have a placement in the taxonomy. You have to connect it to a node to make it available.",
    createNode: "Connect the resource to a node",
  },
  warningMessage: {
    fieldWithWrongLanguage: "This value is fetched from language code: {{language}}",
    translatedField: "This field is auto-translated from language code: nb",
  },
  notFound: {
    description: "The page cannot be found",
  },
  forbiddenPage: {
    description: "You do not have access to this page",
  },
  alertDialog: {
    notSaved: "Document is not saved, do you want to continue?",
    needToRefresh:
      "Someone have saved the same article while you were editing. You need to copy your changes manually and refresh the page",
    continue: "Continue",
    delete: "Delete",
    confirm: "Confirm",
    disconnect: "Disconnect",
    loginAgain: "Login again",
    watchOut: "Watch out!",
    cancel: "Cancel",
  },
  environment: { production: "", staging: "Staging", test: "Test" },
  taxonomy: {
    nodeType: {
      PROGRAMME: "programme",
      SUBJECT: "subject",
      TOPIC: "topic",
    },
    favorite: { add: "Add subject as favorite", remove: "Remove subject as favorite" },
    publishedVersion: "See published version",
    noValue: "No value",
    previewProgrammes: "Preview programmes in frontend",
    addNode: "Add {{nodeType}}",
    newNode: "New {{nodeType}}",
    newNodeName: "Name of new element",
    newResource: "New resource",
    editStructure: "Edit structure",
    editSubjectpage: "Edit subjectpage",
    deleteSubject: "Delete subject",
    addSubject: "Add subject",
    subjectName: "New subject name",
    addExistingNode: "Move existing {{nodeType}} here",
    addExistingLoading: "Moving ...",
    addExistingSuccess: "Node successfully moved",
    existingNode: "Search for existing {{nodeType}} to be moved",
    workflow: "in workflow",
    fullTopic: "Average:",
    TOPIC: "topic",
    SUBJECT: "subject",
    PROGRAMME: "programme",
    qualityDescription:
      "Average quality evaluation of all evaluated resources within the {{nodeType}} ({{count}} evaluated resources)",
    average: "Average",
    qualityEvaluation: "Evaluation of the {{nodeType}}",
    connectExistingNode: "Connect {{nodeType}} to this node",
    connectExistingLoading: "Connection ...",
    connectExistingSuccess: "Node successfully connected!",
    disconnectNode: "Disconnect from parent",
    confirmDisconnect: "Are you sure you want to disconnect this node?",
    newSubject: "New Subject",
    newTopic: "New topic",
    resources: "Resources",
    nodeSettings: "Settings",
    programmeSettings: "Programme settings",
    subjectSettings: "Subject settings",
    topicSettings: "Topic settings",
    currentVersion: "Current version",
    delete: {
      deleteNode: "Delete {{ nodeType }}",
      deleteResource: "Delete resource",
      deleteDisabled: "{{ nodeType }} with {{ nodeChild }} can't be deleted",
      child: "children",
      subTopic: "sub topics",
      topic: "topics",
      confirmDelete: "Are you sure you want to delete this {{ nodeType }}?",
      deletionType: {
        unpublish: "This resource is only used here, and will be unpublished.",
        delete: "This resource is only used here, and will be deleted.",
        deleteConnection: "Deleting this resource will not affect it elsewhere.",
      },
      deletionError: {
        articleError: "Failed to change the status of the resource.",
        connectionError: "Failed to delete the connection between then ode and the resource.",
      },
    },
    version: "Version",
    createResource: "Create new resource",
    addNewPlannedResource: "Create planned resourse",
    resourceType: { label: "Core(K) or supplementary(T)", tabTitle: "Change Core(K)/supplementary(T)" },
    title: "Title",
    comment: "Comment",
    commentPlaceholder: "E.g. content, learning objective or grep",
    contentType: "Content type",
    contentTypePlaceholder: "Choose content type",
    create: "Create",
    add: "Add",
    getExisting: "Or get existing resource",
    inProgress: "This article is in progress",
    addPriority: "Priority",
    supplementary: "Supplementary",
    displayOptions: "Display options",
    changeName: {
      loadError: "Could not fetch translations",
      updateError: "Could not update translations",
      defaultName: "Default name",
      addNewTranslation: "Add new translation",
      buttonTitle: "Change name",
      language: "Language",
      name: "Name",
      namePlaceholder: "Name",
      delete: "Delete",
      title: "Change name",
      cancel: "Cancel",
      add: "Add",
      noTranslations: "No translations available! Using default name as fallback.",
    },
    addTopic: "Add topic",
    addTopicHeader: "Add topic",
    createTopic: "Create new topic",
    searchExistingTopic: "Search for existing topic",
    errorMessage: "An error occurred",
    confirmDeleteTopic: "Are you sure you want to delete this topic?",
    confirmDeleteSubject: "Are you sure you want to delete this subject?",
    linkSettings: "Link",
    setPrimary: "Set as primary link",
    addResource: "Add resource",
    removeResource: "Remove resource from topic",
    searchResource: "Search for resource",
    searchArticle: "Search for topic article",
    or: "Eller",
    urlPlaceholder: "Paste in a link from ndla.no or an article-id",
    wrongType: "Note! This is a different resource type: ",
    noResources: "No resources found",
    addTopicDescription: "Change topic description",
    confirmSetPrimary: "Do you want to make this the main location?",
    jumpToResources: "Jump to resources",
    jumpToStructure: "Jump to structure",
    showLMASubject: "Show LMA-subjects",
    showDASubject: "Show DA-subjects",
    showSASubject: "Show SA-subjects",
    swapTopicArticle: {
      failed: "Failed to swap article",
      placeholder: "Article to swap to",
      info: "Swap topic article",
      success: "Topic article swapped! Reload the page to get the updated topic name.",
    },
    copyResources: {
      error: "Something went wrong during copying",
      info: "Reuse resources from topic",
      placeholder: "Search for existing {{nodeType}} for reuse of resources",
      done: "Resources copied",
      waiting: "Copying resources",
    },
    cloneResources: {
      error: "Something went wrong during cloning",
      info: "Copy and clone resources from topic",
      placeholder: "Search for existing {{nodeType}} for copying of resources",
      done: "Resources cloned",
      waiting: "Cloning resources",
    },
    favorites: "Show favorites",
    quality: "Show quality",
    publish: {
      button: "Publish all resources",
      waiting: "Publishing resourses",
      info: "Are you sure you want to publish all resources associated with this node?",
      done: "Resources published",
      error: "The following resources were not published:",
    },
    info: {
      title: "Information",
      subTitle: "Id and visibility for the element",
      wrongResourceType: 'The node is placed as "{{placedAs}}" in the taxonomy, but is of type "{{isType}}".',
      missingResourceType: "The node with ID {{id}} does not have a resource type. It is probably deleted.",
      wrongArticleType:
        'The article is placed as "{{placedAs}}" in the taxonomy, but the article is of "{{isType}}" type.',
      missingArticleType: "The article with ID {{id}} does not have an article type. It most likely does not exist.",
      wrongConnections: "Bad connections",
      wrongConnectionsSubTitle: "This article has bad connections, see the list below.",
      canBeFixedInDatabase: "The article type can be changed in the database to fix the error.",
      notPublished: "The article has no published version.",
    },
    resource: {
      confirmDelete:
        "Do you want to delete the resource from this folder? This will not affect the placement other places",
      copyError:
        "An error occurred while copying resources. Double check the copied resources and try to fix deficiencies manually, or delete the copied resources and try to copy again",
      addResourceConflict: "The resource you attempted to add already exists on the topic.",
      noResourceId: "Failed to extract the ID from the chosen resource",
      creationFailed: "Failed to create connection",
    },
    removeLink: "Remove link",
    resourceTypes: {
      title: "Content type",
      helpLabel: "What is a content type?",
      subTitle: "What content type does this resource have?",
      placeholder: "Select content type",
    },
    topics: {
      title: "Topic connections",
      topicPlacement: "Topcic placement",
      helpLabel: "What is a topic connection?",
      subTitle: "Where in the taxonomy should this resource be?",
      subTitleTopic: "Where in the taxonomy should the topic description be?",
      chooseTaxonomyPlacement: "Choose placement in taxonomy",
      changeTaxonomyPlacement: "Change placement in taxonomy",
      filestructureButton: "Create a topic connection",
      filestructureHeading: "Select a topic connection",
      filestructureClose: "Close",
      addNewTopic: "Add new topic",
      addNewSubTopic: "Add new sub topic",
      addedTopic: "Added to taxonomy",
      disconnectedTaxonomyWarning: "Invalid topic connection",
      taxonomySubjectConnections:
        "In order for a resource to be available in the structure, it must be linked to one or more topics.",
      description:
        "Choose where the subject should be placed in taxonomy. If you change placement in taxonomy, the old subject will not be deleted if it has subtopics or resources linked to it.",
    },
    grepCodes: {
      edit: "Edit grep codes",
      empty: "No existing grep codes",
      addNew: "Add new grep code",
      delete: "Remove {{grepCode}}",
    },
    copyRevisionDates: {
      text: "Are you sure you want to copy this revision date? This will apply for all nodes and resources underneath this node",
      buttonText: "Copy revision date",
      error: "An error occurred when copying the revision date",
    },
    resourcesPrimary: {
      text: "Are you sure you want to make all connected resources primary?",
      recursiveText: "Are you sure you want to make all connected resources and sub resources primary?",
      buttonText: "Make resources primary",
      recursiveButtonText: "Make resources and sub resources primary",
      error: "An error occured",
      success: "All resources have been converted to primary resources",
    },
    goTo: "Open in structure editor",
    missingResourceType: "Missing resource type",
    metadata: {
      customFields: {
        alterFields: "Add/change metadata",
        addField: "New metadata field",
        languagePlaceholder: "Ndla.no language collection",
        explanationSubject: "Explanation subject",
        programmeSubject: "Common programme subject",
        oldSubjectId: "Old ID for redirecting",
        subjectCategory: "Subject category",
        subjectType: "Subject type",
        resourceGroupPlaceholder: "Grouping",
        RGTooltip: "Show resources Grouped or Ungrouped",
        subjectLMA: "Responsible for the subject",
        subjectSA: "Language responsible for the subject",
        subjectDA: "Desk responsible for the subject",
        keyPlaceholder: "Add key",
        valuePlaceholder: "Add value",
      },
      placeholders: {
        category: "Choose category",
        language: "Choose language",
        type: "Choose type",
        lma: "Choose responsible",
        sa: "Choose language responsible",
        da: "Choose desk responsible",
      },
    },
    errors: {
      failedToDeleteConnection: "An error occurred when deleting the node",
      failedToUpdateConnection: "An error occurred when updating the node",
      failedToCreateConnection: "An error occurred when creating the node",
    },
    learningResources: "Learning resources",
    multidisciplinaryResources: "Multidisciplinary cases",
    multidisciplinary: {
      title: "Multidisciplinary cases",
      dialogTrigger: "Add multidisciplinary case",
      dialogTitle: "Add multidisciplinary case",
      errors: {
        notCase: "The URL points to a multidisciplinary topic, but not a multidisciplinary case.",
        notMultidisciplinary: "The URL does not point to a multidisciplinary topic.",
        failedToFetch: "Failed to fetch resource from URL.",
        invalidUrl: "Invalid URL.",
      },
    },
  },
  notions: {
    edit: "Edit notions",
    closeNotion: "Close notion dialog",
  },
  contextTypes: {
    topic: "Topic",
    frontpage: "About-NDLA article",
    concept: "Concept",
    gloss: "Gloss",
    learningpath: "Learningpath",
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: "Slideshow",
      slideshowTitle: "Movies on slideshow on frontpage",
      movieGroupHeader: "Movies themes",
      addMovieToSlideshow: "Add movie to slideshow",
      addMovieToGroup: 'Add a movie to "{{name}}"',
      comboboxGroupLabel: 'Movies in the group "{{name}}"',
      editMovieGroupName: "Change the names on this movie group",
      deleteMovieGroup: 'Delete "{{name}}"',
      moveMovieGroupUp: "Move up",
      moveMovieGroupDown: "Move down",
      changeOrder: "Change order",
      removeMovieFromGroup: "Remove movie from group",
      removeMovieFromSlideshow: "Remove movie from slideshow",
      createThemeGroup: "Create new movie group",
      saveNameChanges: "Save changes",
      cancel: "Cancel",
      editGroupTitle: "Change the name(s) in this movie group",
      newGroupTitle: "What shall we call the new movie group?",
      notFound: "We can not find metadata for this movie...",
      moreInfoHeader: "More information",
      moreInfoTitle: "Article for Read more-link",
      addArticleToMoreInformation: "Add an article",
      removeArticleFromMoreInformation: "Remove article",
      createGroup: "Create new group",
      groupNamePlaceholder: "Write name in {{lang}}",
    },
  },
  conceptForm: {
    title: "Concept",
    info: {
      lastUpdated: "Last updated",
    },
  },
  glossform: {
    title: "Gloss",
  },
  editorFooter: {
    buttonLabel: "Quality ensurance",
    heading: "Quality ensurance:",
    changeStatus: "Change status",
    back: "Go back",
    inputHeader: "Your note",
    inputHelperText: "Short note",
    cancelLabel: "Cancel",
    saveLabel: "Change status and save draft",
    warningSaveWithoutComment: "Note is missing",
    newStatusPrefix: "New status:",
    statusLabel: "Status:",
    changeHeader: "Changes",
    saveAsNew: "Save as copy",
    prioritized: "Prioritized",
    placeholderPrioritized: "No priority",
  },
  taxonomyVersions: {
    title: "Taxonomy Versions",
    publishedVersion: "Published version",
    otherVersions: "Other versions",
    deleteLocked: "This version cannot be deleted because it is locked",
    deletePublished: "This version cannot be deleted because it is published",
    delete: "Delete version",
    locked: "This version is locked and cannot be deleted",
    publishTitle: "Publish version",
    publishButton: "Publish",
    publishWarning:
      "Are you sure you want to publish this version? The currently published version will be archived, and all new changes within this version will be immediately available on ndla.no",
    status: {
      PUBLISHED: "Published",
      ARCHIVED: "Archived",
      BETA: "Beta",
    },
    about:
      "This page is used for viewing and administering taxonomy versions. Be wary: Publishing a new version will immediately make it available for ndla.no end users.",
    noPublished:
      "No versions have been published! The Draft version of taxonomy is in use until a version is published.",
    editVersionTooltip: "Edit version",
    newVersionTitle: "Create new version",
    newVersionButton: "New version",
    editVersionTitle: "Edit version",
    deleteWarning: "Are you sure you want to delete this version?",
    deleteWarningPublished:
      "Are you sure you want to delete the currently published version? Taxonomy will revert back to the Draft version",
    postError: "Failed to create version",
    putError: "Failed to update version",
    publishError: "Failed to publish version",
    deleteError: "Failed to delete version",
    noOtherVersions: "No other versions exist!",
    previewVersion: "Preview this version on NDLA.no",
    form: {
      name: {
        label: "Name",
        placeholder: "Example Version",
      },
      source: {
        title: "Source version",
        subTitle: "Base this version on an existing version",
        defaultOption: "Draft",
      },
      locked: {
        title: "Locked",
        subTitle: "Lock this version to prevent deletion",
        locked: "Locked",
        unlocked: "Unlocked",
      },
    },
  },
  diff: {
    equalNodes: "These nodes are equal!",
    defaultVersion: "Draft",
    compareVersions: "Compare versions",
    error: {
      originalHashRequired: "The originalHash parameter has to be present in the URL!",
      doesNotExist: "This node does not exist in any of these versions!",
      onlyExistsInOriginal: "This node only exists in the target version",
      onlyExistsInOther: "This node only exists in the source version",
    },
    options: {
      about: "This page enables you to compare a node-tree between two different versions.",
      originalHashLabel: "Target version",
      otherHashLabel: "Source version",
      viewLabel: "View type",
      nodeViewLabel: "Node view",
      fieldViewLabel: "Field view",
      allNodes: "All nodes",
      changedNodes: "Only changed",
      allFields: "All fields",
      changedFields: "Only changed",
      flat: "Flat",
      tree: "Tree",
    },
    childrenChanged: "Children changed",
    resourcesChanged: "Resources changed",
    diffTypes: {
      ADDED: "Added",
      DELETED: "Missing",
      MODIFIED: "Modified",
      NONE: "None",
    },
    isRoot: "Root node",
    nodeTypeTooltips: {
      SUBJECT: "This is a subject",
      TOPIC: "This is a topic",
      PROGRAMME: "This is a programme",
    },
    fields: {
      id: {
        title: "ID",
      },
      name: {
        title: "Name",
      },
      contentUri: {
        title: "Content URI",
      },
      parentId: {
        title: "Parent",
      },
      path: {
        title: "Path",
      },
      paths: {
        title: "Paths",
      },
      connectionId: {
        title: "Connection ID",
      },
      isPrimary: {
        title: "Is Primary",
        isOn: "This node is currently a primary resource",
        isOff: "This node is not currently a primary resource",
      },
      rank: {
        title: "Rank",
      },
      relevance: {
        title: "Relevance",
      },
      translations: {
        title: "Translations",
      },
      articleType: {
        title: "Article Type",
      },
      visible: {
        title: "Visible",
        isOn: "Visible",
        isOff: "Not visible",
      },
      "topic-resources": {
        title: "Resource Grouping",
        isOn: "Grouped",
        isOff: "Ungrouped",
      },
      requestPublish: {
        title: "Publish requested",
        true: "Yes",
        false: "No",
      },
      language: {
        title: "Display language",
      },
      subjectCategory: {
        title: "Subject category",
      },
      explanationSubject: {
        title: "Explanation Subject",
      },
      oldSubjectId: {
        title: "Old Subject ID",
      },
      supportedLanguages: {
        title: "Supported Languages",
      },
      grepCodes: {
        title: "Grep Codes",
      },
      resourceTypes: {
        title: "Resource Types",
      },
    },
  },
  metadata: {
    visible: "Visible",
    notVisible: "is not visible",
    changeVisibility: "Change visibility",
  },
  unsavedChanges: "Unsaved changes",
  messages: {
    severity: {
      info: "Information",
      warning: "Warning",
      success: "Everything is OK!",
      danger: "Watch out!",
    },
  },
  delete: "Delete",
  reset: "Reset",
  campaignBlockForm: {
    title: "Edit campaign block",
    delete: "Remove campaign block",
    sides: {
      left: "Left",
      right: "Right",
    },
  },
  linkBlock: {
    deleteBlock: "Remove link block",
    delete: "Remove link",
    edit: "Edit link",
    create: "Add new link",
    chooseDate: "Choose date",
    linkExists: "This link already exists in the block",
  },
  dragAndDrop: {
    handle: "Drag handle",
  },
  datePicker: {
    chooseMonth: "Month:",
    chooseYear: "Year:",
    labelNext: "Go to next month",
    previousMonth: "Go to previous month",
    goToToday: "Go to today",
  },
  remove: "Remove",
  frontpageForm: {
    error: "An error occurred",
    changeArticle: "Choose article",
    addArticle: "Add article",
    addArticleToMenu: "Add article to menu",
    changeFrontpageArticle: "Change front page article",
    search: "Search for an article",
    frontpageArticle: "Front page article:",
    noFrontpageArticle: "Front page article not set",
    failedTitle: "Failed to show title",
    openChildren: "Show children",
    closeChildren: "Hide children",
    hide: "Hide",
    show: "Show",
  },
  codeEditor: {
    title: "Add code example",
    subtitle: "code example",
    titleLabel: "Title",
    programmingLanguage: "Programming language",
    edit: "Edit code example",
    delete: "Remove code example",
    languageSelect: "Select language:",
    save: "Save",
    abort: "Abort",
  },
  framedContentForm: {
    changeVariant: {
      colored: "Use colored variant",
      neutral: "Use neutral variant",
    },
  },
  blockquoteForm: {
    changeVariant: {
      colored: "Use colored variant",
      neutral: "Use neutral variant",
    },
  },
  fileUpload: {
    title: "Upload files",
  },
  conceptCompare: {
    title: "Compare language versions",
  },
  conceptPreview: {
    title: "Preview concept",
  },
  math: "Math problem",
  editor: {
    versionHistory: {
      who: "Who",
      when: "When",
      message: "Message",
      status: "Status",
    },
  },
  masthead: {
    menu: {
      title: "Open menu",
    },
  },
  footer: {
    info: "This webapplication is developed as Open Source code.",
    editorInChief: "Editor in chief:",
  },
  user: {
    buttonLogOut: "Log out",
  },
  unsupportedElement: {
    title: 'Unsupported element: "{{type}}"',
    description:
      "This element is not supported here. You can either delete the entire element, or move its contents out",
    noContent: "The element had no content",
  },
  matomo: {
    visits: "Visits: {{count}}",
    hits: "Page views: {{count}}",
    avgTime: "Avg. time spent by visitors: {{time}} seconds",
    totalHits: "Total page views: {{count}} ({{contexts}} contexts)",
    totalHearts: "Total number of favorite markings: {{count}}",
    error: "Something went wrong while fetching visitor data",
    switchLabel: "Show visitor numbers",
    popoverDescription_one: "{{count}} unique page view, click to see more visitor numbers",
    popoverDescription_other: "{{count}} unique page views, click to see more visitor numbers",
    noData: "No visitors",
    popoverTitle: "Visitor numbers since december 2024.",
  },
  textGeneration: {
    error: "Something went wrong when generating text. Message from the service: {{message}}",
    errorImage: "Something went wrong. Could not process the image.",
    insert: "Insert",
    replace: "Replace",
    append: "Add after",
    chosenText: "Selected text",
    suggestedText: "Forslag til $t(textGeneration.types.{{type}})",
    dialogTitle: "Generer $t(textGeneration.types.{{type}})",
    generateButton: "Generer $t(textGeneration.types.{{type}})",
    generateTranscription: "Generate transcription",
    types: {
      summary: "summary",
      altText: "alternative text",
      alternativePhrasing: "alternative phrasing",
      metaDescription: "meta description",
      reflection: "reflection questions",
    },
    customPrompts: {
      switchLabel: "Custom prompts",
      roleLabel: "Role prompt",
      roleHelper: 'Describe the role of the AI model. E.g.: "You are a specialist in..."',
      instructionsLabel: "Instruction prompt",
      instructionsHelper: 'Describe the instructions for the AI model. E.g.: "Your task is to..."',
    },
    failed: "Oops, something went wrong! Could not generate $t(textGeneration.types.{{type}}).\n{{error}}",
    failedTranscription: "Oops, something went wrong! Could not generate transcription.",
    responseBox: "Full response from the AI model",
  },
  learningpathForm: {
    genericError: "Something went wrong while retrieving the learning path",
    header: {
      clone: "Copy learning path",
    },
    metadata: {
      title: "Metadata/Content",
      titleLabel: "Title",
      introductionLabel: "Introduction",
      descriptionLabel: "Description",
      metaImageTitle: "Meta image",
      descriptionPlaceholder: "Description of the learning path",
    },
    steps: {
      title: "Learning steps",
      typeTitle: "Add content",
      typeDisabledExplanation: "Learning paths created in ED only support resource steps",
      addStep: "Add step",
      noSteps: "This learning path doesn't have any steps yet.",
      noPublishedVersion: "This resource does not have a published version.",
      formTypes: {
        text: "Text written by myself",
        resource: "Content from NDLA",
        external: "Content from a external website",
      },
      editStep: "Edit step",
      textForm: {
        titleLabel: "Title",
        introductionLabel: "Ingress",
        descriptionLabel: "Description",
      },
      resourceForm: {
        label: "Article from NDLA",
        labelHelper: "Search for article",
        labelHelperPublished:
          "Search for an article. This learning path is already published, so you can only add articles that have a published version",
        descriptionLabel: "Description",
        descriptionHelper:
          "Descriptions are no longer supported on resource steps. This field only appears because you are editing an existing step with a description. We recommend removing the description.",
      },
      externalForm: {
        urlLabel: "URL",
        titleLabel: "Title",
        introductionLabel: "Ingress",
        descriptionLabel: "Description",
        descriptionHelper:
          "Descriptions are no longer supported on external resources. This field only appears because you are editing an existing step with a description. We recommend removing the description.",
      },
    },
    preview: {
      heading: "Preview learning path",
      openExternalLink: "Open in new tab",
      learningpathMenu: "Learning path content",
      learningpathMenuTitle: "Learning steps",
      noSteps: "This learning path has no steps.",
      showPublished: "Show published version",
    },
  },
  articleTraits: {
    VIDEO: "Video",
    AUDIO: "Audio",
    H5P: "Interactive content",
    INTERACTIVE: "Interactive content",
    PODCAST: "Podcast",
  },
  learningstepSamplePage: {
    title: "External learning step samples",
    introduction:
      "This page lists five random learning paths containing external learning steps created in My NDLA. Every time you load the page a new set of samples will appear.",
    linksTo: "Links to ",
    inPath: 'In learning path "{{title}}"',
  },
};

export default phrases;
