/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = "- Produksjonsystem - NDLA";

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Fagstoff ${titleTemplate}`,
    createTopicArticlePage: `Emne ${titleTemplate}`,
    createSubjectpage: `Fagforside ${titleTemplate}`,
    createFrontPageArticePage: `Om-NDLA-artikkel ${titleTemplate}`,
    agreementPage: `Avtale ${titleTemplate}`,
    welcomePage: `Forside ${titleTemplate}`,
    structurePage: `Struktur ${titleTemplate}`,
    programmePage: `Utdanningsprogram ${titleTemplate}`,
    versionsPage: `Versjoner ${titleTemplate}`,
    audioUploaderPage: `Lyd ${titleTemplate}`,
    imageUploaderPage: `Bilde ${titleTemplate}`,
    loginPage: `Logg inn ${titleTemplate}`,
    logoutPage: `Logg ut ${titleTemplate}`,
    ndlaFilmPage: `NDLA Film ${titleTemplate}`,
    podcastUploaderPage: `Podkastepisode ${titleTemplate}`,
    podcastSeriesPage: `Podkastserie ${titleTemplate}`,
    h5pPage: `H5P ${titleTemplate}`,
    nodeDiffPage: `Sammenlign noder ${titleTemplate}`,
    editFrontpage: "Rediger forside",
    comparePage: `Sammenlign versjoner ${titleTemplate}`,
    search: {
      "podcast-series": `Søk podkastserier ${titleTemplate}`,
      audio: `Søk lydfiler ${titleTemplate}`,
      concept: `Søk forklaringer ${titleTemplate}`,
      content: `Søk innhold ${titleTemplate}`,
      image: `Søk bilder ${titleTemplate}`,
    },
    learningpath: {
      new: `Opprett læringssti ${titleTemplate}`,
      edit: `Rediger læringssti ${titleTemplate}`,
      preview: `Forhåndsvis læringssti ${titleTemplate}`,
    },
  },
  dropdown: {
    numberHits: `Søket gav {{hits}} treff`,
    searching: "Søker...",
    create: "Opprett nytt",
    isSelectedItem: "Lagt til",
  },
  meta: {
    description: "Kvalitetssikrede fritt tilgjengelige nettbaserte læremidler for videregående opplæring",
  },
  menu: {
    title: "Meny",
  },
  dialog: {
    close: "Lukk",
    title: "Tittel",
    audio: {
      rulesForUse: "Regler for bruk av lydklipp",
    },
    learnAboutLicenses: "Lær mer om åpne lisenser",
    source: "Kilde",
  },
  license: {
    heading: "Slik gjenbruker du innhold",
    learnMore: "Lær mer om åpne lisenser",
    copyTitle: "Kopier referanse",
    hasCopiedTitle: "Kopiert!",
    embed: "Bygg inn",
    embedCopied: "Kopierte innbyggingskode!",
    download: "Last ned",
    tabs: {
      text: "Tekst",
      images: "Bilder",
      audio: "Lyd",
      video: "Video",
    },
    images: {
      heading: "Slik bruker du bilder fra artikkelen",
      description: "Husk å kopiere teksten som skal legges ved bildet der du bruker det.",
      rules: "Regler for bruk av bildet:",
      source: "Kilde",
      title: "Tittel",
    },
    text: {
      heading: "Slik bruker du tekst fra artikkelen",
      description: "Artikkelen kan være sammensatt av flere tekster som listes opp her.",
      rules: "Regler for bruk av teksten:",
      published: "Publiseringsdato",
    },
    audio: {
      heading: "Slik bruker du lydfiler",
      description: "Husk å kopiere teksten som skal legges ved lydfilen der du bruker den.",
      rules: "Regler for bruk av lydfilen:",
    },
    video: {
      heading: "Slik bruker du video fra artikkelen",
      description: "Husk å kopiere teksten som skal legges ved videoen der du bruker den.",
      rules: "Regler for bruk av videoen:",
    },
  },
  languages: {
    // Adds to list from frontend-packages
    ar: "Arabisk",
    la: "Latin",
    no: "Norsk",
    so: "Somali",
    ti: "Tigrinja",
    und: "Udefinert",
    ukr: "Ukrainsk",
    prs: "Dari",
    san: "Sanskrit",
    heb: "Hebraisk",
    pli: "Pali",
    change: "Bytt til {{language}} versjon",
    none: "Språk",
  },
  // WARNING: Some of these symbols contain special unicode characters that look like normal characters.
  // Make sure not to accidentally change them!
  symbols: {
    "½": "En halv",
    "¼": "En fjerdedel",
    "¾": "Tre fjerdedeler",
    "²": "I andre",
    "³": "I tredje",
    "©": "Copyright",
    "™": "Trademark",
    "°": "Grader",
    "¥": "Yen",
    "‑": "Hard bindestrek",
    "–": "Tankestrek",
    " ": "Hardt mellomrom",
    "§": "Paragraf",
    "¿": "Invertert spørsmåltegn",
  },
  welcomePage: {
    lastFavorited: "Siste hjertemarkerte ressurs: ",
    addSearch: "Legg til nytt søk",
    noHitsSavedSearch: "Ingen treff i dine lagrede søk",
    deleteSavedSearch: "Slett lagret søk",
    deleteSearch: "Slett søk",
    noArticles: "Ingen ressurser ...",
    emptyLastUsed: "Ingen sist redigerte ...",
    emptyConcepts: "Ingen forklaringer ...",
    emptyRevision: "Ingen ressurser i favorittfag som trenger revisjon ...",
    emptySavedSearch: "Ingen lagrede søk",
    guidelines: "Retningslinjer",
    mustBeSearch: "Lenken må være til et søk",
    lastUsed: "Sist redigert",
    lastUsedDescription: "Ressurser du har redigert nylig",
    lastUsedConcepts: "Forklaringer du har redigert nylig",
    savedSearch: "Lagrede søk",
    saveSearch: "Lagre søk",
    chooseSubject: "Velg fag",
    chooseFavoriteSubject: "Velg favorittfag",
    chooseTopic: "Velg emner",
    errorMessage: "Innhenting av data feilet",
    goToSearch: "Gå til søk",
    revision: "Revisjon",
    revisionDescription: "Ressurser som har revisjonsdato innen 365 dager",
    revisionDate: "Revisjonsdato",
    welcomeText: "til ED",
    revisionInfo: "Velg favorittfag ved å stjernemarkere i strukturredigering",
    updated: "Oppdatert",
    primaryConnection: "Vis kun ressurser med primærkobling til mine favorittfag",
    primaryConnectionLabel: "Vis kun primærkobling",
    prioritizedLabel: "Vis kun prioriterte",
    lmaSubjects: "LMA-fag",
    daSubjects: "DA-fag",
    saSubjects: "SA-fag",
    favoriteSubjects: "Favorittfag",
    lmaSubjectsHeading: "Produksjonsflyt i LMA-fag",
    daSubjectsHeading: "Produksjonsflyt i DA-fag",
    saSubjectsHeading: "Produksjonsflyt i SA-fag",
    favoriteSubjectsHeading: "Produksjonsflyt i favorittfag",
    lmaSubjectsDescription: "Status på ressurser i mine LMA-fag i flyten",
    daSubjectsDescription: "Status på ressurser i mine DA-fag i flyten",
    saSubjectsDescription: "Status på ressurser i mine SA-fag i flyten",
    favoriteSubjectsDescription: "Status på ressurser i mine favorittfag i flyten. Utgåtte fag er ikke inkludert",
    noResultsLMASubjects: "Følgende statuser vil ikke vises i oversikten",
    count: "Antall",
    countResponsible: "Antall ansvarlig for",
    pagination: {
      resources: "ressurser",
      concepts: "forklaringer",
      workList: "Sider med {{ resourceType }} du er ansvarlig for",
      lastUsed: "Sider med dine sist redigerte {{ resourceType }}",
      revision: "Sider med utløpende ressurser i dine favorittfag",
      subjectView: "Sider med statistikk for dine {{ group }}",
    },
    workList: {
      heading: "Mine arbeidsoppgaver",
      description: "Ressurser hvor du står som ansvarlig",
      title: "Tittel",
      status: "Status",
      contentType: "Innholdstype",
      primarySubject: "Primærfag",
      topicRelation: "Emnetilhørighet",
      date: "Tildelt",
      ariaLabel: "Oversikt over mine arbeidsoppgaver og forklaringer",
      conceptDescription: "Forklaringer hvor du står som ansvarlig",
      conceptSubject: "Forklaringsfag",
      sortAsc: "Sorter stigende",
      sortDesc: "Sorter synkende",
      pickPageSize: "Velg antall rader",
      numberOfRows: "Antall rader",
      onHold: "Parkert",
      onHoldHeading: "Parkerte ressurser",
      onHoldDescription: "Parkerte ressurser der du står som ansvarlig",
      onHoldFilter: "Ikke tell parkerte",
      loading: "Laster...",
    },
    subjectView: {
      lma: "Fagoversikt LMA-fag",
      da: "Fagoversikt DA-fag",
      sa: "Fagoversikt SA-fag",
      favorites: "Fagoversikt favorittfag",
      description: "Oversikt over statistikk knyttet til ressurser i dine fag",
      heart: "Hjerter",
      heartDescription: "Antall favorittmarkerte ressurser",
      flow: "I flyt",
      flowDescription: "Antall ressurser i flyt",
      old: "Utdaterte",
      oldDescription: "Antall ressurser det er mer enn 5 år siden ble sist faglig oppdatert",
      revision: "Revisjoner",
      revisionDescription: "Antall ressurser med utløpt revisjonsdato",
      published: "Publisert",
      publishedDescription: "Antall publiserte ressurser",
    },
    welcomeBack: "Velkommen",
    listLabels: {
      worklist: "Ressurstyper",
      lastUsed: "Ressurstyper",
      subjectView: "Fagtyper",
      articleStatuses: "Fagtyper",
    },
  },
  updateCodesPage: {
    title: "Oppdater læreplankoder",
    description:
      "Konverter grep-koder fra utgåtte læreplaner til tilsvarende grep-koder for nye læreplaner. Dette endrer alle artikler som har tilknyttede kompetansemål og kjerneelement fra utgåtte læreplaner, både publiserte og upubliserte versjoner. Artiklene trenger ikke endres i etterkant for at nye grep-koder skal bli synlige.",
    buttonText: "Oppdater",
    error: "Noe gikk galt ved oppdatering av grep-koder",
  },
  searchPage: {
    search: "Søk",
    header: {
      content: "Søk etter innhold",
      audio: "Søk etter lydfiler",
      image: "Søk etter bilder",
      concept: "Søk etter forklaringer",
      "podcast-series": "Søk etter podkastserier",
    },
    activeFilters: "Aktive filtre",
    searchButton: "Søk",
    emptyButton: "Tøm",
    title: "Tittel",
    language: "Språk",
    contentNoHits: "Ingen treff i innhold samsvarte med søket ditt på: {{query}}",
    "podcast-seriesNoHits": "Ingen serier samsvarte med søket ditt på: {{query}}",
    conceptNoHits: "Ingen forklaringer samsvarte med søket ditt på: {{query}}",
    audioNoHits: "Ingen lydfiler samsvarte med søket ditt på: {{query}}",
    imageNoHits: "Ingen bilder samsvarte med søket ditt på: {{query}}",
    pageSize: "{{pageSize}} treff per side",
    hitsSelectLabel: "Antall treff per side",
    totalCount: "Antall søketreff",
    highlights: {
      title: "Søketreff",
      content: "Søketreff fra innhold",
      tags: "Søketreff fra nøkkelord",
      embedAttributes: "Søketreff fra innebygde elementer",
      notes: "Søketreff fra versjonslogg",
      previousVersionsNotes: "Søketreff fra versjonslogg",
    },
    save: {
      alreadyExist: "Søket er allerede lagret.",
      fetchFailed: "Kunne ikke laste lagrede søk.",
      other: "Søk feilet.",
    },
  },
  taxonomyResourceType: {
    resource: "Ressurs",
    topic: "Emne",
  },
  articleType: {
    "topic-article": "Emne",
    "frontpage-article": "Om-NDLA-artikkel",
    standard: "Læringsressurs",
  },
  subNavigation: {
    listTitle: {
      create: "Opprett",
      edit: "Rediger",
      admin: "Admin",
      external: "Eksterne systemer",
    },
    media: "Media",
    learningPath: "Læringssti",
    learningPathLink: "Stier",
    brightcoveLink: "Brightcove",
    detailSearch: "Detaljsøk",
    learningResource: "Læringsressurs",
    image: "Bilde",
    audio: "Lydfil",
    podcast: "Podkastepisode",
    podcastSeries: "Podkastserie",
    agreement: "Ny avtale",
    structure: "Strukturredigering",
    programme: "Utdanningsprogram",
    taxonomyVersions: "Taksonomiversjoner",
    searchContent: "Søk innhold",
    searchAudio: "Søk lyd",
    searchPodcastSeries: "Søk serie",
    searchImage: "Søk bilde",
    searchConcepts: "Søk forklaring",
    film: "NDLA film",
    h5p: "Edlib H5P",
    newConcept: "Forklaring",
    newGloss: "Glose",
    newSubject: "Opprett fag",
    newFrontpageArticle: "Om-NDLA-artikkel",
    frontpage: "NDLA forside",
    updateCodes: "Oppdater læreplankoder",
  },
  logo: {
    altText: "Nasjonal digital læringsarena",
  },
  siteNav: {
    chooseSubject: "Velg fag",
    search: "Søk",
    login: "Logg inn",
  },
  loginFailure: {
    errorMessage: "Beklager. Innlogging feilet.",
    loginLink: "Klikk for å prøve igjen.",
    userNotRegistered: "Vi kjente ikke igjen epostadressen din. Har du logget inn med riktig adresse?",
  },
  loginProviders: {
    description: "Logg inn i produksjonssystem med",
  },
  logoutProviders: {
    localLogout: "Logg ut av produksjonssystem",
    or: "eller",
    federatedLogout: "Logg ut av alle tjenester",
    description: "N.B. Alle tjenester inkluderer autentiseringstjenesten (Google eller Facebook).",
  },
  searchForm: {
    placeholder: "Søk etter artikler, aktiviteter eller oppgaver",
    searchTypes: "Søketyper",
    types: {
      conceptQuery: "Søk på forklaring",
      glossQuery: "Søk på glose",
      contentQuery: "Søk på innhold",
      audioQuery: "Søk på lydfiler",
      "podcast-seriesQuery": "Søk på podkastserier",
      imageQuery: "Søk på bilder",
      language: "Velg språk",
      users: "Velg bruker",
      "model-released": "Velg modellklarering",
      subjects: "Velg fag",
      "resource-types": "Velg innholdstype",
      status: "Velg status",
      "draft-status": "Velg status",
      "audio-type": "Velg lydfiltype",
      "concept-type": "Velg forklaringstype",
      license: "Velg lisens",
      "revision-date-from": "Revisjonsdato fra",
      "revision-date-to": "Revisjonsdato til",
      "exclude-revision-log": "Ekskluder endringslogg",
      "responsible-ids": "Velg ansvarlig",
      "filter-inactive": "Inkluder utgåtte fag",
    },
    tagType: {
      query: "Søk:",
      subjects: "Fag: {{value}}",
      language: "Språk: $t(languages.{{value}})",
      users: "Bruker: {{value}}",
      "resource-types": "Innholdstype: {{value}}",
      status: "Status: $t(form.status.{{value}})",
      "draft-status": "Status: $t(form.status.{{value}})",
      "audio-type": "Lydfiltype: {{value}}",
      "concept-type": "Forklaringstype: {{value}}",
      license: "Lisens: {{value}}",
      "model-released": "Modellklarering: {{value}}",
      "revision-date-from": "Revisjonsdato fra: {{value}}",
      "revision-date-to": "Revisjonsdato til: {{value}}",
      "exclude-revision-log": "Endringslogg ekskludert",
      "responsible-ids": "Ansvarlig: {{value}}",
      "filter-inactive": "Utgåtte fag inkludert",
    },
    btn: "Søk",
    empty: "Tøm",
    articleType: {
      all: "Alle",
      standard: "Standard",
      learningResource: "Læringsressurs",
      topicArticle: "Emnebeskrivelse",
      image: "Bilde",
      audio: "Lyd",
    },
    audioType: {
      standard: "Lydfil",
      podcast: "Podkast",
    },
    conceptType: {
      concept: "Forklaring",
      gloss: "Glose",
    },
    order: "Rekkefølge",
    asc: "Stigende",
    desc: "Fallende",
    sorting: "Sortering",
    sort: {
      id: "Id",
      relevance: "Relevans",
      title: "Tittel",
      lastUpdated: "Sist oppdatert",
      revisionDate: "Neste revisjon",
      favorited: "Favorittmarkeringer",
      published: "Sist faglig oppdatert",
    },
    resultError: "Noe gikk feil med innlasting av type: {{type}}",
    favourites: "Mine favorittfag",
    LMASubjects: "Mine LMA-fag",
    SASubjects: "Mine SA-fag",
    DASubjects: "Mine DA-fag",
    archivedIncluded: "Utgåtte fag inkludert",
    error: "Noe gikk galt med søket",
    conceptSubject: "Forklaringsfag: {{name}}",
    multiTaxonomy: "{{count}} plasseringer i taksonomi",
  },
  subjectsPage: {
    subjects: "Fag",
  },
  subjectPage: {
    topics: "Emner",
  },
  editMarkup: {
    linkTitle: "Gå til HTML-editor",
    title: "HTML-editor",
    previewDialogTitle: "Forhåndsvis artikkel",
    subTitle: "Rediger artikkelinnhold med HTML",
    fetchError: "En feil oppsto ved lasting av HTML-editoren. Gå tilbake eller prøv å laste siden på nytt.",
    saveError: "En feil oppsto ved lagring av endringer.",
    back: "Tilbake",
    helpMessage: {
      tooltip: "Om HTML-editoren",
      paragraph1:
        "Det er mulig å formatere HTML-koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisningsfunksjonaliteten aktivt. Lagring med ctrl+s fungerer også.",
      paragraph2:
        "For å minimere eventuelle problemer med formatering og for å sikre at at HTML blir konsistent, så blir koden kjørt gjennom de samme transformeringene som den vanlige editoren. Det vil si at den vil prøve å rette opp ugyldig kode. Linjeskift blir fjerna ved lagring og dermed ignorert.",
    },
  },
  imageSearch: {
    modelReleased: {
      yes: "Modellklarert",
      no: "Ikke modellklarert",
      "not-applicable": "Ikke relevant",
      "not-set": "Ikke valgt",
    },
    placeholder: "Søk i bilder",
    buttonTitle: "Søk",
    useImage: "Bruk bildet",
    metaImageCheckboxLabel: "Sett som metabilde",
    visualElementCheckboxLabel: "Sett som visuelt element",
    noTitle: "Ingen tittel",
    noResultsText: "Fant ingen bilder på søk. Ønsker du å laste opp et nytt bilde?",
    noResultsButtonText: "Last opp bilde",
  },
  videoSearch: {
    searchPlaceholder: "Søk i videoer",
    searchButtonTitle: "Søk",
    loadMoreVideos: "Last flere videoer",
    noResults: "Ingen videoer funnet.",
    addVideo: "Bruk video",
    previewVideo: "Forhåndsvis",
    publishedDate: "Publisert dato",
    duration: "Varighet",
    interactioncount: "Visninger",
    is360Video: "VR-video",
  },
  mathEditor: {
    editMath: "Rediger Matematikk",
    preview: "Forhåndsvisning",
    continue: "Du kan ha ulagrede endringer i matteeditoren. Vil du fortsette?",
  },
  code: {
    continue: "Du kan ha ulagrede endringer i kodevisning. Vil du fortsette?",
  },
  h5pElement: {
    fetchError: "Vi beklager, men en feil oppsto under lasting av H5P-klienten.",
  },
  displayOembed: {
    errorMessage: "En feil oppsto ved visning av oEmbed-innhold.",
    notSupported: "oEmbed av type {{type}} og kilde {{provider}} er ikke støttet.",
  },
  audioSearch: {
    searchPlaceholder: "Søk i lydfiler",
    searchButtonTitle: "Søk",
    useAudio: "Velg lyd",
    noResults: "Ingen resultater funnet",
    noTitle: "Ingen tittel",
  },
  conceptSearch: {
    searchPlaceholder: "Søk i forklaringer",
    searchButtonTitle: "Søk",
    noResults: "Ingen resultater funnet",
    noTitle: "Ingen tittel",
    noContent: "Ingen innhold",
    listLabel: "Valg",
  },
  searchTypes: {
    content: "Innhold",
    audio: "Lyd",
    image: "Bilde",
    concept: "Forklaring",
    "podcast-series": "Serie",
  },
  noEmbedMessage: {
    deleteOnSave: "Element av type {{type}} vil bli slettet ved lagring.",
  },
  conceptpageForm: {
    articlesTitle: "Relaterte artikler",
    articlesSubtitle: "Artikler",
    changeOrder: "Endre rekkefølge",
    removeArticle: "Fjern artikkel",
  },
  subjectpageForm: {
    title: "Fag",
    about: "Om faget",
    description: "Beskrivelse",
    metadata: "Metadata",
    addBanner: "Velg banner",
    changeBanner: "Bytt banner",
    editorsChoices: "Litt forskjellig fra faget",
    articles: "Artikler",
    addArticle: "Legg til artikkel",
    removeArticle: "Fjern artikkel",
    missingVisualElement: "Visuelt element er påkrevd.",
    subjectlinks: "Faglenker",
    addSubject: "Legg til fag",
    moveSubject: "Dra og slipp",
    removeSubject: "Fjern fag",
    connectedTo: "Felles programfag sammen med",
    buildsOn: "Bygger på",
    leadsTo: "Leder til",
  },
  programmepageForm: {
    title: "Utdanningsprogram",
  },
  topicArticleForm: {
    visualElementTitle: {
      image: "Bildetittel",
      video: "Videotittel",
      h5p: "H5P tittel",
      brightcove: "Videotittel",
      external: "Innholdstekst",
    },
    visualElementCopyright: "Opphav",
    removeVisualElement: "Fjern element",
    info: {
      lastUpdated: "Sist faglig oppdatert",
    },
    title: "Emne",
    fields: {
      caption: {
        label: {
          image: "Bildetekst",
          brightcove: "Videotekst",
          external: "Innholdstekst",
        },
        placeholder: {
          image: "Bildetekst",
          brightcove: "Videotekst",
          external: "Innholdstekst",
        },
      },
      alt: {
        label: "Alt-tekst",
        placeholder: "Alt-tekst",
      },
    },
    validation: {
      containsContent: "Kun emner i tverrfaglige tema (case) kan ha tekst i innholdsfeltet.",
      illegalResource: "Emneartikler bør kun ha bilde som visuelt element.",
    },
  },
  agreementForm: {
    title: {
      create: "Avtale",
      update: "Avtale",
    },
    fields: {
      title: {
        label: "Avtaletittel",
        placeholder: "Avtaletittel",
      },
      content: {
        label: "Avtalens innhold",
        placeholder: "Avtalens innhold",
      },
    },
  },
  footnoteForm: {
    title: "Tittel",
    year: "År",
    authors: "Forfatter",
  },
  linkForm: {
    href: "Lenke",
    text: "Tekst",
  },
  audioForm: {
    title: "Lyd",
  },
  podcastSeriesForm: {
    title: "Podkastserie",
    alreadyPartOfSeries: "Del av en annen serie",
    description: "Beskrivelse",
    rss: "Rss-feed",
    adminError: "Du har ikke tilgang til å opprette eller endre podkastserier.",
    hasRSS: "Aktiver RSS-feed for denne serien",
  },
  podcastForm: {
    title: "Podkastepisode",
    fields: {
      header: "Overskrift",
      introduction: "Introduksjon",
      coverPhoto: "Bilde",
      coverPhotoAltText: "Alt-text",
      manuscript: "Tekstversjon",
      series: "Serie",
    },
    information: {
      partOfSeries: "Denne podkasten er en del av serien",
      removeSeries: "Fjern serie",
      noSeries: "Podkasten tilhører ingen serie",
    },
  },
  imageEditor: {
    editImage: "Rediger bildet",
    remove: {
      crop: "Fjern utsnitt",
      focalPoint: "Fjern fokalpunkt",
    },
  },
  imageForm: {
    title: "Bilde",
    copyImageTitle: "Last opp bilde som kopi",
    copyDescription: "Last opp et bilde med samme informasjon som dette bildet",
  },
  contactBlockForm: {
    title: "Kontaktblokk",
    edit: "Rediger kontaktblokk",
    delete: "Fjern kontaktblokk",
    background: {
      subtle: "Subtil",
      moderate: "Moderat",
      strong: "Sterk",
    },
  },
  frontpageArticleForm: {
    title: "Om-NDLA-artikkel",
    validation: {
      illegalSlug: "Bruk av ulovlige tegn i permalenken! Tillatte tegn er alle tall og bokstaver, og bindestrek",
    },
    isFrontpageArticle: {
      toggleArticle: "Bred editor",
    },
  },
  gridForm: {
    title: "Grid",
    background: {
      white: "Hvit",
      transparent: "Transparent",
      gray: "Grå",
    },
    setSticky: "Lås innhold til cellen ved siden av",
    unsetSticky: "Frigjør innhold fra cellen ved siden av",
  },
  pitchForm: {
    title: "Rediger pitch",
    languageExplanation: "Velg språk for skjermleser",
    sizes: {
      normal: "Normal",
      large: "Stor",
    },
  },
  learningResourceForm: {
    metaImage: {
      title: "Bildetittel",
      copyright: "Opphav",
      change: "Bytt metabilde",
    },
    title: "Læringsressurs",
    validation: {
      missingEmbedData:
        "En eller flere inkluderte lyd-, bilde-, eller videoelementer mangler beskrivende tekst eller alternativ tekst.",
    },
    fields: {
      footnotes: {
        edition: "Utgave",
        publisher: "Utgiver",
      },
    },
  },
  keyFigureForm: {
    edit: "Rediger Nøkkeltall",
    title: "Nøkkeltall",
  },
  qualityEvaluationForm: {
    title: "Kvalitetsvurdering",
    unavailable: "Ikke satt",
    dialogTitle: "Oppdater kvalitetsvurdering",
    description:
      "Legg inn en kvalitetsvurdering av {{ resource }} med en beskrivelse av den valgte graderingen. Skalaen er som følger: 1 = enestående, 2 = veldig bra, 3 = OK, 4 = bør fikses, 5 = må fikses.",
    edit: "Rediger kvalitetsvurdering",
    delete: "Slett",
    note: "Notat",
    article: "artikkelen",
    topicArticle: "emnet som helhet",
    needsRevision: "Kvalitetsvurdert til 5",
    error: "En feil oppstod ved oppdatering av taksonomi",
    disabled: "Ressurser uten taksonomi kan ikke kvalitetsvurderes",
    warning:
      "Revisjonsmerknad settes automatisk når man setter kvalitetsvurdering til 5. Artikkelen vil derfor få ulagrede endringer.",
  },
  editorToolbar: {
    bold: "Fet\n({{ctrl}}+b)",
    "bulleted-list": "Punktliste\n({{ctrl}}+l)",
    code: "Kode\n({{ctrl}}+k)",
    "code-block": "Kodeblokk",
    "concept-inline": "Forklaring\n({{ctrl}}+alt+c)",
    "gloss-inline": "Glose\n({{ctrl}}+alt+g)",
    "comment-inline": "Kommentar\n({{ctrl}}+alt+e)",
    footnote: "Fotnote\n({{ctrl}}+alt+f)",
    language: `Språk`,
    noneLanguage: "Ingen",
    "normal-text-value": "Normal",
    "heading-1-value": "Overskrift 1",
    "heading-2-value": "Overskrift 2",
    "heading-3-value": "Overskrift 3",
    "heading-4-value": "Overskrift 4",
    "normal-text": "Normal",
    "heading-1": "Overskrift 1",
    "heading-2": "Overskrift 2\n({{ctrl}}+2)",
    "heading-3": "Overskrift 3\n({{ctrl}}+3)",
    "heading-4": "Overskrift 4\n({{ctrl}}+4)",
    italic: "Kursiv\n({{ctrl}}+i)",
    span: "Språk\n(alt+l)",
    "letter-list": "Bokstavliste\n({{ctrl}}+alt+a)",
    "content-link": "Lenke\n({{ctrl}}+alt+l)",
    mathml: "Matte\n(ctrl+m)",
    "numbered-list": "Nummerert liste\n({{ctrl}}+alt+1)",
    quote: "Sitat\n({{ctrl}}+alt+b)",
    sub: "Senket\n({{ctrl}}+alt+s)",
    sup: "Hevet\n({{ctrl}}+alt+h)",
    twoColumnList: "To-kolonners liste",
    underlined: "Understreket",
    "definition-list": "Definisjonsliste\n({{ctrl}}+alt+d)",
    left: "Venstrejustert",
    center: "Midtstilt",
    right: "Høyrejustert",
    rephrase: "Omformulering",
    symbol: "Symbol\n({{ctrl}}+alt+y)",
    disabled: {
      "comment-inline": "Kommentar kan kun overlappe tekst",
    },
  },
  editorBlockpicker: {
    heading: "Legg til",
    open: "Åpne meny ({{ctrl}}+Enter)",
    close: "Lukk meny",
    tooltip: "Les vår veiledning om bruk av {{ type }}",
    actions: {
      block: "Seksjon",
      factAside: "Faktaboks",
      table: "Tabell",
      framedContent: "Tekst i ramme",
      details: "Ekspanderende boks",
      image: "Bilde",
      video: "Video",
      audio: "Lyd",
      h5p: "H5P",
      url: "Ressurs fra lenke",
      related: "Relatert innhold",
      file: "Fil",
      code: "Kodevisning",
      podcast: "Podkastepisode",
      conceptList: "Forklaringsliste",
      concept: "Forklaring",
      keyFigure: "Nøkkeltall",
      contactBlock: "Kontaktblokk",
      pitch: "Pitch",
      grid: "Grid",
      campaignBlock: "Kampanjeblokk",
      linkBlockList: "Lenkeblokk",
      gloss: "Glose",
      disclaimer: "UU-advarsel",
      comment: "Kommentar",
    },
  },
  form: {
    createNew: "Ulagret {{type}}",
    metadataSection: "Metadata",
    contentSection: "Innhold",
    workflowSection: "Versjonslogg og merknader",
    taxonomySection: "Taksonomi",
    copyrightSection: "Lisens og bruker",
    articleSection: "Artikler",
    podcastSection: "Podkastinformasjon",
    podcastSeriesSection: "Podkastserie",
    podcastEpisodesSection: "Episoder",
    podcastEpisodesTypeName: "Podkaster",
    inlineEdit: "Hurtigredigering",
    save: "Lagre",
    saveAsNewVersion: "Lagre som ny versjon",
    saveAndPublish: "Lagre og publiser",
    saveDraft: "Lagre utkast",
    saveTax: "Lagre taksonomi",
    choose: "Velg",
    saving: "Lagrer...",
    saveSearch: "Lagre søk",
    alreadySaved: "Lagret",
    saved: "Lagret ",
    feil: "Det er fortsatt flere feil i skjemaet",
    copy: "kopi",
    mustSaveFirst: "Du må lagre endringene dine først",
    saveAsCopySuccess: "Ny artikkel lagret",
    openAll: "Åpne alle",
    hideAll: "Lukk alle",
    unpublishedChanges: "(Endret siden siste publisering)",
    unpublishedConcepts: "Artikkelen inneholder upubliserte forklaringer",
    moveContent: "Flytt innhold inn i teksten",
    open: "Åpne",
    close: "Lukk",
    comment: {
      comment: "Kommenter",
      hide: "Skjul kommentar",
      hideComments: "Skjul kommentarer",
      showComments: "Vis kommentarer",
      show: "Vis kommentar",
      commentField: "Kommentarfelt",
      solve: "Kommentaren er merket som uløst. Merk som løst",
      unresolve: "Kommentaren er merket som løst. Merk som uløst",
    },
    preview: {
      button: "Forhåndsvis",
    },
    resize: "Endre størrelse",
    slug: {
      label: "Permalenke",
      edit: "Forandre permalenke",
    },
    name: {
      title: "Tittel",
      aboutTitle: "Tittel",
      slug: "Permalenke",
      introduction: "Ingress",
      creators: "Opphavsperson",
      rightsholders: "Rettighetshaver",
      processors: "Bearbeider",
      tags: "Nøkkelord",
      license: "Lisens",
      origin: "Opphav",
      audioFile: "Lydfil",
      content: "Innhold",
      conceptContent: "Beskrivelse",
      notes: "Merknader",
      metaDescription: "Metabeskrivelse",
      metaImageAlt: "Alt-tekst",
      alttext: "Alt-tekst",
      caption: "Bildetekst",
      imageFile: "Bildefil",
      visualElement: "Visuelt element",
      visualElementCaption: "Figur tekst",
      visualElementAlt: "Alt-tekst",
      validFrom: "Gyldig fra",
      validTo: "Gyldig til",
      description: "Innhold",
      grepCodes: "Læreplankobling",
      desktopBannerId: "Bredt fagsidebilde",
      mobileBannerId: "Smalt fagsidebilde",
      concepts: "Forklaringer",
      relatedContent: "Relatert innhold",
      subjects: "Fag",
      header: "Overskrift",
      manuscript: "Tekstversjon",
      coverPhotoId: "Metabilde",
      revisions: "Revisjoner",
      name: "Navn",
      subtitle: "Undertittel",
      email: "E-post",
      jobTitle: "Stilling",
      language: "Språk",
      author: "Forfatter",
      link: "Lenke",
      size: "Størrelse",
      columns: "Kolonner",
      border: "Vis ramme",
      background: "Bakgrunn",
      contentType: "Innholdstype",
      linkText: "Lenketekst",
      titleLanguage: "Tittel-språk",
      descriptionlanguage: "Beskrivelse-språk",
      url: "Lenke",
      date: "Dato",
      sides: "Hvilken side bildet skal vises på",
      transcription: "Transkripsjon",
      type: "Type",
      text: "Kommentar",
      grade: "Gradering",
      note: "Notat",
      files: "filopplasting",
      code: "Kode",
      disclaimer: "Tilgjengelighet",
    },
    previewProductionArticle: {
      button: "Sammenlign gjeldende versjon med sist publiserte versjon",
      buttonDisabled: "Artikkelinnholdet er identisk med den sist publiserte versjonen",
      version: "Versjon {{revision}}",
      current: "Gjeldende versjon",
      published: "Publisert versjon",
      article: "Artikkel",
      enableDiff: "Marker forskjeller",
      diffInfo:
        "Markerer forskjeller i den upubliserte versjonen. Slettet tekst vil markeres med rødt, endret tekst med gult og ny tekst med grønt. Bilder og blokkelementer vil vises med en ramme rundt, men visningen kan være noe mangelfull for noen elementer.",
    },
    previewLanguageArticle: {
      button: "Sammenlign språkversjoner",
      title: "Utkast på {{language}}",
    },
    previewNewWindow: "Forhåndsvis i nytt vindu",
    contributor: {
      add: "Legg til",
    },
    concept: {
      create: "Opprett ny forklaring",
      edit: "Rediger forklaring",
      remove: "Fjern forklaring",
      source: "Kilde",
      markdown: "Feltet støtter markdown. Bruk formatet [Tekst](https://url) for å lage lenke.",
      subjects: "Kun fag markert som forklaringsfag vil vises i lista.",
    },
    gloss: {
      create: "Opprett ny glose",
      edit: "Rediger glose",
      remove: "Fjern glose",
      removeExample: "Fjern eksempel",
      source: "Kilde",
      markdown: "Feltet støtter markdown. Bruk formatet [Tekst](https://url) for å lage lenke.",
      subjects: "Kun fag markert som forklaringsfag vil vises i lista.",
      gloss: "Gloseord på målspråk",
      originalLanguage: "Originalspråk",
      wordClass: "Ordtype",
      glossHeading: "Glose og ordtype",
      transcriptions: "Transkripsjoner",
      transcription: "Transkripsjon",
      romanization: "Skriftsystem",
      example: "Eksempel",
      language: "Språk",
      languageVariant: "Språkvariant",
      add: "Legg til {{label}}",
      choose: "Velg {{label}}",
      languageMissingFields: "Alle felter for et språk må fylles ut.",
      exampleMissingFields: "Alle felter for et eksempel må fylles ut.",
      glossMissingFields: "En glose må inneholde alle felter.",
      transcriptionMissingFields: "En transkripsjon kan ikke være tom.",
      editExamples: "Rediger eksempler",
      editExamplesHeading: "Velg eksempelsetninger og språk",
      editExamplesLanguage: "Velg hvilke språk du vil vise på glosekortet",
      displayOnGloss: "Vis dette eksempelet på glosekortet",
      titleSection: "Norsk oversettelse",
      audio: {
        helperText: "Legg til lyd fra lyd-api til glosen.",
        button: "Legg til lyd",
      },
      examples: {
        title: "Eksempler på bruk av glosen",
        description: "Legg inn relevante eksempler på bruk av glosen.",
        exampleOnIndex: "Eksempel {{index}}",
        exampleOnLanguage: `Eksempel {{index}} på {{language}}`,
        exampleTextLabel: `Eksempeltekst på {{language}} for eksempel {{index}}`,
        removeLanguageVariant: "Fjern eksempel {{index}} på {{language}}",
        remove: "Fjern eksempel {{index}}",
      },
    },
    conceptList: {
      edit: "Rediger forklaringsliste",
      remove: "Fjern forklaringsliste",
    },
    abort: "Avbryt",
    edit: "Rediger",
    remove: "Fjern",
    validate: "Valider",
    publish: "Publiser",
    savedOk: "Lagret OK",
    publishedOk: "Publisert OK",
    validationOk: "Ingen valideringsfeil funnet",
    createdOk: "Opprettet OK",
    addNewImage: "Legg til nytt bilde",
    addNewAudio: "Legg til ny lyd",
    notes: {
      heading: "Merknader",
      add: "Legg til merknad",
      remove: "Fjern",
      warning: "En merknad må ha tekst",
      areHere: "Du er her",
      published: "Publisert",
      placeholder: "Skriv inn merknad",
      history: {
        user: "Bruker",
        time: "Når",
        status: "Status",
        heading: "Merknadshistorikk",
        note: "Merknad",
        empty: "Ingen merknader",
      },
    },
    updated: {
      label: "Oppdatert dato",
    },
    published: {
      label: "Publisert dato",
      reset: "Resett dato",
    },
    updatePublished: "Endre publisert dato",
    editImage: "Endre bilde",
    editOriginalImage: "Rediger original bilde",
    editAudio: "Endre lyd",
    editOriginalAudio: "Rediger original lyd",
    editPodcast: "Endre podkast",
    editH5p: "Endre H5P",
    resetToProd: {
      success: "Innhold er tilbakestilt, trykk lagre for å lagre endringene",
    },
    resetToVersion: "Tilbakestill til versjon",
    previewVersion: "Sammenlign med publisert",
    variant: {
      create: "Legg til språk",
      translate: "Oversett til nynorsk",
    },
    remainingCharacters: "Maks {{maxLength}} tegn og du har {{remaining}} igjen.",
    title: {
      label: "Tittel",
    },
    introduction: {
      label: "Ingress",
    },
    metaImage: {
      title: "Metabilde",
      label: "Metabilde",
      imageTitle: "Bildetittel",
      helpLabel: "Hva er et metabilde?",
      copyright: "Opphav",
      change: "Bytt metabilde",
      add: "Velg metabilde",
      remove: "Fjern metabilde",
    },
    availability: {
      everyone: "Alle",
      teacher: "Lærere",
      label: "Tilgjengelighet",
      description: "Hvem er artikkelen ment for:",
    },
    modelReleased: {
      label: "Modellklarert",
      yes: "Ja",
      no: "Nei",
      "not-applicable": "Ikke relevant",
      "not-set": "Ikke valgt",
      description: "Om bildet er modellklarert eller ikke:",
    },
    visualElementPicker: {
      h5p: "H5P",
      url: "Ny ressurs",
      video: "Video",
      image: "Bilde",
    },
    visualElement: {
      title: "Visuelt element",
      label: "Visuelt element",
      helpLabel: "Informasjon om visuelt element",
      video: "Videosøk",
      image: "Bildesøk",
      imageUpload: "Last opp bilde",
      h5p: "H5P",
      description:
        "Visuelt element kan settes forskjellig for hvert språk. Dersom visuelt element ikke finnes vil det hentes automatisk fra et annet språk.",
    },
    workflow: {
      title: "Status",
      change: "Endre status",
      qualityAssurance: "Kvalitetssikring",
      saveAsNew: "Lag kopi",
      deleteLanguageVersion: {
        button: "Slett {{languageVersion}} versjon",
        title: "Slett språkversjon",
        dialog: "Er du sikker på at du vil slette denne språkversjonen?",
      },
      statusInfoTooltip: "Hva er forskjellen på ulike statuser?",
      statusLabel: "Status",
      published: "Det finnes en publisert versjon av dette elementet.",
      multipleTaxonomy: "Artikkelen har flere oppføringer i taksonomi.",
      currentStatus: "Gjeldende status: {{status}}.",
      expiration: {
        warn: "En av revisjonene utløper snart (Må revideres innen {{date}}).",
        expired: "En av revisjonene har utløpt (Utløpte {{date}}).",
      },
      deleteComment: {
        title: "Slett kommentar",
        dialog: "Vil du slette denne kommentaren? Det er ikke mulig å gjenopprette den.",
        button: "Slett",
      },
      addComment: {
        createdBy: "Opprettet av",
        warn: "Husk å legge til kommentar",
        description: "Du har endret ansvarlig uten å legge til kommentar!",
        add: "Legg til ny kommentar",
        label: "Skriv inn kommentar",
      },
      updateComment: "Oppdater kommentar",
      deleteCurrentRevision: {
        buttonLabel: "Slett",
        buttonLabelDirty: "Kan ikke slette revisjon med ulagrede endringer",
        buttonLabelPublished: "Kan ikke slette revisjon med (del)publiserte endringer",
        dialogTitle: "Slett gjeldende revisjon",
        dialogText: "Er du sikker på at du vil slette gjeldende revisjon? Det er ikke mulig å gjenopprette den.",
        dialogCancel: "Avbryt",
        dialogConfirm: "Slett",
      },
    },
    status: {
      new: "Ny - Ikke lagret",
      new_language: "Nytt språk - ikke lagret",
      created: "Opprettet",
      planned: "Planlagt",
      in_progress: "I arbeid",
      external_review: "Eksternt gjennomsyn",
      internal_review: "Sisteblikk",
      quality_assurance: "Kvalitetssikring desk",
      language: "Språk",
      for_approval: "Godkjenning LMA",
      end_control: "Sluttkontroll",
      imported: "Fra spoling",
      draft: "Kladd",
      proposal: "Utkast",
      user_test: "Brukertest",
      awaiting_quality_assurance: "Til kvalitetssikring",
      queued_for_language: "Til språk",
      translated: "Ferdig fra språk",
      quality_assured: "Publiseringsklar",
      queued_for_publishing: "Til publisering",
      quality_assured_delayed: "Publ.klar-utsatt",
      queued_for_publishing_delayed: "Publ-utsatt",
      publish_delayed: "Publ-utsatt",
      published: "Publisert",
      has_published: "Har publisert versjon",
      unlisted: "Lenkedelt",
      unpublished: "Avpublisert",
      awaiting_unpublishing: "Til avpublisering",
      awaiting_archiving: "Utsatt arkivering",
      archived: "Slettet",
      republish: "Til republisering",
      sum: "Totalt",
      private: "Privat",
      ready_for_sharing: "Klar for deling",
      deleted: "Slettet",
      actions: {
        PLANNED: "Planlagt",
        IN_PROGRESS: "I arbeid",
        EXTERNAL_REVIEW: "Eksternt gjennomsyn",
        INTERNAL_REVIEW: "Sisteblikk",
        QUALITY_ASSURANCE: "Kvalitetssikring desk",
        LANGUAGE: "Språk",
        FOR_APPROVAL: "Godkjenning LMA",
        END_CONTROL: "Sluttkontroll",
        DRAFT: "Kladd",
        PROPOSAL: "Utkast",
        USER_TEST: "Brukertest",
        AWAITING_QUALITY_ASSURANCE: "Til kvalitetssikring",
        QUEUED_FOR_LANGUAGE: "Til språk",
        TRANSLATED: "Ferdig fra språk",
        QUALITY_ASSURED: "Publiseringsklar",
        QUEUED_FOR_PUBLISHING: "Til publisering",
        QUALITY_ASSURED_DELAYED: "Publ.klar-utsatt",
        QUEUED_FOR_PUBLISHING_DELAYED: "Publ-utsatt",
        PUBLISH_DELAYED: "Publ-utsatt",
        PUBLISHED: "Publisert",
        AWAITING_UNPUBLISHING: "Til avpublisering",
        UNPUBLISHED: "Avpublisert",
        ARCHIVED: "Slettet",
        AWAITING_ARCHIVING: "Utsatt arkivering",
        REPUBLISH: "Til republisering",
      },
      learningpath_statuses: {
        private: "I arbeid",
        published: "Publisert",
        unlisted: "Lenkedelt",
        submitted: "Bedt om offentliggjøring",
      },
    },
    validDate: {
      label: "Gyldighet",
      from: {
        label: "Gyldig fra",
        placeholder: "Fra og med dato",
      },
      to: {
        label: "Gyldig til",
        placeholder: "Til og med dato",
      },
    },
    content: {
      label: "Innhold",
      placeholder: "Innhold",
      figure: {
        notSupported: "Mediatype {{mediaType}} er ikke støttet.",
      },
      relatedArticle: {
        placeholder: "Søk på tittel",
        urlPlaceholder: "http://www.example.com",
        urlLocation: "Nettside hos {{domain}}",
        titlePlaceholder: "Tittel",
        invalidArticle: "Ugyldig artikkel",
        addExternal: "Legg til ekstern artikkel",
        removeExternal: "Slett ekstern artikkel",
        changeExternal: "Endre ekstern artikkel",
        searchExternal: "Skriv inn tittel og url på ekstern artikkel",
        listLabel: "Valg",
      },
      conceptList: {
        subjectMissing: "Fag mangler: {{subjectId}}",
      },
      concept: {
        remove: "Fjern forklaring",
        choose: "Velg forklaring",
      },
      gloss: {
        remove: "Fjern glose",
        choose: "Velg glose",
      },
      link: {
        name: "Navn",
        domains: "Url",
        validDomains: "Gyldige domener",
        goTo: "Gå til",
        insert: "Sett inn lenke",
        update: "Oppdater lenke",
        change: "Endre",
        remove: "Fjern lenke",
        href: "Lenke",
        newTab: "Åpne lenke i ny fane",
        text: "Tekst",
        addTitle: "Legg til lenke",
        changeTitle: "Endre lenke",
        required: "Lenke er påkrevd",
        invalid: "Ugyldig lenke",
        preview: "Forhåndsvis lenke",
        unSupported: "Innholdstypen i lenken er ikke støttet",
        newUrlResource: "Ny ressurs",
        changeUrlResource: "Rediger ressurs: {{type}}",
        fullscreen: "Åpne i nytt vindu",
        description:
          "Lenker til ndla-ressurser spesialhåndteres av systemet og vises korrekt på {{url}}. Interne ressurser vises med lilla bakgrunn og eksterne lenker med blå.",
      },
      footnote: {
        title: "Tittel",
        year: "År",
        authors: {
          label: "Forfatter",
          description: "Obligatorisk med minst 1 forfatter.",
          createOption: "Opprett ny forfatter",
        },
        edition: "Utgave",
        publisher: "Utgiver",
        addTitle: "Legg til fotnote",
        editTitle: "Rediger fotnote",
        removeFootnote: "Fjern fotnote",
      },
      table: {
        "row-remove": "Fjern rad",
        "row-add": "Legg til rad",
        "column-add": "Legg til kolonne",
        "column-remove": "Fjern kolonne",
        "table-remove": "Fjern tabell",
        colgroups: "Colgroups",
        colgroupTitle: "Colgroups for å sette bredde",
        colgroupInfo: "Eksempel: ",
        "edit-colgroups": "Rediger colgroups",
        "enable-header": "Aktiver tittel-kolonne",
        "disable-header": "Deaktiver tittel-kolonne",
        addHeader: "Legg til tittel-rad",
        "column-left": "Venstrejuster kolonne",
        "column-center": "Midtstill kolonne",
        "column-right": "Høyrejuster kolonne",
        row: "rad",
        column: "kolonne",
      },
      normalizedOnLoad:
        "Artikkelen inneholder html-kode som er endret av editoren. Derfor må ressursen republiseres selv om du bare har endret metadata eller læreplankoder.",
      symbol: {
        title: "Sett inn symbol",
        insert: "Sett inn",
      },
    },
    tags: {
      label: "Nøkkelord",
      helpLabel: "Hva er nøkkelord?",
      description: "Obligatorisk med 3 nøkkelord.",
      createOption: "Opprett nytt nøkkelord",
      searchPlaceholder: "Søk etter nøkkelord",
    },
    grepCodes: {
      label: "Kompetansemål og kjerneelementer",
      placeholder: "Skriv inn kode",
      description:
        "Skriv inn koder som starter på riktig format ({{ codes }}) fulgt av ett eller flere siffer. Koder som ikke finnes vil ikke bli opprettet. Separer flere koder med komma. Tekstene vises på bokmål i ed men korrekt i artikkelvisning. Du kan også filtrere på læreplankoder.",
      expired: "Denne koden er ikke lenger aktiv",
    },
    articleDisclaimer: {
      title: "Informasjon om tilgjengelighet for hele artikkelen",
      description:
        "Skriv inn hva som er utfordrende med innholdet i artikkelen. Du kan også legge til lenker til alternativt innhold. Det er utarbeidet maler for dette. Sjekk disse <0>her</0> før du tar i bruk komponenten. ",
    },
    resourceTypes: {
      label: "Innholdstype og egenskaper",
      placeholder: "Legg til egenskap",
    },
    subjects: {
      label: "Fag",
      searchPlaceholder: "Søk etter fag",
      placeholder: "Legg til fag",
    },
    topics: {
      label: "Emnetilknytning",
      placeholder: "Legg til emnetilknytning",
      primaryTopic: "Primærkobling",
      sharedTopic: "Delt emne",
      setPrimaryTopic: "Velg som primærkoblet emne",
      RGTooltip: "Velg mellom Kjernestoff eller Tilleggsstoff",
    },
    metaDescription: {
      label: "Metabeskrivelse",
      helpLabel: "Hva er metabeskrivelse?",
      description: "Beskrivelsen blir synlig i søk.",
    },
    articleSummary: {
      label: "Oppsummering",
      description: "KI-generert oppsummering av artikkelen. Lagres ikke.",
    },
    agreement: {
      label: "Koble til avtale",
      helpLabel: "Hva er en avtale?",
      placeholder: "Søk etter avtale",
    },
    rightsholders: {
      label: "Rettighetshaver",
      labelRemove: "Fjern",
      placeholder: "Skriv navn til rettighetshaver",
      createOption: "Opprett ny rettighetshaver",
    },
    processors: {
      label: "Bearbeider",
      labelRemove: "Fjern",
      placeholder: "Skriv navn til bearbeider",
      createOption: "Opprett ny bearbeider",
    },
    creators: {
      label: "Opphavsperson",
      labelRemove: "Fjern",
      placeholder: "Skriv navn til opphavsperson",
      createOption: "Opprett ny opphavsperson",
      description: "Obligatorisk med minst 1 opphavsperson.",
    },
    license: {
      label: "Lisens",
      helpLabel: "Hva er lisenser?",
      choose: "Velg en lisens",
    },
    responsible: {
      label: "Ansvarlig",
      choose: "Velg ansvarlig",
      noResults: "Ingen treff",
      noResponsible: "Ingen ansvarlig",
      revisionDate: "Antall som nærmer seg revisjonsdato",
      error: "Noe gikk galt ved oppdatering av ansvarlig.",
    },
    origin: {
      label: "Kilde",
    },
    processed: {
      label: "Bearbeidet",
      description: "Innholdet har blitt bearbeidet",
      disabledCause: "Bearbeidet kan kun settes dersom kilde er satt",
    },
    image: {
      file: "Bilde",
      save: "Lagre bilde",
      editImage: "Rediger bildet",
      removeImage: "Fjern bilde",
      alignment: {
        left: "Justering: Venstrestilt",
        right: "Justering: Høyrestilt",
        center: "Justering: Stort i midten",
      },
      sizes: {
        xsmall: "Størrelse: Frimerke",
        small: "Størrelse: Lite",
        medium: "Størrelse: Middels",
        fullwidth: "Størrelse: Stort",
      },
      crop: "Lag utsnitt av bildet",
      aspect: {
        "4_3": "4:3",
        "3_4": "3:4",
        "16_9": "16:9",
        square: "Kvadratisk",
        none: "Fritt",
      },
      focalPoint: "Sett fokalpunkt",
      caption: {
        label: "Bildetekst",
        placeholder: "Bildetekst",
        hide: "Skjul bildetekst",
      },
      alt: {
        label: "Alt-tekst",
        placeholder: "Alt-tekst",
        noText: "Universell utforming krever alt-tekst for bilder som ikke er dekorative.",
      },
      fileUpload: {
        description: "Dra og slipp eller trykk for å laste opp bilde",
        button: "Legg til",
        genericError: "Opplastning av bildefil feilet",
        tooLargeError: "Bildefil er for stor",
        fileTypeInvalidError: "Filtypen er ikke støttet",
      },
      byline: {
        show: "Vis byline",
        hide: "Skjul byline",
      },
      isDecorative: "Bildet er kun dekorativt i denne sammenhengen",
      showBorder: "Vis bilderamme",
    },
    video: {
      caption: {
        label: "Videotekst",
        placeholder: "Videotekst",
      },
      remove: "Fjern video",
      save: "Lagre video",
      editVideo: "Rediger video",
      time: {
        start: "Start",
        stop: "Stopp",
        hms: "h:m:s",
      },
      brightcove: "Åpne i Brightcove",
      toLinkedVideo: "Bytt til synstolket versjon",
      fromLinkedVideo: "Bytt tilbake til original versjon",
      linkedVideoButton: "ST",
    },
    h5p: {
      remove: "Fjern H5P",
      copy: "Kopier H5P",
      copyError: "Kopiering av H5P feilet",
      metadata: {
        alttext: "Alt-tekst",
        save: "Lagre",
        cancel: "Avbryt",
        edit: "Endre H5P metadata",
        description: "Metadataen lagres i artikkelen og vil ikke påvirke H5P-ressursen",
      },
    },
    audio: {
      file: "Lydfil",
      title: {
        label: "Lydtittel",
        placeholder: "Lydtittel",
      },
      manuscript: "Tekstversjon",
      caption: {
        label: "Lydtekst",
        placeholder: "Lydtekst",
      },
      edit: "Rediger lyd",
      remove: "Fjern lydfil",
      chooseAudioType: "Velg lydtype",
      sound: "Lyd",
      speech: "Tale",
      fileUpload: {
        description: "Dra og slipp eller trykk for å laste opp lydfil",
        button: "Legg til",
        genericError: "Opplastning av lydfil feilet",
        fileTypeInvalidError: "Filtypen er ikke støttet",
      },
      copiedFrom: "Lydfil kopieres fra {{language}}. Trykk på søppelbøtten for å slette den og laste opp en ny fil.",
      info: {
        multipleFiles: "Du kan laste opp forskjellig lydfiler for hvert språk.",
        changeFile: "Fjerning og endring av et språk vil ikke påvirke de andre språkene.",
        newLanguage: "Ved oppretting av nytt språk vil en lydfil fra et eksisterende språk foreslås.",
        deleteFiles: "En lydfil slettes kun når den ikke lenger er brukt i et språk.",
      },
      dialog: {
        header: "Lydfiler",
        label: "Informasjon om lyd",
      },
    },
    podcast: {
      remove: "Fjern podkast",
    },
    external: {
      title: "eksternt",
      edit: "Rediger {{type}} element",
      remove: "Fjern {{type}} element",
    },
    related: {
      title: "Relatert innhold",
      subtitle: "Dra artikkel for å endre rekkefølge",
      showMore: "Vis mer relatert innhold",
      showLess: "Vis mindre",
    },
    file: {
      label: "Filer",
      file: {
        label: "Fil",
      },
      download: "Last ned:",
      alt: {
        label: "Alt-tekst",
        placeholder: "Alt-tekst",
      },
      title: {
        label: "Filtittel",
        placeholder: "Filtittel",
      },
      addFile: "Legg til fil",
      removeList: "Fjern filliste",
      placeholder: "Oppgi et filnavn",
      changeName: "Endre navn",
      changeOrder: "Endre rekkefølge",
      removeFile: "Fjern fil",
      missingFileTooltip: "Ser ikke ut til å eksistere på serveren. Den kan ha blitt slettet fra en annen artikkel.",
      missingFilename: "Filtypen støttes ikke",
      fileUpload: {
        description: "Dra og slipp eller trykk for å laste opp fil(er)",
        button: "Legg til",
        genericError: "Opplasting av fil(er) feilet",
        fileTypeInvalidError: "Filtypen er ikke støttet",
        tooManyError: "Maks 5 filer kan lastes opp om gangen",
      },
      showPdf: "Vis ekspandert",
      showPdfTooltip: "Vis ekspandert PDF i artikkel",
    },
    article: {
      label: "Artikkel",
      add: "Legg til artikkel",
    },
    learningpathConnections: {
      sectionTitle: "Bruk av artikkelen i læringsstier",
      title: "Læringsstier som inneholder denne artikkelen",
    },
    myNdla: {
      noFavorites: "Ingen har favorittmerket ressursen.",
      numFavorites: "Ressursen har blitt favorittmerket {{num}} ganger.",
    },
    embedConnections: {
      type: {
        image: "bildet",
        audio: "lydfilen",
        concept: "forklaringen",
        gloss: "glosen",
        article: "artikkelen",
      },
      sectionTitleArticle: "Artikler som bruker {{resource}}",
      sectionTitleConcept: "Forklaringer/gloser som bruker {{resource}}",
      title: "Bruk av {{resource}}",
      info: {
        image: "Bruk av bildet i artikler og/eller forklaringer",
        audio: "Bruk av lydfilen i artikler",
        concept: "Bruk av forklaringen i artikler",
        gloss: "Bruk av glosen i artikler",
        article: "Bruk av artikkelen i andre artikler",
      },
      articles_one: "{{count}} artikkel",
      articles_other: "{{count}} artikler",
      concepts_one: "1 forklaring/glose",
      concepts_other: "{{count}} forklaringer/gloser",
    },
    relatedConcepts: {
      placeholder: "Søk på tittel",
      articlesTitle: "Forklaringer",
      changeOrder: "Endre rekkefølge",
      removeArticle: "Fjern forklaring",
    },
    relatedContent: {
      placeholder: "Søk på tittel",
      articlesTitle: "Innhold",
      changeOrder: "Endre rekkefølge",
      removeArticle: "Fjern innhold",
      addExternal: "Legg til ekstern artikkel",
      link: {
        missingTitle: "Mangler tittel",
        missingUrl: "Url må begynne med http:// eller https://",
        titlePlaceholder: "Tittel",
        urlPlaceholder: "https://example.com",
        addLink: "Legg til",
      },
    },
    section: {
      remove: "Fjern seksjon",
    },
    revisions: {
      add: "Ny revisjon",
      remove: "Fjern revisjon",
      revisionNumber: "Revisjon {{number}}",
      description:
        "Revisjoner krever en beskrivelse og en dato artikkelen utløper på. Bryteren markerer hvorvidt en revisjon er utført eller ikke. Husk at en revidert artikkel må republiseres.",
      datePickerTooltip: "Dato artikkelen utløper dersom revisjonen ikke blir markert som revidert.",
      reminder: "Husk å sjekke om revisjonen du nå har utført krever republisering.",
      switchTooltip: "Hvorvidt artikkelen er revidert eller ikke.",
      inputPlaceholder: "Beskrivelse av revisjonen",
      deleteTooltip: "Fjern denne revisjonen",
    },
    disclaimer: {
      edit: "Endre informasjon on tilgjengelighet",
      title: "Universell utforming - informasjon i løpende tekst",
      description:
        "Skriv inn hva som er problemet med komponenten. Det er utarbeidet maler for dette. Sjekk disse <0>her</0> før du tar i bruk komponenten.",
      editorHeader: "Informasjon om tilgjengelighet for enkeltkomponenter",
    },
    copyright: {
      title: "Rediger lisens",
      edit: "Rediger lisens",
      add: "Legg til lisensiert innhold",
    },
  },
  validation: {
    isRequired: "{{label}} er påkrevd.",
    bothFields: "En {{labelLowerCase}} må inneholde alle felter.",
    isNumeric: "{{label}} må inneholde tall.",
    maxLength: "{{label}} kan ikke ha mer enn {{maxLength}} tegn.",
    minLength: "{{label}} må ha minst {{minLength}} tegn.",
    url: "{{label}} må inneholde en gyldig lenke.",
    urlOrNumber: "{{label}} må inneholde en gyldig lenke eller artikkel-id.",
    dateBeforeInvalid: "{{label}} kan ikke være etter {{afterLabel}}.",
    dateAfterInvalid: "{{label}} kan ikke være før {{beforeLabel}}.",
    minItems_one: "{{label}} feltet må minst inneholde en/ett {{labelLowerCase}}.",
    minItems_other: "{{label}} feltet må minst inneholde {{minItems}} ulike {{labelLowerCase}}",
    noEmptyNote: "En merknad kan ikke være tom",
    noEmptyRevision: "En beskrivelse kan ikke være tom",
    noLicenseWithoutCopyrightHolder: "En lisens kan ikke tas i bruk uten å definere minst en opphaver.",
    maxSizeExceeded: "Filen du prøver å laste opp er for stor. Maksstørrelse: {{maxSize}}. Filstørrelse: {{fileSize}}.",
    grepCodes:
      "Koden er på feil format. Det korrekte formatet er K(E/M) eller TT fulgt av ett eller flere siffer. Eks. KE137, KM2255, TT2",
    podcastImageShape: "Metabilde må være like høyt som det er bredt.",
    podcastImageSize: "Metabilde må være mellom 1400 og 3000 piksler bredt.",
    unfinishedRevision: "Det må være minst en planlagt revisjon.",
    missingRevision: "Det må være minst en revisjon.",
    email: "E-postadressen er ikke gyldig.",
  },
  errorMessage: {
    title: "Oops, noe gikk galt",
    description: "Vi beklager, men en feil oppsto.",
    back: "Tilbake",
    goToFrontPage: "Gå til forsiden",
    invalidUrl: "Ugyldig url",
    noArticleInProd: "Ingen artikkel funnet i prod",
    taxonomy: "Det var et problem ved lasting av taksonomi",
    versionSelect: "Artikkelen finnes ikke i valgt versjon",
    errorWhenFetchingTaxonomyArticle: "Det var et problem ved lasting av den underliggende artikkelen",
    unsavedTaxonomy: "Du har ulagrede endringer. Trykk tilbakestill igjen hvis du ønsker å fortsette.",
    auth0:
      "Autentiseringsfeil. Trykk avbryt for å ta vare på eventuelle endringer du har gjort før du logger inn på nytt. Følgende feilmelding kom fra auth0: {{message}}",
    statusCode: {
      409: "Denne artikkelen har allerede blitt oppdatert. Ta vare på det du har endret og last siden på nytt for å kunne lagre.",
    },
    grepCodes: "Følgende koder har feil format eller eksisterer ikke, og vil ikke bli lagt til: ",
    errorOnSave: "Noe gikk galt under lagring av artikkelen.",
    genericError: "Noe gikk galt, handlingen kunne ikke utføres.",
    missingTaxTitle: "Ikke i taksonomi!",
    missingTax:
      "Artikler og emner kan ikke lagres uten å plasseres i taksonomien. Oppdater taksonomi-blokken og lagre på nytt.",
    invalidTopicPlacements: "Emner uten plassering i taksonomi",
    invalidTopicPlacementsDescription:
      "Nodene som har endt opp her kan ha barn. De har endt opp her fordi de har blitt frakoblet forelder.",
    noTaxNode: "Denne ressursen har ingen plassering i taksonomien. Den må knyttes til en node for å bli tilgjengelig.",
    createNode: "Knytt ressursen til en node",
  },
  warningMessage: {
    fieldWithWrongLanguage: "Dette feltet er hentet fra språkkode: {{language}}",
    translatedField: "Dette feltet er auto-oversatt fra språkkode: nb",
  },
  notFound: {
    description: "Denne siden finnes ikke.",
  },
  forbiddenPage: {
    description: "Du har ikke tilgang til denne siden",
  },
  alertDialog: {
    notSaved: "Dokumentet er ikke lagret, ønsker du å fortsette?",
    needToRefresh:
      "Noen andre har lagret samme artikkel mens du redigerte. For å ta vare på endringene dine må du kopiere dem manuelt og deretter oppdatere siden",
    continue: "Fortsett",
    delete: "Slett",
    confirm: "Bekreft",
    disconnect: "Koble fra",
    loginAgain: "Logg inn på nytt",
    watchOut: "Pass på!",
    cancel: "Avbryt",
  },
  environment: { production: "", staging: "staging", test: "test" },
  taxonomy: {
    nodeType: {
      PROGRAMME: "utdanningsprogram",
      SUBJECT: "fag",
      TOPIC: "emne",
    },
    favorite: { add: "Favorittmarker faget", remove: "Fjern favorittmerking av faget" },
    publishedVersion: "Se publisert versjon",
    noValue: "Ikke satt",
    previewProgrammes: "Forhåndsvis utdanningsprogram i frontend",
    addNode: "Legg til {{nodeType}}",
    newNode: "Nytt {{nodeType}}",
    newNodeName: "Navn på nytt element",
    newResource: "Ny ressurs",
    editStructure: "Rediger struktur",
    editSubjectpage: "Rediger fagforside",
    deleteSubject: "Slett fag",
    addSubject: "Legg til fag",
    subjectName: "Navn på nytt fag",
    addExistingNode: "Flytt eksisterende {{nodeType}} hit",
    addExistingLoading: "Flytter ...",
    addExistingSuccess: "Noden har blitt flyttet!",
    existingNode: "Søk opp eksisterende {{nodeType}} for flytting",
    workflow: "i flyt",
    fullTopic: "Gjennomsnitt:",
    TOPIC: "emnet",
    SUBJECT: "faget",
    PROGRAMME: "utdanningsprogrammet",
    qualityDescription:
      "Gjennomsnitt av kvalitetsvurdering av alle vurderte ressurser i {{nodeType}} ({{count}} vurderte ressurser)",
    average: "Gj.snitt",
    qualityEvaluation: "Satt vurdering av {{nodeType}} som helhet",
    connectExistingNode: "Knytt {{nodeType}} til denne noden",
    connectExistingLoading: "Legger til ...",
    connectExistingSuccess: "Noden har blitt tilknyttet!",
    disconnectNode: "Fjern fra foreldernode",
    confirmDisconnect: "Er du sikker på at du vil koble fra denne noden?",
    newSubject: "Nytt fag",
    newTopic: "Nytt emne",
    resources: "Ressurser",
    nodeSettings: "Innstillinger",
    programmeSettings: "Utdanningsprogram-instillinger",
    subjectSettings: "Faginnstillinger",
    topicSettings: "Emneinnstillinger",
    currentVersion: "Nåværende versjon",
    delete: {
      deleteNode: "Slett {{ nodeType }}",
      deleteResource: "Slett ressurs",
      deleteDisabled: "{{ nodeType }} med {{ childNode }} kan ikke slettes",
      child: "barn",
      subTopic: "underemner",
      topic: "emner",
      confirmDelete: "Er du sikker på at du vil slette dette {{ nodeType }}?",
    },
    version: "Versjon",
    createResource: "Opprett ny ressurs",
    addNewPlannedResource: "Opprett ny planlagt ressurs",
    resourceType: { label: "Kjernestoff eller tilleggstoff", tabTitle: "Endre kjernestoff/tilleggsstoff" },
    title: "Tittel",
    comment: "Kommentar",
    commentPlaceholder: "F.eks. innhold, læremål eller grep",
    contentType: "Innholdstype",
    contentTypePlaceholder: "Velg innholdstype",
    create: "Opprett",
    add: "Legg til",
    getExisting: "Eller hent eksisterende ressurs",
    inProgress: "Denne artikkelen er påbegynt",
    addPriority: "Prioritering",
    supplementary: "Tilleggstoff",
    displayOptions: "Visningsvalg",
    changeName: {
      loadError: "Klarte ikke hente oversettelser",
      updateError: "Klarte ikke oppdatere oversettelser",
      defaultName: "Standardnavn",
      addNewTranslation: "Legg til ny oversettelse",
      buttonTitle: "Endre navn",
      language: "Språk",
      name: "Navn",
      namePlaceholder: "Fagnavn",
      delete: "Slett",
      title: "Endre navn",
      cancel: "Avbryt",
      add: "Legg til",
      noTranslations: "Ingen oversettelser tilgjengelig. Standardnavn vil brukes inntil dette er lagt inn.",
    },
    addTopic: "Legg til nytt emne",
    addTopicHeader: "Legg til emne",
    createTopic: "Opprett nytt emne",
    searchExistingTopic: "Søk etter eksisterende emne",
    errorMessage: "En feil oppsto",
    confirmDeleteTopic: "Er du sikker på at du vil slette emnet?",
    confirmDeleteSubject: "Er du sikker på at du vil slette faget?",
    linkSettings: "Link",
    setPrimary: "Sett til primærkobling",
    addResource: "Legg til ressurs",
    removeResource: "Fjern ressurs fra emne",
    searchResource: "Søk etter ressurs",
    searchArticle: "Søk etter emneartikkel",
    or: "Eller",
    urlPlaceholder: "Lim inn lenke fra ndla.no eller en artikkel-id",
    wrongType: "Obs! Denne ressursen er en annen type",
    noResources: "Ingen ressurser funnet",
    addTopicDescription: "Endre emnebeskrivelse",
    confirmSetPrimary: "Vil du gjøre dette til hovedplassering?",
    jumpToResources: "Hopp til ressurser",
    jumpToStructure: "Hopp til struktur",
    showLMASubject: "Vis LMA-fag",
    showDASubject: "Vis DA-fag",
    showSASubject: "Vis SA-fag",
    swapTopicArticle: {
      failed: "Klarte ikke å bytte emneartikkel",
      placeholder: "Artikkel du vil bytte til",
      info: "Bytt emneartikkel",
      success: "Emneartikkelen er byttet! Last siden på nytt for å få oppdatert navn på emnet.",
    },
    copyResources: {
      info: "Gjenbruk ressurser fra emne",
      placeholder: "Søk opp eksisterende {{nodeType}} for gjenbruk av ressurser",
      done: "Ressurser ferdigkopiert!",
      waiting: "Kopierer ressurser",
      error: "Noe gikk galt under kopiering",
    },
    cloneResources: {
      info: "Kopier og klon ressurser fra emne",
      placeholder: "Søk opp eksisterende {{nodeType}} for kopi av ressurser",
      done: "Ressurser ferdigklonet!",
      waiting: "Kloner ressurser",
      error: "Noe gikk galt under kloning",
    },
    favorites: "Vis favoritter",
    quality: "Vis kvalitet",
    publish: {
      button: "Publiser alle ressurser",
      waiting: "Publiserer ressurser",
      info: "Er du sikker på at du ønsker å publisere alle ressurser som er knyttet til denne noden?",
      done: "Ressurser er publisert",
      error: "Følgende ressurser ble ikke publisert:",
    },
    info: {
      title: "Informasjon",
      subTitle: "Id og synlighet for elementet",
      wrongResourceType: 'Noden er plassert som "{{placedAs}}" i taksonomien, men er av typen "{{isType}}".',
      missingResourceType: "Node med ID {{id}} mangler ressurstype. Den er sannsynligvis slettet.",
      wrongArticleType:
        'Artikkelen er plassert som "{{placedAs}}" i taksonomien, men artikkelen er av typen "{{isType}}".',
      missingArticleType: "Artikkelen med ID {{id}} mangler artikkeltype. Den er sannsynligvis slettet.",
      wrongConnections: "Feilkoblinger",
      wrongConnectionsSubTitle: "Denne artikkelen har feilkoblinger, se listen under.",
      canBeFixedInDatabase: "Artikkeltypen kan endres i databasen for å fikse feilen.",
      notPublished: "Artikkelen har ingen publisert versjon.",
    },
    resource: {
      confirmDelete: "Vil du fjerne ressursen fra denne mappen? Dette vil ikke påvirke plasseringen andre steder",
      copyError:
        "Det oppsto en feil ved kopiering av ressurser. Dobbeltsjekk de kopierte ressursene og prøv å fikse mangler manuelt, eller slett de kopierte ressursene og prøv å kopiere på nytt",
      addResourceConflict: "Ressursen du forsøkte å legge til finnes allerede på emnet.",
      noResourceId: "Klarte ikke hente ut ID fra den valgte ressursen",
      creationFailed: "Klarte ikke å opprette kobling",
    },
    removeLink: "Fjern link",
    resourceTypes: {
      title: "Innholdstype",
      helpLabel: "Hva er en Innholdstype?",
      subTitle: "Hvilken innholdstype har denne ressursen?",
      placeholder: "Velg innholdstype",
    },
    topics: {
      title: "Emnetilknytninger",
      topicPlacement: "Emneplassering",
      helpLabel: "Hva er emnetilknytning?",
      subTitle: "Hvor i taksonomien skal ressursen ligge?",
      subTitleTopic: "Hvor i taksonomien skal emnet ligge?",
      filestructureButton: "Opprett en emnetilknytning",
      chooseTaxonomyPlacement: "Velg plassering i taksonomi",
      changeTaxonomyPlacement: "Endre plassering i taksonomi",
      filestructureHeading: "Velg emnetilknytning",
      filestructureClose: "Lukk",
      addNewTopic: "Legg til nytt emne",
      addNewSubTopic: "Legg til nytt underemne",
      addedTopic: "Lagt til",
      disconnectedTaxonomyWarning: "Ugyldig tilknytning",
      taxonomySubjectConnections:
        "For at en ressurs skal bli tilgjengelig i strukturen må den tilknyttes et eller flere emner.",
      description:
        "Her kan du velge hvor emnet skal ligge i taksonomi. Dersom du endrer plassering i taksonomi, vil ikke det gamle emnet slettes om det har underemner eller ressurser knyttet til seg.",
    },
    grepCodes: {
      edit: "Endre læreplankobling",
      empty: "Ingen registerte koder",
      addNew: "Legg til ny læreplankobling",
      delete: "Fjern {{grepCode}}",
    },
    copyRevisionDates: {
      text: "Er du helt sikker på at du ønsker å kopiere revisjonsdatoen? Dette vil sette alle revisjonsdatoer fra denne noden til alle undernoder og ressurser.",
      buttonText: "Kopier revisjonsdato",
      error: "En feil oppstod under kopiering",
    },
    resourcesPrimary: {
      text: "Er du helt sikker på at du ønsker å gjøre alle tilhørende ressurser om til primærkoblinger?",
      recursiveText:
        "Er du helt sikker på at du ønsker å gjøre alle tilhørende ressurser og underressurser om til primærkoblinger?",
      buttonText: "Gjør alle ressurser om til primærkoblinger",
      recursiveButtonText: "Gjør alle ressurser og underressurser om til primærkoblinger",
      error: "En feil oppstod",
      success: "Alle ressurser er gjort til primærkoblinger",
    },
    goTo: "Åpne i stukturredigering",
    missingResourceType: "Mangler ressurstype",
    metadata: {
      customFields: {
        alterFields: "Legg til/endre metadata",
        addField: "Nytt metadata felt",
        languagePlaceholder: "Språksamling ndla.no",
        explanationSubject: "Forklaringsfag",
        programmeSubject: "Felles programfag",
        oldSubjectId: "ID for videresending",
        subjectCategory: "Fagkategori",
        subjectType: "Fagtype",
        resourceGroupPlaceholder: "Gruppering",
        RGTooltip: "Vis ressurser Gruppert eller Ugruppert",
        subjectLMA: "LMA for faget",
        subjectSA: "SA for faget",
        subjectDA: "DA for faget",
        keyPlaceholder: "Skriv inn nøkkel",
        valuePlaceholder: "Skriv inn verdi",
      },
      placeholders: {
        category: "Velg kategori",
        language: "Velg språk",
        type: "Velg type",
        lma: "Velg LMA",
        sa: "Velg SA",
        da: "Velg DA",
      },
    },
    errors: {
      failedToDeleteConnection: "En feil oppstod ved sletting av noden",
      failedToUpdateConnection: "En feil oppstod ved oppdatering av noden",
      failedToCreateConnection: "En feil oppstod ved opprettelse av noden",
    },
  },
  notions: {
    edit: "Rediger forklaring",
    closeNotion: "Lukk forklaring",
  },
  contextTypes: {
    topic: "Emne",
    frontpage: "Om-NDLA-artikkel",
    concept: "Forklaring",
    gloss: "Glose",
    learningpath: "Læringssti",
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: "Slideshow",
      slideshowTitle: "Filmer i slideshow på forsiden",
      movieGroupHeader: "Filmgrupperinger",
      addMovieToSlideshow: "Legg til film i slideshow",
      addMovieToGroup: 'Legg til film i "{{name}}"',
      comboboxGroupLabel: 'Filmer i gruppen "{{name}}"',
      editMovieGroupName: "Endre navnene til filmgruppen",
      deleteMovieGroup: 'Slett "{{name}}"',
      moveMovieGroupUp: "Flytt opp",
      moveMovieGroupDown: "Flytt ned",
      changeOrder: "Endre rekkefølge",
      removeMovieFromGroup: "Fjern film fra gruppe",
      removeMovieFromSlideshow: "Fjern film fra slideshow",
      createThemeGroup: "Opprett gruppe",
      saveNameChanges: "Lagre endringer",
      cancel: "Avbryt",
      editGroupTitle: "Endre navn på filmgruppen",
      newGroupTitle: "Hva skal gruppen hete?",
      notFound: "Vi finner ikke metadata for denne filmen...",
      moreInfoHeader: "Mer informasjon",
      moreInfoTitle: "Artikkel til Les mer-lenke",
      addArticleToMoreInformation: "Legg til en artikkel",
      removeArticleFromMoreInformation: "Fjern artikkel",
      createGroup: "Lag ny gruppe",
      groupNamePlaceholder: "Skriv navn på {{lang}}",
    },
  },
  conceptForm: {
    title: "Forklaring",
    info: {
      lastUpdated: "Sist oppdatert",
    },
  },
  glossform: {
    title: "Glose",
  },
  editorFooter: {
    buttonLabel: "Kvalitetssikring",
    heading: "Kvalitetssikring:",
    changeStatus: "Endre status",
    back: "Gå tilbake",
    inputHeader: "Din merknad",
    inputHelperText: "Kort merknad påkrevd ved statusendring",
    cancelLabel: "Avbryt",
    saveLabel: "Endre status og lagre utkast",
    warningSaveWithoutComment: "Merknad mangler",
    newStatusPrefix: "Ny status:",
    statusLabel: "Status:",
    changeHeader: "Endringer",
    saveAsNew: "Lagre som kopi",
    prioritized: "Prioritert",
    placeholderPrioritized: "Ingen prioritet",
  },
  taxonomyVersions: {
    title: "Taksonomiversjoner",
    publishedVersion: "Publisert versjon",
    otherVersions: "Øvrige versjoner",
    deleteLocked: "Denne versjonen kan ikke slettes fordi den er låst",
    deletePublished: "Denne versjonen kan ikke slettes fordi den er publisert",
    delete: "Slett versjon",
    locked: "Denne versjonen er låst og kan ikke slettes",
    status: {
      PUBLISHED: "Publisert",
      ARCHIVED: "Arkivert",
      BETA: "Beta",
    },
    about:
      "Denne siden brukes til å se på og administrere taksonomiversjoner. Vær varsom: Å publisere en ny taksonomiversjon vil føre til at alt innhold i den vil være umiddelbart tilgjengelig for sluttbrukere på ndla.no",
    noPublished:
      "Det finnes ingen publisert versjon. Draft-versjonen av taksonomi brukes inntil en versjon blir publisert",
    editVersionTooltip: "Rediger versjon",
    newVersionTitle: "Opprett ny versjon",
    newVersionButton: "Ny versjon",
    editVersionTitle: "Rediger versjon",
    publishTitle: "Publiser versjon",
    publishButton: "Publiser",
    publishWarning:
      "Er du sikker på at du ønsker å publisere denne versjonen? Den nåværende versjonen vil bli arkivert, og alle nye endringer i denne versjonen vil umiddelbart være tilgjengelige på ndla.no",
    deleteWarning: "Er du sikker på at du ønsker å slette denne versjonen?",
    deleteWarningPublished:
      "Er du sikker på at du ønsker å slette den publiserte versjonen? Taksonomi vil revertere tilbake til Draft-versjonen.",
    postError: "Klarte ikke å opprette ny versjon",
    putError: "Klarte ikke å oppdatere versjonen",
    publishError: "Klarte ikke å publisere versjonen",
    deleteError: "Klarte ikke slette versjonen",
    noOtherVersions: "Det finnes ingen andre versjoner!",
    previewVersion: "Forhåndsvis denne versjonen på NDLA.no",
    form: {
      name: {
        label: "Navn",
        placeholder: "Eksempelversjon",
      },
      source: {
        title: "Kildeversjon",
        subTitle: "Velg en annen versjon å basere denne på",
        defaultOption: "Draft",
      },
      locked: {
        title: "Låst",
        subTitle: "Lås versjonen så den ikke kan slettes",
        locked: "Låst",
        unlocked: "Ulåst",
      },
    },
  },
  diff: {
    equalNodes: "Disse nodene er like!",
    defaultVersion: "Draft",
    compareVersions: "Sammenlign versjoner",
    error: {
      originalHashRequired: "originalHash-parameteret er påkrevd i URL'en!",
      doesNotExist: "Denne noden finnes ikke i noen av versjonene!",
      onlyExistsInOriginal: "Denne noden finnes bare i målversjonen",
      onlyExistsInOther: "Denne noden finnes bare i kildeversjonen",
    },
    options: {
      about: "Denne siden lar deg sammenligne et nodetre i to forskjellige versjoner.",
      originalHashLabel: "Målversjon",
      otherHashLabel: "Kildeversjon",
      viewLabel: "Visningstype",
      nodeViewLabel: "Nodevisning",
      fieldViewLabel: "Feltvisning",
      allNodes: "Alle noder",
      changedNodes: "Kun endrede",
      allFields: "Alle felter",
      changedFields: "Kun endrede",
      flat: "Flat",
      tree: "Tre",
    },
    childrenChanged: "Barn endret",
    resourcesChanged: "Ressurser endret",
    diffTypes: {
      ADDED: "Lagt til",
      DELETED: "Mangler",
      MODIFIED: "Endret",
      NONE: "Ingen",
    },
    isRoot: "Rotnode",
    nodeTypeTooltips: {
      SUBJECT: "Dette er et fag",
      TOPIC: "Dette er et emne",
      PROGRAMME: "Dette er et utdanningsprogram",
    },
    fields: {
      id: {
        title: "ID",
      },
      name: {
        title: "Navn",
      },
      contentUri: {
        title: "Innholds-URI",
      },
      parentId: {
        title: "Forelder",
      },
      path: {
        title: "Sti",
      },
      paths: {
        title: "Stier",
      },
      connectionId: {
        title: "Koblings-ID",
      },
      isPrimary: {
        title: "Er primær",
        isOn: "Denne noden er en primærressurs",
        isOff: "Denne noden er ikke en primærressurs",
      },
      rank: {
        title: "Rangering",
      },
      relevance: {
        title: "Relevans",
      },
      translations: {
        title: "Oversettelser",
      },
      articleType: {
        title: "Artikkel-type",
      },
      visible: {
        title: "Synlig",
        isOn: "Synlig",
        isOff: "Usynlig",
      },
      "topic-resources": {
        title: "Gruppering av ressurser",
        isOn: "Gruppert",
        isOff: "Ugruppert",
      },
      requestPublish: {
        title: "Forespurt publisering",
        true: "Ja",
        false: "Nei",
      },
      language: {
        title: "Visningsspråk",
      },
      subjectCategory: {
        title: "Fagkategori",
      },
      explanationSubject: {
        title: "Forklaringsfag",
      },
      oldSubjectId: {
        title: "Gammel fag-ID",
      },
      supportedLanguages: {
        title: "Støttede språk",
      },
      grepCodes: {
        title: "Grep-koder",
      },
      resourceTypes: {
        title: "Ressurstyper",
      },
    },
  },
  metadata: {
    visible: "Synlig",
    notVisible: "er ikke synlig",
    changeVisibility: "Endre synlighet",
  },
  unsavedChanges: "Ulagrede endringer",
  messages: {
    severity: {
      info: "Informasjon",
      warning: "Advarsel",
      success: "Alt OK!",
      danger: "Pass på!",
    },
  },
  delete: "Slett",
  reset: "Tilbakestill",
  campaignBlockForm: {
    title: "Rediger kampanjeblokk",
    delete: "Fjern kampanjeblokk",
    sides: {
      left: "Venstre",
      right: "Høyre",
    },
  },
  linkBlock: {
    deleteBlock: "Fjern lenkeblokk",
    delete: "Fjern lenke",
    edit: "Rediger lenke",
    create: "Sett inn lenke",
    chooseDate: "Velg dato",
    linkExists: "Denne lenken finnes allerede i blokken",
  },
  dragAndDrop: {
    handle: "Håndtak",
  },

  datePicker: {
    chooseMonth: "Måned:",
    chooseYear: "År:",
    labelNext: "Gå til neste måned",
    previousMonth: "Gå til forrige måned",
    goToToday: "Gå til dagens dato",
  },
  remove: "Fjern",
  frontpageForm: {
    error: "En feil oppsto",
    changeArticle: "Velg artikkel",
    addArticle: "Legg til artikkel",
    addArticleToMenu: "Legg til artikkel i meny",
    changeFrontpageArticle: "Skift forsideartikkel",
    search: "Søk etter artikkel",
    frontpageArticle: "Forsideartikkel:",
    noFrontpageArticle: "Ingen forsideartikkel valgt",
    failedTitle: "Klarte ikke vise tittel",
    openChildren: "Vis barn",
    closeChildren: "Skjul barn",
    hide: "Skjul",
    show: "Vis",
  },
  codeEditor: {
    title: "Legg til kodeeksempel",
    subtitle: "kodeeksempel",
    titleLabel: "Tittel",
    programmingLanguage: "Kodespråk",
    edit: "Rediger kodevisning",
    delete: "Fjerne kodevisning",
    languageSelect: "Velg kodespråk:",
    save: "Lagre",
    abort: "Avbryt",
  },
  framedContentForm: {
    changeVariant: {
      colored: "Bruk farget variant",
      neutral: "Bruk nøytral variant",
    },
  },
  blockquoteForm: {
    changeVariant: {
      colored: "Bruk farget variant",
      neutral: "Bruk nøytral variant",
    },
  },
  fileUpload: {
    title: "Last opp filer",
  },
  conceptCompare: {
    title: "Sammenlign språkversjoner",
  },
  conceptPreview: {
    title: "Forhåndsvis forklaring",
  },
  math: "Mattestykke",
  editor: {
    versionHistory: {
      who: "Hvem",
      when: "Når",
      message: "Merknad",
      status: "Status",
    },
  },
  masthead: {
    menu: {
      title: "Åpne meny",
    },
  },
  footer: {
    info: "Nettstedet er utarbeidet som åpen kildekode.",
    editorInChief: "Ansvarlig redaktør:",
  },
  user: {
    buttonLogOut: "Logg ut",
  },
  unsupportedElement: {
    title: 'Ugyldig element: "{{type}}"',
    description: "Dette elementet er ikke støttet her. Du kan enten slette hele elementet, eller trekke ut innholdet",
    noContent: "Elementet hadde ikke noe innhold",
  },
  matomo: {
    visits: "Besøk: {{count}}",
    hits: "Sidevisninger: {{count}}",
    avgTime: "Gj.snitt tid på siden: {{time}} sekunder",
    error: "Noe gikk galt ved henting av besøkstall",
    switchLabel: "Vis besøkstall",
    popoverDescription_one: "{{count}} unik sidevisning, klikk for å se flere besøkstall",
    popoverDescription_other: "{{count}} unike sidevisninger, klikk for å se flere besøkstall",
    noData: "Ingen sidevisninger",
    popoverTitle: "Besøkstall siden desember 2024.",
  },
  textGeneration: {
    error: "Noe gikk galt under generering av tekst. Melding fra tjenesten: {{message}}",
    errorImage: "Noe gikk galt, kunne ikke prosessere bildet.",
    insert: "Sett inn",
    replace: "Erstatt",
    append: "Legg til etter",
    chosenText: "Valgt tekst",
    suggestedText: "Forslag til $t(textGeneration.types.{{type}})",
    dialogTitle: "Generer $t(textGeneration.types.{{type}})",
    generateButton: "Generer $t(textGeneration.types.{{type}})",
    generateTranscription: "Generer transkripsjon",
    types: {
      summary: "oppsummering",
      altText: "alternativ tekst",
      alternativePhrasing: "alternativ formulering",
      metaDescription: "metabeskrivelse",
      reflection: "refleksjonsspørsmål",
    },
    customPrompts: {
      switchLabel: "Egendefinerte prompter",
      roleLabel: "Rolle-prompt",
      roleHelper: 'Beskriv rollen til KI-modellen. F.eks.: "Du er en spesialist innen..."',
      instructionsLabel: "Instruksjons-prompt",
      instructionsHelper: 'Beskriv instruksjonene til KI-modellen. F.eks.: "Du har fått i oppdrag å..."',
    },
    failed: "Her gikk det galt! Klarte ikke å generere $t(textGeneration.types.{{type}}).\n{{error}}",
    failedTranscription: "Her gikk det galt! Klarte ikke å generere transkripsjon.",
    responseBox: "Full respons fra KI-modellen",
  },
  learningpathForm: {
    genericError: "Noe gikk galt under henting av læringsstien",
    header: {
      clone: "Kopier læringssti",
    },
    metadata: {
      title: "Metadata/Innhold",
      titleLabel: "Tittel",
      descriptionLabel: "Beskrivelse",
      metaImageTitle: "Metabilde",
      descriptionPlaceholder: "Beskrivelse av læringsstien",
    },
    steps: {
      title: "Læringssteg",
      typeTitle: "Legg til innhold",
      typeDisabledExplanation: "Stier som opprettes i ED støtter kun ressurs-steg",
      addStep: "Legg til steg",
      noSteps: "Læringsstien har ingen steg ennå.",
      noPublishedVersion: "Denne ressursen har ingen publisert versjon",
      formTypes: {
        text: "Tekst jeg har skrevet selv",
        resource: "Innhold fra NDLA",
        external: "Innhold fra et annet nettsted",
      },
      editStep: "Rediger steg",
      textForm: {
        titleLabel: "Tittel",
        introductionLabel: "Ingress",
        descriptionLabel: "Beskrivelse",
      },
      resourceForm: {
        label: "Artikkel fra NDLA",
        labelHelper: "Søk etter artikkel",
        descriptionLabel: "Beskrivelse",
        descriptionHelper:
          "Beskrivelser er ikke lenger støttet på ressurssteg. Dette feltet dukker kun opp fordi du redigerer et eksisterende steg med beskrivelse. Vi anbefaler å fjerne beskrivelsen.",
      },
      externalForm: {
        urlLabel: "URL",
        titleLabel: "Tittel",
        introductionLabel: "Ingress",
        descriptionLabel: "Beskrivelse",
        descriptionHelper:
          "Beskrivelser er ikke lenger støttet på eksterne ressurser. Dette feltet dukker kun opp fordi du redigerer et eksisterende steg med beskrivelse. Vi anbefaler å fjerne beskrivelsen.",
      },
    },
    preview: {
      heading: "Forhåndsvis læringssti",
      openExternalLink: "Åpne i nytt vindu",
      learningpathMenu: "Innhold i læringssti",
      learningpathMenuTitle: "Læringssteg",
      noSteps: "Læringsstien har ingen steg.",
      showPublished: "Vis publisert versjon",
    },
  },
};

export default phrases;
