/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Produksjonsystem - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Fagstoff ${titleTemplate}`,
    createTopicArticlePage: `Emne ${titleTemplate}`,
    createSubjectpage: `Fagforside ${titleTemplate}`,
    agreementPage: `Avtale ${titleTemplate}`,
    welcomePage: `Forside ${titleTemplate}`,
    structurePage: `Struktur ${titleTemplate}`,
    audioUploaderPage: `Lyd ${titleTemplate}`,
    imageUploaderPage: `Bilde ${titleTemplate}`,
    loginPage: `Logg inn ${titleTemplate}`,
    logoutPage: `Logg ut ${titleTemplate}`,
    ndlaFilmPage: `NDLA Film ${titleTemplate}`,
    podcastUploaderPage: `Podkastepisode ${titleTemplate}`,
    podcastSeriesPage: `Podkastserie ${titleTemplate}`,
    h5pPage: `H5P ${titleTemplate}`,
    publishRequestsPage: `Publiseringsforespørsler ${titleTemplate}`,
    nodeDiffPage: `Sammenlign noder ${titleTemplate}`,
    search: {
      'podcast-series': `Søk podkastserier ${titleTemplate}`,
      audio: `Søk lydfiler ${titleTemplate}`,
      concept: `Søk forklaringer ${titleTemplate}`,
      content: `Søk innhold ${titleTemplate}`,
      image: `Søk bilder ${titleTemplate}`,
    },
  },
  dropdown: {
    numberHits: `Søket gav {{hits}} treff`,
    searching: 'Søker...',
    create: 'Opprett nytt',
    isSelectedItem: 'Lagt til',
  },
  meta: {
    description:
      'Kvalitetssikrede fritt tilgjengelige nettbaserte læremidler for videregående opplæring',
  },
  menu: {
    title: 'Meny',
  },
  dialog: {
    close: 'Lukk',
    title: 'Tittel',
    audio: {
      rulesForUse: 'Regler for bruk av lydklipp',
    },
    learnAboutLicenses: 'Lær mer om åpne lisenser',
    source: 'Kilde',
  },
  license: {
    heading: 'Slik gjenbruker du innhold',
    learnMore: 'Lær mer om åpne lisenser',
    copyTitle: 'Kopier referanse',
    hasCopiedTitle: 'Kopiert!',
    embed: 'Bygg inn',
    embedCopied: 'Kopierte innbyggingskode!',
    download: 'Last ned',
    tabs: {
      text: 'Tekst',
      images: 'Bilder',
      audio: 'Lyd',
      video: 'Video',
    },
    images: {
      heading: 'Slik bruker du bilder fra artikkelen',
      description: 'Husk å kopiere teksten som skal legges ved bildet der du bruker det.',
      rules: 'Regler for bruk av bildet:',
      source: 'Kilde',
      title: 'Tittel',
    },
    text: {
      heading: 'Slik bruker du tekst fra artikkelen',
      description: 'Artikkelen kan være sammensatt av flere tekster som listes opp her.',
      rules: 'Regler for bruk av teksten:',
      published: 'Publiseringsdato',
    },
    audio: {
      heading: 'Slik bruker du lydfiler',
      description: 'Husk å kopiere teksten som skal legges ved lydfilen der du bruker den.',
      rules: 'Regler for bruk av lydfilen:',
    },
    video: {
      heading: 'Slik bruker du video fra artikkelen',
      description: 'Husk å kopiere teksten som skal legges ved videoen der du bruker den.',
      rules: 'Regler for bruk av videoen:',
    },
  },
  language: {
    en: 'Engelsk',
    nb: 'Bokmål',
    nn: 'Nynorsk',
    se: 'Nordsamisk',
    sma: 'Sørsamisk',
    und: 'Udefinert',
    de: 'Tysk',
    ukr: 'Ukrainsk',
    empty: 'Ingen flere språk',
    change: 'Bytt til {{language}} versjon',
  },
  welcomePage: {
    addSearch: 'Legg til nytt søk',
    deleteSavedSearch: 'Slett lagret søk',
    deleteSearch: 'Slett søk',
    emptyLastUsed: 'Ingen sist redigerte',
    emptySavedSearch: 'Ingen lagrede søk',
    guidelines: 'Retningslinjer',
    mustBeSearch: 'Lenken må være til et søk',
    lastUsed: 'Sist redigert',
    savedSearch: 'Lagrede søk',
    saveSearch: 'Lagre søk',
  },
  searchPage: {
    header: {
      content: 'Søk etter innhold',
      audio: 'Søk etter lydfiler',
      image: 'Søk etter bilder',
      concept: 'Søk etter forklaringer',
      'podcast-series': 'Søk etter podkastserier',
    },
    searchButton: 'Søk',
    emptyButton: 'Tøm',
    title: 'Tittel',
    language: 'Språk',
    contentNoHits: 'Ingen innhold samsvarte med søket ditt på: {{query}}',
    'podcast-seriesNoHits': 'Ingen serier samsvarte med søket ditt på: {{query}}',
    conceptNoHits: 'Ingen forklaringer samsvarte med søket ditt på: {{query}}',
    audioNoHits: 'Ingen lydfiler samsvarte med søket ditt på: {{query}}',
    imageNoHits: 'Ingen bilder samsvarte med søket ditt på: {{query}}',
    pageSize: '{{pageSize}} treff per side',
    totalCount: 'Antall søketreff',
    highlights: {
      title: 'Søketreff',
      content: 'Søketreff fra innhold',
      tags: 'Søketreff fra nøkkelord',
      embedAttributes: 'Søketreff fra innebygde elementer',
      notes: 'Søketreff fra versjonslogg',
      previousVersionsNotes: 'Søketreff fra versjonslogg',
    },
    save: {
      alreadyExist: 'Søket er allerede lagret.',
      fetchFailed: 'Kunne ikke laste lagrede søk.',
      other: 'Søk feilet.',
    },
  },
  articleType: {
    'topic-article': 'Emne',
    standard: 'Læringsressurs',
  },
  subNavigation: {
    media: 'Media',
    learningPath: 'Læringssti',
    learningPathLink: 'Gå til læringssti',
    brightcoveLink: 'Gå til Brightcove',
    subjectMatter: 'Opprett læringsressurs',
    detailSearch: 'Detaljsøk',
    topicArticle: 'Opprett emne',
    learningResource: 'Læringsressurs',
    image: 'Nytt bilde',
    audio: 'Ny lydfil',
    podcast: 'Ny podkastepisode',
    podcastSeries: 'Ny podkastserie',
    agreement: 'Ny avtale',
    structure: 'Strukturredigering',
    taxonomyVersions: 'Taksonomiversjoner',
    publishRequests: 'Publiseringsforespørsler',
    searchContent: 'Søk innhold',
    searchAudio: 'Søk lyd',
    searchPodcastSeries: 'Søk serie',
    searchImage: 'Søk bilde',
    searchConcepts: 'Søk forklaring',
    film: 'Rediger NDLA film',
    h5p: 'Rediger H5P',
    newConcept: 'Opprett forklaring',
    newSubject: 'Opprett fag',
  },
  logo: {
    altText: 'Nasjonal digital læringsarena',
  },
  siteNav: {
    chooseSubject: 'Velg fag',
    search: 'Søk',
    login: 'Logg inn',
  },
  loginFailure: {
    errorMessage: 'Beklager. Innlogging feilet.',
    loginLink: 'Klikk for å prøve igjen.',
    userNotRegistered:
      'Vi kjente ikke igjen epostadressen din. Har du logget inn med riktig adresse?',
  },
  loginProviders: {
    description: 'Logg inn i produksjonssystem med',
  },
  logoutProviders: {
    localLogout: 'Logg ut av produksjonssystem',
    or: 'eller',
    federatedLogout: 'Logg ut av alle tjenester',
    description: 'N.B. Alle tjenester inkluderer autentiseringstjenesten (Google eller Facebook).',
  },
  searchForm: {
    placeholder: 'Søk etter artikler, aktiviteter eller oppgaver',
    types: {
      conceptQuery: 'Søk på forklaring',
      contentQuery: 'Søk på innhold',
      audioQuery: 'Søk på lydfiler',
      podcastSeriesQuery: 'Søk på podkastserier',
      imageQuery: 'Søk på bilder',
      language: 'Velg språk',
      users: 'Velg bruker',
      'model-released': 'Velg modellklarering',
      subjects: 'Velg fag',
      'resource-types': 'Velg innholdstype',
      status: 'Velg status',
      'draft-status': 'Velg status',
      'audio-type': 'Velg lydfiltype',
      license: 'Velg lisens',
      'revision-date-from': 'Revisjonsdato fra',
      'revision-date-to': 'Revisjonsdato til',
    },
    tagType: {
      query: 'Innhold',
      subjects: 'Fag',
      language: 'Språk',
      users: 'Bruker',
      'resource-types': 'Innholdstype',
      status: 'Status',
      'draft-status': 'Status',
      'audio-type': 'Lydfiltype',
      license: 'Lisens',
      'model-released': 'Modellklarering',
      'revision-date-from': 'Revisjonsdato fra',
      'revision-date-to': 'Revisjonsdato til',
    },
    btn: 'Søk',
    empty: 'Tøm',
    articleType: {
      all: 'Alle',
      standard: 'Standard',
      learningResource: 'Læringsressurs',
      topicArticle: 'Emnebeskrivelse',
      image: 'Bilde',
      audio: 'Lyd',
    },
    audioType: {
      standard: 'Lydfil',
      podcast: 'Podkast',
    },
    order: 'Rekkefølge',
    asc: 'Stigende',
    desc: 'Fallende',
    sorting: 'Sortering',
    sort: {
      id: 'Id',
      relevance: 'Relevans',
      title: 'Tittel',
      lastUpdated: 'Sist oppdatert',
      revisionDate: 'Neste revisjon',
    },
    resultError: 'Noe gikk feil med innlasting av type: {{type}}',
  },
  subjectsPage: {
    subjects: 'Fag',
  },
  subjectPage: {
    topics: 'Emner',
  },
  editMarkup: {
    linkTitle: 'Gå til HTML-editor',
    title: 'HTML-editor',
    subTitle: 'Rediger artikkelinnhold med HTML',
    fetchError:
      'En feil oppsto ved lasting av HTML-editoren. Gå tilbake eller prøv å laste siden på nytt.',
    saveError: 'En feil oppsto ved lagring av endringer.',
    back: 'Tilbake',
    helpMessage: {
      tooltip: 'Om HTML-editoren',
      paragraph1:
        'Det er mulig å formatere HTML-koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisningsfunksjonaliteten aktivt. Lagring med ctrl+s fungerer også.',
      paragraph2:
        'For å minimere eventuelle problemer med formatering og for å sikre at at HTML blir konsistent, så blir koden kjørt gjennom de samme transformeringene som den vanlige editoren. Det vil si at den vil prøve å rette opp ugyldig kode. Linjeskift blir fjerna ved lagring og dermed ignorert.',
    },
  },
  imageSearch: {
    modelReleased: {
      yes: 'Modellklarert',
      no: 'Ikke modellklarert',
      'not-applicable': 'Ikke relevant',
      'not-set': 'Ikke valgt',
    },
    placeholder: 'Søk i bilder',
    buttonTitle: 'Søk',
    useImage: 'Bruk bildet',
    metaImageCheckboxLabel: 'Sett som metabilde',
    visualElementCheckboxLabel: 'Sett som visuelt element',
    noTitle: 'Ingen tittel',
    noResultsText: 'Fant ingen bilder på søk. Ønsker du å laste opp et nytt bilde?',
    noResultsButtonText: 'Last opp bilde',
  },
  videoSearch: {
    searchPlaceholder: 'Søk i videoer',
    searchButtonTitle: 'Søk',
    loadMoreVideos: 'Last flere videoer',
    noResults: 'Ingen videoer funnet.',
    addVideo: 'Bruk video',
    previewVideo: 'Forhåndsvis',
    publishedDate: 'Publisert dato',
    duration: 'Varighet',
    interactioncount: 'Visninger',
  },
  mathEditor: {
    editMath: 'Rediger Matematikk',
    preview: 'Forhåndsvisning',
    continue: 'Du kan ha ulagrede endringer i matteeditoren. Vil du fortsette?',
  },
  code: {
    continue: 'Du kan ha ulagrede endringer i kodevisning. Vil du fortsette?',
  },
  h5pElement: {
    fetchError: 'Vi beklager, men en feil oppsto under lasting av H5P-klienten.',
  },
  displayOembed: {
    errorMessage: 'En feil oppsto ved visning av oEmbed-innhold.',
    notSupported: 'oEmbed av type {{type}} og kilde {{provider}} er ikke støttet.',
  },
  audioSearch: {
    searchPlaceholder: 'Søk i lydfiler',
    searchButtonTitle: 'Søk',
    useAudio: 'Velg lyd',
    noResults: 'Ingen resultater funnet',
    noTitle: 'Ingen tittel',
  },
  conceptSearch: {
    searchPlaceholder: 'Søk i forklaringer',
    searchButtonTitle: 'Søk',
    noResults: 'Ingen resultater funnet',
    noTitle: 'Ingen tittel',
    noContent: 'Ingen innhold',
  },
  searchTypes: {
    content: 'Innhold',
    audio: 'Lyd',
    image: 'Bilde',
    concept: 'Forklaring',
    'podcast-series': 'Serie',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element av type {{type}} vil bli fjernet ved lagring.',
  },
  conceptpageForm: {
    articlesTitle: 'Relaterte artikler',
    articlesSubtitle: 'Artikler',
    changeOrder: 'Endre rekkefølge',
    removeArticle: 'Fjern artikkel',
  },
  subjectpageForm: {
    title: 'Fag',
    about: 'Om faget',
    description: 'Beskrivelse',
    metadata: 'Metadata',
    addBanner: 'Velg banner',
    changeBanner: 'Bytt banner',
    editorsChoices: 'Litt forskjellig fra faget',
    articles: 'Artikler',
    addArticle: 'Legg til artikkel',
    removeArticle: 'Fjern artikkel',
    missingVisualElement: 'Visuelt element er påkrevd.',
  },
  filterform: {
    title: 'Filter',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Bildetittel',
      video: 'Videotittel',
      h5p: 'H5P tittel',
      brightcove: 'Videotittel',
      external: 'Innholdstekst',
    },
    visualElementCopyright: 'Opphav',
    removeVisualElement: 'Fjern element',
    info: {
      lastUpdated: 'Sist oppdatert: ',
    },
    title: 'Emne',
    fields: {
      caption: {
        label: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innholdstekst',
        },
        placeholder: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innholdstekst',
        },
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
    },
  },
  agreementForm: {
    title: {
      create: 'Avtale',
      update: 'Avtale',
    },
    fields: {
      title: {
        label: 'Avtaletittel',
        placeholder: 'Avtaletittel',
      },
      content: {
        label: 'Avtalens innhold',
        placeholder: 'Avtalens innhold',
      },
    },
  },
  footnoteForm: {
    title: 'Tittel',
    year: 'År',
    authors: 'Forfatter',
  },
  linkForm: {
    href: 'Lenke',
    text: 'Tekst',
  },
  audioForm: {
    title: 'Lyd',
  },
  podcastSeriesForm: {
    title: 'Podkastserie',
    alreadyPartOfSeries: 'Del av en annen serie',
    description: 'Beskrivelse',
    rss: 'Rss-feed',
  },
  podcastForm: {
    title: 'Podkastepisode',
    fields: {
      header: 'Overskrift',
      introduction: 'Introduksjon',
      coverPhoto: 'Bilde',
      coverPhotoAltText: 'Alt-text',
      manuscript: 'Tekstversjon',
      series: 'Serie',
    },
    information: {
      partOfSeries: 'Denne podkasten er en del av serien',
      removeSeries: 'Fjern serie',
      noSeries: 'Podkasten tilhører ingen serie',
    },
  },
  imageEditor: {
    editImage: 'Rediger bildet',
    remove: {
      crop: 'Fjern utsnitt',
      focalPoint: 'Fjern fokuspunkt',
    },
  },
  imageForm: {
    title: 'Bilde',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Bildetittel',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
    },
    title: 'Læringsressurs',
    validation: {
      missingEmbedData:
        'En eller flere inkluderte lyd-, bilde-, eller videoelementer mangler beskrivende tekst eller alternativ tekst.',
    },
    fields: {
      rightAside: {
        title: 'Høyrespalte',
        moveContent: 'Flytt innhold inn i teksten',
        delete: 'Slett høyrespalte',
      },
      footnotes: {
        edition: 'Utgave',
        publisher: 'Utgiver',
      },
    },
  },
  editorToolbar: {
    bold: 'Fet\n({{ctrl}}+b)',
    bulletedList: 'Punktliste\n({{ctrl}}+l)',
    code: 'Kode\n({{ctrl}}+k)',
    codeblock: 'Kodeblokk',
    concept: 'Forklaring\n({{ctrl}}+alt+c)',
    footnote: 'Fotnote\n({{ctrl}}+alt+f)',
    headingOne: 'Overskrift 1',
    headingThree: 'Overskrift 3\n({{ctrl}}+3)',
    headingTwo: 'Overskrift 2\n({{ctrl}}+2)',
    italic: 'Kursiv\n({{ctrl}}+i)',
    lang: 'Språk\n(alt+l)',
    letterList: 'Bokstavliste\n({{ctrl}}+alt+a)',
    link: 'Lenke\n({{ctrl}}+alt+l)',
    mathml: 'Matte\n(ctrl+m)',
    numberedList: 'Nummerert liste\n({{ctrl}}+alt+1)',
    quote: 'Sitat\n({{ctrl}}+alt+b)',
    sub: 'Senket\n({{ctrl}}+alt+s)',
    sup: 'Hevet\n({{ctrl}}+alt+h)',
    twoColumnList: 'To-kolonners liste',
    underlined: 'Understreket',
  },
  editorBlockpicker: {
    heading: 'Legg til',
    actions: {
      block: 'Seksjon',
      factAside: 'Faktaboks',
      table: 'Tabell',
      bodybox: 'Tekst i ramme',
      details: 'Ekspanderende boks',
      image: 'Bilde',
      video: 'Video',
      audio: 'Lyd',
      h5p: 'H5P',
      url: 'Ressurs fra lenke',
      related: 'Relatert innhold',
      file: 'Fil',
      code: 'Kodevisning',
      podcast: 'Podkastepisode',
      concept: 'Forklaring',
    },
  },
  form: {
    metadataSection: 'Metadata',
    contentSection: 'Innhold',
    workflowSection: 'Versjonslogg og merknader',
    taxonomySection: 'Taksonomi',
    copyrightSection: 'Lisens og bruker',
    articleSection: 'Artikler',
    podcastSection: 'Podkastinformasjon',
    podcastSeriesSection: 'Podkastserie',
    podcastEpisodesSection: 'Episoder',
    podcastEpisodesTypeName: 'Podkaster',
    inlineEdit: 'Hurtigredigering',
    save: 'Lagre',
    saveAsNewVersion: 'Lagre som ny versjon',
    saveAndPublish: 'Lagre og publiser',
    saveDraft: 'Lagre utkast',
    saveTax: 'Lagre taksonomi',
    choose: 'Velg',
    saving: 'Lagrer...',
    saveSearch: 'Lagre søk',
    alreadySaved: 'Lagret',
    saved: 'Lagret ',
    feil: 'Det er fortsatt flere feil i skjemaet',
    copy: 'kopi',
    mustSaveFirst: 'Du må lagre endringene dine først',
    saveAsCopySuccess: 'Ny artikkel lagret',
    preview: {
      button: 'Forhåndsvis',
    },
    name: {
      title: 'Tittel',
      aboutTitle: 'Tittel',
      introduction: 'Ingress',
      creators: 'Opphavsperson',
      rightsholders: 'Rettighetshaver',
      processors: 'Bearbeider',
      tags: 'Nøkkelord',
      license: 'Lisens',
      origin: 'Opphav',
      audioFile: 'Lydfil',
      content: 'Innhold',
      notes: 'Merknader',
      metaDescription: 'Metabeskrivelse',
      metaImageAlt: 'Alt-tekst',
      alttext: 'Alt-tekst',
      caption: 'Bildetekst',
      imageFile: 'Bildefil',
      visualElement: 'Visuelt element',
      visualElementCaption: 'Figur tekst',
      visualElementAlt: 'Alt-tekst',
      validFrom: 'Gyldig fra',
      validTo: 'Gyldig til',
      description: 'Innhold',
      conceptContent: 'Beskrivelse',
      grepCodes: 'Læreplankobling',
      desktopBanner: 'Banner til desktop',
      mobileBanner: 'Banner til mobil',
      concepts: 'Forklaringer',
      relatedContent: 'Relatert innhold',
      subjects: 'Fag',
      header: 'Overskrift',
      manuscript: 'Tekstversjon',
      coverPhotoId: 'Metabilde',
      revisions: 'Revisjoner',
      name: 'Navn',
    },
    previewProductionArticle: {
      button: 'Sammenlign gjeldende versjon med gammel versjon',
      version: 'Versjon {{revision}}',
      current: 'Gjeldende versjon',
      article: 'Artikkel',
    },
    previewLanguageArticle: {
      button: 'Sammenlign språkversjoner',
      title: 'Utkast på {{language}}',
    },
    previewNewWindow: 'Forhåndsvis i nytt vindu',
    contributor: {
      add: 'Legg til',
    },
    concept: {
      create: 'Opprett ny forklaring',
      addText: 'Velg en forklaring under og trykk "koble til fagtekst", eller',
      edit: 'Rediger forklaring',
      addConcept: 'Legg til eksisterende forklaring',
      removeConcept: 'Ta bort forklaring',
      source: 'Kilde',
      markdown: 'Feltet støtter markdown. Bruk formatet [Tekst](https://url) for å lage lenke.',
      subjects: 'Kun fag markert som forklaringsfag vil vises i lista.',
    },
    abort: 'Avbryt',
    edit: 'Rediger',
    remove: 'Fjern',
    validate: 'Valider',
    publish: 'Publiser',
    savedOk: 'Lagret OK',
    publishedOk: 'Publisert OK',
    validationOk: 'Ingen valideringsfeil funnet',
    createdOk: 'Opprettet OK',
    addNewImage: 'Legg til nytt bilde',
    addNewAudio: 'Legg til ny lyd',
    notes: {
      heading: 'Merknader',
      add: 'Legg til merknad',
      remove: 'Ta bort',
      warning: 'En merknad må ha tekst',
      areHere: 'Du er her',
      published: 'Publisert',
      history: {
        user: 'Bruker',
        time: 'Når',
        status: 'Status',
        heading: 'Merknadshistorikk',
        note: 'Merknad',
        empty: 'Ingen merknader',
      },
    },
    updated: {
      label: 'Oppdatert dato',
    },
    published: {
      label: 'Publisert dato',
      reset: 'Resett dato',
    },
    updatePublished: 'Endre publisert dato',
    editImage: 'Endre bilde',
    editOriginalImage: 'Rediger original bilde',
    editAudio: 'Endre lyd',
    editPodcast: 'Endre podkast',
    resetToProd: {
      button: 'Tilbakestill endringer',
      modal: 'Vil du tilbakestille utkastet til slik det er på ndla forsiden?',
      success: 'Innhold er tilbakestilt, trykk lagre for å lagre endringene',
    },
    resetToVersion: 'Tilbakestill til versjon',
    previewVersion: 'Se versjon',
    variant: {
      create: 'Legg til språk',
      translate: 'Oversett til nynorsk',
    },
    remainingCharacters: 'Maks {{maxLength}} tegn og du har {{remaining}} igjen.',
    title: {
      label: 'Tittel',
    },
    introduction: {
      label: 'Ingress',
    },
    metaImage: {
      title: 'Metabilde',
      label: 'Metabilde',
      imageTitle: 'Bildetittel',
      helpLabel: 'Hva er et metabilde?',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
      add: 'Velg metabilde',
      remove: 'Fjern metabilde',
    },
    availability: {
      everyone: 'Alle',
      teacher: 'Lærere',
      label: 'Tilgjengelighet',
      description: 'Hvem er artikkelen ment for:',
    },
    modelReleased: {
      label: 'Modellklarert',
      yes: 'Ja',
      no: 'Nei',
      'not-applicable': 'Ikke relevant',
      'not-set': 'Ikke valgt',
      description: 'Om bildet er modellklarert eller ikke:',
    },
    markdown: {
      button: 'Klikk for å se markdown',
      helpLabel: 'Hva er markdown?',
    },
    visualElement: {
      title: 'Visuelt element',
      label: 'Visuelt element',
      helpLabel: 'Informasjon om visuelt element',
      video: 'Videosøk',
      image: 'Bildesøk',
      imageUpload: 'Last opp bilde',
      h5p: 'H5P',
    },
    workflow: {
      title: 'Status',
      change: 'Endre status',
      qualityAssurance: 'Kvalitetssikring',
      saveAsNew: 'Lag kopi',
      deleteLanguageVersion: {
        button: 'Slett {{languageVersion}} versjon',
        title: 'Slett språkversjon',
        modal: 'Er du sikker på at du vil slette denne språkversjonen?',
      },
      statusInfoTooltip: 'Hva er forskjellen på ulike statuser?',
      statusLabel: 'Status',
      published: 'Det finnes en publisert versjon av dette elementet.',
      multipleTaxonomy: 'Artikkelen har flere oppføringer i taksonomi.',
      currentStatus: 'Gjeldende status: {{status}}.',
      expiration: {
        warn: 'En av revisjonene utløper snart (Må revideres innen {{date}}).',
        expired: 'En av revisjonene har utløpt (Utløpte {{date}}).',
      },
    },
    status: {
      new: 'Ny - Ikke lagret',
      new_language: 'Nytt språk - ikke lagret',
      created: 'Opprettet',
      imported: 'Fra spoling',
      draft: 'Kladd',
      proposal: 'Utkast',
      user_test: 'Brukertest',
      awaiting_quality_assurance: 'Til kvalitetssikring',
      queued_for_language: 'Til språk',
      translated: 'Ferdig fra språk',
      quality_assured: 'Publiseringsklar',
      queued_for_publishing: 'Til publisering',
      quality_assured_delayed: 'Publ.klar-utsatt',
      queued_for_publishing_delayed: 'Publ-utsatt',
      published: 'Publisert',
      has_published: 'Har publisert versjon',
      unlisted: 'Lenkedelt',
      unpublished: 'Avpublisert',
      awaiting_unpublishing: 'Til avpublisering',
      awaiting_archiving: 'Utsatt arkivering',
      archived: 'Slettet',
      actions: {
        DRAFT: 'Kladd',
        PROPOSAL: 'Utkast',
        USER_TEST: 'Brukertest',
        AWAITING_QUALITY_ASSURANCE: 'Til kvalitetssikring',
        QUEUED_FOR_LANGUAGE: 'Til språk',
        TRANSLATED: 'Ferdig fra språk',
        QUALITY_ASSURED: 'Publiseringsklar',
        QUEUED_FOR_PUBLISHING: 'Til publisering',
        QUALITY_ASSURED_DELAYED: 'Publ.klar-utsatt',
        QUEUED_FOR_PUBLISHING_DELAYED: 'Publ-utsatt',
        PUBLISHED: 'Publiser',
        AWAITING_UNPUBLISHING: 'Til avpublisering',
        UNPUBLISHED: 'Avpubliser',
        ARCHIVED: 'Slett',
        AWAITING_ARCHIVING: 'Utsatt arkivering',
      },
      learningpath_statuses: {
        private: 'Kladd',
        published: 'Offentlig',
        unlisted: 'Lenkedelt',
        submitted: 'Bedt om offentliggjøring',
      },
    },
    validDate: {
      label: 'Gyldighet',
      from: {
        label: 'Gyldig fra',
        placeholder: 'Fra og med dato',
      },
      to: {
        label: 'Gyldig til',
        placeholder: 'Til og med dato',
      },
    },
    content: {
      label: 'Innhold',
      placeholder: 'Innhold',
      figure: {
        notSupported: 'Mediatype {{mediaType}} er ikke støttet.',
        confirmDelete: 'Er du sikker på at du vil slette denne figuren?',
      },
      relatedArticle: {
        placeholder: 'Søk på tittel',
        urlPlaceholder: 'http://www.example.com',
        urlLocation: 'Nettside hos {{domain}}',
        titlePlaceholder: 'Tittel',
        invalidArticle: 'Ugyldig artikkel',
        addExternal: 'Legg til ekstern artikkel',
        removeExternal: 'Slett ekstern artikkel',
        changeExternal: 'Endre ekstern artikkel',
        searchExternal: 'Skriv inn tittel og url på ekstern artikkel',
      },
      concept: {
        remove: 'Fjern forklaring',
        choose: 'Velg forklaring',
      },
      link: {
        name: 'Navn',
        domains: 'Url',
        validDomains: 'Gyldige domener',
        goTo: 'Gå til',
        insert: 'Sett inn lenke',
        update: 'Oppdater lenke',
        change: 'Endre',
        remove: 'Fjern lenke',
        href: 'Lenke',
        newTab: 'Åpne lenke i ny fane',
        text: 'Tekst',
        addTitle: 'Legg til lenke',
        changeTitle: 'Endre lenke',
        required: 'Lenke er påkrevd',
        invalid: 'Ugyldig lenke',
        preview: 'Forhåndsvis lenke',
        unSupported: 'Innholdstypen i lenken er ikke støttet',
        newUrlResource: 'Ny ressurs',
        changeUrlResource: 'Rediger ressurs: {{type}}',
        description:
          'Lenker til ndla-ressurser spesialhåndteres av systemet og vises korrekt på {{url}}. Ndla-ressurser vises med blå bakgrunn og eksterne lenker med gul.',
      },
      footnote: {
        title: 'Tittel',
        year: 'År',
        authors: {
          label: 'Forfatter',
          description: 'Obligatorisk med minst 1 forfatter.',
          createOption: 'Opprett ny forfatter',
        },
        edition: 'Utgave',
        publisher: 'Utgiver',
        addTitle: 'Legg til fotnote',
        editTitle: 'Rediger fotnote',
        removeFootnote: 'Fjern fotnote',
      },
      table: {
        'row-remove': 'Fjern rad',
        'row-add': 'Legg til rad',
        'column-add': 'Legg til kolonne',
        'column-remove': 'Fjern kolonne',
        'table-remove': 'Fjern tabell',
        colgroups: 'Colgroups',
        colgroupTitle: 'Colgroups for å sette bredde',
        colgroupInfo: 'Eksempel: ',
        'edit-colgroups': 'Rediger colgroups',
        'enable-header': 'Aktiver tittel-kolonne',
        'disable-header': 'Deaktiver tittel-kolonne',
        addHeader: 'Legg til tittel-rad',
        'column-left': 'Venstrejuster kolonne',
        'column-center': 'Midtstill kolonne',
        'column-right': 'Høyrejuster kolonne',
        row: 'rad',
        column: 'kolonne',
      },
    },
    tags: {
      label: 'Nøkkelord',
      helpLabel: 'Hva er nøkkelord?',
      description: 'Obligatorisk med 3 nøkkelord.',
      createOption: 'Opprett nytt nøkkelord',
      searchPlaceholder: 'Søk etter nøkkelord',
    },
    categories: {
      label: 'Liste og filter',
      description: 'Format: Liste:Filter1:Filter2',
      searchPlaceholder: 'Søk etter lister',
    },
    grepCodes: {
      label: 'Kompetansemål og kjerneelementer',
      placeholder: 'Skriv inn kode',
      description:
        'Skriv inn koder på formatet K(E/M) eller TT fulgt av ett eller flere siffer. Eks. KE137, KM2255, TT2. Koder som ikke finnes vil ikke bli opprettet. Separer flere koder med komma. Tekstene vises på bokmål i ed men korrekt i artikkelvisning.',
    },
    resourceTypes: {
      label: 'Innholdstype og egenskaper',
      placeholder: 'Legg til egenskap',
    },
    subjects: {
      label: 'Fag',
      searchPlaceholder: 'Søk etter fag',
      placeholder: 'Legg til fag',
    },
    topics: {
      label: 'Emnetilknytning',
      placeholder: 'Legg til emnetilknytning',
      primaryTopic: 'Primærkobling',
      sharedTopic: 'Delt emne',
      setPrimaryTopic: 'Velg som primærkoblet emne',
      RGTooltip: 'Velg mellom Kjernestoff eller Tilleggsstoff',
    },
    metaDescription: {
      label: 'Metabeskrivelse',
      helpLabel: 'Hva er metabeskrivelse?',
      description: 'Beskrivelsen blir synlig i søk.',
    },
    agreement: {
      label: 'Koble til avtale',
      helpLabel: 'Hva er en avtale?',
      placeholder: 'Søk etter avtale',
    },
    rightsholders: {
      label: 'Rettighetshaver',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv navn til rettighetshaver',
      createOption: 'Opprett ny rettighetshaver',
    },
    processors: {
      label: 'Bearbeider',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv navn til bearbeider',
      createOption: 'Opprett ny bearbeider',
    },
    creators: {
      label: 'Opphavsperson',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv navn til opphavsperson',
      createOption: 'Opprett ny opphavsperson',
      description: 'Obligatorisk med minst 1 opphavsperson.',
    },
    license: {
      label: 'Lisens',
      helpLabel: 'Hva er lisenser?',
      choose: 'Velg en lisens',
    },
    origin: {
      label: 'Opphav',
    },
    image: {
      file: 'Bilde',
      save: 'Lagre bilde',
      editImage: 'Rediger bildet',
      removeImage: 'Ta bort bilde',
      alignment: {
        left: 'Justering: Venstrestilt',
        right: 'Justering: Høyrestilt',
        center: 'Justering: Stort i midten',
      },
      sizes: {
        xsmall: 'Størrelse: Frimerke',
        small: 'Størrelse: Lite',
        medium: 'Størrelse: Middels',
        fullwidth: 'Størrelse: Stort',
      },
      crop: 'Lag utsnitt av bildet',
      focalPoint: 'Sett fokalpunkt',
      caption: {
        label: 'Bildetekst',
        placeholder: 'Bildetekst',
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
        noText: 'Universal utforming krever alt-tekst.',
      },
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp bilde',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp bilde',
      },
      byline: {
        show: 'Vis byline',
        hide: 'Skjul byline',
      },
    },
    video: {
      caption: {
        label: 'Videotekst',
        placeholder: 'Videotekst',
      },
      remove: 'Fjern video',
      save: 'Lagre video',
      time: {
        start: 'Start',
        stop: 'Stopp',
        hms: 'h:m:s',
      },
      brightcove: 'Åpne i Brightcove',
      toLinkedVideo: 'Bytt til synstolket versjon',
      fromLinkedVideo: 'Bytt tilbake til original versjon',
      linkedVideoButton: 'ST',
    },
    audio: {
      file: 'Lydfil',
      title: {
        label: 'Lydtittel',
        placeholder: 'Lydtittel',
      },
      manuscript: 'Tekstversjon',
      caption: {
        label: 'Lydtekst',
        placeholder: 'Lydtekst',
      },
      remove: 'Ta bort lydfil',
      sound: 'Lyd',
      speech: 'Tale',
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp lydfil',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp lydfil',
      },
      copiedFrom:
        'Lydfil kopieres fra {{language}}. Trykk på søppelbøtten for å fjerne den og laste opp en ny fil.',
      info: {
        multipleFiles: 'Du kan laste opp forskjellig lydfiler for hvert språk.',
        changeFile: 'Fjerning og endring av et språk vil ikke påvirke de andre språkene.',
        newLanguage:
          'Ved oppretting av nytt språk vil en lydfil fra et eksisterende språk foreslås.',
        deleteFiles: 'En lydfil slettes kun når den ikke lenger er brukt i et språk.',
      },
      modal: {
        header: 'Lydfiler',
        label: 'Informasjon om lyd',
      },
    },
    podcast: {
      remove: 'Ta bort podkast',
    },
    external: {
      title: 'eksternt',
      edit: 'Rediger {{type}} element',
      remove: 'Fjern {{type}} element',
    },
    related: {
      title: 'Relatert innhold',
      subtitle: 'Dra artikkel for å endre rekkefølge',
      showMore: 'Vis mer relatert innhold',
      showLess: 'Vis mindre',
    },
    file: {
      label: 'Filer',
      file: {
        label: 'Fil',
      },
      download: 'Last ned:',
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
      title: {
        label: 'Filtittel',
        placeholder: 'Filtittel',
      },
      addFile: 'Legg til fil',
      removeList: 'Fjern filliste',
      placeholder: 'Oppgi et filnavn',
      changeName: 'Endre navn',
      changeOrder: 'Endre rekkefølge',
      removeFile: 'Ta bort fil',
      missingFileTooltip:
        'Ser ikke ut til å eksistere på serveren. Den kan ha blitt slettet fra en annen artikkel.',
      missingFilename: 'Filtypen støttes ikke',
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp file(r)',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp file(r)',
        noFilesAdded: 'Ingen filer er lagt til',
      },
      showPdf: 'Vis ekspandert',
      showPdfTooltip: 'Vis ekspandert PDF i artikkel',
    },
    article: {
      label: 'Artikkel',
      add: 'Legg til artikkel',
    },
    learningpathConnections: {
      sectionTitle: 'Bruk av artikkelen i læringsstier',
      title: 'Læringsstier som inneholder denne artikkelen',
    },
    embedConnections: {
      type: {
        image: 'bildet',
        audio: 'lydfilen',
        concept: 'forklaringen',
        article: 'artikkelen',
      },
      sectionTitleArticle: 'Artikler som bruker {{resource}}',
      sectionTitleConcept: 'Forklaringer som bruker {{resource}}',
      title: 'Bruk av {{resource}}',
      info: {
        image: 'Bruk av bildet i artikler og/eller forklaringer',
        audio: 'Bruk av lydfilen i artikler',
        concept: 'Bruk av forklaringen i artikler',
        article: 'Bruk av artikkelen i andre artikler',
      },
      articles: '{{count}} artikkel',
      articles_plural: '{{count}} artikler',
      concepts: '1 forklaring',
      concepts_plural: '{{count}} forklaringer',
    },
    relatedConcepts: {
      placeholder: 'Søk på tittel',
      articlesTitle: 'Forklaringer',
      changeOrder: 'Endre rekkefølge',
      removeArticle: 'Fjern forklaring',
    },
    relatedContent: {
      placeholder: 'Søk på tittel',
      articlesTitle: 'Innhold',
      changeOrder: 'Endre rekkefølge',
      removeArticle: 'Fjern innhold',
      addExternal: 'Legg til ekstern artikkel',
      link: {
        missingTitle: 'Mangler tittel',
        missingUrl: 'Url må begynne med http:// eller https://',
        titlePlaceholder: 'Tittel',
        urlPlaceholder: 'https://example.com',
        addLink: 'Legg til',
      },
    },
    section: {
      remove: 'Ta bort seksjon',
    },
    revisions: {
      add: 'Ny revisjon',
      remove: 'Fjern revisjon',
      description:
        'Revisjoner krever en beskrivelse og en dato artikkelen utløper på. Bryteren bestemmer hvorvidt en revisjon er utført eller ikke. Lagrede revisjoner kan ikke slettes, bare oppdateres.',
      datePickerTooltip:
        'Dato artikkelen utløper dersom revisjonen ikke blir markert som revidert.',
      switchTooltip: 'Hvorvidt artikkelen er revidert eller ikke.',
      inputPlaceholder: 'Beskrivelse av revisjonen',
      deleteTooltip: 'Fjern denne revisjonen',
    },
  },
  validation: {
    isRequired: '{{label}} er påkrevd.',
    bothFields: 'En {{labelLowerCase}} må inneholde alle felter.',
    isNumeric: '{{label}} må inneholde tall.',
    maxLength: '{{label}} kan ikke ha mer enn {{maxLength}} tegn.',
    minLength: '{{label}} må ha minst {{minLength}} tegn.',
    url: '{{label}} må inneholde en gyldig lenke.',
    urlOrNumber: '{{label}} må inneholde en gyldig lenke eller artikkel-id.',
    dateBeforeInvalid: '{{label}} kan ikke være etter {{afterLabel}}.',
    dateAfterInvalid: '{{label}} kan ikke være før {{beforeLabel}}.',
    minItems: '{{label}} feltet må minst inneholde en/ett {{labelLowerCase}}.',
    minItems_plural: '{{label}} feltet må minst inneholde {{minItems}} ulike {{labelLowerCase}}',
    noEmptyNote: 'En merknad kan ikke være tom',
    noEmptyRevision: 'En beskrivelse kan ikke være tom',
    noLicenseWithoutCopyrightHolder:
      'En lisens kan ikke tas i bruk uten å definere minst en opphaver.',
    maxSizeExceeded:
      'Filen du prøver å laste opp er for stor. Maksstørrelse: {{maxSize}}. Filstørrelse: {{fileSize}}.',
    grepCodes:
      'Koden er på feil format. Det korrekte formatet er K(E/M) eller TT fulgt av ett eller flere siffer. Eks. KE137, KM2255, TT2',
    podcastImageShape: 'Metabilde må være like høyt som det er bredt.',
    podcastImageSize: 'Metabilde må være mellom 1400 og 3000 piksler bredt.',
  },
  errorMessage: {
    title: 'Oops, noe gikk galt',
    description: 'Vi beklager, men en feil oppsto.',
    back: 'Tilbake',
    goToFrontPage: 'Gå til forsiden',
    invalidUrl: 'Ugyldig url',
    noArticleInProd: 'Ingen artikkel funnet i prod',
    taxonomy: 'Det var et problem ved lasting av taksonomi',
    errorWhenFetchingTaxonomyArticle:
      'Det var et problem ved lasting av den underliggende artikkelen',
    unsavedTaxonomy: 'Du har ulagrede endringer. Trykk avbryt igjen hvis du ønsker å fortsette.',
    auth0:
      'Autentiseringsfeil. Trykk avbryt for å ta vare på eventuelle endringer du har gjort før du logger inn på nytt. Følgende feilmelding kom fra auth0: {{message}}',
    statusCode: {
      409: 'Denne artikkelen har allerede blitt oppdatert. Ta vare på det du har endret og last siden på nytt for å kunne lagre.',
    },
    grepCodes: 'Følgende koder har feil format eller eksisterer ikke, og vil ikke bli lagt til: ',
  },
  warningMessage: {
    fieldWithWrongLanguage: 'Dette feltet er hentet fra språkkode: {{language}}',
  },
  notFound: {
    description: 'Denne siden finnes ikke.',
  },
  forbiddenPage: {
    description: 'Du har ikke tilgang til denne siden',
  },
  alertModal: {
    notSaved: 'Dokumentet er ikke lagret, ønsker du å fortsette?',
    needToRefresh:
      'Noen andre har lagret samme artikkel mens du redigerte. For å ta vare på endringene dine må du kopiere dem manuelt og deretter oppdatere siden',
    continue: 'Fortsett',
    delete: 'Slett',
    confirm: 'Bekreft',
    loginAgain: 'Logg inn på nytt',
  },
  taxonomy: {
    editStructure: 'Rediger struktur',
    editSubjectpage: 'Rediger fagforside',
    deleteSubject: 'Slett fag',
    addSubject: 'Legg til nytt fag',
    addExistingTopic: 'Flytt eksisterende emne hit',
    addExistingLoading: 'Flytter emne',
    addExistingSuccess: 'Emnet har blitt flyttet!',
    newSubject: 'Nytt fag',
    existingTopic: 'Eksisterende emne',
    newTopic: 'Nytt emne',
    resources: 'Ressurser',
    subjectSettings: 'Faginnstillinger',
    topicSettings: 'Emneinnstillinger',
    currentVersion: 'Nåværende versjon',
    deleteNode: 'Slett',
    confirmDelete: 'Er du sikker på at du vil slette denne noden?',
    changeName: {
      loadError: 'Klarte ikke hente oversettelser',
      updateError: 'Klarte ikke oppdatere oversettelser',
      defaultName: 'Standardnavn',
      addNewTranslation: 'Legg til ny oversettelse',
      buttonTitle: 'Endre navn',
      language: 'Språk',
      name: 'Navn',
      namePlaceholder: 'Fagnavn',
      delete: 'Slett',
      title: 'Endre fagnavn',
      cancel: 'Avbryt',
      add: 'Legg til',
      noTranslations:
        'Ingen oversettelser tilgjengelig. Standardnavn vil brukes inntil dette er lagt inn.',
    },
    addTopic: 'Legg til nytt emne',
    errorMessage: 'En feil oppsto',
    confirmDeleteTopic: 'Er du sikker på at du vil slette emnet?',
    confirmDeleteSubject: 'Er du sikker på at du vil slette faget?',
    linkSettings: 'Link',
    setPrimary: 'Sett til primærkobling',
    addResource: 'Legg til ressurs',
    removeResource: 'Fjern ressurs fra emne',
    searchResource: 'Søk etter ressurs',
    searchArticle: 'Søk etter emneartikkel',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Obs! Denne ressursen er en annen type',
    noResources: 'Ingen ressurser funnet',
    addTopicDescription: 'Endre emnebeskrivelse',
    confirmSetPrimary: 'Vil du gjøre dette til hovedplassering?',
    jumpToResources: 'Hopp til ressurser',
    copyResources: {
      info: 'Gjenbruk ressurser fra emne',
      done: 'Ressurser ferdigkopiert!',
      waiting: 'Kopierer ressurser',
      error: 'Noe gikk galt under kopiering',
    },
    cloneResources: {
      info: 'Kopier og klon ressurser fra emne',
      done: 'Ressurser ferdigklonet!',
      waiting: 'Kloner ressurser',
      error: 'Noe gikk galt under kloning',
    },
    favorites: 'Vis favoritter',
    publish: {
      button: 'Publiser alle ressurser',
      waiting: 'Publiserer ressurser',
      info:
        'Er du sikker på at du ønsker å publisere alle ressurser som er knyttet til denne noden?',
      done: 'Ressurser er publisert',
      error: 'Følgende ressurser ble ikke publisert:',
    },
    info: {
      title: 'Informasjon',
      subTitle: 'Id og synlighet for elementet',
      wrongArticleType:
        'Artikkelen er plassert som "{{placedAs}}" i taksonomien, men artikkelen er av typen "{{isType}}".',
      missingArticleType:
        'Artikkelen med ID {{id}} mangler artikkeltype. Den er sannsynligvis slettet.',
      wrongConnections: 'Feilkoblinger',
      wrongConnectionsSubTitle: 'Denne artikkelen har feilkoblinger, se listen under.',
      canBeFixedInDatabase: 'Artikkeltypen kan endres i databasen for å fikse feilen.',
    },
    resource: {
      confirmDelete:
        'Vil du fjerne ressursen fra denne mappen? Dette vil ikke påvirke plasseringen andre steder',
      copyError:
        'Det oppsto en feil ved kopiering av ressurser. Dobbeltsjekk de kopierte ressursene og prøv å fikse mangler manuelt, eller slett de kopierte ressursene og prøv å kopiere på nytt',
      addResourceConflict: 'Ressursen du forsøkte å legge til finnes allerede på emnet.',
      noResourceId: 'Klarte ikke hente ut ID fra den valgte ressursen',
      creationFailed: 'Klarte ikke å opprette kobling',
    },
    removeLink: 'Fjern link',
    resourceTypes: {
      title: 'Innholdstype',
      helpLabel: 'Hva er en Innholdstype?',
      subTitle: 'Hvilken innholdstype har denne ressursen?',
      placeholder: 'Velg innholdstype',
    },
    topics: {
      title: 'Emnetilknytninger',
      topicPlacement: 'Emneplassering',
      helpLabel: 'Hva er emnetilknytning?',
      subTitle: 'Hvor i taksonomien skal ressursen ligge?',
      subTitleTopic: 'Hvor i taksonomien skal emnet ligge?',
      filestructureButton: 'Opprett en emnetilknytning',
      chooseTaxonomyPlacement: 'Velg plassering i taksonomi',
      changeTaxonomyPlacement: 'Endre plassering i taksonomi',
      filestructureHeading: 'Velg emnetilknytning',
      filestructureClose: 'Lukk',
      addNewTopic: 'Legg til nytt emne',
      addNewSubTopic: 'Legg til nytt underemne',
      addedTopic: 'Lagt til',
      disconnectedTaxonomyWarning: 'Ugyldig tilknytning',
    },
    grepCodes: {
      edit: 'Endre læreplankobling',
      empty: 'Ingen registerte koder',
      addNew: 'Legg til ny læreplankobling',
    },
    copyRevisionDates: {
      text:
        'Er du helt sikker på at du ønsker å kopiere revisjonsdatoen? Dette vil sette alle revisjonsdatoer fra denne noden til alle undernoder og ressurser.',
      buttonText: 'Kopier revisjonsdato',
      error: 'En feil oppstod under kopiering',
    },
    goTo: 'Åpne i stukturredigering',
    missingResourceType: 'Mangler ressurstype',
    metadata: {
      customFields: {
        cancelPublishRequest: 'Avlys forespørsel om delvis publisering av struktur',
        requestPublish: 'Be om delpublisering av struktur',
        requestVersionError: 'Publiseringsforespørsler kan bare opprettes fra standardversjonen',
        alterFields: 'Legg til/endre metadata',
        addField: 'Nytt metadata felt',
        languagePlaceholder: 'Visningsspråk ndla.no',
        explanationSubject: 'Forklaringsfag',
        oldSubjectId: 'ID for videresending',
        subjectCategory: 'Fagkategori',
        subjectType: 'Fagtype',
        resourceGroupPlaceholder: 'Gruppering av ressurser',
        RGTooltip: 'Vis ressurser Gruppert eller Ugruppert',
      },
      placeholders: {
        category: 'Velg kategori',
        language: 'Velg språkkode',
        type: 'Velg type',
      },
    },
  },
  notions: {
    edit: 'Rediger forklaring',
    closeNotion: 'Lukk forklaring',
  },
  contextTypes: {
    topic: 'Emne',
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: 'Slideshow',
      slideshowTitle: 'Filmer i slideshow',
      slideshowSubTitle: 'på forsiden',
      movieGroupHeader: 'Filmgrupperinger',
      addMovieToSlideshow: 'Legg til film i slideshow',
      addMovieToGroup: 'Legg til film i "{{name}}"',
      editMovieGroupName: 'Endre navnene til filmgruppen',
      deleteMovieGroup: 'Slett "{{name}}"',
      moveMovieGroupUp: 'Flytt opp',
      moveMovieGroupDown: 'Flytt ned',
      changeOrder: 'Endre rekkefølge',
      removeMovieFromGroup: 'Ta vekk film fra gruppe',
      removeMovieFromSlideshow: 'Ta vekk film fra slideshow',
      createThemeGroup: 'Opprett gruppe',
      saveNameChanges: 'Lagre endringer',
      cancel: 'Avbryt',
      editGroupTitle: 'Endre navn(ene) på filmgruppen:',
      newGroupTitle: 'Hva skal gruppen hete?',
      notFound: 'Vi finner ikke metadata for denne filmen...',
    },
  },
  modal: {
    closeModal: 'Lukk',
  },
  conceptform: {
    title: 'Forklaring',
  },
  editorFooter: {
    buttonLabel: 'Kvalitetssikring',
    heading: 'Kvalitetssikring:',
    changeStatus: 'Endre status',
    back: 'Gå tilbake',
    inputHeader: 'Din merknad',
    inputHelperText: 'Kort merknad påkrevd ved statusendring',
    cancelLabel: 'Avbryt',
    saveLabel: 'Endre status og lagre utkast',
    warningSaveWithoutComment: 'Merknad mangler',
    newStatusPrefix: 'Ny status:',
    statusLabel: 'Status:',
    changeHeader: 'Endringer',
    saveAsNew: 'Lagre som kopi',
  },
  taxonomyVersions: {
    title: 'Taksonomiversjoner',
    publishedVersion: 'Publisert versjon',
    otherVersions: 'Øvrige versjoner',
    deleteLocked: 'Denne versjonen kan ikke slettes fordi den er låst',
    deletePublished: 'Denne versjonen kan ikke slettes fordi den er publisert',
    delete: 'Slett versjon',
    locked: 'Denne versjonen er låst',
    status: {
      PUBLISHED: 'Publisert',
      ARCHIVED: 'Arkivert',
      BETA: 'Beta',
    },
    about:
      'Denne siden brukes til å se på og administrere taksonomiversjoner. Vær varsom: Å publisere en ny taksonomiversjon vil føre til at alt innhold i den vil være umiddelbart tilgjengelig for sluttbrukere på ndla.no',
    noPublished:
      'Det finnes ingen publisert versjon. Standard-versjonen av taksonomi brukes inntil en versjon blir publisert',
    editVersionTooltip: 'Rediger versjon',
    newVersionTitle: 'Opprett ny versjon',
    newVersionButton: 'Ny versjon',
    editVersionTitle: 'Rediger versjon',
    publishButton: 'Publiser',
    publishWarning:
      'Er du sikker på at du ønsker å publisere denne versjonen? Den nåværende versjonen vil bli arkivert, og alle nye endringer i denne versjonen vil umiddelbart være tilgjengelige på ndla.no',
    deleteWarning: 'Er du sikker på at du ønsker å slette denne versjonen?',
    deleteWarningPublished:
      'Er du sikker på at du ønsker å slette den publiserte versjonen? Taksonomi vil revertere tilbake til standard-versjonen.',
    postError: 'Klarte ikke å opprette ny versjon',
    putError: 'Klarte ikke å oppdatere versjonen',
    publishError: 'Klarte ikke å publisere versjonen',
    deleteError: 'Klarte ikke slette versjonen',
    noOtherVersions: 'Det finnes ingen andre versjoner!',
    previewVersion: 'Forhåndsvis denne versjonen på NDLA.no',
    form: {
      name: {
        label: 'Navn',
        placeholder: 'Eksempelversjon',
      },
      source: {
        title: 'Kildeversjon',
        subTitle: 'Velg en annen versjon å basere denne på',
        defaultOption: 'N/A',
      },
      locked: {
        title: 'Låst',
        subTitle: 'Er versjonen låst?',
        locked: 'Låst',
        unlocked: 'Ulåst',
      },
    },
  },
  publishRequests: {
    title: 'Publiseringsforespørsler',
    nodePublished: 'Noden har blitt publisert!',
    showInStructure: 'Vis i struktur',
    compare: 'Sammenlign',
    errors: {
      noPublishedVersion: 'Klarte ikke finne publisert versjon',
    },
  },
  diff: {
    published:
      'Nodepubliseringen har startet. Dette kan ta litt tid. Prosessen er fullført når denne siden viser at de to versjonene er like',
    publishing: 'Publiserer node...',
    publish: 'Publiser node',
    publishWarning:
      'Er du sikker på at du ønsker å publisere denne noden? Alle endringer vil umiddelbart bli tilgjengelige i målversjonen',
    publishError: 'Publisering av node feilet',
    equalNodes: 'Disse nodene er like!',
    defaultVersion: 'Standardsversjon',
    compareVersions: 'Sammenlign versjoner',
    error: {
      originalHashRequired: "originalHash-parameteret er påkrevd i URL'en!",
      doesNotExist: 'Denne noden finnes ikke i noen av versjonene!',
      onlyExistsInOriginal: 'Denne noden finnes bare i målversjonen',
      onlyExistsInOther: 'Denne noden finnes bare i kildeversjonen',
    },
    options: {
      originalHashLabel: 'Målversjon',
      otherHashLabel: 'Kildeversjon',
      viewLabel: 'Visningstype',
      nodeViewLabel: 'Nodevisning',
      fieldViewLabel: 'Feltvisning',
      allNodes: 'Alle noder',
      changedNodes: 'Kun endrede',
      allFields: 'Alle felter',
      changedFields: 'Kun endrede',
      flat: 'Flat',
      tree: 'Tre',
    },
    childrenChanged: 'Barn endret',
    resourcesChanged: 'Ressurser endret',
    diffTypes: {
      ADDED: 'Lagt til',
      DELETED: 'Mangler',
      MODIFIED: 'Endret',
      NONE: 'Ingen',
    },
    isRoot: 'Rotnode',
    nodeTypeTooltips: {
      SUBJECT: 'Dette er et fag',
      TOPIC: 'Dette er et emne',
    },
    fields: {
      id: {
        title: 'ID',
      },
      name: {
        title: 'Navn',
      },
      contentUri: {
        title: 'Innholds-URI',
      },
      parent: {
        title: 'Forelder',
      },
      path: {
        title: 'Sti',
      },
      paths: {
        title: 'Stier',
      },
      connectionId: {
        title: 'Koblings-ID',
      },
      isPrimary: {
        title: 'Er primær',
        isOn: 'Denne noden er en primærressurs',
        isOff: 'Denne noden er ikke en primærressurs',
      },
      primary: {
        title: 'Er primær',
        isOn: 'Denne noden er en primærressurs',
        isOff: 'Denne noden er ikke en primærressurs',
      },
      rank: {
        title: 'Rangering',
      },
      relevance: {
        title: 'Relevans',
      },
      translations: {
        title: 'Oversettelser',
      },
      articleType: {
        title: 'Artikkel-type',
      },
      visible: {
        title: 'Synlig',
        isOn: 'Synlig',
        isOff: 'Usynlig',
      },
      'topic-resources': {
        title: 'Gruppering av ressurser',
        isOn: 'Gruppert',
        isOff: 'Ugruppert',
      },
      requestPublish: {
        title: 'Forespurt publisering',
        true: 'Ja',
        false: 'Nei',
      },
      language: {
        title: 'Visningsspråk',
      },
      subjectCategory: {
        title: 'Fagkategori',
      },
      explanationSubject: {
        title: 'Forklaringsfag',
      },
      oldSubjectId: {
        title: 'Gammel fag-ID',
      },
      supportedLanguages: {
        title: 'Støttede språk',
      },
      grepCodes: {
        title: 'Grep-koder',
      },
      resourceTypes: {
        title: 'Ressurstyper',
      },
    },
  },
  metadata: {
    visible: 'er synlig',
    notVisible: 'er ikke synlig',
    changeVisibility: 'Endre synlighet',
  },
  languages: {
    ar: 'Arabisk',
    de: 'Tysk',
    en: 'Engelsk',
    se: 'Nordsamisk',
    sma: 'Sørsamisk',
    so: 'Somali',
    ti: 'Tigrinja',
    zh: 'Kinesisk',
  },
};

export default phrases;
