/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Produksjonsystem - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Fagstoff ${titleTemplate}`,
    createTopicArticlePage: `Emne ${titleTemplate}`,
    createSubjectpage: `Fagforside ${titleTemplate}`,
    agreementPage: `Avtale ${titleTemplate}`,
    welcomePage: `Forside ${titleTemplate}`,
    structurePage: `Struktur ${titleTemplate}`,
    audioUploaderPage: `Lyd ${titleTemplate}`,
    imageUploaderPage: `Bilde ${titleTemplate}`,
    loginPage: `Logg inn ${titleTemplate}`,
    logoutPage: `Logg ut ${titleTemplate}`,
    ndlaFilmPage: `NDLA Film ${titleTemplate}`,
    podcastUploaderPage: `Podkastepisode ${titleTemplate}`,
    podcastSeriesPage: `Podkastserie ${titleTemplate}`,
    h5pPage: `H5P ${titleTemplate}`,
    search: {
      'podcast-series': `Søk podkastserier ${titleTemplate}`,
      audio: `Søk lydfiler ${titleTemplate}`,
      concept: `Søk forklaringer ${titleTemplate}`,
      content: `Søk innhold ${titleTemplate}`,
      image: `Søk bilder ${titleTemplate}`,
    },
  },
  dropdown: {
    numberHits: `Søket gav {{hits}} treff`,
    searching: 'Søker...',
    create: 'Opprett nytt',
    isSelectedItem: 'Lagt til',
  },
  meta: {
    description:
      'Kvalitetssikra fritt tilgjengelige nettbaserte læremidler for videregående opplæring',
  },
  menu: {
    title: 'Meny',
  },
  dialog: {
    close: 'Lukk',
    title: 'Tittel',
    audio: {
      rulesForUse: 'Reglar for bruk av lydklipp',
    },
    learnAboutLicenses: 'Lær meir om opne lisensar',
    source: 'Kjelde',
  },
  license: {
    heading: 'Slik gjenbruker du innhald',
    learnMore: 'Lær meir om opne lisensar',
    copyTitle: 'Kopier referanse',
    hasCopiedTitle: 'Kopiert!',
    embed: 'Bygg inn',
    embedCopied: 'Kopierte innbyggingskode!',
    download: 'Last ned',
    tabs: {
      text: 'Tekst',
      images: 'Bilde',
      audio: 'Lyd',
      video: 'Video',
    },
    images: {
      heading: 'Slik bruker du bilder frå artikkelen',
      description: 'Hugs å kopiera teksten som skal leggjast ved bildet der du bruker det.',
      rules: 'Regler for bruk av bildet:',
      source: 'Kjelde',
      title: 'Tittel',
    },
    text: {
      heading: 'Slik bruker du tekst frå artikkelen',
      description: 'Artikkelen kan vera samansett av fleire ulike tekstar som vert lista her.',
      rules: 'Reglar for bruk av teksten:',
      published: 'Publiseringsdato',
    },
    audio: {
      heading: 'Slik bruker du lydfiler',
      description: 'Hugs å kopiera teksten som skal leggjast ved lydfila der du bruker ho.',
      rules: 'Regler for bruk av lydfila:',
    },
    video: {
      heading: 'Slik bruker du video fra artikkelen',
      description: 'Hugs å kopiera teksten som skal leggjast ved videoen der du bruker han.',
      rules: 'Regler for bruk av videoen:',
    },
  },
  language: {
    en: 'Engelsk',
    nb: 'Bokmål',
    nn: 'Nynorsk',
    se: 'Nordsamisk',
    sma: 'Sørsamisk',
    unknown: 'Ukjent',
    und: 'Udefinert',
    de: 'Tysk',
    ukr: 'Ukrainsk',
    empty: 'Ingen fleire språk',
    change: 'Bytt til {{language}} versjon',
  },
  welcomePage: {
    addSearch: 'Legg til nytt søk',
    deleteSavedSearch: 'Slett lagra søk',
    deleteSearch: 'Slett søk',
    emptyLastUsed: 'Ingen sist redigerte',
    emptySavedSearch: 'Ingen lagra søk',
    guidelines: 'Retningslinjer',
    mustBeSearch: 'Lenka må være til eit søk',
    lastUsed: 'Sist redigert',
    savedSearch: 'Lagra søk',
    saveSearch: 'Lagre søk',
  },
  searchPage: {
    header: {
      content: 'Søk etter innhald',
      audio: 'Søk etter lydfiler',
      image: 'Søk etter bilder',
      concept: 'Søk etter forklaringar',
      'podcast-series': 'Søk etter podkastserier',
    },
    searchButton: 'Søk',
    emptyButton: 'Tøm',
    title: 'Tittel',
    language: 'Språk',
    contentNoHits: 'Ingen innhald samsvarte med søket ditt på: {{query}}',
    conceptNoHits: 'Ingen forklaringar samsvarte med søket ditt på: {{query}}',
    'podcast-seriesNoHits': 'Ingen serier samsvarte med søket ditt på: {{query}}',
    audioNoHits: 'Ingen lydfiler samsvarte med søket ditt på: {{query}}',
    imageNoHits: 'Ingen bilder samsvarte med søket ditt på: {{query}}',
    pageSize: '{{pageSize}} treff per side',
    totalCount: 'Antall søketreff',
    highlights: {
      title: 'Søketreff',
      content: 'Søketreff frå innhold',
      tags: 'Søketreff frå nøkkelord',
      embedAttributes: 'Søketreff frå innebygde elementer',
      notes: 'Søketreff frå versjonslogg',
      previousVersionsNotes: 'Søketreff frå versjonslogg',
    },
    save: {
      alreadyExist: 'Søket er allereie lagra.',
      fetchFailed: 'Kunne ikkje laste lagra søk.',
      other: 'Lagring feila.',
    },
  },
  articleType: {
    'topic-article': 'Emne',
    standard: 'Læringsressurs',
  },
  subNavigation: {
    media: 'Media',
    learningPath: 'Læringssti',
    learningPathLink: 'Gå til læringssti',
    brightcoveLink: 'Gå til Brightcove',
    subjectMatter: 'Opprett læringsressurs',
    detailSearch: 'Detaljsøk',
    topicArticle: 'Opprett emne',
    learningResource: 'Læringsressurs',
    image: 'Nytt bilde',
    audio: 'Ny lydfil',
    podcast: 'Ny podkastepisode',
    podcastSeries: 'Ny podkastserie',
    agreement: 'Ny avtale',
    structure: 'Strukturredigering',
    searchContent: 'Søk innhald',
    searchAudio: 'Søk lyd',
    searchPodcastSeries: 'Søk serie',
    searchImage: 'Søk bilde',
    searchConcepts: 'Søk forklaring',
    film: 'Rediger NDLA film',
    h5p: 'Rediger H5P',
    newConcept: 'Opprett forklaring',
    newSubject: 'Opprett fag',
  },
  logo: {
    altText: 'Nasjonal digital læringsarena',
  },
  siteNav: {
    chooseSubject: 'Velg fag',
    search: 'Søk',
    login: 'Logg inn',
  },
  loginFailure: {
    errorMessage: 'Beklager. Innlogging feila.',
    loginLink: 'Klikk for å prøve igjen.',
    userNotRegistered:
      'Vi kjente ikkje igjen epostadressa di. Har du logga inn med riktig adresse?',
  },
  loginProviders: {
    description: 'Logg inn i produksjonssystem med',
  },
  logoutProviders: {
    localLogout: 'Logg ut av produksjonssystem',
    or: 'eller',
    federatedLogout: 'Logg ut av alle tjenester',
    description: 'N.B. Alle tjenester inkluderer autentiseringstjenesten (Google eller Facebook).',
  },
  searchForm: {
    placeholder: 'Søk etter artikler, aktiviteter eller oppgaver',
    types: {
      conceptQuery: 'Søk på forklaringar',
      contentQuery: 'Søk på innhald',
      audioQuery: 'Søk på lydfiler',
      podcastSeriesQuery: 'Søk på podkastserier',
      imageQuery: 'Søk på bilder',
      language: 'Velg språk',
      users: 'Velg bruker',
      'model-released': 'Velg modellklarering',
      subjects: 'Velg fag',
      'resource-types': 'Velg innhaldstype',
      status: 'Velg status',
      'draft-status': 'Velg status',
      'audio-type': 'Velg lydfiltype',
      license: 'Velg lisens',
    },
    tagType: {
      query: 'Innhald',
      subjects: 'Fag',
      language: 'Språk',
      users: 'Bruker',
      'resource-types': 'Innhaldstype',
      status: 'Status',
      'draft-status': 'Status',
      'audio-type': 'Lydfiltype',
      license: 'Lisens',
      'model-released': 'Modellklarering',
    },
    btn: 'Søk',
    empty: 'Tøm',
    articleType: {
      all: 'Alle',
      standard: 'Standard',
      learningResource: 'Læringsressurs',
      topicArticle: 'Emnebeskrivelse',
      image: 'Bilde',
      audio: 'Lyd',
    },
    audioType: {
      standard: 'Lydfil',
      podcast: 'Podkast',
    },
    order: 'Rekkefølge',
    asc: 'Stigende',
    desc: 'Fallende',
    sorting: 'Sortering',
    sort: {
      id: 'Id',
      relevance: 'Relevans',
      title: 'Tittel',
      lastUpdated: 'Sist oppdatert',
    },
    resultError: 'Noko gjekk feil med innlasting av type: {{type}}',
  },
  subjectsPage: {
    subjects: 'Fag',
  },
  subjectPage: {
    topics: 'Emner',
  },
  editMarkup: {
    linkTitle: 'Gå til HTML-editor',
    title: 'HTML-editor',
    subTitle: 'Rediger artikkelinnhold med HTML',
    fetchError:
      'Ein feil oppsto ved lasting av HTML-editoren. Gå tilbake eller prøv å laste sida på nytt.',
    saveError: 'Ein feil oppsto ved lagring av endringar.',
    back: 'Tilbake',
    helpMessage: {
      tooltip: 'Om HTML-editoren',
      paragraph1:
        'Det er mogeleg å formatere  HTML-koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisningsfunksjonaliteten aktivt. Lagring ved ctrl+s fungerer også.',
      paragraph2:
        'For å minimere eventuelle problemer med formatering og for å sikre at at HTML blir konsistent, så blir koden kjørt gjennom dei samme transformeringane som den vanlige editoren. Det betyr at den vil prøve å rette opp ugyldig kode. Linjeskift blir fjerna ved lagring og dermed ignorert.',
    },
  },
  imageSearch: {
    placeholder: 'Søk i bilder',
    buttonTitle: 'Søk',
    useImage: 'Bruk bildet',
    metaImageCheckboxLabel: 'Sett som metabilde',
    visualElementCheckboxLabel: 'Sett som visuelt element',
    noTitle: 'Ingen tittel',
    noResultsText: 'Fann ingen bilder på søk. Ønskjer du å laste opp eit nytt bilde?',
    noResultsButtonText: 'Last opp bilde',
    modelReleased: {
      yes: 'Modellklarert',
      no: 'Ikkje modellklarert',
      'not-applicable': 'Ikkje relevant',
      'not-set': 'Ikkje valgt',
    },
  },
  videoSearch: {
    searchPlaceholder: 'Søk i videoar',
    searchButtonTitle: 'Søk',
    loadMoreVideos: 'Last fleire videoar',
    noResults: 'Ingen videoar funnet.',
    addVideo: 'Bruk video',
    previewVideo: 'Forhåndsvis',
    publishedDate: 'Publisert dato',
    duration: 'Varighet',
    interactioncount: 'Visninger',
  },
  mathEditor: {
    editMath: 'Rediger Matematikk',
    preview: 'Forhåndsvisning',
    continue: 'Du kan ha ulagra endringar i matteeditoren. Vil du fortsette?',
  },
  code: {
    continue: 'Du kan ha ulagra endringar i kodevisning. Vil du fortsette?',
  },
  h5pElement: {
    fetchError: 'Vi beklagar, men ein feil oppsto under lasting av H5P-klienten.',
  },
  displayOembed: {
    errorMessage: 'Ein feil oppsto ved visning av oEmbed-innhald.',
    notSupported: 'oEmbed av type {{type}} og kjelde {{provider}} er ikkje støtta.',
  },
  audioSearch: {
    searchPlaceholder: 'Søk i lydfiler',
    searchButtonTitle: 'Søk',
    useAudio: 'Velg lyd',
    noResults: 'Ingen resultat funnet',
    noTitle: 'Ingen tittel',
  },
  conceptSearch: {
    searchPlaceholder: 'Søk i forklaringar',
    searchButtonTitle: 'Søk',
    noResults: 'Ingen resultat funnet',
    noTitle: 'Ingen tittel',
    noContent: 'Ingen innhald',
  },
  searchTypes: {
    content: 'Innhald',
    audio: 'Lyd',
    image: 'Bilde',
    concept: 'Forklaring',
    'podcast-series': 'Serie',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element av type {{type}} vil bli fjerna ved lagring.',
  },
  conceptpageForm: {
    articlesTitle: 'Relaterte artiklar',
    articlesSubtitle: 'Artiklar',
    changeOrder: 'Endre rekkefølgje',
    removeArticle: 'Fjern artikkel',
  },
  subjectpageForm: {
    title: 'Fag',
    about: 'Om faget',
    description: 'Beskrivelse',
    metadata: 'Metadata',
    addBanner: 'Velg banner',
    changeBanner: 'Bytt banner',
    editorsChoices: 'Litt forskjellig frå faget',
    articles: 'Artiklar',
    addArticle: 'Legg til artikkel',
    removeArticle: 'Fjern artikkel',
    missingVisualElement: 'Visuelt element er påkrevd.',
  },
  filterform: {
    title: 'Filter',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Bildetittel',
      video: 'Videotittel',
      h5p: 'H5P-tittel',
      brightcove: 'Videotittel',
      external: 'Innhaldstekst',
    },
    visualElementCopyright: 'Opphav',
    removeVisualElement: 'Fjern element',
    info: {
      lastUpdated: 'Sist oppdatert: ',
    },
    title: 'Emne',
    fields: {
      caption: {
        label: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innhaldstekst',
        },
        placeholder: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innhaldstekst',
        },
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
    },
  },
  agreementForm: {
    title: {
      create: 'Avtale',
      update: 'Avtale',
    },
    fields: {
      title: {
        label: 'Avtaletittel',
        placeholder: 'Avtaletittel',
      },
      content: {
        label: 'Avtalens innhald',
        placeholder: 'Avtalens innhald',
      },
    },
  },
  footnoteForm: {
    title: 'Tittel',
    year: 'År',
    authors: 'Forfatter',
  },
  linkForm: {
    href: 'Lenke',
    text: 'Tekst',
  },
  audioForm: {
    title: 'Lyd',
  },
  podcastSeriesForm: {
    title: 'Podkastserie',
    alreadyPartOfSeries: 'Del av ein anna serie',
    description: 'Beskrivelse',
  },
  podcastForm: {
    title: 'Podkastepisode',
    fields: {
      header: 'Overskrift',
      introduction: 'Introduksjon',
      coverPhoto: 'Bilde',
      coverPhotoAltText: 'Alt-tekst',
      manuscript: 'Tekstversjon',
      series: 'Serie',
    },
    information: {
      partOfSeries: 'Denne podkasten er ein del av serien',
      removeSeries: 'Fjern serie',
      noSeries: 'Podkasten tilhøyrer ingen serie',
    },
  },
  imageEditor: {
    editImage: 'Rediger bildet',
    remove: {
      crop: 'Fjern utsnitt',
      focalPoint: 'Fjern fokuspunkt',
    },
  },
  imageForm: {
    title: 'Bilde ',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Bildetittel',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
    },
    title: 'Læringsressurs',
    validation: {
      missingEmbedData:
        'Ein eller fleire inkluderte lyd-, bilde-, eller videoelementer mangler beskrivende tekst eller alternativ tekst.',
    },
    fields: {
      rightAside: {
        title: 'Høgrespalte',
        moveContent: 'Flytt innhald inn i teksten',
        delete: 'Slett høgrespalte',
      },
      footnotes: {
        edition: 'Utgåve',
        publisher: 'Utgjevar',
      },
    },
  },
  editorToolbar: {
    bold: 'Feit\n({{ctrl}}+b)',
    bulletedList: 'Punktliste\n({{ctrl}}+l)',
    code: 'Kode\n({{ctrl}}+k)',
    codeblock: 'Kodeblokk',
    concept: 'Forklaring\n({{ctrl}}+alt+c)',
    footnote: 'Fotnote\n({{ctrl}}+alt+f)',
    headingOne: 'Overskrift 1',
    headingThree: 'Overskrift 3\n({{ctrl}}+3)',
    headingTwo: 'Overskrift 2\n({{ctrl}}+2)',
    italic: 'Kursiv\n({{ctrl}}+i)',
    lang: 'Språk\n(alt+l)',
    letterList: 'Bokstavliste\n({{ctrl}}+alt+a)',
    link: 'Lenke\n({{ctrl}}+alt+l)',
    mathml: 'Matte\n({{ctrl}}+m)',
    numberedList: 'Nummerert liste\n({{ctrl}}+alt+1)',
    quote: 'Sitat\n({{ctrl}}+alt+b)',
    sub: 'Senka\n({{ctrl}}+alt+s)',
    sup: 'Hevet\n({{ctrl}}+alt+h)',
    twoColumnList: 'To-kolonners liste',
    underlined: 'Understreka',
  },
  editorBlockpicker: {
    heading: 'Legg til',
    actions: {
      block: 'Seksjon',
      factAside: 'Faktaboks',
      table: 'Tabell',
      bodybox: 'Tekst i ramme',
      details: 'Ekspanderande boks',
      image: 'Bilde',
      video: 'Video',
      audio: 'Lyd',
      h5p: 'H5P',
      url: 'Ressurs fra lenke',
      related: 'Relatert innhald',
      file: 'Fil',
      code: 'Kodevisning',
      podcast: 'Podkastepisode',
    },
  },
  form: {
    articleSection: 'Artiklar',
    metadataSection: 'Metadata',
    contentSection: 'Innhald',
    workflowSection: 'Versjonslogg og merknader',
    taxonomySection: 'Taksonomi',
    copyrightSection: 'Lisens og bruker',
    podcastSection: 'Podkastinformasjon',
    podcastSeriesSection: 'Podkastserie',
    podcastEpisodesSection: 'Episoder',
    podcastEpisodesTypeName: 'Podkaster',
    inlineEdit: 'Hurtigredigering',
    save: 'Lagre',
    saveAsNewVersion: 'Lagre som ny versjon',
    saveAndPublish: 'Lagre og publiser',
    saveDraft: 'Lagre utkast',
    saveTax: 'Lagre taksonomi',
    choose: 'Velg',
    saving: 'Lagrer...',
    saveSearch: 'Lagre søk',
    alreadySaved: 'Lagra',
    saved: 'Lagra ',
    feil: 'Det er fortsatt flere feil i skjemaet',
    copy: 'kopi',
    saveAsCopySuccess: 'Ny artikkel lagret',
    preview: {
      button: 'Forhandsvis',
    },
    name: {
      title: 'Tittel',
      aboutTitle: 'Tittel',
      introduction: 'Ingress',
      creators: 'Opphavsperson',
      rightsholders: 'Rettighetshaver',
      processors: 'Bearbeider',
      tags: 'Nøkkelord',
      license: 'Lisens',
      origin: 'Opphav',
      audioFile: 'Lydfil',
      content: 'Innhald',
      notes: 'Merknader',
      metaDescription: 'Metabeskrivelse',
      metaImageAlt: 'Alt-tekst',
      alttext: 'Alt-tekst',
      caption: 'Bildetekst',
      imageFile: 'Bildefil',
      visualElement: 'Visuelt element',
      visualElementCaption: 'Figur tekst',
      visualElementAlt: 'Alt tekst',
      validFrom: 'Gyldig fra',
      validTo: 'Gyldig til',
      description: 'Innhald',
      conceptContent: 'Skildring',
      grepCodes: 'Læreplankobling',
      desktopBanner: 'Banner til desktop',
      mobileBanner: 'Banner til mobil',
      concepts: 'Forklaringar',
      relatedContent: 'Relaterte forklaringar',
      subjects: 'Fag',
      header: 'Overskrift',
      manuscript: 'Tekstversjon',
      coverPhotoId: 'Metabilde',
    },
    previewProductionArticle: {
      button: 'Samanlikn gjeldande versjon med gamal versjon',
      version: 'Versjon {{revision}}',
      current: 'Gjeldende versjon',
      article: 'Artikkel',
    },
    previewLanguageArticle: {
      button: 'Samanlikn språkversjonar',
      title: 'Utkast på {{language}}',
    },
    previewNewWindow: 'Forhåndsvis i nytt vindu',
    contributor: {
      add: 'Legg til',
    },
    abort: 'Avbryt',
    edit: 'Rediger',
    remove: 'Fjern',
    validate: 'Valider',
    publish: 'Publiser',
    savedOk: 'Lagra OK',
    publishedOk: 'Publisert OK',
    validationOk: 'Ingen valideringsfeil funnet',
    createdOk: 'Oppretta OK',
    addNewImage: 'Legg til nytt bilde',
    mustSaveFirst: 'Du må lagre endringene dine først',
    addNewAudio: 'Legg til ny lyd',
    notes: {
      heading: 'Merknader',
      add: 'Legg til merknad',
      remove: 'Ta bort',
      warning: 'Ein merknad må ha tekst',
      areHere: 'Du er her',
      published: 'Publisert',
      history: {
        user: 'Bruker',
        time: 'Når',
        status: 'Status',
        heading: 'Merknadshistorikk',
        note: 'Merknad',
        empty: 'Ingen merknader',
      },
    },
    updated: {
      label: 'Oppdatert dato',
    },
    published: {
      label: 'Publisert dato',
      reset: 'Resett dato',
    },
    updatePublished: 'Endre publisert dato',
    editImage: 'Endre bilde',
    editOriginalImage: 'Rediger original bilde',
    editAudio: 'Endre lyd',
    editPodcast: 'Endre podkast',
    resetToProd: {
      button: 'Tilbakestill endringer',
      modal: 'Vil du tilbakestille utkastet til slik det er på ndla forsida?',
      success: 'Innhold er tilbakestilt, trykk lagre for å lagre endringene',
    },
    resetToVersion: 'Tilbakestill til versjon',
    previewVersion: 'Se versjon',
    variant: {
      create: 'Legg til språk',
      translate: 'Oversett til nynorsk',
    },
    remainingCharacters: 'Maks {{maxLength}} teikn og du har {{remaining}} igjen.',
    title: {
      label: 'Tittel',
    },
    introduction: {
      label: 'Ingress',
    },
    metaImage: {
      title: 'Metabilde',
      label: 'Metabilde',
      imageTitle: 'Bildetittel',
      helpLabel: 'Kva er eit metabilde?',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
      add: 'Velg metabilde',
      remove: 'Fjern metabilde',
    },
    availability: {
      everyone: 'Alle',
      teacher: 'Lærarar',
      label: 'Tilgjengelighet',
      description: 'Kven er artikkelen meint for:',
    },
    modelReleased: {
      label: 'Modellklarert',
      yes: 'Ja',
      no: 'Nei',
      'not-applicable': 'Ikkje relevant',
      'not-set': 'Ikkje valgt',
      description: 'Om bildet er modellklarert eller ikkje:',
    },
    markdown: {
      button: 'Klikk for å se markdown',
      helpLabel: 'Kva er markdown?',
    },
    visualElement: {
      title: 'Legg til visuelt element',
      label: 'Visuelt element',
      helpLabel: 'Informasjon om visuelt element',
      video: 'Videosøk',
      image: 'Bildesøk',
      imageUpload: 'Last opp bilde',
      h5p: 'H5P',
    },
    concept: {
      create: 'Opprett ny forklaring',
      addText: 'Velg ei forklaring under og trykk "koble til fagtekst", eller',
      edit: 'Rediger forklaring',
      addConcept: 'Legg til eksisterande forklaring',
      removeConcept: 'Ta bort forklaring',
      source: 'Kjelde',
      markdown: 'Feltet støtter markdown. Bruk formatet [Tekst](https://url) for å lage lenke.',
      subjects: 'Berre fag markert som forklaringsfag vil visast i lista.',
    },
    workflow: {
      title: 'Status',
      change: 'Endre status',
      qualityAssurance: 'Kvalitetssikring',
      saveAsNew: 'Lag kopi',
      deleteLanguageVersion: {
        button: 'Slett språkversjon',
        title: 'Slett språkversjon',
        modal: 'Er du sikker på at du vil slette denne språkversjonen?',
      },
      statusInfoTooltip: 'Kva er forskjella på dei ulike statusane?',
      statusLabel: 'Status',
      published: 'Det finst ein publisert versjon av dettet elementet.',
      multipleTaxonomy: 'Artikkelen har fleire oppføringar i taksonomi.',
      currentStatus: 'Gjeldande status: {{status}}.',
    },
    status: {
      new: 'Ny - Ikke lagret',
      new_language: 'Nytt språk - ikke lagret',
      created: 'Oppretta',
      imported: 'Fra spoling',
      draft: 'Kladd',
      proposal: 'Utkast',
      user_test: 'Brukertest',
      awaiting_quality_assurance: 'Til kvalitetssikring',
      queued_for_language: 'Til språk',
      translated: 'Ferdig fra språk',
      quality_assured: 'Publiseringsklar',
      quality_assured_delayed: 'Publ.klar-utsatt',
      queued_for_publishing: 'Til publisering',
      queued_for_publishing_delayed: 'Publ-utsatt',
      published: 'Publisert',
      has_published: 'Har publisert versjon',
      unlisted: 'Lenkedelt',
      unpublished: 'Avpublisert',
      awaiting_unpublishing: 'Til avpublisering',
      awaiting_archiving: 'Utsatt arkivering',
      archived: 'Slettet',
      actions: {
        DRAFT: 'Kladd',
        PROPOSAL: 'Utkast',
        USER_TEST: 'Brukertest',
        AWAITING_QUALITY_ASSURANCE: 'Til kvalitetssikring',
        QUEUED_FOR_LANGUAGE: 'Til språk',
        TRANSLATED: 'Ferdig fra språk',
        QUALITY_ASSURED: 'Publiseringsklar',
        QUEUED_FOR_PUBLISHING: 'Til publisering',
        QUALITY_ASSURED_DELAYED: 'Publ.klar-utsatt',
        QUEUED_FOR_PUBLISHING_DELAYED: 'Publ-utsatt',
        PUBLISHED: 'Publiser',
        AWAITING_UNPUBLISHING: 'Til avpublisering',
        UNPUBLISHED: 'Avpubliser',
        ARCHIVED: 'Slett',
        AWAITING_ARCHIVING: 'Utsatt arkivering',
      },
      learningpath_statuses: {
        private: 'Kladd',
        published: 'Offentleg',
        unlisted: 'Lenkedelt',
        submitted: 'Bedt om offentleggjering',
      },
    },
    validDate: {
      label: 'Gyldighet',
      from: {
        label: 'Gyldig fra',
        placeholder: 'Fra og med dato',
      },
      to: {
        label: 'Gyldig til',
        placeholder: 'Til og med dato',
      },
    },
    content: {
      label: 'Innhald',
      placeholder: 'Innhald',
      figure: {
        notSupported: 'Mediatype {{mediaType}} er ikkje støtta.',
        confirmDelete: 'Er du sikker på at du vil slette denne figuren?',
      },
      relatedArticle: {
        placeholder: 'Søk på tittel',
        urlPlaceholder: 'http://www.example.com',
        urlLocation: 'Nettside hos {{domain}}',
        titlePlaceholder: 'Tittel',
        invalidArticle: 'Ugyldig artikkel',
        addExternal: 'Legg til ekstern artikkel',
        removeExternal: 'Slett ekstern artikkel',
        changeExternal: 'Endre ekstern artikkel',
        searchExternal: 'Skriv inn tittel og url på ekstern artikkel',
      },
      concept: {
        remove: 'Fjern forklaring',
        choose: 'Velg forklaring',
      },
      link: {
        name: 'Namn',
        domains: 'Url',
        validDomains: 'Gyldige domener',
        goTo: 'Gå til',
        insert: 'Sett inn lenke',
        update: 'Oppdater lenke',
        change: 'Endre',
        remove: 'Fjern lenke',
        href: 'Lenke',
        newTab: 'Åpne lenke i ny fane',
        text: 'Tekst',
        addTitle: 'Legg til lenke',
        changeTitle: 'Endre lenke',
        required: 'Lenke er påkrevd',
        invalid: 'Ugyldig lenke',
        preview: 'Forhåndsvis lenke',
        unSupported: 'Innhaldstypen i lenka er ikkje støtta',
        newUrlResource: 'Ny ressurs',
        changeUrlResource: 'Rediger ressurs: {{type}}',
        description:
          'Lenker til ndla-ressursar spesialhandterast av systemet og visast korrekt på {{- url}}. Ndla-ressursar visast med blå bakgrunn og eksterne lenker med gul.',
      },
      footnote: {
        title: 'Tittel',
        year: 'År',
        authors: {
          label: 'Forfatter',
          description: 'Obligatorisk med minst 1 forfatter.',
          createOption: 'Opprett ny forfatter',
        },
        edition: 'Utgåve',
        publisher: 'Utgjevar',
        addTitle: 'Legg til fotnote',
        editTitle: 'Rediger fotnote',
        removeFootnote: 'Fjern fotnote',
      },
      table: {
        'row-remove': 'Fjern rad',
        'row-add': 'Legg til rad',
        'column-add': 'Legg til kolonne',
        'column-remove': 'Fjern kolonne',
        'table-remove': 'Fjern tabell',
        addHead: 'Legg til kolonne-overskrift',
        disableRowHeaders: 'Deaktiver rad-overskrift',
        enableRowHeaders: 'Aktiver rad-overskrift',
      },
    },
    tags: {
      label: 'Nøkkelord',
      helpLabel: 'Kva er nøkkelord?',
      description: 'Obligatorisk med 3 nøkkelord.',
      createOption: 'Opprett nytt nøkkelord',
      searchPlaceholder: 'Søk etter nøkkelord',
    },
    categories: {
      label: 'Liste og filter',
      description: 'Format: Liste:Filter1:Filter2',
      searchPlaceholder: 'Søk etter lister',
    },
    grepCodes: {
      label: 'Kompetansemål og kjerneelementer',
      placeholder: 'Skriv inn kode',
      description:
        'Skriv inn koder på formatet K(E/M) eller TT fulgt av eit eller fleire siffer. Eks. KE137, KM2255, TT2. Koder som ikkje eksisterer vil ikkje bli oppretta. Separer fleire kodar med komma. Tekstene visast på bokmål i ed, men korrekt i artikkelvisning.',
    },
    resourceTypes: {
      label: 'Innhaldstype og egenskaper',
      placeholder: 'Legg til egenskap',
    },
    subjects: {
      label: 'Fag',
      searchPlaceholder: 'Søk etter fag',
      placeholder: 'Legg til fag',
    },
    topics: {
      label: 'Emnetilknytning',
      placeholder: 'Legg til emnetilknytning',
      primaryTopic: 'Primærkobling',
      sharedTopic: 'Delt emne',
      setPrimaryTopic: 'Vel som primærkoblet emne',
      RGTooltip: 'Vel mellom Kjernestoff eller Tilleggsstoff',
    },
    metaDescription: {
      label: 'Metabeskrivelse',
      description: 'Beskrivelsen blir synlig i søk.',
      helpLabel: 'Kva er metabeskrivelse?',
    },
    agreement: {
      label: 'Koble til avtale',
      helpLabel: 'Kva er ei avtale?',
      placeholder: 'Søk etter avtale',
    },
    rightsholders: {
      label: 'Rettighetshaver',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv namn til rettighetshaver',
      createOption: 'Opprett ny rettighetshaver',
    },
    processors: {
      label: 'Bearbeider',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv namn til bearbeider',
      createOption: 'Opprett ny bearbeider',
    },
    creators: {
      label: 'Opphavsperson',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv namn til opphavsperson',
      createOption: 'Opprett ny opphavsperson',
      description: 'Obligatorisk med minst 1 opphavsperson.',
    },
    license: {
      label: 'Lisens',
      helpLabel: 'Kva er lisensar?',
      choose: 'Velg ein lisens',
    },
    origin: {
      label: 'Opphav',
    },
    image: {
      file: 'Bilde',
      save: 'Lagre bilde',
      editImage: 'Rediger bilde',
      removeImage: 'Ta bort bilde',
      alignment: {
        left: 'Justering: Venstrestilt',
        right: 'Justering: Høgrestilt',
        center: 'Justering: Stort i midten',
      },
      sizes: {
        xsmall: 'Størrelse: Frimerke',
        small: 'Størrelse: Lite',
        medium: 'Størrelse: Middels',
        fullwidth: 'Størrelse: Stort',
      },
      crop: 'Lag utsnitt av bildet',
      focalPoint: 'Sett fokalpunkt',
      caption: {
        label: 'Bildetekst',
        placeholder: 'Bildetekst',
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
        noText: 'Universal utforming krever alt-tekst.',
      },
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp bilde',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp bilde',
      },
      byline: {
        show: 'Vis byline',
        hide: 'Skjul byline',
      },
    },
    video: {
      caption: {
        label: 'Videotekst',
        placeholder: 'Videotekst',
      },
      remove: 'Fjern video',
      save: 'Lagre video',
      time: {
        start: 'Start',
        stop: 'Stopp',
        hms: 'h:m:s',
      },
      brightcove: 'Åpne i Brightcove',
      toLinkedVideo: 'Bytt til synstolket versjon',
      fromLinkedVideo: 'Bytt tilbake til original versjon',
      linkedVideoButton: 'ST',
    },
    audio: {
      file: 'Lydfil',
      title: {
        label: 'Lydtittel',
        placeholder: 'Lydtittel',
      },
      manuscript: 'Tekstversjon',
      caption: {
        label: 'Lydtekst',
        placeholder: 'Lydtekst',
      },
      remove: 'Ta bort lydfil',
      sound: 'Lyd',
      speech: 'Tale',
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp lydfil',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp lydfil',
      },
      copiedFrom:
        'Lydfil kopieres fra {{language}}. Trykk på søppelbøtten for å fjerne den og laste opp ei ny fil.',
      info: {
        multipleFiles: 'Du kan laste opp forskjellige lydfilar for kvart språk.',
        changeFile: 'Fjerning og endring av eit språk vil ikkje påverke dei andre språka.',
        newLanguage:
          'Ved oppretting av eit nytt språk vil ei lydfil fra eit eksisterande språk foreslås.',
        deleteFiles: 'Ei lydfil slettes bare når den ikkje lenger brukes i eit språk.',
      },
      modal: {
        header: 'Lydfiler',
        label: 'Informasjon om lydfiler',
      },
    },
    podcast: {
      remove: 'Ta bort podkast',
    },
    external: {
      title: 'eksternt',
      edit: 'Rediger {{type}} element',
      remove: 'Fjern {{type}} element',
    },
    related: {
      title: 'Relatert innhald',
      subtitle: 'Dra artikkel for å endra rekkefølgje',
      showMore: 'Vis meir relatert innhald',
      showLess: 'Vis mindre',
    },
    file: {
      label: 'Filer',
      file: {
        label: 'Fil',
      },
      download: 'Last ned:',
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
      title: {
        label: 'Filtittel',
        placeholder: 'Filtittel',
      },
      addFile: 'Legg til fil',
      removeList: 'Fjern filliste',
      placeholder: 'Oppgi eit filnamn',
      changeName: 'Endre namn',
      changeOrder: 'Endre rekkefølgje',
      removeFile: 'Ta bort fil',
      missingFileTooltip:
        'Ser ikkje ut til å eksistere på serveren. Den kan ha blitt sletta frå ein annan artikkel.',
      missingFilename: 'Filtypen støttes ikke',
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp file(r)',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp file(r)',
        noFilesAdded: 'Ingen filer er lagt til',
      },
      showPdf: 'Vis ekspandert',
      showPdfTooltip: 'Vis ekspandert PDF i artikkel',
    },
    article: {
      label: 'Artikkel',
      add: 'Legg til artikkel',
    },
    learningpathConnections: {
      sectionTitle: 'Bruk av artikkelen i læringsstiar',
      title: 'Læringsstiar som inneheld denne artikkelen',
    },
    embedConnections: {
      type: {
        image: 'bildet',
        audio: 'lydfilen',
        concept: 'forklaringa',
        article: 'artikkelen',
      },
      sectionTitleArticle: 'Artiklar som bruker {{resource}}',
      sectionTitleConcept: 'Forklaringar som bruker {{resource}}',
      title: 'Bruk av {{resource}}',
      info: {
        image: 'Bruk av bildet i artiklar og/eller forklaringar',
        audio: 'Bruk av lydfilen i artikler',
        concept: 'Bruk av forklaringa i artikler',
        article: 'Bruk av artikkelen i andre artiklar',
      },
      articles: '1 artikkel',
      articles_plural: '{{count}} artikler',
      concepts: '1 forklaring',
      concepts_plural: '{{count}} forklaringar',
    },
    relatedConcepts: {
      placeholder: 'Søk på tittel',
      articlesTitle: 'Forklaringar',
      changeOrder: 'Endre rekkefølgje',
      removeArticle: 'Fjern forklaring',
    },
    relatedContent: {
      placeholder: 'Søk på tittel',
      articlesTitle: 'Innhald',
      changeOrder: 'Endre rekkefølgje',
      removeArticle: 'Fjern innhald',
      addExternal: 'Legg til ekstern artikkel',
      link: {
        missingTitle: 'Mangler tittel',
        missingUrl: 'Url må begynne med http:// eller https://',
        titlePlaceholder: 'Tittel',
        urlPlaceholder: 'https://example.com',
        addLink: 'Legg til',
      },
    },
    section: {
      remove: 'Ta bort seksjon',
    },
  },
  validation: {
    isRequired: '{{label}} er påkrevd.',
    bothFields: 'Ein {{labelLowerCase}} må inneholde alle felt.',
    isNumeric: '{{label}} må inneholde tall.',
    maxLength: '{{label}} kan ikkje ha meir enn {{maxLength}} teikn.',
    minLength: '{{label}} må ha minst {{minLength}} teikn.',
    url: '{{label}} må inneholde ei gyldig lenke.',
    urlOrNumber: '{{label}} må inneholde ei gyldig lenke eller artikkel-id.',
    dateBeforeInvalid: '{{label}} kan ikkje være etter {{afterLabel}}.',
    dateAfterInvalid: '{{label}} kan ikkje være før {{beforeLabel}}.',
    minItems: '{{label}} feltet må minst inneholde ein/eitt {{labelLowerCase}}.',
    minItems_plural: '{{label}} feltet må minst inneholde {{count}} ulike {{labelLowerCase}}.',
    noEmptyNote: 'Ein merknad kan ikkje være tom',
    noLicenseWithoutCopyrightHolder:
      'Ein lisens kan ikkje takast i bruk uten å definere minst ein opphavar.',
    maxSizeExceeded:
      'Filen du forsøkar å laste opp er for stor. Maksstorleik: {{maxSize}} MB. Filstorleik: {{fileSize}} MB.',
    grepCodes:
      'Koden er på feil format. Det korrekte formatet er K(E/M) eller TT fulgt av eit eller fleire siffer. Eks. KE137, KM2255, TT2.',
    podcastImageShape: 'Metabilde må være like høgt som det er breitt.',
    podcastImageSize: 'Metabilde må være mellom 1400 og 3000 pikslar breitt.',
  },
  errorMessage: {
    title: 'Oops, noko gjekk gale',
    description: 'Vi beklager, men ein feil oppsto.',
    back: 'Tilbake',
    goToFrontPage: 'Gå til forsida',
    invalidUrl: 'Ugyldig url',
    noArticleInProd: 'Ingen artikkel funnet i prod',
    taxonomy: 'Det var eit problem ved lasting av taksonomi',
    errorWhenFetchingTaxonomyArticle:
      'Det var eit problem ved lasting av den underliggande artikkelen',
    unsavedTaxonomy: 'Du har ulagra endringar. Trykk avbryt igjen viss du ønsker å fortsette.',
    auth0:
      'Autentiseringsfeil. Trykk avbryt for å ta vare på eventuelle endringer du har gjort før du logger inn på nytt. Følgende feilmelding kom fra auth0: {{message}}',
    statusCode: {
      409: 'Denne artikkelen har allerede blitt oppdatert. Ta vare på det du har endra og last sida på nytt for å kunne lagre.',
    },
    grepCodes: 'Følgande koder har feil format eller eksisterer ikkje, og blir ikkje lagt til: ',
  },
  warningMessage: {
    fieldWithWrongLanguage: 'Dette feltet er henta frå språkkode: {{language}}',
  },
  notFound: {
    description: 'Denne sida finnes ikkje.',
  },
  forbiddenPage: {
    description: 'Du har ikkje tilgang til denne sida',
  },
  alertModal: {
    notSaved: 'Dokumentet er ikkje lagra, ønsker du å fortsette?',
    needToRefresh:
      'Nokon har lagra samme artikkel medan du redigerte. For å ta vare på endringane dine må du kopiere dei manuelt og deretter oppdatere sida',
    continue: 'Fortsett',
    delete: 'Slett',
    confirm: 'Bekreft',
    loginAgain: 'Logg inn på nytt',
  },
  taxonomy: {
    editStructure: 'Rediger struktur',
    editSubjectpage: 'Rediger fagforside',
    deleteSubject: 'Slett fag',
    addSubject: 'Legg til nytt fag',
    addExistingTopic: 'Flytt eksisterande emne hit',
    newSubject: 'Nytt fag',
    resources: 'Ressurser',
    existingTopic: 'Eksisterande emne',
    newTopic: 'Nytt emne',
    subjectSettings: 'Faginnstillinger',
    topicSettings: 'Emneinnstillinger',
    changeName: {
      loadError: 'Klarte ikkje hente omsetjingar',
      updateError: 'Klarte ikkje oppdatere omsetjingar',
      defaultName: 'Standardnamn',
      addNewTranslation: 'Legg til ny omsetjing',
      buttonTitle: 'Endre namn',
      language: 'Språk',
      name: 'Namn',
      namePlaceholder: 'Fagnamn',
      delete: 'Slett',
      title: 'Endre fagnamn',
      cancel: 'Avbryt',
      add: 'Legg til',
      noTranslations:
        'Ingen omsetjingar tilgjengeleg! Standardnamn vil brukes inntil dette er lagt inn.',
    },
    addTopic: 'Legg til nytt emne',
    errorMessage: 'Ein feil oppsto',
    confirmDeleteTopic: 'Er du sikker på at du vil slette emnet?',
    confirmDeleteSubject: 'Er du sikker på at du vil slette faget?',
    linkSettings: 'Link',
    setPrimary: 'Sett til primærkobling',
    addResource: 'Legg til ressurs',
    removeResource: 'Fjern ressurs frå emne',
    searchResource: 'Søk etter ressurs',
    searchArticle: 'Søk etter emneartikkel',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Obs! Denne ressursen er ein anna type',
    noResources: 'Ingen ressurser funnet',
    addTopicDescription: 'Endre emnebeskrivelse',
    confirmSetPrimary: 'Vil du gjere dette til hovedplassering?',
    jumpToResources: 'Hopp til ressurser',
    copyResources: 'Gjenbruk ressurser fra emne',
    copyAndCloneResources: 'Kopier og klon ressurser fra emne',
    favorites: 'Vis favorittar',
    publish: {
      button: 'Publiser alt',
      waiting: 'Publiserar ressurser',
      done: 'Ressurser er publisert',
      error: 'Følgande ressurser blei ikkje publisert:',
    },
    info: {
      title: 'Informasjon',
      subTitle: 'Id og synlighet for elementet',
      wrongArticleType:
        'Artikkelen er plassert som "{{placedAs}}" i taksonomien, men artikkelen er av typen "{{isType}}".',
      missingArticleType:
        'Artikkelen med ID {{id}} manglar artikkeltype. Han er sannsynlegvis sletta.',
      wrongConnections: 'Feilkoplingar',
      wrongConnectionsSubTitle: 'Denne artikkelen har feilkoplingar, sjå lista under.',
      canBeFixedInDatabase: 'Artikkeltypen kan endres i databasen for å fikse feilen.',
    },
    resource: {
      confirmDelete:
        'Vil du fjerne ressursen frå denne mappa? Dette vil ikkje påverke plasseringa andre steder',
      copyError:
        'Det oppstod ein feil ved kopiering av ressursar. Dobbeltsjekk dei kopierte ressursane og prøv å fikse manglar manuelt, eller slett dei kopierte ressursane og prøv å kopiere på nytt',
      addResourceConflict: 'Ressursen du forsøkte å legge til finnes allerede på emnet.',
      noResourceId: 'Klarte ikkje henta ut ID frå den valde ressursen',
      creationFailed: 'Klarte ikkje å opprette kobling',
    },
    removeLink: 'Fjern lenke',
    resourceTypes: {
      title: 'Innhaldstype',
      helpLabel: 'Kva er ei Innhaldstype?',
      subTitle: 'Kva for ei innhaldstype har denne ressursen?',
      placeholder: 'Velg innhaldstype',
    },
    topics: {
      title: 'Emnetilknytninger',
      topicPlacement: 'Emneplassering',
      helpLabel: 'Kva er emnetilknytning?',
      subTitle: 'Kvar i taksonomien skal ressursen ligge?',
      subTitleTopic: 'Kvar i taksonomien skal emneskildringa ligge?',
      filestructureButton: 'Opprett en emnetilknytning',
      chooseTaxonomyPlacement: 'Velg plassering i taksonomi',
      changeTaxonomyPlacement: 'Endre plassering i taksonomi',
      filestructureHeading: 'Velg emnetilknytning',
      addNewTopic: 'Legg til nytt emne',
      addNewSubTopic: 'Legg til nytt underemne',
      filestructureClose: 'Lukk',
      addedTopic: 'Lagt til',
      disconnectedTaxonomyWarning: 'Ugyldig tilknytning',
    },
    grepCodes: {
      edit: 'Endre læreplankobling',
      empty: 'Ingen registerte koder',
      addNew: 'Legg til ny læreplankobling',
    },
    goTo: 'Åpne i stukturredigering',
    missingResourceType: 'Mangler ressurstype',
    metadata: {
      customFields: {
        alterFields: 'Legg til/endra metadata',
        addField: 'Nytt metadata felt',
        languagePlaceholder: 'Visningsspråk ndla.no',
        explanationSubject: 'Forklaringsfag',
        oldSubjectId: 'ID for vidaresending',
        subjectCategory: 'Fagkategori',
        resourceGroupPlaceholder: 'Gruppering av ressursar',
        RGTooltip: 'Vis ressursar Gruppert eller Ugruppert',
      },
      placeholders: {
        category: 'Velg kategori',
        language: 'Velg språkkode',
      },
    },
  },
  notions: {
    edit: 'Rediger forklaring',
    closeNotion: 'Lukk forklaring',
  },
  contextTypes: {
    topic: 'Emne',
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: 'Slideshow',
      slideshowTitle: 'Filmer i slideshow',
      slideshowSubTitle: 'på forsida',
      movieGroupHeader: 'Filmgrupperinger',
      addMovieToSlideshow: 'Legg til film i slideshow',
      addMovieToGroup: 'Legg til film i "{{name}}"',
      editMovieGroupName: 'Endre namna til filmgruppa',
      deleteMovieGroup: 'Slett "{{name}}"',
      moveMovieGroupUp: 'Flytt opp',
      moveMovieGroupDown: 'Flytt ned',
      changeOrder: 'Endre rekkjefølgje',
      removeMovieFromGroup: 'Ta vekk film fra gruppe',
      removeMovieFromSlideshow: 'Ta vekk film fra slideshow',
      createThemeGroup: 'Opprett gruppe',
      saveNameChanges: 'Lagre endringer',
      cancel: 'Avbryt',
      editGroupTitle: 'Endre namn(a) på filmgruppa:',
      newGroupTitle: 'Kva skal gruppa heite?',
      notFound: 'Vi finn ikkje metadata for denne filmen...',
    },
  },
  modal: {
    closeModal: 'Lukk',
  },
  conceptform: {
    title: 'Forklaring',
  },
  editorFooter: {
    buttonLabel: 'Kvalitetssikring',
    heading: 'Kvalitetssikring:',
    changeStatus: 'Endre status',
    back: 'Gå tilbake',
    inputHeader: 'Din merknad',
    inputHelperText: 'Kort merknad påkrevd ved statusendring',
    cancelLabel: 'Avbryt',
    saveLabel: 'Endre status og lagre utkast',
    warningSaveWithoutComment: 'Merknad mangler',
    newStatusPrefix: 'Ny status:',
    statusLabel: 'Status:',
    changeHeader: 'Endringer',
    saveAsNew: 'Lagre som kopi',
  },
  metadata: {
    visible: 'er synleg',
    notVisible: 'er ikkje synleg',
    changeVisibility: 'Endre synlegheit',
  },
  languages: {
    ar: 'Arabisk',
    de: 'Tysk',
    en: 'Engelsk',
    se: 'Nordsamisk',
    sma: 'Sørsamisk',
    so: 'Somali',
    ti: 'Tigrinja',
    zh: 'Kinesisk',
  },
};

export default phrases;
