/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = "- Produksjonsystem - NDLA";

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Fagstoff ${titleTemplate}`,
    createTopicArticlePage: `Emne ${titleTemplate}`,
    createSubjectpage: `Fagforside ${titleTemplate}`,
    createFrontPageArticePage: `Om-NDLA-artikkel ${titleTemplate}`,
    agreementPage: `Avtale ${titleTemplate}`,
    welcomePage: `Forside ${titleTemplate}`,
    structurePage: `Struktur ${titleTemplate}`,
    programmePage: `Utdanningsprogram ${titleTemplate}`,
    versionsPage: `Versjonar ${titleTemplate}`,
    audioUploaderPage: `Lyd ${titleTemplate}`,
    imageUploaderPage: `Bilete ${titleTemplate}`,
    loginPage: `Logg inn ${titleTemplate}`,
    logoutPage: `Logg ut ${titleTemplate}`,
    ndlaFilmPage: `NDLA Film ${titleTemplate}`,
    podcastUploaderPage: `Podkastepisode ${titleTemplate}`,
    podcastSeriesPage: `Podkastserie ${titleTemplate}`,
    h5pPage: `H5P ${titleTemplate}`,
    nodeDiffPage: `Samanlikne nodar ${titleTemplate}`,
    editFrontpage: "Rediger forside",
    comparePage: `Samanlikne versjonar ${titleTemplate}`,
    search: {
      "podcast-series": `Søk podkastserier ${titleTemplate}`,
      audio: `Søk lydfiler ${titleTemplate}`,
      concept: `Søk forklaringer ${titleTemplate}`,
      content: `Søk innhold ${titleTemplate}`,
      image: `Søk bilete ${titleTemplate}`,
    },
  },
  dropdown: {
    numberHits: `Søket gav {{hits}} treff`,
    searching: "Søker...",
    create: "Opprett nytt",
    isSelectedItem: "Lagt til",
  },
  meta: {
    description: "Kvalitetssikra fritt tilgjengelige nettbaserte læremidler for videregående opplæring",
  },
  menu: {
    title: "Meny",
  },
  dialog: {
    close: "Lukk",
    title: "Tittel",
    audio: {
      rulesForUse: "Reglar for bruk av lydklipp",
    },
    learnAboutLicenses: "Lær meir om opne lisensar",
    source: "Kjelde",
  },
  license: {
    heading: "Slik gjenbruker du innhald",
    learnMore: "Lær meir om opne lisensar",
    copyTitle: "Kopier referanse",
    hasCopiedTitle: "Kopiert!",
    embed: "Bygg inn",
    embedCopied: "Kopierte innbyggingskode!",
    download: "Last ned",
    tabs: {
      text: "Tekst",
      images: "Bilete",
      audio: "Lyd",
      video: "Video",
    },
    images: {
      heading: "Slik bruker du bilete frå artikkelen",
      description: "Hugs å kopiera teksten som skal leggjast ved biletet der du bruker det.",
      rules: "Regler for bruk av biletet:",
      source: "Kjelde",
      title: "Tittel",
    },
    text: {
      heading: "Slik bruker du tekst frå artikkelen",
      description: "Artikkelen kan vera samansett av fleire ulike tekstar som vert lista her.",
      rules: "Reglar for bruk av teksten:",
      published: "Publiseringsdato",
    },
    audio: {
      heading: "Slik bruker du lydfiler",
      description: "Hugs å kopiera teksten som skal leggjast ved lydfila der du bruker ho.",
      rules: "Regler for bruk av lydfila:",
    },
    video: {
      heading: "Slik bruker du video fra artikkelen",
      description: "Hugs å kopiera teksten som skal leggjast ved videoen der du bruker han.",
      rules: "Regler for bruk av videoen:",
    },
  },
  languages: {
    // Adds to list from frontend-packages
    ar: "Arabisk",
    la: "Latin",
    no: "Norsk",
    so: "Somali",
    ti: "Tigrinja",
    und: "Udefinert",
    ukr: "Ukrainsk",
    prs: "Dari",
    san: "Sanskrit",
    heb: "Hebraisk",
    pli: "Pali",
    empty: "Ingen fleire språk",
    change: "Bytt til {{language}} versjon",
    none: "Ingen",
  },
  welcomePage: {
    lastFavorited: "Siste hjertemarkerte ressurs: ",
    addSearch: "Legg til nytt søk",
    deleteSavedSearch: "Slett lagra søk",
    noHitsSavedSearch: "Ingen treff i dine lagra søk",
    deleteSearch: "Slett søk",
    noArticles: "Ingen ressursar ...",
    emptyLastUsed: "Ingen sist redigerte ...",
    emptyConcepts: "Ingen forklaringar ...",
    emptyRevision: "Ingen ressursar i favorittfag som treng revisjon ...",
    emptySavedSearch: "Ingen lagra søk",
    guidelines: "Retningslinjer",
    mustBeSearch: "Lenka må være til eit søk",
    lastUsed: "Sist redigert",
    lastUsedDescription: "Ressursar du har redigert nyleg",
    lastUsedConcepts: "Forklaringar du har redigert nyleg",
    savedSearch: "Lagra søk",
    saveSearch: "Lagre søk",
    chooseSubject: "Velg fag",
    chooseFavoriteSubject: "Velg favorittfag",
    chooseTopic: "Velg emner",
    errorMessage: "Innhenting av data feila",
    goToSearch: "Gå til søk",
    revision: "Revisjon",
    revisionDescription: "Ressursar som har revisjonsdato innen 365 dagar",
    revisionDate: "Revisjonsdato",
    welcomeText: "til ED",
    revisionInfo: "Vel favorittfag ved å stjernemarkere i strukturredigering",
    updated: "Oppdatert",
    primaryConnection: "Berre vis ressursar med primærkopling til mine favorittfag",
    primaryConnectionLabel: "Berre vis primærkopling",
    prioritizedLabel: "Berre vis prioriterte",
    lmaSubjects: "LMA-fag",
    daSubjects: "DA-fag",
    saSubjects: "SA-fag",
    favoriteSubjects: "Favorittfag",
    lmaSubjectsHeading: "Produksjonsflyt i LMA-fag",
    daSubjectsHeading: "Produksjonsflyt i DA-fag",
    saSubjectsHeading: "Produksjonsflyt i SA-fag",
    favoriteSubjectsHeading: "Produksjonsflyt i favorittfag",
    lmaSubjectsDescription: "Status på ressursar i LMA-faga mine i flyten",
    daSubjectsDescription: "Status på ressursar i DA-faga mine i flyten",
    saSubjectsDescription: "Status på ressursar i SA-faga mine i flyten",
    favoriteSubjectsDescription: "Status på ressursar i favorittfaga mine i flyten. Utgåtte fag ikkje inkludert",
    noResultsLMASubjects: "Følgjande statusar vil ikkje visast i oversikta",
    count: "Antall",
    countResponsible: "Antall ansvarleg for",
    pagination: {
      resources: "ressursar",
      concepts: "forklaringar",
      workList: "Sider med {{ resourceType }} du er ansvarleg for",
      lastUsed: "Sider med dine sist redigerte {{ resourceType }}",
      revision: "Sider med utløpande ressursar i favorittfaga dine",
      subjectView: "Sider med statistikk for dine {{ group }}",
    },
    workList: {
      heading: "Mine arbeidsoppgåver",
      description: "Ressursar der du står som ansvarleg",
      title: "Tittel",
      status: "Status",
      contentType: "Innhaldstype",
      primarySubject: "Primærfag",
      topicRelation: "Emnetilknytting",
      date: "Tildelt",
      ariaLabel: "Oversikt over arbeidsoppgåvene og forklaringane mine",
      conceptDescription: "Forklaringar der du står som ansvarleg",
      conceptSubject: "Forklaringsfag",
      sortAsc: "Sorter stigande",
      sortDesc: "Sorter synkande",
      pickPageSize: "Velg antall rader",
      numberOfRows: "Antall rader",
      onHold: "Parkert",
      onHoldHeading: "Parkerte ressursar",
      onHoldDescription: "Parkerte ressursar der du står som ansvarleg",
      onHoldFilter: "Ikkje tell parkerte",
      loading: "Laster...",
    },
    subjectView: {
      lma: "Fagoversikt LMA-fag",
      da: "Fagoversikt DA-fag",
      sa: "Fagoversikt SA-fag",
      favorites: "Fagoversikt favorittfag",
      description: "Oversikt over statistikk knytta til ressursar i faga dine",
      heart: "Hjerter",
      heartDescription: "Talet på favorittmarkerte ressursar",
      flow: "I flyt",
      flowDescription: "Tal på ressursar i flyt",
      old: "Utdaterte",
      oldDescription: "Tal på ressurser det er meir enn 5 år sidan vart sist fagleg oppdatert",
      revision: "Revisjonar",
      revisionDescription: "Tal på ressursar med utgått revisjonsdato",
      published: "Publisert",
      publishedDescription: "Tal på publiserte ressursar",
    },
    welcomeBack: "Velkommen",
    listLabels: {
      worklist: "Ressurstypar",
      lastUsed: "Ressurstypar",
      subjectView: "Fagtypar",
      articleStatuses: "Fagtypar",
    },
  },
  searchPage: {
    header: {
      content: "Søk etter innhald",
      audio: "Søk etter lydfiler",
      image: "Søk etter bilete",
      concept: "Søk etter forklaringar",
      "podcast-series": "Søk etter podkastserier",
    },
    activeFilters: "Aktive filtre",
    searchButton: "Søk",
    emptyButton: "Tøm",
    title: "Tittel",
    language: "Språk",
    contentNoHits: "Ingen treff i innhald samsvarte med søket ditt på: {{query}}",
    conceptNoHits: "Ingen forklaringar samsvarte med søket ditt på: {{query}}",
    "podcast-seriesNoHits": "Ingen serier samsvarte med søket ditt på: {{query}}",
    audioNoHits: "Ingen lydfiler samsvarte med søket ditt på: {{query}}",
    imageNoHits: "Ingen bilete samsvarte med søket ditt på: {{query}}",
    pageSize: "{{pageSize}} treff per side",
    hitsSelectLabel: "Antall treff per side",
    totalCount: "Antall søketreff",
    highlights: {
      title: "Søketreff",
      content: "Søketreff frå innhold",
      tags: "Søketreff frå nøkkelord",
      embedAttributes: "Søketreff frå innebygde elementer",
      notes: "Søketreff frå versjonslogg",
      previousVersionsNotes: "Søketreff frå versjonslogg",
    },
    save: {
      alreadyExist: "Søket er allereie lagra.",
      fetchFailed: "Kunne ikkje laste lagra søk.",
      other: "Lagring feila.",
    },
  },
  articleType: {
    "topic-article": "Emne",
    "frontpage-article": "Om-NDLA-artikkel",
    standard: "Læringsressurs",
  },
  subNavigation: {
    listTitle: {
      create: "Opprett",
      edit: "Rediger",
      admin: "Admin",
      external: "Eksterne systemar",
    },
    media: "Media",
    learningPath: "Læringssti",
    learningPathLink: "Gå til læringssti",
    brightcoveLink: "Brightcove",
    detailSearch: "Detaljsøk",
    learningResource: "Læringsressurs",
    image: "Bilete",
    audio: "Lydfil",
    podcast: "Podkastepisode",
    podcastSeries: "Podkastserie",
    agreement: "Ny avtale",
    structure: "Strukturredigering",
    programme: "Utdanningsprogram",
    taxonomyVersions: "Taksonomiversjonar",
    searchContent: "Søk innhald",
    searchAudio: "Søk lyd",
    searchPodcastSeries: "Søk serie",
    searchImage: "Søk bilete",
    searchConcepts: "Søk forklaring",
    film: "NDLA film",
    h5p: "Edlib H5P",
    newConcept: "Forklaring",
    newGloss: "Glose",
    newSubject: "Opprett fag",
    newFrontpageArticle: "Om-NDLA-artikkel",
    frontpage: "NDLA forside",
  },
  logo: {
    altText: "Nasjonal digital læringsarena",
  },
  siteNav: {
    chooseSubject: "Velg fag",
    search: "Søk",
    login: "Logg inn",
  },
  loginFailure: {
    errorMessage: "Beklager. Innlogging feila.",
    loginLink: "Klikk for å prøve igjen.",
    userNotRegistered: "Vi kjente ikkje igjen epostadressa di. Har du logga inn med riktig adresse?",
  },
  loginProviders: {
    description: "Logg inn i produksjonssystem med",
  },
  logoutProviders: {
    localLogout: "Logg ut av produksjonssystem",
    or: "eller",
    federatedLogout: "Logg ut av alle tjenester",
    description: "N.B. Alle tjenester inkluderer autentiseringstjenesten (Google eller Facebook).",
  },
  searchForm: {
    placeholder: "Søk etter artikler, aktiviteter eller oppgaver",
    searchTypes: "Søketypar",
    types: {
      conceptQuery: "Søk på forklaringar",
      glossQuery: "Søk på glose",
      contentQuery: "Søk på innhald",
      audioQuery: "Søk på lydfiler",
      "podcast-seriesQuery": "Søk på podkastserier",
      imageQuery: "Søk på bilete",
      language: "Velg språk",
      users: "Velg bruker",
      "model-released": "Velg modellklarering",
      subjects: "Velg fag",
      "resource-types": "Velg innhaldstype",
      status: "Velg status",
      "draft-status": "Velg status",
      "audio-type": "Velg lydfiltype",
      "concept-type": "Velg forklaringstype",
      license: "Velg lisens",
      "revision-date-from": "Revisjonsdato fra",
      "revision-date-to": "Revisjonsdato til",
      "exclude-revision-log": "Ekskluder endringslogg",
      "responsible-ids": "Velg ansvarleg",
      "filter-inactive": "Inkluder utgåtte fag",
    },
    tagType: {
      query: "Søk: {{value}}",
      subjects: "Fag: {{value}}",
      language: "Språk: $t(languages.{{value}})",
      users: "Bruker: {{value}}",
      "resource-types": "Innhaldstype: {{value}}",
      status: "Status: $t(form.status.{{value}})",
      "draft-status": "Status: $t(form.status.{{value}})",
      "audio-type": "Lydfiltype: {{value}}",
      "concept-type": "Forklaringstype: {{value}}",
      license: "Lisens: {{value}}",
      "model-released": "Modellklarering: {{value}}",
      "revision-date-from": "Revisjonsdato fra: {{value}}",
      "revision-date-to": "Revisjonsdato til: {{value}}",
      "exclude-revision-log": "Endringslogg ekskludert",
      "responsible-ids": "Ansvarleg: {{value}}",
      "filter-inactive": "Utgåtte fag inkludert",
    },
    btn: "Søk",
    empty: "Tøm",
    articleType: {
      all: "Alle",
      standard: "Standard",
      learningResource: "Læringsressurs",
      topicArticle: "Emnebeskrivelse",
      image: "Bilete",
      audio: "Lyd",
    },
    audioType: {
      standard: "Lydfil",
      podcast: "Podkast",
    },
    conceptType: {
      concept: "Forklaring",
      gloss: "Glose",
    },
    order: "Rekkefølge",
    asc: "Stigende",
    desc: "Fallende",
    sorting: "Sortering",
    sort: {
      id: "Id",
      relevance: "Relevans",
      title: "Tittel",
      lastUpdated: "Sist oppdatert",
      revisionDate: "Neste revisjon",
      favorited: "Favorittmarkeringar",
      published: "Sist faglig oppdatert",
    },
    resultError: "Noko gjekk feil med innlasting av type: {{type}}",
    favourites: "Mine favorittfag",
    LMASubjects: "Mine LMA-fag",
    SASubjects: "Mine SA-fag",
    DASubjects: "Mine DA-fag",
    archivedIncluded: "Utgåtte fag inkludert",
    error: "Noko gjekk galt med søket",
    conceptSubject: "Forklaringsfag: {{name}}",
    multiTaxonomy: "{{count}} plasseringer i taksonomi",
  },
  subjectsPage: {
    subjects: "Fag",
  },
  subjectPage: {
    topics: "Emner",
  },
  editMarkup: {
    linkTitle: "Gå til HTML-editor",
    title: "HTML-editor",
    previewDialogTitle: "Forhåndsvis artikkel",
    subTitle: "Rediger artikkelinnhold med HTML",
    fetchError: "Ein feil oppsto ved lasting av HTML-editoren. Gå tilbake eller prøv å laste sida på nytt.",
    saveError: "Ein feil oppsto ved lagring av endringar.",
    back: "Tilbake",
    helpMessage: {
      tooltip: "Om HTML-editoren",
      paragraph1:
        "Det er mogeleg å formatere  HTML-koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisningsfunksjonaliteten aktivt. Lagring ved ctrl+s fungerer også.",
      paragraph2:
        "For å minimere eventuelle problemer med formatering og for å sikre at at HTML blir konsistent, så blir koden kjørt gjennom dei samme transformeringane som den vanlige editoren. Det betyr at den vil prøve å rette opp ugyldig kode. Linjeskift blir fjerna ved lagring og dermed ignorert.",
    },
  },
  imageSearch: {
    placeholder: "Søk i bilete",
    buttonTitle: "Søk",
    useImage: "Bruk biletet",
    metaImageCheckboxLabel: "Sett som metabilete",
    visualElementCheckboxLabel: "Sett som visuelt element",
    noTitle: "Ingen tittel",
    noResultsText: "Fann ingen bilete på søk. Ønskjer du å laste opp eit nytt bilete?",
    noResultsButtonText: "Last opp bilete",
    modelReleased: {
      yes: "Modellklarert",
      no: "Ikkje modellklarert",
      "not-applicable": "Ikkje relevant",
      "not-set": "Ikkje valgt",
    },
  },
  videoSearch: {
    searchPlaceholder: "Søk i videoar",
    searchButtonTitle: "Søk",
    loadMoreVideos: "Last fleire videoar",
    noResults: "Ingen videoar funnet.",
    addVideo: "Bruk video",
    previewVideo: "Forhåndsvis",
    publishedDate: "Publisert dato",
    duration: "Varighet",
    interactioncount: "Visninger",
    is360Video: "VR-video",
  },
  mathEditor: {
    editMath: "Rediger Matematikk",
    preview: "Forhåndsvisning",
    continue: "Du kan ha ulagra endringar i matteeditoren. Vil du fortsette?",
  },
  code: {
    continue: "Du kan ha ulagra endringar i kodevisning. Vil du fortsette?",
  },
  h5pElement: {
    fetchError: "Vi beklagar, men ein feil oppsto under lasting av H5P-klienten.",
  },
  displayOembed: {
    errorMessage: "Ein feil oppsto ved visning av oEmbed-innhald.",
    notSupported: "oEmbed av type {{type}} og kjelde {{provider}} er ikkje støtta.",
  },
  audioSearch: {
    searchPlaceholder: "Søk i lydfiler",
    searchButtonTitle: "Søk",
    useAudio: "Velg lyd",
    noResults: "Ingen resultat funnet",
    noTitle: "Ingen tittel",
  },
  conceptSearch: {
    searchPlaceholder: "Søk i forklaringar",
    searchButtonTitle: "Søk",
    noResults: "Ingen resultat funnet",
    noTitle: "Ingen tittel",
    noContent: "Ingen innhald",
    listLabel: "Valg",
  },
  searchTypes: {
    content: "Innhald",
    audio: "Lyd",
    image: "Bilete",
    concept: "Forklaring",
    "podcast-series": "Serie",
  },
  noEmbedMessage: {
    deleteOnSave: "Element av type {{type}} vil bli fjerna ved lagring.",
  },
  conceptpageForm: {
    articlesTitle: "Relaterte artiklar",
    articlesSubtitle: "Artiklar",
    changeOrder: "Endre rekkefølgje",
    removeArticle: "Fjern artikkel",
  },
  subjectpageForm: {
    title: "Fag",
    about: "Om faget",
    description: "Beskrivelse",
    metadata: "Metadata",
    addBanner: "Velg banner",
    changeBanner: "Bytt banner",
    editorsChoices: "Litt forskjellig frå faget",
    articles: "Artiklar",
    addArticle: "Legg til artikkel",
    removeArticle: "Fjern artikkel",
    missingVisualElement: "Visuelt element er påkrevd.",
    subjectlinks: "Faglenkjer",
    addSubject: "Legg til fag",
    moveSubject: "Dra og slepp",
    removeSubject: "Fjern fag",
    connectedTo: "Felles programfag saman med",
    buildsOn: "Bygger på",
    leadsTo: "Leier til",
  },
  programmepageForm: {
    title: "Utdanningsprogram",
  },
  topicArticleForm: {
    visualElementTitle: {
      image: "Biletetittel",
      video: "Videotittel",
      h5p: "H5P-tittel",
      brightcove: "Videotittel",
      external: "Innhaldstekst",
    },
    visualElementCopyright: "Opphav",
    removeVisualElement: "Fjern element",
    info: {
      lastUpdated: "Sist faglig oppdatert",
    },
    title: "Emne",
    fields: {
      caption: {
        label: {
          image: "Biletetekst",
          brightcove: "Videotekst",
          external: "Innhaldstekst",
        },
        placeholder: {
          image: "Biletetekst",
          brightcove: "Videotekst",
          external: "Innhaldstekst",
        },
      },
      alt: {
        label: "Alt-tekst",
        placeholder: "Alt-tekst",
      },
    },
    validation: {
      containsContent:
        "Emneartiklar bør kun ha tittel, ingress og visuelt element. Innhold trengs ikkje i dei fleste tilfeller.",
      illegalResource: "Emneartiklar bør kun ha bilete som visuelt element.",
    },
  },
  agreementForm: {
    title: {
      create: "Avtale",
      update: "Avtale",
    },
    fields: {
      title: {
        label: "Avtaletittel",
        placeholder: "Avtaletittel",
      },
      content: {
        label: "Avtalens innhald",
        placeholder: "Avtalens innhald",
      },
    },
  },
  footnoteForm: {
    title: "Tittel",
    year: "År",
    authors: "Forfatter",
  },
  linkForm: {
    href: "Lenke",
    text: "Tekst",
  },
  audioForm: {
    title: "Lyd",
  },
  podcastSeriesForm: {
    title: "Podkastserie",
    alreadyPartOfSeries: "Del av ein anna serie",
    description: "Beskrivelse",
    rss: "Rss-feed",
    adminError: "Du har ikkje tilgang til å opprette eller endre podkastserier.",
    hasRSS: "Aktiver RSS-feed for denne serien",
  },
  podcastForm: {
    title: "Podkastepisode",
    fields: {
      header: "Overskrift",
      introduction: "Introduksjon",
      coverPhoto: "Bilete",
      coverPhotoAltText: "Alt-tekst",
      manuscript: "Tekstversjon",
      series: "Serie",
    },
    information: {
      partOfSeries: "Denne podkasten er ein del av serien",
      removeSeries: "Fjern serie",
      noSeries: "Podkasten tilhøyrer ingen serie",
    },
  },
  imageEditor: {
    editImage: "Rediger biletet",
    remove: {
      crop: "Fjern utsnitt",
      focalPoint: "Fjern fokalpunkt",
    },
  },
  imageForm: {
    title: "Bilete ",
  },
  contactBlockForm: {
    title: "Kontaktblokk",
    edit: "Rediger kontaktblokk",
    delete: "Fjern kontaktblokk",
    background: {
      subtle: "Subtil",
      moderate: "Moderat",
      strong: "Sterk",
    },
  },
  frontpageArticleForm: {
    title: "Om-NDLA-artikkel",
    validation: {
      illegalSlug: "Bruk av ulovlige tegn i permalenken! Tillatte tegn er alle tall og bokstaver, og bindestrek",
    },
    isFrontpageArticle: {
      toggleArticle: "Brei editor",
    },
  },
  gridForm: {
    title: "Grid",
    background: {
      white: "Kvit",
      transparent: "Transparent",
      gray: "Grå",
    },
    setSticky: "Lås innhald til cella ved sida av",
    unsetSticky: "Frigjer innhald frå cella ved sida av",
  },
  pitchForm: {
    title: "Rediger pitch",
    languageExplanation: "Vel språk for skjermlesar",
    sizes: {
      normal: "Normal",
      large: "Stor",
    },
  },
  learningResourceForm: {
    metaImage: {
      title: "Biletetittel",
      copyright: "Opphav",
      change: "Bytt metabilete",
    },
    title: "Læringsressurs",
    validation: {
      missingEmbedData:
        "Ein eller fleire inkluderte lyd-, bilete-, eller videoelementer mangler beskrivende tekst eller alternativ tekst.",
    },
    fields: {
      footnotes: {
        edition: "Utgåve",
        publisher: "Utgjevar",
      },
    },
  },
  keyFigureForm: {
    title: "Nykeltal",
    edit: "Rediger nykeltal",
  },
  qualityEvaluationForm: {
    title: "Kvalitetsvurdering",
    unavailable: "Ikkje satt",
    modalTitle: "Oppdater kvalitetsvurdering",
    description:
      "Legg inn ei kvalitetsvurdering av {{ resource }} med ei beskriving av den valde graderinga. Skalaen er som følgjer: 1 = eineståande, 2 = veldig bra, 3 = OK, 4 = bør fiksast, 5 = må fiksast.",
    edit: "Rediger kvalitetsvurdering",
    delete: "Slett",
    note: "Notat",
    article: "artikkelen",
    topicArticle: "emnet som heilskap",
    needsRevision: "Kvalitetsvurdert til 5",
    error: "Ein feil oppstod ved oppdatering av taksonomi",
    disabled: "Ressursar utan taksonomi kan ikkje kvalitetsvurderast",
    warning:
      "Revisjonsmerknad blir sett automatisk når ein set kvalitetsvurdering til 5. Artikkelen vil derfor få ulagra endringar.",
  },
  editorToolbar: {
    bold: "Feit\n({{ctrl}}+b)",
    "bulleted-list": "Punktliste\n({{ctrl}}+l)",
    code: "Kode\n({{ctrl}}+k)",
    "code-block": "Kodeblokk",
    "concept-inline": "Forklaring\n({{ctrl}}+alt+c)",
    "gloss-inline": "Glose\n({{ctrl}}+alt+g)",
    "comment-inline": "Kommentar\n({{ctrl}}+alt+e)",
    footnote: "Fotnote\n({{ctrl}}+alt+f)",
    language: `Språk`,
    noneLanguage: "Ingen",
    "normal-text-value": "Normal",
    "heading-1-value": "Overskrift 1",
    "heading-2-value": "Overskrift 2",
    "heading-3-value": "Overskrift 3",
    "heading-4-value": "Overskrift 4",
    "normal-text": "Normal",
    "heading-1": "Overskrift 1",
    "heading-2": "Overskrift 2\n({{ctrl}}+2)",
    "heading-3": "Overskrift 3\n({{ctrl}}+3)",
    "heading-4": "Overskrift 4\n({{ctrl}}+4)",
    italic: "Kursiv\n({{ctrl}}+i)",
    span: "Språk\n(alt+l)",
    "letter-list": "Bokstavliste\n({{ctrl}}+alt+a)",
    "content-link": "Lenke\n({{ctrl}}+alt+l)",
    mathml: "Matte\n({{ctrl}}+m)",
    "numbered-list": "Nummerert liste\n({{ctrl}}+alt+1)",
    quote: "Sitat\n({{ctrl}}+alt+b)",
    sub: "Senka\n({{ctrl}}+alt+s)",
    sup: "Hevet\n({{ctrl}}+alt+h)",
    twoColumnList: "To-kolonners liste",
    underlined: "Understreka",
    "definition-list": "Definisjonsliste\n({{ctrl}}+alt+d)",
    left: "Venstrejustert",
    center: "Midtstilt",
    right: "Høgrejustert",
    disabled: {
      "comment-inline": "Kommentar kan kun overlappe tekst",
    },
  },
  editorBlockpicker: {
    heading: "Legg til",
    open: "Åpne meny ({{ctrl}}+Enter)",
    close: "Lukk meny",
    actions: {
      block: "Seksjon",
      factAside: "Faktaboks",
      table: "Tabell",
      framedContent: "Tekst i ramme",
      details: "Ekspanderande boks",
      image: "Bilete",
      video: "Video",
      audio: "Lyd",
      h5p: "H5P",
      url: "Ressurs fra lenke",
      related: "Relatert innhald",
      file: "Fil",
      code: "Kodevisning",
      podcast: "Podkastepisode",
      conceptList: "Forklaringsliste",
      concept: "Forklaring",
      keyFigure: "Nykeltal",
      contactBlock: "Kontaktblokk",
      pitch: "Pitch",
      grid: "Grid",
      campaignBlock: "Kampanjeblokk",
      linkBlockList: "Lenkeblokk",
      gloss: "Glose",
      disclaimer: "UU-åtvaring",
      comment: "Kommentar",
    },
  },
  form: {
    createNew: "Ulagra {{type}}",
    articleSection: "Artiklar",
    metadataSection: "Metadata",
    contentSection: "Innhald",
    workflowSection: "Versjonslogg og merknader",
    taxonomySection: "Taksonomi",
    copyrightSection: "Lisens og bruker",
    podcastSection: "Podkastinformasjon",
    podcastSeriesSection: "Podkastserie",
    podcastEpisodesSection: "Episoder",
    podcastEpisodesTypeName: "Podkaster",
    inlineEdit: "Hurtigredigering",
    save: "Lagre",
    saveAsNewVersion: "Lagre som ny versjon",
    saveAndPublish: "Lagre og publiser",
    saveDraft: "Lagre utkast",
    saveTax: "Lagre taksonomi",
    choose: "Velg",
    saving: "Lagrer...",
    saveSearch: "Lagre søk",
    alreadySaved: "Lagra",
    saved: "Lagra ",
    feil: "Det er fortsatt flere feil i skjemaet",
    copy: "kopi",
    saveAsCopySuccess: "Ny artikkel lagret",
    openAll: "Opne alle",
    hideAll: "Lukk alle",
    unpublishedChanges: "(Endra sidan siste publisering)",
    moveContent: "Flytt innhald inn i teksten",
    open: "Åpne",
    close: "Lukk",
    comment: {
      comment: "Kommenter",
      hide: "Skjul kommentar",
      hideComments: "Skjul kommentarar",
      showComments: "Vis kommentarar",
      show: "Vis kommentar",
      commentField: "Kommentarfelt",
      solve: "Kommentaren er merka som uløyst. Merk som løyst",
      unresolve: "Kommentaren er merka som løyst. Merk som uløyst",
    },
    preview: {
      button: "Forhandsvis",
    },
    resize: "Endre storleik",
    slug: {
      label: "Permalenke",
      edit: "Forandre permalenke",
    },
    name: {
      slug: "Permalenke",
      title: "Tittel",
      aboutTitle: "Tittel",
      introduction: "Ingress",
      creators: "Opphavsperson",
      rightsholders: "Rettighetshaver",
      processors: "Bearbeider",
      tags: "Nøkkelord",
      license: "Lisens",
      origin: "Opphav",
      audioFile: "Lydfil",
      content: "Innhald",
      notes: "Merknader",
      metaDescription: "Metabeskrivelse",
      metaImageAlt: "Alt-tekst",
      alttext: "Alt-tekst",
      caption: "Biletetekst",
      imageFile: "Biletefil",
      visualElement: "Visuelt element",
      visualElementCaption: "Figur tekst",
      visualElementAlt: "Alt tekst",
      validFrom: "Gyldig fra",
      validTo: "Gyldig til",
      description: "Innhald",
      conceptContent: "Skildring",
      grepCodes: "Læreplankobling",
      desktopBannerId: "Breitt fagsidebilete",
      mobileBannerId: "Smalt fagsidebilete",
      concepts: "Forklaringar",
      relatedContent: "Relaterte forklaringar",
      subjects: "Fag",
      header: "Overskrift",
      manuscript: "Tekstversjon",
      coverPhotoId: "Metabilete",
      revisions: "Revisjonar",
      name: "Namn",
      subtitle: "Undertittel",
      email: "E-post",
      jobTitle: "Stilling",
      language: "Språk",
      author: "Forfattar",
      link: "Lenke",
      size: "Storleik",
      columns: "Kolonner",
      border: "Vis ramme",
      background: "Bakgrunn",
      contentType: "Innhaldstype",
      linkText: "Lenketekst",
      titleLanguage: "Tittel-språk",
      descriptionlanguage: "Beskrivelse-språk",
      url: "Lenke",
      date: "Dato",
      sides: "Kva for ei side biletet skal vises på",
      transcription: "Transkripsjon",
      type: "Type",
      text: "Kommentar",
      grade: "Gradering",
      note: "Notat",
      files: "filopplasting",
      code: "Kode",
      disclaimer: "Tilgjengelighet",
    },
    previewProductionArticle: {
      button: "Samanlikn gjeldande versjon med sist publiserte versjon",
      buttonDisabled: "Artikkelinnhaldet er identisk med sist publiserte versjon",
      version: "Versjon {{revision}}",
      current: "Gjeldende versjon",
      published: "Publisert versjon",
      article: "Artikkel",
      enableDiff: "Marker forskjeller",
      diffInfo:
        "Markerer forskjellar i den upubliserte versjonen. Sletta tekst vil markerast med raudt, endra tekst med gult og ny tekst med grønt. Bilete og blokkelement vil visast med ei ramme rundt, men visninga kan vera noko mangelfull for nokre element.",
    },
    previewLanguageArticle: {
      button: "Samanlikn språkversjonar",
      title: "Utkast på {{language}}",
    },
    previewNewWindow: "Forhåndsvis i nytt vindu",
    contributor: {
      add: "Legg til",
    },
    abort: "Avbryt",
    edit: "Rediger",
    remove: "Fjern",
    validate: "Valider",
    publish: "Publiser",
    savedOk: "Lagra OK",
    publishedOk: "Publisert OK",
    validationOk: "Ingen valideringsfeil funnet",
    createdOk: "Oppretta OK",
    addNewImage: "Legg til nytt bilete",
    mustSaveFirst: "Du må lagre endringene dine først",
    addNewAudio: "Legg til ny lyd",
    notes: {
      heading: "Merknader",
      add: "Legg til merknad",
      remove: "Fjern",
      warning: "Ein merknad må ha tekst",
      areHere: "Du er her",
      published: "Publisert",
      placeholder: "Skriv inn merknad",
      history: {
        user: "Bruker",
        time: "Når",
        status: "Status",
        heading: "Merknadshistorikk",
        note: "Merknad",
        empty: "Ingen merknader",
      },
    },
    updated: {
      label: "Oppdatert dato",
    },
    published: {
      label: "Publisert dato",
      reset: "Resett dato",
    },
    updatePublished: "Endre publisert dato",
    editImage: "Endre bilete",
    editOriginalImage: "Rediger original bilete",
    editAudio: "Endre lyd",
    editOriginalAudio: "Rediger original lyd",
    editPodcast: "Endre podkast",
    editH5p: "Endre H5P",
    resetToProd: {
      button: "Tilbakestill endringer",
      modal: "Vil du tilbakestille utkastet til slik det er på ndla forsida?",
      success: "Innhold er tilbakestilt, trykk lagre for å lagre endringene",
    },
    resetToVersion: "Tilbakestill til versjon",
    previewVersion: "Samanlikn med publisert",
    variant: {
      create: "Legg til språk",
      translate: "Oversett til nynorsk",
    },
    remainingCharacters: "Maks {{maxLength}} teikn og du har {{remaining}} igjen.",
    title: {
      label: "Tittel",
    },
    introduction: {
      label: "Ingress",
    },
    metaImage: {
      title: "Metabilete",
      label: "Metabilete",
      imageTitle: "Biletetittel",
      helpLabel: "Kva er eit metabilete?",
      copyright: "Opphav",
      change: "Bytt metabilete",
      add: "Velg metabilete",
      remove: "Fjern metabilete",
    },
    availability: {
      everyone: "Alle",
      teacher: "Lærarar",
      label: "Tilgjengelighet",
      description: "Kven er artikkelen meint for:",
    },
    modelReleased: {
      label: "Modellklarert",
      yes: "Ja",
      no: "Nei",
      "not-applicable": "Ikkje relevant",
      "not-set": "Ikkje valgt",
      description: "Om biletet er modellklarert eller ikkje:",
    },
    markdown: {
      button: "Klikk for å se markdown",
      helpLabel: "Kva er markdown?",
    },
    visualElement: {
      title: "Legg til visuelt element",
      label: "Visuelt element",
      helpLabel: "Informasjon om visuelt element",
      video: "Videosøk",
      image: "Biletesøk",
      imageUpload: "Last opp bilete",
      h5p: "H5P",
      description:
        "Visuelt element kan setjast ulikt for kvart språk. Dersom visuelt element ikkje finst, vil det hentast automatisk frå eit anna språk.",
    },
    visualElementPicker: {
      h5p: "H5P",
      url: "Ny ressurs",
      video: "Video",
      image: "Bilete",
    },
    concept: {
      create: "Opprett ny forklaring",
      edit: "Rediger forklaring",
      remove: "Fjern forklaring",
      source: "Kjelde",
      markdown: "Feltet støtter markdown. Bruk formatet [Tekst](https://url) for å lage lenke.",
      subjects: "Berre fag markert som forklaringsfag vil visast i lista.",
    },
    gloss: {
      create: "Opprett ny glose",
      edit: "Rediger glose",
      remove: "Fjern glose",
      removeExample: "Fjern eksempel",
      source: "Kjelde",
      markdown: "Feltet støtter markdown. Bruk formatet [Tekst](https://url) for å lage lenke.",
      subjects: "Berre fag markert som forklaringsfag vil visast i lista.",
      gloss: "Gloseord på målspråk",
      originalLanguage: "Originalspråk",
      wordClass: "Ordtype",
      glossHeading: "Glose og ordtype",
      transcriptions: "Transkripsjonar",
      transcription: "Transkripsjon",
      romanization: "Skriftsystem",
      example: "Eksempel",
      language: "Språk",
      languageVariant: "Språkvariant",
      add: "Legg til {{label}}",
      choose: "Velg {{label}}",
      languageMissingFields: "Alle felt for eit språk må fyllast ut.",
      exampleMissingFields: "Alle felt for eit eksempel må fyllast ut.",
      glossMissingFields: "Ei glose må innehalde alle felt.",
      transcriptionMissingFields: "Ein transkripsjon kan ikkje være tom.",
      editExamples: "Rediger døme",
      editExamplesHeading: "Vel dømesetningar og språk",
      editExamplesLanguage: "Vel kva språk du vil visa på glosekortet",
      displayOnGloss: "Vis dette dømet på glosekortet",
      titleSection: "Norsk omsetjing",
      audio: {
        helperText: "Legg til lyd fra lyd-api til glosen.",
        button: "Legg til lyd",
      },
      examples: {
        title: "Eksemplar på bruk av glosen",
        description: "Legg inn relevante eksemplar på bruk av glosen.",
        exampleOnIndex: "Eksempel {{index}}",
        exampleOnLanguage: `Eksempel {{index}} på {{language}}`,
        exampleTextLabel: `Eksempeltekst på {{language}} for eksempel {{index}}`,
        removeLanguageVariant: "Fjern eksempel {{index}} på {{language}}",
        remove: "Fjern eksempel {{index}}",
      },
    },
    conceptList: {
      edit: "Rediger forklaringsliste",
      remove: "Fjern forklaringsliste",
    },
    workflow: {
      title: "Status",
      change: "Endre status",
      qualityAssurance: "Kvalitetssikring",
      saveAsNew: "Lag kopi",
      deleteLanguageVersion: {
        button: "Slett {{languageVersion}} versjon",
        title: "Slett språkversjon",
        modal: "Er du sikker på at du vil slette denne språkversjonen?",
      },
      statusInfoTooltip: "Kva er forskjella på dei ulike statusane?",
      statusLabel: "Status",
      published: "Det finst ein publisert versjon av dettet elementet.",
      multipleTaxonomy: "Artikkelen har fleire oppføringar i taksonomi.",
      currentStatus: "Gjeldande status: {{status}}.",
      expiration: {
        warn: "Ein av revisjonane utløper snart (Må revideras innen {{date}}).",
        expired: "Ein av revisjonane har utløpt (Utløpte {{date}}).",
      },
      deleteComment: {
        title: "Slett kommentar",
        modal: "Vil du slette denne kommentaren? Det er ikkje mogleg å gjenopprette han.",
        button: "Slett",
      },
      addComment: {
        createdBy: "Oppretta av",
        warn: "Hugs å legge til kommentar",
        description: "Du har endra ansvarleg uten å legge til kommentar!",
        add: "Legg til ny kommentar",
        label: "Skriv inn kommentar",
      },
      updateComment: "Oppdater kommentar",
    },
    status: {
      new: "Ny - Ikke lagret",
      new_language: "Nytt språk - ikke lagret",
      created: "Oppretta",
      planned: "Planlagd",
      in_progress: "I arbeid",
      external_review: "Eksternt gjennomsyn",
      internal_review: "Sisteblikk",
      quality_assurance: "Kvalitetssikring desk",
      language: "Språk",
      for_approval: "Godkjenning LMA",
      end_control: "Sluttkontroll",
      imported: "Frå spoling",
      draft: "Kladd",
      proposal: "Utkast",
      user_test: "Brukertest",
      awaiting_quality_assurance: "Til kvalitetssikring",
      queued_for_language: "Til språk",
      translated: "Ferdig fra språk",
      quality_assured: "Publiseringsklar",
      quality_assured_delayed: "Publ.klar-utsatt",
      queued_for_publishing: "Til publisering",
      queued_for_publishing_delayed: "Publ-utsatt",
      publish_delayed: "Publ-utsatt",
      published: "Publisert",
      has_published: "Har publisert versjon",
      unlisted: "Lenkedelt",
      unpublished: "Avpublisert",
      awaiting_unpublishing: "Til avpublisering",
      awaiting_archiving: "Utsatt arkivering",
      archived: "Slettet",
      republish: "Til republisering",
      sum: "Totalt",
      private: "Privat",
      actions: {
        PLANNED: "Planlagd",
        IN_PROGRESS: "I arbeid",
        EXTERNAL_REVIEW: "Eksternt gjennomsyn",
        INTERNAL_REVIEW: "Sisteblikk",
        QUALITY_ASSURANCE: "Kvalitetssikring desk",
        LANGUAGE: "Språk",
        FOR_APPROVAL: "Godkjenning LMA",
        END_CONTROL: "Sluttkontroll",
        DRAFT: "Kladd",
        PROPOSAL: "Utkast",
        USER_TEST: "Brukertest",
        AWAITING_QUALITY_ASSURANCE: "Til kvalitetssikring",
        QUEUED_FOR_LANGUAGE: "Til språk",
        TRANSLATED: "Ferdig fra språk",
        QUALITY_ASSURED: "Publiseringsklar",
        QUEUED_FOR_PUBLISHING: "Til publisering",
        QUALITY_ASSURED_DELAYED: "Publ.klar-utsatt",
        QUEUED_FOR_PUBLISHING_DELAYED: "Publ-utsatt",
        PUBLISH_DELAYED: "Publ-utsatt",
        PUBLISHED: "Publiser",
        AWAITING_UNPUBLISHING: "Til avpublisering",
        UNPUBLISHED: "Avpubliser",
        ARCHIVED: "Slett",
        AWAITING_ARCHIVING: "Utsatt arkivering",
        REPUBLISH: "Til republisering",
      },
      learningpath_statuses: {
        private: "Kladd",
        published: "Offentleg",
        unlisted: "Lenkedelt",
        submitted: "Bedt om offentleggjering",
      },
    },
    validDate: {
      label: "Gyldighet",
      from: {
        label: "Gyldig fra",
        placeholder: "Fra og med dato",
      },
      to: {
        label: "Gyldig til",
        placeholder: "Til og med dato",
      },
    },
    content: {
      label: "Innhald",
      placeholder: "Innhald",
      figure: {
        notSupported: "Mediatype {{mediaType}} er ikkje støtta.",
      },
      relatedArticle: {
        placeholder: "Søk på tittel",
        urlPlaceholder: "http://www.example.com",
        urlLocation: "Nettside hos {{domain}}",
        titlePlaceholder: "Tittel",
        invalidArticle: "Ugyldig artikkel",
        addExternal: "Legg til ekstern artikkel",
        removeExternal: "Slett ekstern artikkel",
        changeExternal: "Endre ekstern artikkel",
        searchExternal: "Skriv inn tittel og url på ekstern artikkel",
        listLabel: "Valg",
      },
      conceptList: {
        subjectMissing: "Fag manglar: {{subjectId}}",
      },
      concept: {
        remove: "Fjern forklaring",
        choose: "Velg forklaring",
      },
      gloss: {
        remove: "Fjern glose",
        choose: "Velg glose",
      },
      link: {
        name: "Namn",
        domains: "Url",
        validDomains: "Gyldige domener",
        goTo: "Gå til",
        insert: "Sett inn lenke",
        update: "Oppdater lenke",
        change: "Endre",
        remove: "Fjern lenke",
        href: "Lenke",
        newTab: "Åpne lenke i ny fane",
        text: "Tekst",
        addTitle: "Legg til lenke",
        changeTitle: "Endre lenke",
        required: "Lenke er påkrevd",
        invalid: "Ugyldig lenke",
        preview: "Forhåndsvis lenke",
        unSupported: "Innhaldstypen i lenka er ikkje støtta",
        newUrlResource: "Ny ressurs",
        changeUrlResource: "Rediger ressurs: {{type}}",
        fullscreen: "Åpne i nytt vindu",
        description:
          "Lenker til ndla-ressursar spesialhandterast av systemet og visast korrekt på {{- url}}. Interne ressursar visast med lilla bakgrunn og eksterne lenker med blå.",
      },
      footnote: {
        title: "Tittel",
        year: "År",
        authors: {
          label: "Forfatter",
          description: "Obligatorisk med minst 1 forfatter.",
          createOption: "Opprett ny forfatter",
        },
        edition: "Utgåve",
        publisher: "Utgjevar",
        addTitle: "Legg til fotnote",
        editTitle: "Rediger fotnote",
        removeFootnote: "Fjern fotnote",
      },
      table: {
        "row-remove": "Fjern rad",
        "row-add": "Legg til rad",
        "column-add": "Legg til kolonne",
        "column-remove": "Fjern kolonne",
        "table-remove": "Fjern tabell",
        colgroups: "Colgroups",
        colgroupTitle: "Colgroups for å sette bredde",
        colgroupInfo: "Eksempel: ",
        "edit-colgroups": "Rediger colgroups",
        "enable-header": "Aktiver tittel-kolonne",
        "disable-header": "Deaktiver tittel-kolonne",
        addHeader: "Legg til tittel-rad",
        "column-left": "Venstrejuster kolonne",
        "column-center": "Midtstill kolonne",
        "column-right": "Høyrejuster kolonne",
        row: "rad",
        column: "kolonne",
      },
      normalizedOnLoad:
        "Artikkelen inneheld HTML-kode som er endra av editoren. Derfor må ressursen republiserast sjølv om du berre har endra metadata eller læreplankodar.",
    },
    tags: {
      label: "Nøkkelord",
      helpLabel: "Kva er nøkkelord?",
      description: "Obligatorisk med 3 nøkkelord.",
      createOption: "Opprett nytt nøkkelord",
      searchPlaceholder: "Søk etter nøkkelord",
    },
    categories: {
      label: "Liste og filter",
      description: "Format: Liste:Filter1:Filter2",
      searchPlaceholder: "Søk etter lister",
    },
    grepCodes: {
      label: "Kompetansemål og kjerneelementer",
      placeholder: "Skriv inn kode",
      description:
        "Skriv inn koder som starter på riktig format ({{ codes }} fulgt av eit eller fleire siffer. Koder som ikkje eksisterer vil ikkje bli oppretta. Tekstene visast på bokmål i ed, men korrekt i artikkelvisning.",
    },
    articleDisclaimer: {
      title: "Informasjon om tilgjengelegheit for heile artikkelen",
      description:
        "Skriv inn kva som er utfordrande med innhaldet i artikkelen. Du kan òg leggje til lenker til alternativt innhald. Det er utarbeidd malar for dette. Sjekk desse før du tek i bruk komponenten.",
    },
    resourceTypes: {
      label: "Innhaldstype og egenskaper",
      placeholder: "Legg til egenskap",
    },
    subjects: {
      label: "Fag",
      searchPlaceholder: "Søk etter fag",
      placeholder: "Legg til fag",
    },
    topics: {
      label: "Emnetilknytning",
      placeholder: "Legg til emnetilknytning",
      primaryTopic: "Primærkobling",
      sharedTopic: "Delt emne",
      setPrimaryTopic: "Vel som primærkoblet emne",
      RGTooltip: "Vel mellom Kjernestoff eller Tilleggsstoff",
    },
    metaDescription: {
      label: "Metabeskrivelse",
      description: "Beskrivelsen blir synlig i søk.",
      helpLabel: "Kva er metabeskrivelse?",
    },
    agreement: {
      label: "Koble til avtale",
      helpLabel: "Kva er ei avtale?",
      placeholder: "Søk etter avtale",
    },
    rightsholders: {
      label: "Rettighetshaver",
      labelRemove: "Fjern",
      placeholder: "Skriv namn til rettighetshaver",
      createOption: "Opprett ny rettighetshaver",
    },
    processors: {
      label: "Bearbeider",
      labelRemove: "Fjern",
      placeholder: "Skriv namn til bearbeider",
      createOption: "Opprett ny bearbeider",
    },
    creators: {
      label: "Opphavsperson",
      labelRemove: "Fjern",
      placeholder: "Skriv namn til opphavsperson",
      createOption: "Opprett ny opphavsperson",
      description: "Obligatorisk med minst 1 opphavsperson.",
    },
    license: {
      label: "Lisens",
      helpLabel: "Kva er lisensar?",
      choose: "Velg ein lisens",
    },
    responsible: {
      label: "Ansvarleg",
      choose: "Velg ansvarleg",
      noResults: "Ingen treff",
      noResponsible: "Ingen ansvarleg",
      revisionDate: "Antall som nærmar seg revisjonsdato",
      error: "Noe gjekk gale ved oppdatering av ansvarleg.",
    },
    origin: {
      label: "Opphav",
    },
    processed: {
      label: "Omarbeidd",
      description: "Innhaldet har vorte omarbeidd",
      disabledCause: "Omarbeidd kan kun settast dersom opphav er satt",
    },
    image: {
      file: "Bilete",
      save: "Lagre bilete",
      editImage: "Rediger bilete",
      removeImage: "Fjern bilete",
      alignment: {
        left: "Justering: Venstrestilt",
        right: "Justering: Høgrestilt",
        center: "Justering: Stort i midten",
      },
      sizes: {
        xsmall: "Størrelse: Frimerke",
        small: "Størrelse: Lite",
        medium: "Størrelse: Middels",
        fullwidth: "Størrelse: Stort",
      },
      crop: "Lag utsnitt av biletet",
      aspect: {
        "4_3": "4:3",
        "3_4": "3:4",
        "16_9": "16:9",
        square: "Kvadratisk",
        none: "Fritt",
      },
      focalPoint: "Sett fokalpunkt",
      caption: {
        label: "Biletetekst",
        placeholder: "Biletetekst",
        hide: "Skjul biletetekst",
      },
      alt: {
        label: "Alt-tekst",
        placeholder: "Alt-tekst",
        noText: "Universell utforming krever alt-tekst for bilde som ikkje er dekorative.",
      },
      fileUpload: {
        description: "Dra og slipp eller trykk for å laste opp bilete",
        button: "Legg til",
        genericError: "Opplasting av biletfil feila",
        tooLargeError: "Biletfil  er for stor",
        fileTypeInvalidError: "Filtypen er ikkje støtta",
      },
      byline: {
        show: "Vis byline",
        hide: "Skjul byline",
      },
      isDecorative: "Bildet er kun dekorativt i denne samanhengen",
      showBorder: "Vis bilderamme",
    },
    video: {
      caption: {
        label: "Videotekst",
        placeholder: "Videotekst",
      },
      remove: "Fjern video",
      save: "Lagre video",
      editVideo: "Rediger video",
      time: {
        start: "Start",
        stop: "Stopp",
        hms: "h:m:s",
      },
      brightcove: "Åpne i Brightcove",
      toLinkedVideo: "Bytt til synstolket versjon",
      fromLinkedVideo: "Bytt tilbake til original versjon",
      linkedVideoButton: "ST",
    },
    h5p: {
      remove: "Fjern H5P",
      copy: "Kopier H5P",
      copyError: "Kopiering av H5P-elementet feila",
      metadata: {
        alttext: "Alt-tekst",
        save: "Lagre",
        cancel: "Avbryt",
        edit: "Endre H5P metadata",
        description: "Metadataen blir lagra i artikkelen og vil ikkje påverka H5P-ressursen",
      },
    },
    audio: {
      file: "Lydfil",
      title: {
        label: "Lydtittel",
        placeholder: "Lydtittel",
      },
      manuscript: "Tekstversjon",
      caption: {
        label: "Lydtekst",
        placeholder: "Lydtekst",
      },
      edit: "Rediger lydfil",
      remove: "Fjern lydfil",
      chooseAudioType: "Velg lydtype",
      sound: "Lyd",
      speech: "Tale",
      fileUpload: {
        description: "Dra og slipp eller trykk for å laste opp lydfil",
        button: "Legg til",
        genericError: "Opplastning av lydfil feila",
        fileTypeInvalidError: "Filtypen er ikkje støtta",
      },
      copiedFrom: "Lydfil kopierast frå {{language}}. Trykk på søppelbøtta for å slette den og laste opp ei ny fil.",
      info: {
        multipleFiles: "Du kan laste opp forskjellige lydfiler for kvart språk.",
        changeFile: "Fjerning og endring av eit språk vil ikkje påverke dei andre språka.",
        newLanguage: "Ved oppretting av eit nytt språk vil ei lydfil fra eit eksisterande språk foreslås.",
        deleteFiles: "Ei lydfil slettast berre når den ikkje lenger brukes i eit språk.",
      },
      modal: {
        header: "Lydfiler",
        label: "Informasjon om lydfiler",
      },
    },
    podcast: {
      remove: "Fjern podkast",
    },
    external: {
      title: "eksternt",
      edit: "Rediger {{type}} element",
      remove: "Fjern {{type}} element",
    },
    related: {
      title: "Relatert innhald",
      subtitle: "Dra artikkel for å endra rekkefølgje",
      showMore: "Vis meir relatert innhald",
      showLess: "Vis mindre",
    },
    file: {
      label: "Filer",
      file: {
        label: "Fil",
      },
      download: "Last ned:",
      alt: {
        label: "Alt-tekst",
        placeholder: "Alt-tekst",
      },
      title: {
        label: "Filtittel",
        placeholder: "Filtittel",
      },
      addFile: "Legg til fil",
      removeList: "Fjern filliste",
      placeholder: "Oppgi eit filnamn",
      changeName: "Endre namn",
      changeOrder: "Endre rekkefølgje",
      removeFile: "Fjern fil",
      missingFileTooltip: "Ser ikkje ut til å eksistere på serveren. Den kan ha blitt sletta frå ein annan artikkel.",
      missingFilename: "Filtypen støttes ikke",
      fileUpload: {
        description: "Dra og slipp eller trykk for å laste opp fil(er)",
        button: "Legg til",
        genericError: "Opplasting av fil(er) feila",
        fileTypeInvalidError: "Filtypen er ikkje støttet",
        tooManyError: "Maks 5 filer kan lastast opp om gongen",
      },
      showPdf: "Vis ekspandert",
      showPdfTooltip: "Vis ekspandert PDF i artikkel",
    },
    article: {
      label: "Artikkel",
      add: "Legg til artikkel",
    },
    learningpathConnections: {
      sectionTitle: "Bruk av artikkelen i læringsstiar",
      title: "Læringsstiar som inneheld denne artikkelen",
    },
    myNdla: {
      noFavorites: "Ingen har favorittmerka ressursen.",
      numFavorites: "Ressursen har vorte favorittmerka {{num}} gonger.",
    },
    embedConnections: {
      type: {
        image: "biletet",
        audio: "lydfilen",
        concept: "forklaringa",
        gloss: "glosen",
        article: "artikkelen",
      },
      sectionTitleArticle: "Artiklar som bruker {{resource}}",
      sectionTitleConcept: "Forklaringar som bruker {{resource}}",
      title: "Bruk av {{resource}}",
      info: {
        image: "Bruk av biletet i artiklar og/eller forklaringar",
        audio: "Bruk av lydfilen i artikler",
        concept: "Bruk av forklaringa i artikler",
        gloss: "Bruk av glosen i artikler",
        article: "Bruk av artikkelen i andre artiklar",
      },
      articles: "1 artikkel",
      articles_plural: "{{count}} artikler",
      concepts: "1 forklaring/glose",
      concepts_plural: "{{count}} forklaringar/gloser",
    },
    relatedConcepts: {
      placeholder: "Søk på tittel",
      articlesTitle: "Forklaringar",
      changeOrder: "Endre rekkefølgje",
      removeArticle: "Fjern forklaring",
    },
    relatedContent: {
      placeholder: "Søk på tittel",
      articlesTitle: "Innhald",
      changeOrder: "Endre rekkefølgje",
      removeArticle: "Fjern innhald",
      addExternal: "Legg til ekstern artikkel",
      link: {
        missingTitle: "Mangler tittel",
        missingUrl: "Url må begynne med http:// eller https://",
        titlePlaceholder: "Tittel",
        urlPlaceholder: "https://example.com",
        addLink: "Legg til",
      },
    },
    section: {
      remove: "Fjern seksjon",
    },
    revisions: {
      add: "Ny revisjon",
      remove: "Fjern revisjon",
      revisionNumber: "Revisjon {{number}}",
      description:
        "Revisjonar krev ei skildring og ein dato artikkelen går ut på. Bryteren markerar i kva grad ein revisjon er utført eller ikkje. Hugs at ein revidert artikkel må republiserast.",
      datePickerTooltip: "Dato artikkelen går ut dersom revisjonen ikkje blir markert som revidert.",
      reminder: "Hugs å sjekke om revisjonen du no har utført krev republisering.",
      switchTooltip: "I kva grad artikkelen er revidert eller ikkje.",
      inputPlaceholder: "Beskrivelse av revisjonen",
      deleteTooltip: "Fjern denne revisjonen",
    },
    disclaimer: {
      edit: "Endre informasjon on tilgjengelighet",
      title: "Universell utforming - informasjon i løpande tekst",
      description:
        "Skriv inn kva som er problemet med komponenten. Det er utarbeidd malar for dette. Sjekk desse før du tek i bruk komponenten.",
      editorHeader: "Informasjon om tilgjengelegheit for enkeltkomponentar",
    },
    copyright: {
      title: "Rediger lisens",
      edit: "Rediger lisens",
      add: "Legg til lisensiert innhold",
    },
  },
  validation: {
    isRequired: "{{label}} er påkrevd.",
    bothFields: "Ein {{labelLowerCase}} må inneholde alle felt.",
    isNumeric: "{{label}} må inneholde tall.",
    maxLength: "{{label}} kan ikkje ha meir enn {{maxLength}} teikn.",
    minLength: "{{label}} må ha minst {{minLength}} teikn.",
    url: "{{label}} må inneholde ei gyldig lenke.",
    urlOrNumber: "{{label}} må inneholde ei gyldig lenke eller artikkel-id.",
    dateBeforeInvalid: "{{label}} kan ikkje være etter {{afterLabel}}.",
    dateAfterInvalid: "{{label}} kan ikkje være før {{beforeLabel}}.",
    minItems: "{{label}} feltet må minst inneholde ein/eitt {{labelLowerCase}}.",
    minItems_plural: "{{label}} feltet må minst inneholde {{count}} ulike {{labelLowerCase}}.",
    noEmptyNote: "Ein merknad kan ikkje være tom",
    noEmptyRevision: "Ein beskrivelse kan ikkje være tom",
    noLicenseWithoutCopyrightHolder: "Ein lisens kan ikkje takast i bruk uten å definere minst ein opphavar.",
    maxSizeExceeded:
      "Filen du forsøkar å laste opp er for stor. Maksstorleik: {{maxSize}} MB. Filstorleik: {{fileSize}} MB.",
    grepCodes:
      "Koden er på feil format. Det korrekte formatet er K(E/M) eller TT fulgt av eit eller fleire siffer. Eks. KE137, KM2255, TT2.",
    podcastImageShape: "Metabilete må være like høgt som det er breitt.",
    podcastImageSize: "Metabilete må være mellom 1400 og 3000 pikslar breitt.",
    unfinishedRevision: "Det må være minst ein planlagd revisjon.",
    missingRevision: "Det må være minst ein revisjon.",
    email: "E-postadressa er ikkje gyldig.",
  },
  errorMessage: {
    title: "Oops, noko gjekk gale",
    description: "Vi beklager, men ein feil oppsto.",
    back: "Tilbake",
    goToFrontPage: "Gå til forsida",
    invalidUrl: "Ugyldig url",
    noArticleInProd: "Ingen artikkel funnet i prod",
    taxonomy: "Det var eit problem ved lasting av taksonomi",
    versionSelect: "Artikkelen finst ikkje i vald versjon",
    errorWhenFetchingTaxonomyArticle: "Det var eit problem ved lasting av den underliggande artikkelen",
    unsavedTaxonomy: "Du har ulagra endringar. Trykk tilbakestill igjen viss du ønsker å fortsette.",
    auth0:
      "Autentiseringsfeil. Trykk avbryt for å ta vare på eventuelle endringer du har gjort før du logger inn på nytt. Følgende feilmelding kom fra auth0: {{message}}",
    statusCode: {
      409: "Denne artikkelen har allerede blitt oppdatert. Ta vare på det du har endra og last sida på nytt for å kunne lagre.",
    },
    grepCodes: "Følgande koder har feil format eller eksisterer ikkje, og blir ikkje lagt til: ",
    errorOnSave: "Noko gjekk gale under lagring av artikkelen.",
    genericError: "Noko gjekk gale, handlinga kunne ikkje utførast.",
    missingTaxTitle: "Ikkje i taksonomi!",
    missingTax:
      "Artiklar og emner kan ikkje lagrast uten å plasserast i taksonomien. Oppdater taksonomi-blokka og lagre på nytt.",
    invalidTopicPlacements: "Emner uten plassering i taksonomi",
  },
  warningMessage: {
    fieldWithWrongLanguage: "Dette feltet er henta frå språkkode: {{language}}",
  },
  notFound: {
    description: "Denne sida finnes ikkje.",
  },
  forbiddenPage: {
    description: "Du har ikkje tilgang til denne sida",
  },
  alertModal: {
    notSaved: "Dokumentet er ikkje lagra, ønsker du å fortsette?",
    needToRefresh:
      "Nokon har lagra samme artikkel medan du redigerte. For å ta vare på endringane dine må du kopiere dei manuelt og deretter oppdatere sida",
    continue: "Fortsett",
    delete: "Slett",
    confirm: "Bekreft",
    disconnect: "Kople frå",
    loginAgain: "Logg inn på nytt",
    watchOut: "Pass på!",
  },
  environment: { production: "", staging: "staging", test: "test" },
  taxonomy: {
    nodeType: {
      PROGRAMME: "utdanningsprogram",
      SUBJECT: "fag",
      TOPIC: "emne",
    },
    favorite: { add: "Favorittmerk faget", remove: "Fjern favorittmarkering av faget" },
    publishedVersion: "Sjå publisert versjon",
    noValue: "Ikkje satt",
    previewProgrammes: "Forhåndsvis utdanningsprogram i frontend",
    addNode: "Legg til {{nodeType}}",
    newNode: "Nytt {{nodeType}}",
    newNodeName: "Namn på nytt element",
    newResource: "Ny ressurs",
    editStructure: "Rediger struktur",
    editSubjectpage: "Rediger fagforside",
    deleteSubject: "Slett fag",
    addSubject: "Legg til fag",
    subjectName: "Namn på nytt fag",
    addExistingNode: "Flytt eksisterande {{nodeType}} hit",
    addExistingLoading: "Flyttar ...",
    addExistingSuccess: "Noden har blitt flytta!",
    existingNode: "Søk opp eksisterande {{nodeType}} for flytting",
    workflow: "i flyt",
    fullTopic: "Gjennomsnitt:",
    TOPIC: "emnet",
    SUBJECT: "faget",
    PROGRAMME: "utdanningsprogrammet",
    qualityDescription:
      "Snitt av kvalitetsvurdering av alle vurderte ressursar i {{nodeType}} ({{count}} vurderte ressurser)",
    average: "Gj.snitt",
    qualityEvaluation: "Heilskapleg vurdering av {{nodeType}}",
    connectExistingNode: "Knytt {{nodeType}} til denne noden",
    connectExistingLoading: "Legger til ...",
    connectExistingSuccess: "Noden har blitt knytta til!",
    disconnectNode: "Fjern frå foreldernode",
    confirmDisconnect: "Er du sikker på at du vil fråkople denne noden?",
    newSubject: "Nytt fag",
    resources: "Ressurser",
    newTopic: "Nytt emne",
    nodeSettings: "Innstillinger",
    programmeSettings: "Utdanningsprogram-instillingar",
    subjectSettings: "Faginnstillinger",
    topicSettings: "Emneinnstillinger",
    currentVersion: "Noverande versjon",
    delete: {
      deleteNode: "Slett {{ nodeType }}",
      deleteDisabled: "{{ nodeType }} med {{ childNode }} kan ikkje slettast",
      deleteResource: "Slett ressurs",
      child: "barn",
      subTopic: "underemner",
      topic: "emner",
      confirmDelete: "Er du sikker på at du vil slette dette {{ nodeType }}?",
    },

    version: "Versjon",
    createResource: "Opprett ny ressurs",
    addNewPlannedResource: "Opprett ny planlagd ressurs",
    resourceType: { label: "Kjernestoff eller tilleggstoff", tabTitle: "Endre kjernestoff/tilleggstoff" },
    title: "Tittel",
    comment: "Kommentar",
    commentPlaceholder: "F.eks. innhald, læremål eller grep",
    contentType: "Innhaldstype",
    contentTypePlaceholder: "Velg innhaldstype",
    create: "Opprett",
    add: "Legg til",
    getExisting: "Eller hent eksisterande ressurs",
    inProgress: "Denne artikkelen har blitt byrja på",
    addPriority: "Prioritering",
    supplementary: "Tilleggstoff",
    displayOptions: "Visningsvalg",
    changeName: {
      loadError: "Klarte ikkje hente omsetjingar",
      updateError: "Klarte ikkje oppdatere omsetjingar",
      defaultName: "Standardnamn",
      addNewTranslation: "Legg til ny omsetjing",
      buttonTitle: "Endre namn",
      language: "Språk",
      name: "Namn",
      namePlaceholder: "Namn",
      delete: "Slett",
      title: "Endre namn",
      cancel: "Avbryt",
      add: "Legg til",
      noTranslations: "Ingen omsetjingar tilgjengeleg! Standardnamn vil brukes inntil dette er lagt inn.",
    },
    addTopic: "Legg til nytt emne",
    addTopicHeader: "Legg til emne",
    createTopic: "Opprett nytt emne",
    searchExistingTopic: "Søk etter eksisterande emne",
    errorMessage: "Ein feil oppsto",
    confirmDeleteTopic: "Er du sikker på at du vil slette emnet?",
    confirmDeleteSubject: "Er du sikker på at du vil slette faget?",
    linkSettings: "Link",
    setPrimary: "Sett til primærkobling",
    addResource: "Legg til ressurs",
    removeResource: "Fjern ressurs frå emne",
    searchResource: "Søk etter ressurs",
    searchArticle: "Søk etter emneartikkel",
    or: "Eller",
    urlPlaceholder: "Lim inn lenke fra ndla.no eller ein artikkel-id",
    wrongType: "Obs! Denne ressursen er ein anna type",
    noResources: "Ingen ressurser funnet",
    addTopicDescription: "Endre emnebeskrivelse",
    confirmSetPrimary: "Vil du gjere dette til hovedplassering?",
    jumpToResources: "Hopp til ressurser",
    jumpToStructure: "Hopp til struktur",
    showLMASubject: "Vis LMA-fag",
    showDASubject: "Vis DA-fag",
    showSASubject: "Vis SA-fag",
    swapTopicArticle: {
      failed: "Klarte ikkje å bytte emneartikkel",
      placeholder: "Artikkel du vil bytte til",
      info: "Bytt emneartikkel",
      success: "Emneartikkelen er bytta! Last sida på nytt for å få oppdatert navn på emnet.",
    },
    copyResources: {
      error: "Noko gjekk feil med kopiering",
      info: "Gjenbruk ressurser fra emne",
      placeholder: "Søk opp eksisterande {{nodeType}} for gjenbruk av ressursar",
      done: "Ressurser ferdigkopiert!",
      waiting: "Kopierer ressurser",
    },
    cloneResources: {
      error: "Noko gjekk feil med kloning",
      info: "Kopier og klon ressurser fra emne",
      placeholder: "Søk opp eksistarende {{nodeType}} for kopi av ressursar",
      done: "Ressurser ferdigklonet!",
      waiting: "Kloner ressurser",
    },
    favorites: "Vis favorittar",
    quality: "Vis kvalitet",
    publish: {
      button: "Publiser alle ressursar",
      waiting: "Publiserar ressurser",
      info: "Er du sikker på at du ønskjar å publisere alle ressursane som er knytta til denne noden?",
      done: "Ressurser er publisert",
      error: "Følgande ressurser blei ikkje publisert:",
    },
    info: {
      title: "Informasjon",
      subTitle: "Id og synlighet for elementet",
      wrongArticleType:
        'Artikkelen er plassert som "{{placedAs}}" i taksonomien, men artikkelen er av typen "{{isType}}".',
      missingArticleType: "Artikkelen med ID {{id}} manglar artikkeltype. Han er sannsynlegvis sletta.",
      wrongConnections: "Feilkoplingar",
      wrongConnectionsSubTitle: "Denne artikkelen har feilkoplingar, sjå lista under.",
      canBeFixedInDatabase: "Artikkeltypen kan endres i databasen for å fikse feilen.",
      notPublished: "Artikkelen har ingen publisert versjon.",
    },
    resource: {
      confirmDelete: "Vil du fjerne ressursen frå denne mappa? Dette vil ikkje påverke plasseringa andre steder",
      copyError:
        "Det oppstod ein feil ved kopiering av ressursar. Dobbeltsjekk dei kopierte ressursane og prøv å fikse manglar manuelt, eller slett dei kopierte ressursane og prøv å kopiere på nytt",
      addResourceConflict: "Ressursen du forsøkte å legge til finnes allerede på emnet.",
      noResourceId: "Klarte ikkje hente ut ID frå den valde ressursen",
      creationFailed: "Klarte ikkje å opprette kobling",
    },
    removeLink: "Fjern lenke",
    resourceTypes: {
      title: "Innhaldstype",
      helpLabel: "Kva er ei Innhaldstype?",
      subTitle: "Kva for ei innhaldstype har denne ressursen?",
      placeholder: "Velg innhaldstype",
    },
    topics: {
      title: "Emnetilknytninger",
      topicPlacement: "Emneplassering",
      helpLabel: "Kva er emnetilknytning?",
      subTitle: "Kvar i taksonomien skal ressursen ligge?",
      subTitleTopic: "Kvar i taksonomien skal emneskildringa ligge?",
      filestructureButton: "Opprett en emnetilknytning",
      chooseTaxonomyPlacement: "Velg plassering i taksonomi",
      changeTaxonomyPlacement: "Endre plassering i taksonomi",
      filestructureHeading: "Velg emnetilknytning",
      addNewTopic: "Legg til nytt emne",
      addNewSubTopic: "Legg til nytt underemne",
      filestructureClose: "Lukk",
      addedTopic: "Lagt til",
      disconnectedTaxonomyWarning: "Ugyldig tilknytning",
      taxonomySubjectConnections:
        "For at ein ressurs skal bli tilgjengeleg i strukturen, må han knytast til eitt eller fleire emne.",
      description:
        "Her kan du velje kvar emnet skal liggje i taksonomien. Dersom du endrar plassering i taksonomien, vil ikkje det gamle emnet bli sletta om det har underemne eller ressursar knytt til seg.",
    },
    grepCodes: {
      edit: "Endre læreplankobling",
      empty: "Ingen registerte koder",
      addNew: "Legg til ny læreplankobling",
      delete: "Fjern {{grepCode}}",
    },
    copyRevisionDates: {
      text: "Er du heilt sikker på at du ønsker å kopiere denne revisjonsdatoen? Dette vil sette alle revisjonsdatoar frå denne noden til alle undernoder og ressursar.",
      buttonText: "Kopier revisjonsdato",
      error: "Ein feil oppstod under kopiering",
    },
    resourcesPrimary: {
      text: "Er du heilt sikker på at du ønsker å gjere alle tilhøyrande ressursar om til primærkoblingar?",
      recursiveText:
        "Er du heilt sikker på at du ønsker å gjere alle tilhøyrande ressursar og underressursar om til primærkoblingar?",
      buttonText: "Gjer alle ressursar om til primærkoblingar",
      recursiveButtonText: "Gjer alle ressursar og underressursar om til primærkoblingar",
      error: "Ein feil oppstod",
      success: "Alle ressursar er gjort om til primærkoblingar",
    },
    goTo: "Åpne i stukturredigering",
    missingResourceType: "Mangler ressurstype",
    metadata: {
      customFields: {
        alterFields: "Legg til/endra metadata",
        addField: "Nytt metadata felt",
        languagePlaceholder: "Språksamling ndla.no",
        explanationSubject: "Forklaringsfag",
        programmeSubject: "Felles programfag",
        oldSubjectId: "ID for vidaresending",
        subjectCategory: "Fagkategori",
        subjectType: "Fagtype",
        resourceGroupPlaceholder: "Gruppering",
        RGTooltip: "Vis ressursar Gruppert eller Ugruppert",
        subjectLMA: "LMA for faget",
        subjectSA: "SA for faget",
        subjectDA: "DA for faget",
        keyPlaceholder: "Skriv inn nøkkel",
        valuePlaceholder: "Skriv inn verdi",
      },
      placeholders: {
        category: "Velg kategori",
        language: "Velg språk",
        type: "Velg type",
        lma: "Velg LMA",
        sa: "Velg SA",
        da: "Velg DA",
      },
    },
  },
  notions: {
    edit: "Rediger forklaring",
    closeNotion: "Lukk forklaring",
  },
  contextTypes: {
    topic: "Emne",
    frontpage: "Om-NDLA-artikkel",
    concept: "Forklaring",
    gloss: "Glose",
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: "Slideshow",
      slideshowTitle: "Filmer i slideshow på forsida",
      movieGroupHeader: "Filmgrupperinger",
      addMovieToSlideshow: "Legg til film i slideshow",
      addMovieToGroup: 'Legg til film i "{{name}}"',
      comboboxGroupLabel: 'Filmer i gruppa "{{name}}"',
      editMovieGroupName: "Endre namna til filmgruppa",
      deleteMovieGroup: 'Slett "{{name}}"',
      moveMovieGroupUp: "Flytt opp",
      moveMovieGroupDown: "Flytt ned",
      changeOrder: "Endre rekkjefølgje",
      removeMovieFromGroup: "Fjern film fra gruppe",
      removeMovieFromSlideshow: "Fjern film fra slideshow",
      createThemeGroup: "Opprett gruppe",
      saveNameChanges: "Lagre endringer",
      cancel: "Avbryt",
      editGroupTitle: "Endre namn på filmgruppa",
      newGroupTitle: "Kva skal gruppa heite?",
      notFound: "Vi finn ikkje metadata for denne filmen...",
      moreInfoHeader: "Meir informasjon",
      moreInfoTitle: "Artikkel til Les meir-lenke",
      addArticleToMoreInformation: "Legg til ein artikkel",
      removeArticleFromMoreInformation: "Fjern artikkel",
      createGroup: "Lag ny gruppe",
    },
  },
  modal: {
    closeModal: "Lukk",
  },
  conceptForm: {
    title: "Forklaring",
    info: {
      lastUpdated: "Sist oppdatert",
    },
  },
  glossform: {
    title: "Glose",
  },
  editorFooter: {
    buttonLabel: "Kvalitetssikring",
    heading: "Kvalitetssikring:",
    changeStatus: "Endre status",
    back: "Gå tilbake",
    inputHeader: "Din merknad",
    inputHelperText: "Kort merknad påkrevd ved statusendring",
    cancelLabel: "Avbryt",
    saveLabel: "Endre status og lagre utkast",
    warningSaveWithoutComment: "Merknad mangler",
    newStatusPrefix: "Ny status:",
    statusLabel: "Status:",
    changeHeader: "Endringer",
    saveAsNew: "Lagre som kopi",
    prioritized: "Prioritert",
    placeholderPrioritized: "Ingen prioritet",
  },
  taxonomyVersions: {
    title: "Taksonomiversjonar",
    publishedVersion: "Publisert versjon",
    otherVersions: "Øvrige versjonar",
    deleteLocked: "Denne versjonen kan ikkje slettast fordi den er låst",
    deletePublished: "Denne versjonen kan ikkje slettast fordi den er publisert",
    delete: "Slett versjon",
    locked: "Denne versjonen er låst og kan ikkje slettast",
    status: {
      PUBLISHED: "Publisert",
      ARCHIVED: "Arkivert",
      BETA: "Beta",
    },
    about:
      "Denne siden brukast til å sjå på og administrere taksonomiversjonar. Vær varsom: Å publisere ein ny taksonomiversjon vil føre til at alt innhald i den vil være umiddelbart tilgjengeleg for sluttbrukarar på ndla.no",
    noPublished:
      "Det finnes ingen publisert versjon. Draft-versjonen av taksonomi brukast inntil ein versjon blir publisert",
    editVersionTooltip: "Rediger versjon",
    newVersionTitle: "Opprett ny versjon",
    editVersionTitle: "Rediger versjon",
    newVersionButton: "Ny versjon",
    publishTitle: "Publiser versjon",
    publishButton: "Publiser",
    publishWarning:
      "Er du sikker på at du ønskjar å publisera denne versjonen? Den nåværanda versjonen vil bli arkivert, og alle nye endringar i denne versjonen vil umiddelbart være tilgjengelege på ndla.no",
    deleteWarning: "Er du sikker på at du ønsker å slette denne versjonen?",
    deleteWarningPublished:
      "Er du sikker på at du ønsker å slette den publiserte versjonen? Taksonomi vil revertere tilbake til Draft-versjonen.",
    postError: "Klarte ikkje å opprette ny versjon",
    putError: "Klarte ikkje å oppdatere versjonen",
    publishError: "Klarte ikkje å publisere versjonen",
    deleteError: "Klarte ikkje å slette versjonen",
    noOtherVersions: "Det finnes ingen andre versjonar!",
    previewVersion: "Forhåndsvis denne versjonen på NDLA.no",
    form: {
      name: {
        label: "Namn",
        placeholder: "Eksempelversjon",
      },
      source: {
        title: "Kildeversjon",
        subTitle: "Velg ei anna versjon å basere denne på",
        defaultOption: "Draft",
      },
      locked: {
        title: "Låst",
        subTitle: "Lås versjonen så den ikkje kan slettast",
        locked: "Låst",
        unlocked: "Ulåst",
      },
    },
  },
  diff: {
    equalNodes: "Disse nodene er like!",
    defaultVersion: "Draft",
    compareVersions: "Samanlikne versjonar",
    error: {
      originalHashRequired: "originalHash-parameteret er påkrevd i URL'en!",
      doesNotExist: "Denne noden finnast ikkje i nokon av desse versjonane",
      onlyExistsInOriginal: "Denne noden finnast berre i målversjonen",
      onlyExistsInOther: "Denne noden finnast berre i kildeversjonen",
    },
    options: {
      about: "Denne sida lar deg samanlikne eit nodetre i to forskjellige versjoner.",
      originalHashLabel: "Målversjon",
      otherHashLabel: "Kildeversjon",
      viewLabel: "Visningstype",
      nodeViewLabel: "Nodevisning",
      fieldViewLabel: "Feltvisning",
      allNodes: "Alle noder",
      changedNodes: "Kun endra",
      allFields: "Alle felt",
      changedFields: "Kun endra",
      flat: "Flat",
      tree: "Tre",
    },
    childrenChanged: "Barn endra",
    resourcesChanged: "Ressurser endret",
    diffTypes: {
      ADDED: "Lagt til",
      DELETED: "Manglar",
      MODIFIED: "Endra",
      NONE: "Ingen",
    },
    isRoot: "Rotnode",
    nodeTypeTooltips: {
      SUBJECT: "Dette er eit fag",
      TOPIC: "Dette er eit emne",
      PROGRAMME: "Dette er eit utdanningsprogram",
    },
    fields: {
      id: {
        title: "ID",
      },
      name: {
        title: "Namn",
      },
      contentUri: {
        title: "Innholds-URI",
      },
      parentId: {
        title: "Forelder",
      },
      path: {
        title: "Sti",
      },
      paths: {
        title: "Stier",
      },
      connectionId: {
        title: "Koblings-ID",
      },
      isPrimary: {
        title: "Er primær",
        isOn: "Denne noden er ein primærressurs",
        isOff: "Denne noden er ikkje ein primærressurs",
      },
      rank: {
        title: "Rangering",
      },
      relevance: {
        title: "Relevans",
      },
      translations: {
        title: "Oversetjinger",
      },
      articleType: {
        title: "Artikkel-type",
      },
      visible: {
        title: "Synleg",
        isOn: "Synleg",
        isOff: "Usynleg",
      },
      "topic-resources": {
        title: "Gruppering av ressurser",
        isOn: "Gruppert",
        isOff: "Ugruppert",
      },
      requestPublish: {
        title: "Forespurt publisering",
        true: "Ja",
        false: "Nei",
      },
      language: {
        title: "Visningsspråk",
      },
      subjectCategory: {
        title: "Fagkategori",
      },
      explanationSubject: {
        title: "Forklaringsfag",
      },
      oldSubjectId: {
        title: "Gammal fag-ID",
      },
      supportedLanguages: {
        title: "Støtta språk",
      },
      grepCodes: {
        title: "Grep-koder",
      },
      resourceTypes: {
        title: "Ressurstypar",
      },
    },
  },
  metadata: {
    visible: "Synleg",
    notVisible: "er ikkje synleg",
    changeVisibility: "Endre synlegheit",
  },
  unsavedChanges: "Ulagra endringar",
  messages: {
    severity: {
      info: "Informasjon",
      warning: "Advarsel",
      success: "Alt OK!",
      danger: "Pass på!",
    },
  },
  delete: "Slett",
  reset: "Tilbakestill",
  campaignBlockForm: {
    title: "Rediger kampanjeblokk",
    delete: "Fjern kampanjeblokk",
    sides: {
      left: "Venstre",
      right: "Høgre",
    },
  },
  linkBlock: {
    deleteBlock: "Fjern lenkeblokk",
    delete: "Fjern lenke",
    edit: "Rediger lenke",
    create: "Sett inn lenke",
    chooseDate: "Velg dato",
    linkExists: "Denne lenka finnast allereie i blokka",
  },
  dragAndDrop: {
    handle: "Handtak",
  },
  datePicker: {
    chooseMonth: "Månad:",
    chooseYear: "År:",
    labelNext: "Gå til neste månad",
    previousMonth: "Gå til forrige månad",
    goToToday: "Gå til dagens dato",
  },
  remove: "Fjern",
  frontpageForm: {
    error: "Ein feil oppsto",
    changeArticle: "Velg artikkel",
    addArticle: "Legg til artikkel",
    addArticleToMenu: "Legg til artikkel i meny",
    changeFrontpageArticle: "Skift forsideartikkel",
    search: "Søk etter artikkel",
    frontpageArticle: "Forsideartikkel:",
    noFrontpageArticle: "Ingen forsideartikkel valgt",
    failedTitle: "Klarte ikkje vise tittel",
    openChildren: "Vis barn",
    closeChildren: "Skjul barn",
    hide: "Skjul",
    show: "Vis",
  },
  codeEditor: {
    title: "Legg til kodeeksempel",
    titleLabel: "Tittel",
    programmingLanguage: "Kodespråk",
    edit: "Rediger kodevisning",
    delete: "Fjerne kodevisning",
  },
  framedContentForm: {
    changeVariant: {
      colored: "Bruk farga variant",
      neutral: "Bruk nøytral variant",
    },
  },
  blockquoteForm: {
    changeVariant: {
      colored: "Bruk farga variant",
      neutral: "Bruk nøytral variant",
    },
  },
  fileUpload: {
    title: "Last opp filer",
  },
  conceptCompare: {
    title: "Samanlikn språkversjonar",
  },
  conceptPreview: {
    title: "Forhåndsvis forklaring",
  },
  math: "Mattestykke",
};

export default phrases;
