/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Production system - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Learning resource ${titleTemplate}`,
    createTopicArticlePage: `Topic ${titleTemplate}`,
    createSubjectpage: `Subjectpage ${titleTemplate}`,
    agreementPage: `Agreement ${titleTemplate}`,
    searchContentPage: `Search content ${titleTemplate}`,
    searchMediaPage: `Search media ${titleTemplate}`,
    searchConceptPage: `Search concepts ${titleTemplate}`,
    welcomePage: `Frontpage ${titleTemplate}`,
    structurePage: `Structure ${titleTemplate}`,
    audioUploaderPage: `Audio ${titleTemplate}`,
    imageUploaderPage: `Image ${titleTemplate}`,
    loginPage: `Login ${titleTemplate}`,
    logoutPage: `Logout ${titleTemplate}`,
  },
  meta: {
    description: 'Norwegian Digital Learning Arena, Open Educational Resources',
  },
  menu: {
    title: 'Menu',
  },
  dropdown: {
    numberHits: `Search returned {hits} hits`,
    searching: 'Searching...',
    create: 'Create new',
    isSelectedItem: 'Added',
  },
  article: {
    author: 'Author',
    published: 'Published',
    edition: 'Edition',
    publisher: 'Publisher',
    created: 'Created',
    lastUpdated: 'Last updated',
    closeLabel: 'Close',
    useContent: 'Cite or use',
    additionalLabel: 'Additional content',
    urlContributionsLabel: 'See {name}`s contributions',
    urlAuthorLabel: 'Read more about {name}',
    multipleAuthorsLabelAbbreviation: 'et al.',
    multipleAuthorsLabel: 'Article authors:',
    multipleAuthorsLabelAria: 'Authors of this article are {names}',
    multipleAuthorsLabelAriaConjunction: 'og',
    singleAuthorsLabelAria: 'The author of this article is {name}',
  },
  dialog: {
    close: 'Close',
    title: 'Title',
    audio: {
      rulesForUse: 'Rules for use of audio',
    },
    learnAboutLicenses: 'Learn more about open licenses',
    source: 'Source',
  },
  license: {
    heading: 'Howto reuse content',
    tabs: {
      text: 'Text',
      images: 'Images',
      audio: 'Audio',
      video: 'Video',
    },
    images: {
      heading: 'How to use images from the article',
      description:
        'Remember to copy the text to be attached to the image where you use it.',
      rules: 'Rules for use of image:',
      source: 'Source',
      title: 'Title',
    },
    text: {
      heading: 'How to use text from the article',
      description:
        'The article may be composed of several different texts, which are listed here.',
      rules: 'Rules for use of text:',
      published: 'Published',
    },
    audio: {
      heading: 'How to use audio files from the article',
      description:
        'Remember to copy the text to be attached to the audio where you use it.',
      rules: 'Rules for use of audio file:',
    },
    video: {
      heading: 'How to use videos from the article',
      description:
        'Remember to copy the text to be attached to the video where you use it.',
      rules: 'Rules for use of audio file:',
    },
    learnMore: 'Learn more about open licenses',
    copyTitle: 'Copy reference',
    embed: 'Embed',
    embedCopied: 'Copied embed code!',
    hasCopiedTitle: 'Copied!',
    download: 'Download',
    creditType: {
      originator: 'Originator',
      authorDesc: 'This article is made by several originators',
      photographer: 'Photographer',
      artist: 'Artist',
      editorial: 'Editorial',
      writer: 'Writer',
      scriptwriter: 'Scriptwriter',
      reader: 'Reader',
      translator: 'Translator',
      director: 'Director',
      illustrator: 'Illustrator',
      cowriter: 'Cowriter',
      composer: 'Composer',
      processor: 'Processor',
      facilitator: 'facilitator',
      linguistic: 'Linguistic',
      idea: 'Idea',
      compiler: 'Compiler',
      correction: 'Correction',
      rightsholder: 'Rightsholder',
      publisher: 'Publisher',
      distributor: 'Distributor',
      supplier: 'Supplier',
    },
  },
  language: {
    en: 'English',
    nb: 'Norwegian - Bokmål',
    nn: 'Norwegian - Nynorsk',
    se: 'Sami',
    sma: 'Southern Sami',
    unknown: 'Unknown',
    de: 'German',
    empty: 'No languages left',
    change: 'Change to {language} version',
  },
  welcomePage: {
    lastUsed: 'Last used',
    emptyLastUsed: 'Empty last used list',
    savedSearch: 'Saved searches',
    emptySavedSearch: 'No saved searches',
    guidelines: 'Guidelines',
  },
  searchPage: {
    header: {
      content: 'Search for content',
      media: 'Search for media',
      concept: 'Search for concepts',
    },
    searchButton: 'Search',
    emptyButton: 'Empty',
    title: 'Title',
    language: 'Language',
    contentNoHits: 'Your search - {query} - did not match any content.',
    conceptNoHits: 'Your search - {query} - did not match any concept.',
    mediaNoHits: 'Your search - {query} - did not match any media.',
    pageSize: '{pageSize} hits per page',
    totalCount: 'Total results',
  },
  articleType: {
    'topic-article': 'Topic',
    standard: 'Subject matter',
  },
  subNavigation: {
    learningPath: 'Learningpath',
    learningPathLink: 'Go to learningpath',
    subjectMatter: 'Subject matter',
    detailSearch: 'Detail search',
    topicArticle: 'Create new topic',
    learningResource: 'Learning resource',
    image: 'New image',
    audio: 'New Audiofile',
    agreement: 'New Agreement',
    structure: 'Structure',
    searchContent: 'Search content',
    searchMedia: 'Search media',
    searchConcepts: 'Search concepts',
    film: 'Edit NDLA film',
    h5p: 'Edit H5P',
    newConcept: 'Create new concept',
  },
  logo: {
    altText: 'The Norwegian Digital Learning Arena',
  },
  siteNav: {
    chooseSubject: 'Choose Subject',
    search: 'Search',
    login: 'Login',
    logout: 'Logout [{name}]',
  },
  loginFailure: {
    errorMessage: 'Sorry. Login failed.',
    loginLink: 'Click to try again.',
    userNotRegistered:
      'We did not recognize your email address. Did you use the correct email address?',
  },
  loginProviders: {
    description: 'Log in with',
  },
  logoutProviders: {
    localLogout: 'Logg ut av prouctionsystem',
    or: 'eller',
    federatedLogout: 'Log out of all providers',
    description:
      'N.B. All providers include the identityprovider (Google or Facebook).',
  },
  searchForm: {
    placeholder: 'Search articles',
    types: {
      conceptQuery: 'Search for concept',
      contentQuery: 'Search for content',
      mediaQuery: 'Search for media',
      language: 'Select language',
      users: 'Select editor',
      subjects: 'Select subject',
      resourceTypes: 'Select resource type',
      draftStatus: 'Select status',
    },
    tagType: {
      query: 'Query',
      subjects: 'Subject',
      language: 'Language',
      users: 'Editor',
      resourceTypes: 'Resource type',
      draftStatus: 'Status',
    },
    btn: 'Search',
    empty: 'Empty',
    articleType: {
      all: 'All',
      standard: 'Standard',
      learningResource: 'Learning resource',
      topicArticle: 'Topic description',
      image: 'Image',
      audio: 'Audio',
    },
    order: 'Rekkefølge',
    asc: 'Ascending',
    desc: 'Descending',
    sorting: 'Sorting',
    sort: {
      id: 'Id',
      relevance: 'Relevance',
      title: 'Title',
      lastUpdated: 'Last updated',
    },
    resultError: 'Something went wrong with type: {type}',
  },
  subjectsPage: {
    subjects: 'Subjects',
  },
  subjectPage: {
    topics: 'Topics',
  },
  editMarkup: {
    linkTitle: 'Go to HTML editor',
    title: 'HTML editor',
    subTitle: 'Edit article with HTML',
    fetchError:
      'An error occurred while loding an article into the HTML editor. Go back or try to reload the page.',
    saveError: 'An error occurred while saving article changes.',
    helpMessage: {
      paragraph1:
        'It is possible to format the HTML code by pressing F1 and then selecting Format. Note that this could lead to changes in whitespace (indentations, linebreaks and spaces) when saving. Feel free to use the preview feature rapidly. ',
      paragraph2:
        'To minimize potential problems with formatting and to secure consistent HTML, the same transformations as in the regular editor is applied. This means that for instance linebreaks will be changed to<br> when saving, and illegal code is attempted to be corrected.',
    },
  },
  imageSearch: {
    placeholder: 'Search images',
    buttonTitle: 'Search',
    useImage: 'Use image',
    noTitle: 'No title',
    noResultsText: 'No images found. Would you like to upload a new image?',
    noResultsButtonText: 'Upload image',
  },
  videoSearch: {
    searchPlaceholder: 'Search videos',
    searchButtonTitle: 'Search',
    loadMoreVideos: 'Load more videos',
    noResults: 'No videos found',
    addVideo: 'Use video',
    previewVideo: 'Preview',
    publishedDate: 'Published date',
    duration: 'Duration',
    interactioncount: 'Views',
  },
  mathEditor: {
    editMath: 'Edit Math',
    preview: 'Preview',
    continue:
      'You have unsaved changes in the math editor. Do you want to continue?',
  },
  h5pElement: {
    fetchError: 'Sorry, an error occurd while loading the H5P client.',
  },
  displayOembed: {
    errorMessage: 'An error occurd when displaying oEmbed.',
    notSupported:
      'oEmbed of type {type} and provider {provider} is not supported.',
  },
  audioSearch: {
    searchPlaceholder: 'Search in audio files',
    searchButtonTitle: 'Search',
    useAudio: 'Chose audio',
    noResults: 'No audio files found',
    noTitle: 'No title',
  },
  conceptSearch: {
    searchPlaceholder: 'Search in concepts',
    searchButtonTitle: 'Search',
    noResults: 'No concepts found',
    noTitle: 'No title',
    noContent: 'No content',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element of type {type} will be deleted on save.',
  },
  subjectpageForm: {
    title: 'Subject',
    about: 'About subject',
    subjectName: 'Subject name',
    description: 'Description',
    metadata: 'Metadata',
    desktopBanner: 'Desktop banner',
    mobileBanner: 'Mobile banner',
    addBanner: 'Choose banner image',
    changeBanner: 'Change banner image',
    editorsChoices: 'Editor choices from the subject',
    articles: 'Articles',
    addArticle: 'Add article',
    changeOrder: 'Change order',
    removeArticle: 'Remove article',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Image title',
      video: 'Video title',
      brightcove: 'Video title',
      external: 'Content title',
      h5p: 'H5P title',
    },
    visualElementCopyright: 'Origin',
    removeVisualElement: 'Remove element',
    info: {
      lastUpdated: 'Last updated: ',
    },
    title: 'Topic description | {title} ({key})',
    fields: {
      caption: {
        label: {
          image: 'Video caption',
          brightcove: 'Video caption',
          external: 'Content caption',
        },
        placeholder: {
          image: 'Image caption',
          brightcove: 'Video caption',
          external: 'Content caption',
        },
      },
      alt: {
        label: 'Alt-text',
        placeholder: 'Alt-text',
      },
    },
  },
  footnoteForm: {
    title: 'Title',
    year: 'Year',
    authors: 'Author',
  },
  linkForm: {
    href: 'Link',
    text: 'Text',
  },
  audioForm: {
    title: 'audio file',
  },
  imageEditor: {
    remove: {
      crop: 'Remove crop',
      focalPoint: 'Remove focal point',
    },
  },
  imageForm: {
    title: 'Image',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Image title',
      copyright: 'Copyright',
      change: 'Change meta image',
    },
    title: 'Learning resource',
    validation: {
      missingEmbedData:
        'One or more inlcuded video, image, or audio elements is missing caption or alternative text.',
    },
    fields: {
      rightAside: {
        title: 'Right column',
        moveContent: 'Move content into the text',
        delete: 'Delete right aside',
      },
      footnotes: {
        edition: 'Edition',
        publisher: 'Publisher',
      },
    },
  },
  editorToolbar: {
    bold: 'Bold',
    italic: 'Italic',
    underlined: 'Underlined',
    quote: 'Quote',
    link: 'Link',
    numberedList: 'Numbered list',
    bulletedList: 'Bulleted list',
    twoColumnList: 'Two-column list',
    letterList: 'Letter list',
    headingOne: 'Heading 1',
    headingTwo: 'Heading 2',
    headingThree: 'Heading 3',
    footnote: 'Footnote',
    mathml: 'Math',
    concept: 'Concept',
  },
  editorBlockpicker: {
    heading: 'Add',
    actions: {
      block: 'Section',
      factAside: 'Factbox',
      table: 'Table',
      bodybox: 'Text in frame',
      details: 'Expandable box',
      solutionbox: 'Solution box',
      image: 'Image',
      video: 'Video',
      audio: 'Audio',
      h5p: 'H5P',
      url: 'Resource from link',
      related: 'Related article',
      file: 'File',
    },
  },
  form: {
    metadataSection: 'Metadata',
    contentSection: 'Content',
    workflowSection: 'Version log and notes',
    taxonomySection: 'Taxonomy',
    copyrightSection: 'License and authors',
    save: 'Save',
    saveAsNewVersion: 'Save as new version',
    saveDraft: 'Save draft',
    saveTax: 'Save taxonomy',
    saving: 'Saving...',
    choose: 'Choose',
    saved: 'Saved ',
    copy: 'copy',
    saveAsCopySuccess: 'New article saved',
    preview: {
      button: 'Preview',
    },
    name: {
      title: 'Title',
      introduction: 'Ingress',
      creators: 'Creators',
      rightsholders: 'Rightsholders',
      processors: 'Processors',
      tags: 'Tags',
      license: 'License',
      origin: 'Origin',
      audioFile: 'Audio file',
      content: 'Content',
      notes: 'Notes',
      metaDescription: 'Meta description',
      metaImageAlt: 'Alt-text',
      alttext: 'Alt-text',
      caption: 'Caption',
      imageFile: 'Imagefile',
      visualElementCaption: 'Caption',
      visualElementAlt: 'Alt-text',
      validFrom: 'Valid from',
      validTo: 'Valid to',
      description: 'Content',
      conceptContent: 'Description',
      grepCodes: 'Curriculum connection',
    },
    previewProductionArticle: {
      button: 'Compare draft and article',
      article: 'Published version',
      draft: 'Draft',
    },
    previewLanguageArticle: {
      button: 'Compare language versions',
      title: 'Draft on {language}',
    },
    previewNewWindow: 'Preview in a new window',
    contributor: {
      add: 'Add',
    },
    detailBox: {
      changeTitle: 'Change title',
      placeholder: 'Short summary',
    },
    mustSaveFirst: 'You must save your changes first',
    abort: 'Abort',
    edit: 'Edit',
    remove: 'Remove',
    validate: 'Validate',
    publish: 'Publish',
    savedOk: 'Saved OK',
    publishedOk: 'Published OK',
    validationOk: 'No validation errors found',
    createdOk: 'Created OK',
    addNewImage: 'Add new image',
    addNewAudio: 'Add new audio',
    notes: {
      heading: 'Notes',
      add: 'Add new note',
      remove: 'Remove note',
      warning: 'A note must contain text',
      areHere: 'You are here',
      published: 'Published',
      history: {
        user: 'User',
        time: 'When',
        status: 'Status',
        heading: 'Notes history',
        note: 'Note',
        empty: 'No notes',
      },
    },
    updated: {
      label: 'Updated date',
    },
    published: {
      label: 'Published date',
      reset: 'Reset date',
    },
    updatePublished: 'Update published date',
    editImage: 'Edit image',
    editOriginalImage: 'Edit orginal image',
    editAudio: 'Edit audio',
    resetToProd: {
      button: 'Reset to prod',
      modal: 'Do you want to reset the draft as it is on the ndla frontpage?',
      success: 'Content is reset, press save to save changes',
    },
    resetToVersion: 'Reset to version',
    previewVersion: 'See version',
    variant: {
      create: 'Create variant',
      translate: 'Translate to Nynorsk',
    },
    remainingCharacters:
      'Max {maxLength, number} characters and you have {remaining, number} remaining.',
    title: {
      label: 'Title',
    },
    introduction: {
      label: 'Introduction',
    },
    metaImage: {
      copyright: 'Copyright',
      change: 'Change meta image',
      title: 'Meta image',
      imageTitle: 'Image title',
      label: 'Meta image',
      helpLabel: 'What is a meta image?',
      add: 'Choose meta image',
      remove: 'Remove meta image',
    },
    markdown: {
      button: 'Click to view markdown',
      helpLabel: 'What is markdown?',
    },
    visualElement: {
      title: 'Add visual element',
      label: 'Visual element',
      video: 'Video search',
      image: 'Image search',
      imageUpload: 'Upload image',
      h5p: 'H5P',
    },
    concept: {
      create: 'Create concept',
      addText: 'Choose a concept and press "connect to topic", or',
      edit: 'Edit concept',
      addConcept: 'Add existing concept',
      source: 'Source',
    },
    workflow: {
      title: 'Status',
      change: 'Change status',
      qualityAssurance: 'Quality assurance',
      saveAsNew: 'Make copy',
      deleteLanguageVersion: {
        button: 'Delete language version',
        title: 'Delete language version',
        modal: 'Are you sure that you want to delete this language version?',
      },
      statusInfoTooltip: 'Whats the difference between statuses?',
      statusLabel: 'Status',
      published: 'There exists a published version of this item.',
      multipleTaxonomy: 'The article has multiple entries in taxonomy.',
    },
    status: {
      new: 'New - unsaved',
      new_language: 'New language - unsaved',
      created: 'Created',
      imported: 'Imported',
      draft: 'Draft',
      proposal: 'Proposal',
      user_test: 'User test',
      awaiting_quality_assurance: 'Quality assurance',
      queued_for_language: 'Queued for language',
      translated: 'Language done',
      quality_assured: 'Ready for publishing',
      queued_for_publishing: 'Queued for publishing',
      published: 'Published',
      unpublished: 'Unpublished',
      awaiting_unpublishing: 'Awaiting unpublishing',
      archived: 'Archived',
      actions: {
        DRAFT: 'Draft',
        PROPOSAL: 'Proposal',
        USER_TEST: 'User test',
        AWAITING_QUALITY_ASSURANCE: 'To Quality assurance',
        QUEUED_FOR_LANGUAGE: 'Queued for language',
        TRANSLATED: 'Language done',
        QUALITY_ASSURED: 'Ready for publishing',
        QUEUED_FOR_PUBLISHING: 'Queue for publishng',
        PUBLISHED: 'Publish',
        AWAITING_UNPUBLISHING: 'Queue for unpublishing',
        UNPUBLISHED: 'Unpublish',
        ARCHIVED: 'Archive',
      },
      learningpath_statuses: {
        private: 'Draft',
        published: 'Public',
        unlisted: 'Link shared',
        submitted: 'Requested publication',
      },
    },
    validDate: {
      label: 'Valid date',
      from: {
        label: 'Valid from',
        placeholder: 'From date',
      },
      to: {
        label: 'Valid to',
        placeholder: 'To date',
      },
    },
    content: {
      label: 'Content',
      placeholder: 'Write here...',
      figure: {
        notSupported: 'Media type {mediaType} is not supported.',
        confirmDelete: 'Are you sure that you will delete this figure?',
      },
      relatedArticle: {
        placeholder: 'Search for title',
        urlPlaceholder: 'Url',
        titlePlaceholder: 'Title',
        urlLocation: 'Webpage at {domain}',
        invalidArticle: 'Invalid article',
        addExternal: 'Add external article',
        searchExternal: 'Write the url and title of the external article',
      },
      concept: {
        remove: 'Remove concept',
        choose: 'Choose concept',
      },
      link: {
        goTo: 'Go to',
        insert: 'Insert link',
        update: 'Update link',
        change: 'Change',
        remove: 'Remove link',
        href: 'Link',
        newTab: 'Open link in new tab',
        text: 'Text',
        addTitle: 'Add link',
        changeTitle: 'Change link',
        required: 'Link is required',
        invalid: 'Invalid link',
        preview: 'Preview link',
        unSupported: 'Content in link is not supported',
        newUrlResource: 'New resource',
        changeUrlResource: 'Edit resource: {type}',
      },
      footnote: {
        title: 'Title',
        year: 'Year',
        authors: {
          label: 'Author',
          description: 'Required with at least one author.',
          createOption: 'Create new author',
        },
        edition: 'Edition',
        publisher: 'Publisher',
        addTitle: 'Add footnote',
        editTitle: 'Edit footnote',
        removeFootnote: 'Remove footnote',
      },
      table: {
        'row-remove': 'Remove row',
        'row-add': 'Add row',
        'column-add': 'Add column',
        'column-remove': 'Remove column',
        'table-remove': 'Remove table',
      },
    },
    tags: {
      label: 'Tags',
      helpLabel: 'What is a tag?',
      description: '3 tags is required.',
      createOption: 'Create new tag',
      searchPlaceholder: 'Search for tags',
    },
    categories: {
      label: 'List and filters',
      description: 'Format: list:filter1:filter2',
      searchPlaceholder: 'Search for lists',
    },
    grepCodes: {
      label: 'Competences and core elements',
      placeholder: 'Type code',
      description:
        'Type in codes using the format K(E/M) or TT followed by one or more digits. Ex. KE137, KM2255, TT2. Non existing codes will not be created.',
    },
    resourceTypes: {
      label: 'Resource type and properties',
      placeholder: 'Add property',
    },
    subjects: {
      label: 'Subjects',
      searchPlaceholder: 'Search for subjects',
      placeholder: 'Add subjects',
    },
    filter: {
      label: 'Filter',
      placeholder: 'Add filter',
      core: 'Core',
      supplementary: 'Supplementary',
      setRelevance: 'Set relevance',
    },
    topics: {
      label: 'Topics',
      placeholder: 'Add topic',
      primaryTopic: 'Primary topic',
      sharedTopic: 'Shared topic',
      setPrimaryTopic: 'Set as primary topic',
    },
    metaDescription: {
      label: 'Meta description',
      helpLabel: 'What is a meta description?',
      description: 'The description will be viewable in search.',
    },
    agreement: {
      label: 'Connect to agreement',
      helpLabel: 'What is an agreement?',
      placeholder: 'Search for agreement',
    },
    rightsholders: {
      label: 'Rightsholder',
      labelRemove: 'Remove',
      placeholder: 'Type name of rightholder',
      createOption: 'Add new rightsholder',
    },
    processors: {
      label: 'Processor',
      labelRemove: 'Remove',
      placeholder: 'Type name of processor',
      createOption: 'Add new processor',
    },
    creators: {
      label: 'Creator',
      labelRemove: 'Remove',
      placeholder: 'Type name of creator',
      createOption: 'Add new creator',
      description: 'Required with at least one creator.',
    },
    license: {
      label: 'License',
      helpLabel: 'What is a license?',
      choose: 'Choose a license',
    },
    origin: {
      label: 'Origin',
    },
    caption: {
      label: 'Caption',
      placeholder: 'Caption',
    },
    image: {
      file: 'Image',
      save: 'Save image',
      editImage: 'Edit image',
      removeImage: 'Remove image',
      alignment: {
        left: 'Left aligned',
        right: 'Right aligned',
        center: 'Large centered',
      },
      sizes: {
        xsmall: 'Size: Tiny',
        small: 'Size: Small',
        medium: 'Size: Medium',
        fullwidth: 'Size: Large',
      },
      crop: 'Crop image',
      focalPoint: 'Set focalpoint',
      alt: {
        label: 'Alt-text',
        placeholder: 'Alt-text',
      },
      caption: {
        label: 'Image caption',
        placeholder: 'Image caption',
        noText: 'WCAG requires alt-text.',
      },
      dragdrop: {
        main: 'Drag and drop',
        sub: 'or click to upload image',
        ariaLabel: 'Drag and drop or click to upload image',
      },
    },
    video: {
      caption: {
        label: 'Video caption',
        placeholder: 'Video caption',
      },
      remove: 'Remove video',
    },
    audio: {
      file: 'Audio file',
      title: {
        label: 'Audio title',
        placeholder: 'Audio title',
      },
      caption: {
        label: 'Audio caption',
        placeholder: 'Audio caption',
      },
      remove: 'Remove audio',
      sound: 'Audio',
      speech: 'Speech',
    },
    external: {
      title: 'external',
      edit: 'Edit {type} element',
      remove: 'Remove {type} element',
    },
    related: {
      title: 'Related articles',
      showMore: 'Show more related articles',
      showLess: 'Show less',
    },
    file: {
      label: 'Files',
      file: {
        label: 'File',
      },
      alt: {
        label: 'Alt text',
        placeholder: 'Alt text',
      },
      download: 'Download:',
      title: {
        label: 'File title',
        placeholder: 'File title',
      },
      addFile: 'Add file',
      removeList: 'Remove file list',
      placeholder: 'Filename',
      changeName: 'Change name',
      changeOrder: 'Change the order',
      removeFile: 'Remove file',
      editSubjectpage: 'Edit subjectpage',
      missingTitle: '[Missing filename]',
      missingFileTooltip:
        'This files does not seem to exist on the server. It might have been deleted from another article.',
    },
    article: {
      label: 'Article',
      add: 'Add article',
    },
  },
  validation: {
    isRequired: '{label} is required.',
    isNumeric: '{label} must contain digits.',
    bothFields: 'One {labelLowerCase} must contain all fields.',
    url: '{label} must contain a valid link.',
    urlOrNumber: '{label} must contain a valid link or article-id.',
    dateBeforeInvalid: '{label} can not be after {afterLabel}.',
    dateAfterInvalid: '{label} can not be before {beforeLabel}.',
    maxLength:
      '{label} must not have more than {maxLength, number} characters.',
    minLength: '{length} must have at least {minLength, number} characters.',
    minItems:
      '{label} must have at least {minItems, plural, one{one} other{# unique}} {labelLowerCase}.',
    noEmptyNote: 'A note cannot be empty',
    grepCodes:
      'The code format is wrong. The correct format is K(E/M) or TT followed by one or more digits. Ex. KE137, KM2255, TT2.',
  },
  errorMessage: {
    title: 'Oops, something went wrong',
    description: 'Sorry, an error occurd.',
    back: 'Back',
    goToFrontPage: 'Go to frontpage',
    invalidUrl: 'Invalid url',
    noArticleInProd: 'No article found in prod',
    taxonomy: 'There was a problem loading taxonomy',
    auth0:
      'Authentication error. Press cancel to take care of any changes you have made before logging in again. The following error message came from auth0: {message}',
    statusCode: {
      409: 'This article has already been updated. Keep what you have changed and reload the page to save.',
    },
  },
  notFound: {
    description: 'The page cannot be found',
  },
  forbiddenPage: {
    description: 'You do not have access to this page',
  },
  alertModal: {
    notSaved: 'Document is not saved, do you want to continue?',
    needToRefresh:
      'Someone have saved the same article while you were editing. You need to copy your changes manually and refresh the page',
    continue: 'Continue',
    delete: 'Delete',
    confirm: 'Confirm',
    loginAgain: 'Login again',
  },
  taxonomy: {
    editStructure: '  Edit structure',
    addSubject: 'Add new subject',
    addExistingTopic: 'Move existing topic here',
    newSubject: 'New Subject',
    existingTopic: 'Existing topic',
    newTopic: 'New topic',
    editFilter: 'Edit filter',
    emptyFilter: 'No hits',
    errorMessage: 'An error occurred',
    addTopic: 'Add topic',
    changeName: 'Change name',
    topicSettings: 'Topic settings',
    subjectSettings: 'Subject settings',
    linkSettings: 'Link',
    setPrimary: 'Set as primary link',
    addFilter: 'Add filter',
    connectFilters: 'Connect filters',
    confirmDelete: 'Are you sure you want to delete the filter?',
    addResource: 'Add resource',
    searchResource: 'Search for resource',
    searchArticle: 'Search for topic article',
    confirmDeleteTopic: 'Are you sure you want to delete this topic?',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Note! This is a different resource type: ',
    noResources: 'No resources found',
    addTopicDescription: 'Change topic description',
    confirmSetPrimary: 'Do you want to make this the main location?',
    removeLink: 'Remove link',
    jumpToResources: 'Jump to resources',
    copyResources: 'Copy resources from topic',
    favorites: 'Show favorites',
    publish: {
      button: 'Publish all',
      waiting: 'Publishing resourses',
      done: 'Resources published',
      error: 'The following resources were not published:',
    },
    resource: {
      confirmDelete:
        'Do you want to delete the resource from this folder? This will not affect the placement other places',
      chooseFilter: 'Connect to filters',
    },
    resourceTypes: {
      title: 'Content type',
      subTitle: 'What content type does this resource have?',
      placeholder: 'Select content type',
    },
    topics: {
      title: 'Topic connections',
      topicPlacement: 'Topcic placement',
      subTitle: 'Where in the taxonomy should this resource be?',
      subTitleTopic: 'Where in the taxonomy should the topic description be?',
      filestructureButton: 'Create a topic connection',
      filestructureHeading: 'Select a topic connection',
      filestructureClose: 'Close',
      addNewTopic: 'Add new topic',
      addNewSubTopic: 'Add new sub topic',
      addedTopic: 'Added to taxonomy',
      filterTopic: 'Filter topics',
      disconnectedTaxonomyWarning: 'Invalid topic connection',
    },
    filters: {
      title: 'Filters',
      subTitle: 'Which filters should be applied?',
      additional: 'Additional resource',
      core: 'Core resource',
    },
    grepCodes: {
      edit: 'Edit grep codes',
      empty: 'No existing grep codes',
      addNew: 'Add new grep code',
    },
    missingResourceType: 'Missing resource type',
  },
  notions: {
    edit: 'Edit notions',
    closeNotion: 'Close notion dialog',
  },
  contextTypes: {
    topic: 'Topic',
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: 'Slideshow:',
      slideshowTitle: 'Movies on slideshow',
      slideshowSubTitle: 'on frontpage',
      movieGroupHeader: 'Movies themes:',
      addMovieToSlideshow: 'Add movie to slideshow',
      addMovieToGroup: 'Add a movie to "{name}"',
      editMovieGroupName: 'Change the names on this movie group',
      deleteMovieGroup: 'Delete "{name}"',
      moveMovieGroupUp: 'Move up',
      moveMovieGroupDown: 'Move down',
      changeOrder: 'Change order',
      removeMovieFromGroup: 'Remove movie from group',
      removeMovieFromSlideshow: 'Remove movie from slideshow',
      createThemeGroup: 'Create new movie group',
      saveNameChanges: 'Save changes',
      cancel: 'Cancel',
      groupNamePlaceholder: 'Write name in {lang}',
      editGroupTitle: 'Change the name(s) in this movie group:',
      newGroupTitle: 'What shall we call the new movie group?',
      notFound: 'We can not find metadata for this movie...',
    },
  },
  modal: {
    closeModal: 'Close',
  },
  conceptform: {
    title: 'Concept',
  },
  editorFooter: {
    buttonLabel: 'Quality ensurance',
    heading: 'Quality ensurance:',
    changeStatus: 'Change status',
    back: 'Go back',
    inputHeader: 'Your note',
    inputHelperText: 'Short note',
    cancelLabel: 'Cancel',
    saveLabel: 'Change status and save draft',
    warningSaveWithoutComment: 'Note is missing',
    newStatusPrefix: 'New status:',
    statusLabel: 'Status:',
    changeHeader: 'Changes',
    saveAsNew: 'Save as copy',
  },
  metadata: {
    visible: 'is visible',
    notVisible: 'is not visible',
    changeVisibility: 'Change visibility',
  },
};

export default phrases;
