/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Produksjonsystem - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Fagstoff ${titleTemplate}`,
    createTopicArticlePage: `Emne ${titleTemplate}`,
    agreementPage: `Avtale ${titleTemplate}`,
    searchContentPage: `Søk innhald ${titleTemplate}`,
    searchMediaPage: `Søk media ${titleTemplate}`,
    searchConceptPage: `Søk forklaringar ${titleTemplate}`,
    welcomePage: `Forside ${titleTemplate}`,
    structurePage: `Struktur ${titleTemplate}`,
    audioUploaderPage: `Lyd ${titleTemplate}`,
    imageUploaderPage: `Bilde ${titleTemplate}`,
    loginPage: `Logg inn ${titleTemplate}`,
    logoutPage: `Logg ut ${titleTemplate}`,
  },
  dropdown: {
    numberHits: `Søket gav {hits} treff`,
    searching: 'Søker...',
    create: 'Opprett nytt',
    isSelectedItem: 'Lagt til',
  },
  meta: {
    description:
      'Kvalitetssikra fritt tilgjengelige nettbaserte læremidler for videregående opplæring',
  },
  article: {
    lastUpdated: 'Sist oppdatert',
    edition: 'Utgåve',
    publisher: 'Utgjevar',
    useContent: 'Bruk innhald',
    closeLabel: 'Lukk',
    additionalLabel: 'Tilleggsstoff',
    urlContributionsLabel: 'Sjå kva {name} har bidratt med',
    urlAuthorLabel: 'Les meir om {name}',
    multipleAuthorsLabelAbbreviation: 'm. fl.',
    multipleAuthorsLabel: 'Opphavere av artikkel:',
    multipleAuthorsLabelAria: 'Opphavere av artikkelen er {names}',
    multipleAuthorsLabelAriaConjunction: 'og',
    singleAuthorsLabelAria: 'Opphaver av artikkelen er {name}',
  },
  dialog: {
    close: 'Lukk',
    title: 'Tittel',
    audio: {
      rulesForUse: 'Reglar for bruk av lydklipp',
    },
    learnAboutLicenses: 'Lær meir om opne lisensar',
    source: 'Kjelde',
  },
  license: {
    heading: 'Slik gjenbruker du innhald',
    learnMore: 'Lær meir om opne lisensar',
    copyTitle: 'Kopier referanse',
    hasCopiedTitle: 'Kopiert!',
    embed: 'Bygg inn',
    embedCopied: 'Kopierte innbyggingskode!',
    download: 'Last ned',
    tabs: {
      text: 'Tekst',
      images: 'Bilde',
      audio: 'Lyd',
      video: 'Video',
    },
    images: {
      heading: 'Slik bruker du bilder frå artikkelen',
      description:
        'Hugs å kopiera teksten som skal leggjast ved bildet der du bruker det.',
      rules: 'Regler for bruk av bildet:',
      source: 'Kjelde',
      title: 'Tittel',
    },
    text: {
      heading: 'Slik bruker du tekst frå artikkelen',
      description:
        'Artikkelen kan vera samansett av fleire ulike tekstar som vert lista her.',
      rules: 'Reglar for bruk av teksten:',
      published: 'Publiseringsdato',
    },
    audio: {
      heading: 'Slik bruker du lydfiler',
      description:
        'Hugs å kopiera teksten som skal leggjast ved lydfila der du bruker ho.',
      rules: 'Regler for bruk av lydfila:',
    },
    video: {
      heading: 'Slik bruker du video fra artikkelen',
      description:
        'Hugs å kopiera teksten som skal leggjast ved videoen der du bruker han.',
      rules: 'Regler for bruk av videoen:',
    },
    creditType: {
      originator: 'Opphavsmann',
      authorDesc: 'Denne artikkelen er laga av fleire opphavsmenn',
      photographer: 'Fotograf',
      artist: 'Kunstnar',
      editorial: 'Redaksjonelt',
      writer: 'Forfattar',
      scriptwriter: 'Manusforfattar',
      reader: 'Innlesar',
      translator: 'Omsetjar',
      director: 'Regissør',
      illustrator: 'Illustratør',
      cowriter: 'Medforfatter',
      composer: 'Komponist',
      processor: 'Tilarbeidar',
      facilitator: 'Tilretteleggjar',
      linguistic: 'Språkleg',
      idea: 'Idé',
      compiler: 'Sammenstillar',
      correction: 'Korrektur',
      rightsholder: 'Rettshaver',
      publisher: 'Forlag',
      distributor: 'Distributør',
      supplier: 'Leverandør',
    },
  },
  language: {
    en: 'Engelsk',
    nb: 'Bokmål',
    nn: 'Nynorsk',
    se: 'Samisk',
    sma: 'Sørsamisk',
    unknown: 'Ukjent',
    de: 'Tysk',
    empty: 'Ingen flere språk',
    change: 'Bytt til {language} versjon',
  },
  welcomePage: {
    lastUsed: 'Sist brukt',
    emptyLastUsed: 'Ingen sist brukte',
    savedSearch: 'Lagra søk',
    emptySavedSearch: 'Ingen lagra søk',
    guidelines: 'Retningslinjer',
  },
  searchPage: {
    header: {
      content: 'Søk etter innhald',
      media: 'Søk etter media',
      concept: 'Søk etter forklaringar',
    },
    searchButton: 'Søk',
    emptyButton: 'Tøm',
    title: 'Tittel',
    language: 'Språk',
    contentNoHits: 'Ingen innhald samsvarte med søket ditt på: {query}',
    conceptNoHits: 'Ingen forklaringar samsvarte med søket ditt på: {query}',
    mediaNoHits: 'Ingen media samsvarte med søket ditt på: {query}',
    pageSize: '{pageSize} treff per side',
    totalCount: 'Antall søketreff',
  },
  articleType: {
    'topic-article': 'Emne',
    standard: 'Læringsressurs',
  },
  subNavigation: {
    media: 'Media',
    learningPath: 'Læringssti',
    learningPathLink: 'Gå til læringssti',
    subjectMatter: 'Opprett læringsressurs',
    detailSearch: 'Detaljsøk',
    topicArticle: 'Opprett emne',
    learningResource: 'Læringsressurs',
    image: 'Nytt Bilde',
    audio: 'Ny Lydfil',
    agreement: 'Ny Avtale',
    structure: 'Strukturredigering',
    searchContent: 'Søk innhald',
    searchMedia: 'Søk media',
    searchConcepts: 'Søk begrep',
    film: 'Rediger NDLA film',
    h5p: 'Rediger H5P',
    newConcept: 'Opprett begrep',
  },
  logo: {
    altText: 'Nasjonal digital læringsarena',
  },
  siteNav: {
    chooseSubject: 'Velg fag',
    search: 'Søk',
    login: 'Logg inn',
    logout: 'Logg ut [{name}]',
  },
  loginFailure: {
    errorMessage: 'Beklager. Innlogging feila.',
    loginLink: 'Klikk for å prøve igjen.',
  },
  loginProviders: {
    description: 'Logg inn i produksjonssystem med',
  },
  logoutProviders: {
    localLogout: 'Logg ut av produksjonssystem',
    or: 'eller',
    federatedLogout: 'Logg ut av alle tjenester',
    description:
      'N.B. Alle tjenester inkluderer autentiseringstjenesten (Google eller Facebook).',
  },
  searchForm: {
    placeholder: 'Søk etter artikler, aktiviteter eller oppgaver',
    types: {
      conceptQuery: 'Søk på Forklaringar',
      contentQuery: 'Søk på Innhald',
      mediaQuery: 'Søk på Media',
      language: 'Velg Språk',
      users: 'Velg bruker',
      subjects: 'Velg fag',
      resourceTypes: 'Velg innhaldstype',
      draftStatus: 'Velg status',
    },
    tagType: {
      query: 'Innhald',
      subjects: 'Fag',
      language: 'Språk',
      users: 'Bruker',
      resourceTypes: 'Innhaldstype',
      draftStatus: 'Status',
    },
    btn: 'Søk',
    empty: 'Tøm',
    articleType: {
      all: 'Alle',
      standard: 'Standard',
      learningResource: 'Læringsressurs',
      topicArticle: 'Emnebeskrivelse',
      image: 'Bilde',
      audio: 'Lyd',
    },
    order: 'Rekkefølge',
    asc: 'Stigende',
    desc: 'Fallende',
    sorting: 'Sortering',
    sort: {
      id: 'Id',
      relevance: 'Relevans',
      title: 'Tittel',
      lastUpdated: 'Sist oppdatert',
    },
    resultError: 'Noko gjekk feil med innlasting av type: {type}',
  },
  subjectsPage: {
    subjects: 'Fag',
  },
  subjectPage: {
    topics: 'Emner',
  },
  editMarkup: {
    linkTitle: 'Gå til HTML-editor',
    title: 'HTML-editor',
    subTitle: 'Rediger artikkelinnhold med HTML',
    fetchError:
      'Ein feil oppsto ved lasting av HTML-editoren. Gå tilbake eller prøv å laste sida på nytt.',
    saveError: 'Ein feil oppsto ved lagring av endringar.',
    back: 'Tilbake',
    helpMessage: {
      paragraph1:
        'Det er mogeleg å formatere  HTML-koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisningsfunksjonaliteten aktivt. ',
      paragraph2:
        'For å minimere eventuelle problemer med formatering og for å sikre at at HTML blir konsistent, så blir koden kjørt gjennom dei samme transformeringane som den vanlige editoren. Det betyr at linjeskift t.d. blir endra til <br> ved lagring, óg at den vil prøve å rette opp ugyldig kode.',
    },
  },
  imageSearch: {
    placeholder: 'Søk i bilder',
    buttonTitle: 'Søk',
    useImage: 'Bruk bildet',
    noTitle: 'Ingen tittel',
    noResultsText:
      'Fann ingen bilder på søk. Ønskjer du å laste opp eit nytt bilde?',
    noResultsButtonText: 'Last opp bilde',
  },
  videoSearch: {
    searchPlaceholder: 'Søk i videoar',
    searchButtonTitle: 'Søk',
    loadMoreVideos: 'Last flere videoar',
    noResults: 'Ingen videoar funnet.',
    addVideo: 'Bruk video',
    previewVideo: 'Forhåndsvis',
    publishedDate: 'Publisert dato',
    duration: 'Varighet',
    interactioncount: 'Visninger',
  },
  mathEditor: {
    editMath: 'Rediger Matematikk',
    preview: 'Forhåndsvisning',
    continue: 'Du har ulagrede endringer i matteeditoren. Vil du fortsette?',
  },
  h5pElement: {
    fetchError:
      'Vi beklager, men ein feil oppsto under lasting av H5P-klienten.',
  },
  displayOembed: {
    errorMessage: 'Ein feil oppsto ved visning av oEmbed-innhald.',
    notSupported: 'oEmbed av type {type} og kjelde {provider} er ikkje støtta.',
  },
  audioSearch: {
    searchPlaceholder: 'Søk i lydfiler',
    searchButtonTitle: 'Søk',
    useAudio: 'Velg lyd',
    noResults: 'Ingen resultat funnet',
    noTitle: 'Ingen tittel',
  },
  conceptSearch: {
    searchPlaceholder: 'Søk i forklaringar',
    searchButtonTitle: 'Søk',
    noResults: 'Ingen resultat funnet',
    noTitle: 'Ingen tittel',
    noContent: 'Ingen innhald',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element av type {type} vil bli fjerna ved lagring.',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Bildetittel',
      h5p: 'H5P-tittel',
      brightcove: 'Videotittel',
      external: 'Innhaldstekst',
    },
    visualElementCopyright: 'Opphav',
    removeVisualElement: 'Fjern element',
    info: {
      lastUpdated: 'Sist oppdatert: ',
    },
    title: 'Emnebeskrivelse | {title} ({key})',
    fields: {
      caption: {
        label: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innhaldstekst',
        },
        placeholder: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innhaldstekst',
        },
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
    },
  },
  agreementForm: {
    title: {
      create: 'Avtale',
      update: 'Avtale',
    },
    fields: {
      title: {
        label: 'Avtaletittel',
        placeholder: 'Avtaletittel',
      },
      content: {
        label: 'Avtalens innhald',
        placeholder: 'Avtalens innhald',
      },
    },
  },
  footnoteForm: {
    title: 'Tittel',
    year: 'År',
    authors: 'Forfatter',
  },
  linkForm: {
    href: 'Lenke',
    text: 'Tekst',
  },
  audioForm: {
    title: 'Lyd',
  },
  imageEditor: {
    editImage: 'Rediger bildet',
    remove: {
      crop: 'Fjern utsnitt',
      focalPoint: 'Fjern fokuspunkt',
    },
  },
  imageForm: {
    title: 'Bilde ',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Bildetittel',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
    },
    title: 'Læringsressurs',
    validation: {
      missingEmbedData:
        'Ein eller fleire inkluderte lyd-, bilde-, eller videoelementer mangler beskrivende tekst eller alternativ tekst.',
    },
    fields: {
      rightAside: {
        title: 'Høgrespalte',
        moveContent: 'Flytt innhald inn i teksten',
        delete: 'Slett høgrespalte',
      },
      footnotes: {
        edition: 'Utgåve',
        publisher: 'Utgjevar',
      },
    },
  },
  editorToolbar: {
    bold: 'Feit',
    italic: 'Kursiv',
    underlined: 'Understreka',
    quote: 'Sitat',
    link: 'Lenke',
    numberedList: 'Nummerert liste',
    bulletedList: 'Punktliste',
    twoColumnList: 'To-kolonners liste',
    letterList: 'Bokstavliste',
    headingOne: 'Overskrift 1',
    headingTwo: 'Overskrift 2',
    headingThree: 'Overskrift 3',
    footnote: 'Fotnote',
    mathml: 'Matte',
    concept: 'Forklaring',
  },
  editorBlockpicker: {
    heading: 'Legg til',
    actions: {
      block: 'Seksjon',
      factAside: 'Faktaboks',
      table: 'Tabell',
      bodybox: 'Tekst i ramme',
      details: 'Ekspanderande boks',
      solutionbox: 'Fasitboks',
      image: 'Bilde',
      video: 'Video',
      audio: 'Lyd',
      h5p: 'H5P',
      url: 'Ressurs fra lenke',
      related: 'Relatert artikkel',
      file: 'Fil',
    },
  },
  detailBox: {
    changeTitle: 'Endre overskrift',
    placeholder: 'Kort sammendrag',
  },
  form: {
    metadataSection: 'Metadata',
    contentSection: 'Innhald',
    workflowSection: 'Versjonslogg og merknader',
    taxonomytSection: 'Taksonomi',
    copyrightSection: 'Lisens og bruker',
    save: 'Lagre',
    saveDraft: 'Lagre utkast',
    saveTax: 'Lagre taksonomi',
    choose: 'Velg',
    saving: 'Lagrer...',
    saved: 'Lagra ',
    copy: 'kopi',
    saveAsCopySuccess: 'Ny artikkel lagret',
    preview: {
      button: 'Forhandsvis',
    },
    name: {
      title: 'Tittel',
      introduction: 'Introduksjon',
      creators: 'Opphavsperson',
      rightsholders: 'Rettighetshaver',
      processors: 'Bearbeider',
      tags: 'Nøkkelord',
      license: 'Lisens',
      origin: 'Opphav',
      audioFile: 'Lydfil',
      content: 'Innhald',
      notes: 'Merknader',
      metaDescription: 'Metabeskrivelse',
      metaImageAlt: 'Alt-tekst',
      alttext: 'Alt-tekst',
      caption: 'Bildetekst',
      imageFile: 'Bildefil',
      visualElementCaption: 'Figur tekst',
      visualElementAlt: 'Alt tekst',
      validFrom: 'Gyldig fra',
      validTo: 'Gyldig til',
      description: 'Innhald',
      conceptContent: 'Beskrivning',
    },
    previewProductionArticle: {
      button: 'Samanlikn utkast og artikkel',
      article: 'Artikkel',
      draft: 'Utkast',
    },
    detailBox: {
      changeTitle: 'Endre overskrift',
      placeholder: 'Kort sammendrag',
    },
    previewLanguageArticle: {
      button: 'Samanlikn språkversjonar',
      title: 'Utkast på {language}',
    },
    previewNewWindow: 'Forhåndsvis i nytt vindu',
    contributor: {
      add: 'Legg til',
    },
    abort: 'Avbryt',
    edit: 'Rediger',
    remove: 'Fjern',
    validate: 'Valider',
    publish: 'Publiser',
    savedOk: 'Lagra OK',
    publishedOk: 'Publisert OK',
    validationOk: 'Ingen valideringsfeil funnet',
    createdOk: 'Oppretta OK',
    addNewImage: 'Legg til nytt bilde',
    mustSaveFirst: 'Du må lagre endringene dine først',
    addNewAudio: 'Legg til ny lyd',
    notes: {
      heading: 'Merknader',
      add: 'Legg til merknad',
      remove: 'Ta bort',
      warning: 'Ein merknad må ha tekst',
      history: {
        user: 'Bruker',
        time: 'Når',
        status: 'Status',
        heading: 'Merknadshistorikk',
        note: 'Merknad',
        empty: 'Ingen merknader',
      },
    },
    updated: {
      label: 'Oppdatert dato',
    },
    published: {
      label: 'Publisert dato',
      reset: 'Resett dato',
    },
    updatePublished: 'Endre publisert dato',
    editImage: 'Endre bilde',
    editOriginalImage: 'Rediger orginal bilde',
    editAudio: 'Endre lyd',
    resetToProd: {
      button: 'Tilbakestill endringer',
      modal: 'Vil du tilbakestille utkastet til slik det er på ndla forsida?',
    },
    variant: {
      create: 'Legg til språk',
    },
    remainingCharacters:
      'Maks {maxLength, number} tegn og du har {remaining, number} igjen.',
    title: {
      label: 'Tittel',
    },
    introduction: {
      label: 'Ingress',
    },
    metaImage: {
      title: 'Metabilde',
      label: 'Metabilde',
      imageTitle: 'Bildetittel',
      helpLabel: 'Kva er eit metabilde?',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
      add: 'Velg metabilde',
    },
    visualElement: {
      title: 'Legg til visuelt element',
      label: 'Visuelt element',
      video: 'Videosøk',
      image: 'Bildesøk',
      imageUpload: 'Last opp bilde',
      h5p: 'H5P',
    },
    concept: {
      create: 'Opprett nytt begrep',
      addText: 'Velg eit begrep under og trykk "koble til fagtekst", eller',
      edit: 'Rediger begrep',
      addConcept: 'Legg til eksisterande begrep',
      source: 'Kjelde',
    },
    workflow: {
      title: 'Status',
      change: 'Endre status',
      qualityAssurance: 'Kvalitetssikring',
      saveAsNew: 'Lagre kopi som ny artikkel',
      deleteLanguageVersion: {
        button: 'Slett språkversjon',
        title: 'Slett språkversjon',
        modal: 'Er du sikker på at du vil slette denne språkversjonen?',
      },
      statusInfoTooltip: 'Kva er forskjella på dei ulike statusane?',
      statusLabel: 'Status',
    },
    status: {
      new: 'Ny - Ikke lagret',
      new_language: 'Nytt språk - ikke lagret',
      created: 'Oppretta',
      imported: 'Fra spoling',
      draft: 'Kladd',
      proposal: 'Utkast',
      user_test: 'Brukertest',
      awaiting_quality_assurance: 'Til kvalitetssikring',
      queued_for_language: 'Til språk',
      translated: 'Ferdig fra språk',
      quality_assured: 'Publiseringsklar',
      queued_for_publishing: 'Til publisering',
      published: 'Publisert',
      unpublished: 'Avpublisert',
      awaiting_unpublishing: 'Til avpublisering',
      archived: 'Arkivert',
      actions: {
        DRAFT: 'Kladd',
        PROPOSAL: 'Utkast',
        USER_TEST: 'Brukertest',
        AWAITING_QUALITY_ASSURANCE: 'Til kvalitetssikring',
        QUEUED_FOR_LANGUAGE: 'Til språk',
        TRANSLATED: 'Ferdig fra språk',
        QUALITY_ASSURED: 'Publiseringsklar',
        QUEUED_FOR_PUBLISHING: 'Til publisering',
        PUBLISHED: 'Publiser',
        AWAITING_UNPUBLISHING: 'Til avpublisering',
        UNPUBLISHED: 'Avpubliser',
        ARCHIVED: 'Arkiver',
      },
    },
    validDate: {
      label: 'Gyldighet',
      from: {
        label: 'Gyldig fra',
        placeholder: 'Fra og med dato',
      },
      to: {
        label: 'Gyldig til',
        placeholder: 'Til og med dato',
      },
    },
    content: {
      label: 'Innhald',
      placeholder: 'Innhald',
      figure: {
        notSupported: 'Mediatype {mediaType} er ikkje støtta.',
        confirmDelete: 'Er du sikker på at du vil slette denne figuren?',
      },
      relatedArticle: {
        placeholder: 'Søk på tittel',
        urlPlaceholder: 'http://www.example.com',
        urlLocation: 'Nettside hos {domain}',
        titlePlaceholder: 'Tittel',
        invalidArticle: 'Ugyldig artikkel',
        addExternal: 'Legg til ekstern artikkel',
        searchExternal: 'Skriv inn url og tittel på ekstern artikkel',
      },
      concept: {
        remove: 'Fjern begrep',
        choose: 'Velg begrep',
      },
      link: {
        goTo: 'Gå til',
        insert: 'Sett inn lenke',
        update: 'Oppdater lenke',
        change: 'Endre',
        remove: 'Fjern lenke',
        href: 'Lenke',
        newTab: 'Åpne lenke i ny fane',
        text: 'Tekst',
        addTitle: 'Legg til lenke',
        changeTitle: 'Endre lenke',
        required: 'Lenke er påkrevd',
        invalid: 'Ugyldig lenke',
        preview: 'Forhåndsvis lenke',
        unSupported: 'Innhaldstypen i lenka er ikkje støtta',
        newUrlResource: 'Ny ressurs',
        changeUrlResource: 'Rediger ressurs: {type}',
      },
      footnote: {
        title: 'Tittel',
        year: 'År',
        authors: {
          label: 'Forfatter',
          description: 'Obligatorisk med minst 1 forfatter.',
          createOption: 'Opprett ny forfatter',
        },
        edition: 'Utgåve',
        publisher: 'Utgjevar',
        addTitle: 'Legg til fotnote',
        editTitle: 'Rediger fotnote',
        removeFootnote: 'Fjern fotnote',
      },
      table: {
        'row-remove': 'Fjern rad',
        'row-add': 'Legg til rad',
        'column-add': 'Legg til kolonne',
        'column-remove': 'Fjern kolonne',
        'table-remove': 'Fjern tabell',
      },
    },
    tags: {
      label: 'Nøkkelord',
      helpLabel: 'Kva er nøkkelord?',
      description: 'Obligatorisk med 3 nøkkelord.',
      createOption: 'Opprett nytt nøkkelord',
    },
    resourceTypes: {
      label: 'Innhaldstype og egenskaper',
      placeholder: 'Legg til egenskap',
    },
    subjects: {
      label: 'Fag',
      searchPlaceholder: 'Søk etter fag',
      placeholder: 'Legg til fag',
    },
    filter: {
      label: 'Filter',
      placeholder: 'Legg til filter',
      core: 'Kjernestoff',
      supplementary: 'Tilleggsstoff',
      setRelevance: 'Velg relevans',
    },
    topics: {
      label: 'Emnetilknytning',
      placeholder: 'Legg til emnetilknytning',
      primaryTopic: 'Primærkobling',
      sharedTopic: 'Delt emne',
      setPrimaryTopic: 'Velg som primærkoblet emne',
    },
    metaDescription: {
      label: 'Metabeskrivelse',
      description: 'Beskrivelsen blir synlig i søk.',
      helpLabel: 'Kva er metabeskrivelse?',
    },
    agreement: {
      label: 'Koble til avtale',
      helpLabel: 'Kva er ei avtale?',
      placeholder: 'Søk etter avtale',
    },
    rightsholders: {
      label: 'Rettighetshaver',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv namn til rettighetshaver',
      createOption: 'Opprett ny rettighetshaver',
    },
    processors: {
      label: 'Bearbeider',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv namn til bearbeider',
      createOption: 'Opprett ny bearbeider',
    },
    creators: {
      label: 'Opphavsperson',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv namn til opphavsperson',
      createOption: 'Opprett ny opphavsperson',
      description: 'Obligatorisk med minst 1 opphavsperson.',
    },
    license: {
      label: 'Lisens',
      helpLabel: 'Kva er lisensar?',
    },
    origin: {
      label: 'Opphav',
    },
    image: {
      file: 'Bilde',
      save: 'Lagre bilde',
      editImage: 'Rediger bilde',
      removeImage: 'Ta bort bilde',
      alignment: {
        left: 'Justering: Venstrestilt',
        right: 'Justering: Høgrestilt',
        center: 'Justering: Stort i midten',
      },
      sizes: {
        xsmall: 'Størrelse: Frimerke',
        small: 'Størrelse: Lite',
        medium: 'Størrelse: Middels',
        fullwidth: 'Størrelse: Stort',
      },
      crop: 'Lag utsnitt av bildet',
      focalPoint: 'Sett fokalpunkt',
      caption: {
        label: 'Bildetekst',
        placeholder: 'Bildetekst',
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
        noText: 'Universal utforming krever alt-tekst.',
      },
      dragdrop: {
        main: 'Dra og slipp',
        sub: 'eller trykk for å laste opp bilde',
        ariaLabel: 'Dra og slipp eller trykk for å laste opp bilde',
      },
    },
    video: {
      caption: {
        label: 'Videotekst',
        placeholder: 'Videotekst',
      },
      remove: 'Fjern video',
    },
    audio: {
      file: 'Lydfil',
      title: {
        label: 'Lydtittel',
        placeholder: 'Lydtittel',
      },
      caption: {
        label: 'Lydtekst',
        placeholder: 'Lydtekst',
      },
      remove: 'Ta bort lydfil',
      sound: 'Lyd',
      speech: 'Tale',
    },
    external: {
      title: 'eksternt',
      edit: 'Rediger {type} element',
      remove: 'Fjern {type} element',
    },
    related: {
      title: 'Relaterte artikler',
      showMore: 'Vis flere relaterte artikler',
      showLess: 'Vis mindre',
    },
    file: {
      label: 'Filer',
      file: {
        label: 'Fil',
      },
      download: 'Last ned:',
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
      title: {
        label: 'Filtittel',
        placeholder: 'Filtittel',
      },
      addFile: 'Legg til fil',
      removeList: 'Fjern filliste',
      placeholder: 'Oppgi et filnavn',
      changeName: 'Endre navn',
      changeOrder: 'Endre rekkefølge',
      removeFile: 'Ta bort fil',
    },
  },
  validation: {
    isRequired: '{label} er påkrevd.',
    bothFields: 'En {labelLowerCase} må inneholde alle felter.',
    isNumeric: '{label} må inneholde tall.',
    maxLength: '{label} kan ikkje ha meir enn {maxLength, number} tegn.',
    minLength: '{label} må ha minst {minLength, number} tegn.',
    url: '{label} må inneholde ei gyldig lenke.',
    dateBeforeInvalid: '{label} kan ikkje være etter {afterLabel}.',
    dateAfterInvalid: '{label} kan ikkje være før {beforeLabel}.',
    minItems:
      '{label} feltet må minst inneholde {minItems, plural, one{en} other{# ulike}} {labelLowerCase}.',
    noEmptyNote: 'Ein merknad kan ikkje være tom',
  },
  errorMessage: {
    title: 'Oops, noko gjekk gale',
    description: 'Vi beklager, men ein feil oppsto.',
    back: 'Tilbake',
    goToFrontPage: 'Gå til forsida',
    invalidUrl: 'Ugyldig url',
    noArticleInProd: 'Ingen artikkel funnet i prod',
    taxonomy: 'Det var eit problem ved lasting av taksonomi',
    auth0:
      'Autentiseringsfeil. Trykk avbryt for å ta vare på eventuelle endringer du har gjort før du logger inn på nytt. Følgende feilmelding kom fra auth0: {message}',
    statusCode: {
      409: 'Denne artikkelen har allerede blitt oppdatert. Ta vare på det du har endra og last sida på nytt for å kunne lagre.',
    },
  },
  notFound: {
    description: 'Denne sida finnes ikkje.',
  },
  forbiddenPage: {
    description: 'Du har ikkje tilgang til denne sida',
  },
  alertModal: {
    notSaved: 'Dokumentet er ikkje lagra, ønsker du å fortsette?',
    continue: 'Fortsett',
    delete: 'Slett',
    confirm: 'Bekreft',
    loginAgain: 'Logg inn på nytt',
  },
  taxonomy: {
    editStructure: 'Rediger struktur',
    addSubject: 'Legg til nytt fag',
    addExistingTopic: 'Legg til eksisterende emne',
    newSubject: 'Nytt fag',
    existingTopic: 'Eksisterende emne',
    newTopic: 'Nytt emne',
    subjectSettings: 'Faginstillinger',
    topicSettings: 'Emneinstillinger',
    changeName: 'Endre namn',
    addTopic: 'Legg til nytt emne',
    errorMessage: 'Ein feil oppsto',
    emptyFilter: 'Ingen treff',
    editFilter: 'Rediger filter',
    addFilter: 'Nytt filter',
    connectFilters: 'Koble til filter',
    confirmDelete: 'Er du sikker på at du vil slette filteret?',
    confirmDeleteTopic:
      'Vil du slette dette emnet frå mappa? Dette påvirker ikkje plasseringa andre steder',
    linkSettings: 'Link',
    setPrimary: 'Sett til primærkobling',
    addResource: 'Legg til ressurs',
    searchResource: 'Søk etter ressurs',
    searchArticle: 'Søk etter emneartikkel',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Obs! Denne ressursen er ein anna type',
    noResources: 'Ingen ressurser funnet',
    addTopicDescription: 'Endre emnebeskrivelse',
    confirmSetPrimary: 'Vil du gjere dette til hovedplassering?',
    jumpToResources: 'Hopp til ressurser',
    resource: {
      confirmDelete:
        'Vil du fjerne ressursen frå denne mappa? Dette vil ikkje påverke plasseringa andre steder',
      chooseFilter: 'Koble til filter',
    },
    removeLink: 'Fjern lenke',
    resourceTypes: {
      title: 'Innhaldstype',
      subTitle: 'Kva for ei innhaldstype har denne ressursen?',
      placeholder: 'Velg innhaldstype',
    },
    topics: {
      title: 'Emnetilknytninger',
      topicPlacement: 'Emneplassering',
      subTitle: 'Kvar i taksonomien skal ressursen ligge?',
      subTitleTopic: 'Hvor i taksonomien skal emnebeskrivelsen ligge?',
      filestructureButton: 'Opprett en emnetilknytning',
      chooseTaxonomyPlacement: 'Velg plassering i taksonomi',
      changeTaxonomyPlacement: 'Endre plassering i taksonomi',
      filestructureHeading: 'Velg emnetilknytning',
      addNewTopic: 'Legg til nytt emne',
      addNewSubTopic: 'Legg til nytt underemne',
      filestructureClose: 'Lukk',
      addedTopic: 'Lagt til',
      filterTopic: 'Filtrer emner',
      disconnectedTaxonomyWarning: 'Ugyldig tilknytning',
    },
    filters: {
      title: 'Filter',
      subTitle: 'Kva for eit fagfilter gjeld for denne ressursen?',
      additional: 'Tilleggsressurs',
      core: 'Kjerneressurs',
    },
    goTo: 'Åpne i stukturredigering',
  },
  notions: {
    edit: 'Rediger begrep',
    closeNotion: 'Lukk begrepsmodal',
  },
  contextTypes: {
    topic: 'Emne',
  },
  ndlaFilm: {
    editor: {
      slideshowHeader: 'Slideshow:',
      slideshowTitle: 'Filmer i slideshow',
      slideshowSubTitle: 'på forsida',
      movieGroupHeader: 'Filmgrupperinger:',
      addMovieToSlideshow: 'Legg til film i slideshow',
      addMovieToGroup: 'Legg til film i "{name}"',
      editMovieGroupName: 'Endre navna til filmgruppa',
      deleteMovieGroup: 'Slett "{name}"',
      moveMovieGroupUp: 'Flytt opp',
      moveMovieGroupDown: 'Flytt ned',
      changeOrder: 'Endre rekkjefølgje',
      removeMovieFromGroup: 'Ta vekk film fra gruppe',
      removeMovieFromSlideshow: 'Ta vekk film fra slideshow',
      createThemeGroup: 'Opprett gruppe',
      saveNameChanges: 'Lagre endringer',
      cancel: 'Avbryt',
      groupNamePlaceholder: 'Skriv navn på {lang}',
      editGroupTitle: 'Endre navn(a) på filmgruppa:',
      newGroupTitle: 'Kva skal gruppa heite?',
      notFound: 'Vi finn ikkje metadata for denne filmen...',
    },
  },
  modal: {
    closeModal: 'Lukk',
  },
  conceptform: {
    title: 'Begrep',
  },
  editorFooter: {
    buttonLabel: 'Kvalitetssikring',
    heading: 'Kvalitetssikring:',
    label: '',
    changeStatus: 'Endre status',
    back: 'Gå tilbake',
    inputHeader: 'Din merknad',
    inputHelperText: 'Kort merknad påkrevd ved statusendring',
    cancelLabel: 'Avbryt',
    saveLabel: 'Endre status og lagre utkast',
    warningSaveWithoutComment: 'Merknad mangler',
    newStatusPrefix: 'Ny status:',
    statusLabel: 'Status:',
    changeHeader: 'Endringer',
    saveAsNew: 'Lagre som kopi',
  },
};

export default phrases;
