/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Production system - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Learning resource ${titleTemplate}`,
    createTopicArticlePage: `Topic ${titleTemplate}`,
    agreementPage: `Agreement ${titleTemplate}`,
    searchPage: `Search ${titleTemplate}`,
    welcomePage: `Frontpage ${titleTemplate}`,
    structurePage: `Structure ${titleTemplate}`,
    audioUploaderPage: `Audio ${titleTemplate}`,
    imageUploaderPage: `Image ${titleTemplate}`,
  },
  meta: {
    description: 'Norwegian Digital Learning Arena, Open Educational Resources',
  },
  article: {
    author: 'Author',
    published: 'Published',
    edition: 'Edition',
    publisher: 'Publisher',
    created: 'Created',
    lastUpdated: 'Last updated',
    closeLabel: 'Close',
    useContent: 'Cite or use',
    additionalLabel: 'Additional content',
    urlContributionsLabel: 'See {name}`s contributions',
    urlAuthorLabel: 'Read more about {name}',
    multipleAuthorsLabelAbbreviation: 'et al.',
    multipleAuthorsLabel: 'Article authors:',
    multipleAuthorsLabelAria: 'Authors of this article are {names}',
    multipleAuthorsLabelAriaConjunction: 'og',
    singleAuthorsLabelAria: 'The author of this article is {name}',
  },
  dialog: {
    close: 'Close',
    title: 'Title',
    audio: {
      rulesForUse: 'Rules for use of audio',
    },
    learnAboutLicenses: 'Learn more about open licenses',
    source: 'Source',
  },
  license: {
    heading: 'Howto reuse content',
    tabs: {
      text: 'Text',
      images: 'Images',
      audio: 'Audio',
      video: 'Video',
    },
    images: {
      heading: 'How to use images from the article',
      description:
        'Remember to copy the text to be attached to the image where you use it.',
      rules: 'Rules for use of image:',
      source: 'Source',
      title: 'Title',
    },
    text: {
      heading: 'How to use text from the article',
      description:
        'The article may be composed of several different texts, which are listed here.',
      rules: 'Rules for use of text:',
      published: 'Published',
    },
    audio: {
      heading: 'How to use audio files from the article',
      description:
        'Remember to copy the text to be attached to the audio where you use it.',
      rules: 'Rules for use of audio file:',
    },
    video: {
      heading: 'How to use videos from the article',
      description:
        'Remember to copy the text to be attached to the video where you use it.',
      rules: 'Rules for use of audio file:',
    },
    learnMore: 'Learn more about open licenses',
    copyTitle: 'Copy reference',
    embed: 'Embed',
    embedCopied: 'Copied embed code!',
    hasCopiedTitle: 'Copied!',
    download: 'Download',
    creditType: {
      originator: 'Originator',
      authorDesc: 'This article is made by several originators',
      photographer: 'Photographer',
      artist: 'Artist',
      editorial: 'Editorial',
      writer: 'Writer',
      scriptwriter: 'Scriptwriter',
      reader: 'Reader',
      translator: 'Translator',
      director: 'Director',
      illustrator: 'Illustrator',
      cowriter: 'Cowriter',
      composer: 'Composer',
      processor: 'Processor',
      facilitator: 'facilitator',
      linguistic: 'Linguistic',
      idea: 'Idea',
      compiler: 'Compiler',
      correction: 'Correction',
      rightsholder: 'Rightsholder',
      publisher: 'Publisher',
      distributor: 'Distributor',
      supplier: 'Supplier',
    },
  },
  language: {
    en: 'English',
    nb: 'Norwegian - Bokmål',
    nn: 'Norwegian - Nynorsk',
    se: 'Swedish',
    unknown: 'Unknown',
    de: 'German',
    empty: 'No languages left',
  },
  welcomePage: {
    lastUsed: 'Last used',
    emptyLastUsed: 'Empty last used list',
    savedSearch: 'Saved searches',
    emptySavedSearch: 'No saved searches',
    guidelines: 'Guidelines',
  },
  searchPage: {
    header: {
      content: 'Search for content',
      media: 'Search for media',
    },
    searchButton: 'Search',
    emptyButton: 'Empty',
    title: 'Title',
    language: 'Language',
    contentNoHits: 'Your search - {query} - did not match any content.',
    mediaNoHits: 'Your search - {query} - did not match any media.',
    pageSize: '{pageSize} hits per page',
    totalCount: 'Total results',
  },
  subNavigation: {
    media: 'Media',
    learningPath: 'Learningpath',
    subjectMatter: 'Subject matter',
    detailSearch: 'Detail search',
    topicArticle: 'Topic',
    learningResource: 'Learning resource',
    image: 'Image',
    audio: 'Audio',
    agreement: 'Agreement',
    structure: 'Structure',
    concept: 'Concept',
    searchContent: 'Search content',
    searchMedia: 'Search media',
  },
  logo: {
    altText: 'The Norwegian Digital Learning Arena',
  },
  siteNav: {
    chooseSubject: 'Choose Subject',
    search: 'Search',
    login: 'Login',
    logout: 'Logout [{name}]',
  },
  loginFailure: {
    errorMessage: 'Sorry. Login failed.',
    loginLink: 'Click to try again.',
  },
  loginProviders: {
    description: 'Log in with',
  },
  logoutProviders: {
    localLogout: 'Logg ut av prouctionsystem',
    or: 'eller',
    federatedLogout: 'Log out of all providers',
    description:
      'N.B. All providers include the identityprovider (Google or Facebook).',
  },
  searchForm: {
    placeholder: 'Search articles',
    types: {
      contentQuery: 'Search for content',
      mediaQuery: 'Search for media',
      language: 'Select language',
      subjects: 'Select subject',
      resourceTypes: 'Select resource type',
      draftStatus: 'Select status',
    },
    tagType: {
      query: 'Query',
      subjects: 'Subject',
      language: 'Language',
      resourceTypes: 'Resource type',
      draftStatus: 'Status',
    },
    btn: 'Search',
    empty: 'Empty',
    articleType: {
      all: 'All',
      standard: 'Standard',
      learningResource: 'Learning resource',
      topicArticle: 'Topic description',
      image: 'Image',
      audio: 'Audio',
    },
    order: 'Rekkefølge',
    asc: 'Ascending',
    desc: 'Descending',
    sorting: 'Sorting',
    sort: {
      id: 'Id',
      relevance: 'Relevance',
      title: 'Title',
      lastUpdated: 'Last updated',
    },
    resultError: 'Something went wrong with type: {type}',
  },
  subjectsPage: {
    subjects: 'Subjects',
  },
  subjectPage: {
    topics: 'Topics',
  },
  editMarkup: {
    linkTitle: 'Go to HTML editor',
    title: 'HTML editor',
    subTitle: 'Edit article with HTML',
    fetchError:
      'An error occurred while loding an article into the HTML editor. Go back or try to reload the page.',
    saveError: 'An error occurred while saving article changes.',
    helpMessage: {
      paragraph1:
        'Det er mulig å formatter  HTML koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisning funksjonaliteten aktivt. ',
      paragraph2:
        'For å minimerer eventuelle problemer med formatering og sikre at at HTML blir konsistent så blir koden kjørt gjennom de samme transformeringen som WYSIWYG editoren. Det betyr at linjeskift f.eks. blir endret til <br> ved lagring og samt at den vil prøve å rette opp kode som ikke følger følgende regler:',
    },
  },
  imageSearch: {
    placeholder: 'Search images',
    buttonTitle: 'Search',
    useImage: 'Use image',
    noTitle: 'No title',
    noResultsText: 'No images found. Would you like to upload a new image?',
    noResultsButtonText: 'Upload image',
  },
  videoSearch: {
    searchPlaceholder: 'Search videos',
    searchButtonTitle: 'Search',
    loadMoreVideos: 'Load more videos',
    noResults: 'No videos found',
    addVideo: 'Use video',
    previewVideo: 'Preview',
    publishedDate: 'Published date',
    duration: 'Duration',
    interactioncount: 'Views',
  },
  mathEditor: {
    editMath: 'Edit Math',
    preview: 'Preview',
    continue:
      'You have unsaved changes in the math editor. Do you want to continue?',
  },
  h5pElement: {
    fetchError: 'Sorry, an error occurd while loading the H5P client.',
  },
  displayOembed: {
    errorMessage: 'An error occurd when displaying oEmbed.',
    notSupported:
      'oEmbed of type {type} and provider {provider} is not supported.',
  },
  audioSearch: {
    searchPlaceholder: 'Search in audio files',
    searchButtonTitle: 'Search',
    useAudio: 'Chose audio',
    noResults: 'No audio files found',
    noTitle: 'No title',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element of type {type} will be deleted on save.',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Image title',
      video: 'Video title',
      brightcove: 'Video title',
      external: 'Content title',
      h5p: 'H5P title',
    },
    visualElementCopyright: 'Origin',
    removeVisualElement: 'Remove element',
    info: {
      lastUpdated: 'Last updated: {updated}',
    },
    title: 'Topic description | {title} ({key})',
    fields: {
      caption: {
        label: {
          image: 'Video caption',
          brightcove: 'Video caption',
          external: 'Content caption',
        },
        placeholder: {
          image: 'Image caption',
          brightcove: 'Video caption',
          external: 'Content caption',
        },
      },
      alt: {
        label: 'Alt-text',
        placeholder: 'Alt-text',
      },
    },
  },
  audioForm: {
    title: {
      create: 'You are now creating a audio file',
      update: 'You are now editing a audio file',
    },
  },
  imageEditor: {
    remove: {
      crop: 'Remove crop',
      focalPoint: 'Remove focal point',
    },
  },
  imageForm: {
    title: 'Image | {title} ({key})',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Image title',
      copyright: 'Copyright',
      change: 'Change meta image',
    },
    title: 'Learning resource | {title} ({key})',
    validation: {
      missingEmbedData:
        'One or more inlcuded video, image, or audio elements is missing caption or alternative text.',
    },
    fields: {
      rightAside: {
        title: 'Right column',
        moveContent: 'Move content into the text',
        delete: 'Delete right aside',
      },
      metaImage: {
        title: 'Meta image',
        label: 'Meta image',
      },
      footnotes: {
        edition: 'Edition',
        publisher: 'Publisher',
      },
    },
  },
  editorToolbar: {
    bold: 'Bold',
    italic: 'Italic',
    underlined: 'Underlined',
    quote: 'Quote',
    link: 'Link',
    numberedList: 'Numbered list',
    bulletedList: 'Bulleted list',
    twoColumnList: 'Two-column list',
    letterList: 'Letter list',
    headingOne: 'Heading 1',
    headingTwo: 'Heading 2',
    headingThree: 'Heading 3',
    footnote: 'Footnote',
    mathml: 'Math',
  },
  editorBlockpicker: {
    heading: 'Add',
    actions: {
      block: 'Paragraph',
      factAside: 'Factbox',
      table: 'Table',
      bodybox: 'Text in frame',
      details: 'Expandable box',
      image: 'Image',
      video: 'Video',
      audio: 'Audio',
      h5p: 'H5P',
      url: 'Resource from link',
      related: 'Related article',
      file: 'File',
    },
  },
  form: {
    metadataSection: 'Metadata',
    contentSection: 'Content',
    workflowSection: 'Workflow',
    taxonomytSection: 'Taxonomy',
    copyrightSection: 'License and authors',
    save: 'Save',
    saveDraft: 'Save draft',
    saveTax: 'Save taxonomy',
    saving: 'Saving...',
    choose: 'Choose',
    saved: 'Saved ',
    preview: {
      button: 'Preview',
    },
    previewProductionArticle: {
      button: 'Compare draft and article',
      article: 'Article',
      draft: 'Draft',
    },
    previewLanguageArticle: {
      button: 'Compare different language versions',
      title: 'Draft on {language}',
    },
    contributor: {
      add: 'Add',
    },
    abort: 'Abort',
    edit: 'Edit',
    remove: 'Remove',
    validate: 'Validate',
    publish: 'Publish',
    savedOk: 'Saved OK',
    publishedOk: 'Published OK',
    validationOk: 'No validation errors found',
    createdOk: 'Created OK',
    addNewImage: 'Add new image',
    addNewAudio: 'Add new audio',
    notes: {
      heading: 'Notes',
      add: 'Add new note',
      remove: 'Remove note',
      warning: 'A note must contain text',
      history: {
        heading: 'Notes history',
        note: 'Note',
        empty: 'No notes',
      },
    },
    editImage: 'Edit image',
    editAudio: 'Edit audio',
    resetToProd: {
      button: 'Reset to prod',
      modal: 'Do you want to reset the draft as it is on the ndla frontpage?',
    },
    variant: {
      create: 'Create variant +',
    },
    remainingCharacters:
      'Max {maxLength, number} characters and you have {remaining, number} remaining.',
    title: {
      label: 'Title',
    },
    introduction: {
      label: 'Introduction',
    },
    visualElement: {
      title: 'Add visual element',
      label: 'Visual element',
      video: 'Video search',
      image: 'Image search',
      imageUpload: 'Upload image',
      h5p: 'H5P',
    },
    workflow: {
      title: 'Status',
      change: 'Change status',
      qualityAssurance: 'Quality assurance',
      deleteLanguageVersion: {
        button: 'Delete language version',
        title: 'Delete language version',
        modal: 'Are you sure that you want to delete this language version?',
      },
    },
    status: {
      created: 'Created',
      imported: 'Imported',
      draft: 'Draft',
      proposal: 'Proposal',
      user_test: 'User test',
      awaiting_quality_assurance: 'Quality assurance',
      quality_assured: 'Quality assured',
      queued_for_publishing: 'Queued for publishing',
      published: 'Published',
      unpublished: 'Unpublished',
      awaiting_unpublishing: 'Awaiting unpublishing',
      archived: 'Archived',
      actions: {
        DRAFT: 'Draft',
        PROPOSAL: 'Proposal',
        USER_TEST: 'User test',
        AWAITING_QUALITY_ASSURANCE: 'To Quality assurance',
        QUALITY_ASSURED: 'Quality assured',
        QUEUED_FOR_PUBLISHING: 'Queue for publishng',
        PUBLISHED: 'Publish',
        AWAITING_UNPUBLISHING: 'Queue for unpublishing',
        UNPUBLISHED: 'Unpublish',
        ARCHIVED: 'Archive',
      },
    },
    validDate: {
      label: 'Valid date',
      from: {
        label: 'Valid from',
        placeholder: 'From date',
      },
      to: {
        label: 'Valid to',
        placeholder: 'To date',
      },
    },
    content: {
      label: 'Content',
      placeholder: 'Write here...',
      figure: {
        notSupported: 'Media type {mediaType} is not supported.',
        confirmDelete: 'Are you sure that you will delete this figure?',
      },
      relatedArticle: {
        placeholder: 'Search for title',
        urlPlaceholder: 'Url',
        titlePlaceholder: 'Title',
        urlLocation: 'Webpage at {domain}',
        emptyFilter: 'No related articles found',
        emptyList: 'There are no related articles in this list',
        invalidArticle: 'Invalid article',
        addExternal: 'Add external article',
        searchExternal: 'Write the url and title of the external article',
      },
      link: {
        goTo: 'Go to',
        insert: 'Insert link',
        update: 'Update link',
        change: 'Change',
        remove: 'Remove link',
        href: 'Link',
        title: 'Title',
        newTab: 'Open link in new tab',
        text: 'Text',
        addTitle: 'Add link',
        changeTitle: 'Change link',
        required: 'Link is required',
        invalid: 'Invalid link',
        preview: 'Preview link',
        unSupported: 'Content in link is not supported',
        newUrlResource: 'New resource',
        changeUrlResource: 'Edit resource: {type}',
      },
      footnote: {
        title: 'Title',
        year: 'Year',
        authors: {
          label: 'Author',
          description: 'Required with at least one author.',
          createOption: 'Create new author',
          emptyFilter: ' ',
          emptyList: ' ',
        },
        edition: 'Edition',
        publisher: 'Publisher',
        addTitle: 'Add footnote',
        editTitle: 'Edit footnote',
        removeFootnote: 'Remove footnote',
      },
      table: {
        'row-remove': 'Remove row',
        'row-add': 'Add row',
        'column-add': 'Add column',
        'column-remove': 'Remove column',
        'table-remove': 'Remove table',
      },
    },
    tags: {
      label: 'Tags',
      description: '3 tags is required.',
      createOption: 'Create new tag',
      emptyList: 'No tags available',
      emptyFilter: 'No matching tags found',
    },
    resourceTypes: {
      label: 'Resource type and properties',
      placeholder: 'Add property',
      emptyList: 'No properties available',
      emptyFilter: 'No matching properties found',
    },
    filter: {
      label: 'Filter',
      placeholder: 'Add filter',
      emptyList: 'No filters available',
      emptyFilter: 'No matching filters found',
      core: 'Core',
      supplementary: 'Supplementary',
      setRelevance: 'Set relevance',
    },
    topics: {
      label: 'Topics',
      placeholder: 'Add topic',
      emptyList: 'No topics available',
      emptyFilter: 'No matching topics found',
      primaryTopic: 'Primary topic',
      sharedTopic: 'Shared topic',
      setPrimaryTopic: 'Set as primary topic',
    },
    metaDescription: {
      label: 'Meta description',
      description: 'The description will be viewable in search.',
    },
    agreement: {
      label: 'Connect to agreement',
      placeholder: 'Search for agreement',
      emptyFilter: 'No matching agreement found',
      emptyList: 'No agreements in the list',
    },
    rightsholders: {
      label: 'Rightsholder',
      labelRemove: 'Remove',
      placeholder: 'Type name of rightholder',
      createOption: 'Add new rightsholder',
      emptyFilter: ' ',
      emptyList: ' ',
    },
    processors: {
      label: 'Processor',
      labelRemove: 'Remove',
      placeholder: 'Type name of processor',
      createOption: 'Add new processor',
      emptyFilter: ' ',
      emptyList: ' ',
    },
    creators: {
      label: 'Creator',
      labelRemove: 'Remove',
      placeholder: 'Type name of creator',
      createOption: 'Add new creator',
      description: 'Required with at least one creator.',
      emptyFilter: ' ',
      emptyList: ' ',
    },
    license: {
      label: 'Lisens',
    },
    origin: {
      label: 'Origin',
    },
    caption: {
      label: 'Caption',
      placeholder: 'Caption',
    },
    image: {
      file: 'Image',
      alt: {
        label: 'Alt-text',
        placeholder: 'Alt-text',
      },
      caption: {
        label: 'Image caption',
        placeholder: 'Image caption',
      },
    },
    video: {
      caption: {
        label: 'Video caption',
        placeholder: 'Video caption',
      },
    },
    audio: {
      file: 'Audio file',
      title: {
        label: 'Audio title',
        placeholder: 'Audio title',
      },
      caption: {
        label: 'Audio caption',
        placeholder: 'Audio caption',
      },
      sound: 'Audio',
      speech: 'Speech',
    },
    related: {
      title: 'Related articles',
      showMore: 'Show more related articles',
      showLess: 'Show less',
    },
    file: {
      label: 'Files',
      file: {
        label: 'File',
      },
      alt: {
        label: 'Alt text',
        placeholder: 'Alt text',
      },
      download: 'Download:',
      title: {
        label: 'File title',
        placeholder: 'File title',
      },
      addFile: 'Add file',
      removeList: 'Remove file list',
    },
  },
  validation: {
    isRequired: '{label} is required.',
    isNumeric: '{label} must contain digits.',
    bothFields: 'One {labelLowerCase} must contain all fields.',
    url: '{label} must contain a valid link.',
    dateBeforeInvalid: '{label} can not be after {afterLabel}.',
    dateAfterInvalid: '{label} can not be before {beforeLabel}.',
    maxLength:
      '{label} must not have more than {maxLength, number} characters.',
    minLength: '{length} must have at least {minLength, number} characters.',
    minItems:
      '{label} must have at least {minItems, plural, one{one} other{# unique}} {labelLowerCase}.',
    noEmptyNote: 'En merknad kan ikke være en tom',
  },
  footer: {
    aboutNDLA: 'About NDLA',
    selectLanguage: 'Choose language (språk): ',
    footerInfo: 'This webapplication is developed by NDLA as Open Source code.',
    footerEditiorInChief: 'Editor in chief: ',
    footerManagingEditor: 'Managing editor: ',
  },
  errorMessage: {
    title: 'Oops, something went wrong',
    description: 'Sorry, an error occurd.',
    back: 'Back',
    goToFrontPage: 'Go to frontpage',
    invalidUrl: 'Invalid url',
    noArticleInProd: 'No article found in prod',
    taxonomy: 'There was a problem loading taxonomy',
    auth0:
      'Authentication error. Press cancel to take care of any changes you have made before logging in again. The following error message came from auth0: {message}',
    statusCode: {
      409: 'This article has already been updated. Keep what you have changed and reload the page to save.',
    },
  },
  notFound: {
    description: 'The page cannot be found',
  },
  forbiddenPage: {
    description: 'You do not have access to this page',
  },
  alertModal: {
    notSaved: 'Document is not saved, do you want to continue?',
    continue: 'Continue',
    delete: 'Delete',
    confirm: 'Confirm',
    loginAgain: 'Login again',
  },
  taxonomy: {
    editStructure: '  Edit structure',
    addSubject: 'Add new subject',
    addExistingTopic: 'Add existing topic',
    newSubject: 'New Subject',
    existingTopic: 'Existing topic',
    newTopic: 'New topic',
    editFilter: 'Edit filter',
    emptyFilter: 'No hits',
    errorMessage: 'An error occurred',
    addTopic: 'Add topic',
    changeName: 'Change name',
    topicSettings: 'Topic settings',
    subjectSettings: 'Subject settings',
    linkSettings: 'Link',
    setPrimary: 'Set as primary link',
    addFilter: 'Add filter',
    connectFilters: 'Connect filters',
    confirmDelete: 'Are you sure you want to delete the filter?',
    addResource: 'Add resource',
    searchResource: 'Search for resource',
    searchArticle: 'Search for topic article',
    confirmDeleteTopic:
      'Are you sure you want to delete the topic from the folder? This does not affect the topic location elsewhere',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Note! This is a different resource type: ',
    noResources: 'No resources found',
    addTopicDescription: 'Change topic description',
    confirmSetPrimary: 'Do you want to make this the main location?',
    removeLink: 'Remove link',
    jumpToResources: 'Jump to resources',
    resource: {
      confirmDelete:
        'Do you want to delete the resource from this folder? This will not affect the placement other places',
      chooseFilter: 'Connect to filters',
    },
    resourceTypes: {
      title: 'Content type',
      subTitle: 'What content type does this resource have?',
      placeholder: 'Select content type',
    },
    topics: {
      title: 'Topic connections',
      subTitle: 'Where in the taxonomy should this resource be?',
      filestructureButton: 'Create a topic connection',
      filestructureHeading: 'Select a topic connection',
      filestructureClose: 'Close',
      addedTopic: 'Added to taxonomy',
      filterTopic: 'Filter topics',
      disconnectedTaxonomyWarning: 'Invalid topic connection',
    },
    filters: {
      title: 'Filters',
      subTitle: 'Which filters should be applied?',
      additional: 'Additional resource',
      core: 'Core resource',
    },
  },
  contextTypes: {
    topic: 'Topic',
  },
};

export default phrases;
