/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

const titleTemplate = '- Produksjonsystem - NDLA';

const phrases = {
  htmlTitles: {
    titleTemplate,
    createLearningResourcePage: `Fagstoff ${titleTemplate}`,
    createTopicArticlePage: `Emne ${titleTemplate}`,
    agreementPage: `Avtale ${titleTemplate}`,
    searchPage: `Søk ${titleTemplate}`,
    welcomePage: `Forside ${titleTemplate}`,
    structurePage: `Struktur ${titleTemplate}`,
    audioUploaderPage: `Lyd ${titleTemplate}`,
    imageUploaderPage: `Bilde ${titleTemplate}`,
  },
  meta: {
    description:
      'Kvalitetssikrede fritt tilgjengelige nettbaserte læremidler for videregående opplæring',
  },
  article: {
    lastUpdated: 'Sist oppdatert',
    edition: 'Utgave',
    publisher: 'Utgiver',
    useContent: 'Bruk innhold',
    closeLabel: 'Lukk',
    additionalLabel: 'Tilleggsstoff',
    urlContributionsLabel: 'Se hva {name} har bidratt med',
    urlAuthorLabel: 'Les mer om {name}',
    multipleAuthorsLabelAbbreviation: 'm. fl.',
    multipleAuthorsLabel: 'Opphavere av artikkel:',
    multipleAuthorsLabelAria: 'Opphavere av artikkelen er {names}',
    multipleAuthorsLabelAriaConjunction: 'og',
    singleAuthorsLabelAria: 'Opphaver av artikkelen er {name}',
  },
  dialog: {
    close: 'Lukk',
    title: 'Tittel',
    audio: {
      rulesForUse: 'Regler for bruk av lydklipp',
    },
    learnAboutLicenses: 'Lær mer om åpne lisenser',
    source: 'Kilde',
  },
  license: {
    heading: 'Slik gjenbruker du innhold',
    learnMore: 'Lær mer om åpne lisenser',
    copyTitle: 'Kopier referanse',
    hasCopiedTitle: 'Kopiert!',
    embed: 'Bygg inn',
    embedCopied: 'Kopierte innbyggingskode!',
    download: 'Last ned',
    tabs: {
      text: 'Tekst',
      images: 'Bilder',
      audio: 'Lyd',
      video: 'Video',
    },
    images: {
      heading: 'Slik bruker du bilder fra artikkelen',
      description:
        'Husk å kopiere teksten som skal legges ved bildet der du bruker det.',
      rules: 'Regler for bruk av bildet:',
      source: 'Kilde',
      title: 'Tittel',
    },
    text: {
      heading: 'Slik bruker du tekst fra artikkelen',
      description:
        'Artikkelen kan være sammensatt av flere tekster som listes opp her.',
      rules: 'Regler for bruk av teksten:',
      published: 'Publiseringsdato',
    },
    audio: {
      heading: 'Slik bruker du lydfiler',
      description:
        'Husk å kopiere teksten som skal legges ved lydfilen der du bruker den.',
      rules: 'Regler for bruk av lydfilen:',
    },
    video: {
      heading: 'Slik bruker du video fra artikkelen',
      description:
        'Husk å kopiere teksten som skal legges ved videoen der du bruker den.',
      rules: 'Regler for bruk av videoen:',
    },
    creditType: {
      originator: 'Opphavsmann',
      authorDesc: 'Denne artikkelen er laget av flere opphavsmenn',
      photographer: 'Fotograf',
      artist: 'Kunstner',
      editorial: 'Redaksjonelt',
      writer: 'Forfatter',
      scriptwriter: 'Manusforfatter',
      reader: 'Innleser',
      translator: 'Oversetter',
      director: 'Regissør',
      illustrator: 'Illustratør',
      cowriter: 'Medforfatter',
      composer: 'Komponist',
      processor: 'Bearbeider',
      facilitator: 'Tilrettelegger',
      linguistic: 'Språklig',
      idea: 'Idé',
      compiler: 'Sammenstiller',
      correction: 'Korrektur',
      rightsholder: 'Rettighetshaver',
      publisher: 'Forlag',
      distributor: 'Distributør',
      supplier: 'Leverandør',
    },
  },
  language: {
    en: 'Engelsk',
    nb: 'Bokmål',
    nn: 'Nynorsk',
    se: 'Svensk',
    unknown: 'Ukjent',
    de: 'Tysk',
    empty: 'Ingen flere språk',
  },
  welcomePage: {
    lastUsed: 'Sist brukt',
    emptyLastUsed: 'Ingen sist brukte',
    savedSearch: 'Lagrede søk',
    emptySavedSearch: 'Ingen lagrede søk',
    guidelines: 'Retningslinjer',
  },
  searchPage: {
    header: {
      content: 'Søk etter innhold',
      media: 'Søk etter media',
    },
    searchButton: 'Søk',
    emptyButton: 'Tøm',
    title: 'Tittel',
    language: 'Språk',
    contentNoHits: 'Ingen innhold samsvarte med søket ditt på: {query}',
    mediaNoHits: 'Ingen media samsvarte med søket ditt på: {query}',
    pageSize: '{pageSize} treff per side',
    totalCount: 'Antall søketreff',
  },
  subNavigation: {
    media: 'Media',
    learningPath: 'Læringssti',
    subjectMatter: 'Fagstoff',
    detailSearch: 'Detaljsøk',
    topicArticle: 'Emne',
    learningResource: 'Fagstoff',
    image: 'Bilde',
    audio: 'Lyd',
    agreement: 'Avtale',
    structure: 'Struktur',
    concept: 'Begrep',
    searchContent: 'Søk innhold',
    searchMedia: 'Søk media',
  },
  logo: {
    altText: 'Nasjonal digital læringsarena',
  },
  siteNav: {
    chooseSubject: 'Velg fag',
    search: 'Søk',
    login: 'Logg inn',
    logout: 'Logg ut [{name}]',
  },
  loginFailure: {
    errorMessage: 'Beklager. Innlogging feilet.',
    loginLink: 'Klikk for å prøve igjen.',
  },
  loginProviders: {
    description: 'Logg inn i produksjonssystem med',
  },
  logoutProviders: {
    localLogout: 'Logg ut av produksjonssystem',
    or: 'eller',
    federatedLogout: 'Logg ut av alle tjenester',
    description:
      'N.B. Alle tjenester inkluderer autentiseringstjenesten (Google eller Facebook).',
  },
  searchForm: {
    placeholder: 'Søk etter artikler, aktiviteter eller oppgaver',
    types: {
      contentQuery: 'Søk på Innhold',
      mediaQuery: 'Søk på Media',
      language: 'Velg Språk',
      subjects: 'Velg fag',
      resourceTypes: 'Velg innholdstype',
      draftStatus: 'Velg status',
    },
    tagType: {
      query: 'Innhold',
      subjects: 'Fag',
      language: 'Språk',
      resourceTypes: 'Innholdstype',
      draftStatus: 'Status',
    },
    btn: 'Søk',
    empty: 'Tøm',
    articleType: {
      all: 'Alle',
      standard: 'Standard',
      learningResource: 'Læringsressurs',
      topicArticle: 'Emnebeskrivelse',
      image: 'Bilde',
      audio: 'Lyd',
    },
    order: 'Rekkefølge',
    asc: 'Stigende',
    desc: 'Fallende',
    sorting: 'Sortering',
    sort: {
      id: 'Id',
      relevance: 'Relevans',
      title: 'Tittel',
      lastUpdated: 'Sist oppdatert',
    },
    resultError: 'Noe gikk feil med innlasting av type: {type}',
  },
  subjectsPage: {
    subjects: 'Fag',
  },
  subjectPage: {
    topics: 'Emner',
  },
  editMarkup: {
    linkTitle: 'Gå til HTML editor',
    title: 'HTML editor',
    subTitle: 'Editer artikkel innhold med HTML',
    fetchError:
      'En feil oppsto ved lasting av artikkel HTML editoren. Gå tilbake eller prøv å last siden på nytt.',
    saveError: 'En feil oppsto ved lagring av endringer.',
    back: 'Tilbake',
    helpMessage: {
      paragraph1:
        'Det er mulig å formatter  HTML koden ved å trykke på F1 og velge Format. Merk at dette kan føre til at whitespace (indentering, linjeskift og mellomrom) kan endre seg ved lagring. Bruk gjerne forhåndsvisning funksjonaliteten aktivt. ',
      paragraph2:
        'For å minimerer eventuelle problemer med formatering og sikre at at HTML blir konsistent så blir koden kjørt gjennom de samme transformeringen som WYSIWYG editoren. Det betyr at linjeskift f.eks. blir endret til <br> ved lagring og samt at den vil prøve å rette opp ugyldig kode.',
    },
  },
  imageSearch: {
    placeholder: 'Søk i bilder',
    buttonTitle: 'Søk',
    useImage: 'Bruk bildet',
    noTitle: 'Ingen tittel',
    noResultsText:
      'Fant ingen bilder på søk. Ønsker du å laste opp et nytt bilde?',
    noResultsButtonText: 'Last opp bilde',
  },
  videoSearch: {
    searchPlaceholder: 'Søk i videoer',
    searchButtonTitle: 'Søk',
    loadMoreVideos: 'Last flere videor',
    noResults: 'Ingen videor funnet.',
    addVideo: 'Bruk video',
    previewVideo: 'Forhåndsvis',
    publishedDate: 'Publisert dato',
    duration: 'Varighet',
    interactioncount: 'Visninger',
  },
  mathEditor: {
    editMath: 'Rediger Matematikk',
    preview: 'Forhåndsvisning',
    continue: 'Du har ulagrede endringer i matteeditoren. Vil du fortsette?',
  },
  h5pElement: {
    fetchError:
      'Vi beklager, men en feil oppsto under lasting av H5P-klienten.',
  },
  displayOembed: {
    errorMessage: 'En feil oppsto ved visning av oEmbed-innhold.',
    notSupported: 'oEmbed av type {type} og kilde {provider} er ikke støttet.',
  },
  audioSearch: {
    searchPlaceholder: 'Søk i lydfiler',
    searchButtonTitle: 'Søk',
    useAudio: 'Velg lyd',
    noResults: 'Ingen resultater funnet',
    noTitle: 'Ingen tittel',
  },
  noEmbedMessage: {
    deleteOnSave: 'Element av type {type} vil bli fjernet ved lagring.',
  },
  topicArticleForm: {
    visualElementTitle: {
      image: 'Bildetittel',
      h5p: 'H5P tittel',
      brightcove: 'Videotittel',
      external: 'Innholdstekst',
    },
    visualElementCopyright: 'Opphav',
    removeVisualElement: 'Fjern element',
    info: {
      lastUpdated: 'Sist oppdatert: {updated}',
    },
    title: 'Emnebeskrivelse | {title} ({key})',
    fields: {
      caption: {
        label: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innholdstekst',
        },
        placeholder: {
          image: 'Bildetekst',
          brightcove: 'Videotekst',
          external: 'Innholdstekst',
        },
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
    },
  },
  agreementForm: {
    title: {
      create: 'Avtale',
      update: 'Avtale',
    },
    fields: {
      title: {
        label: 'Avtaletittel',
        placeholder: 'Avtaletittel',
      },
      content: {
        label: 'Avtalens innhold',
        placeholder: 'Avtalens innhold',
      },
    },
  },
  audioForm: {
    title: 'Lyd | {title} ({key})',
  },
  imageEditor: {
    remove: {
      crop: 'Fjern utsnitt',
      focalPoint: 'Fjern fokuspunkt',
    },
  },
  imageForm: {
    title: 'Bilde | {title} ({key})',
  },
  learningResourceForm: {
    metaImage: {
      title: 'Bildetittel',
      copyright: 'Opphav',
      change: 'Bytt metabilde',
    },
    title: 'Fagstoff | {title} ({key})',
    validation: {
      missingEmbedData:
        'En eller flere inkluderte lyd-, bilde-, eller videoelementer mangler beskrivende tekst eller alternativ tekst.',
    },
    fields: {
      rightAside: {
        title: 'Høyrespalte',
        moveContent: 'Flytt innhold inn i teksten',
        delete: 'Slett høyrespalte',
      },
      metaImage: {
        title: 'Metabilde',
        label: 'Metabilde',
        helpLabel: 'Hva er et metabilde?',
      },
      footnotes: {
        edition: 'Utgave',
        publisher: 'Utgiver',
      },
    },
  },
  editorToolbar: {
    bold: 'Fet',
    italic: 'Kursiv',
    underlined: 'Understreket',
    quote: 'Sitat',
    link: 'Lenke',
    numberedList: 'Nummerert liste',
    bulletedList: 'Punktliste',
    twoColumnList: 'To-kolonners liste',
    letterList: 'Bokstavliste',
    headingOne: 'Overskrift 1',
    headingTwo: 'Overskrift 2',
    headingThree: 'Overskrift 3',
    footnote: 'Fotnote',
    mathml: 'Matte',
  },
  editorBlockpicker: {
    heading: 'Legg til',
    actions: {
      block: 'Paragraf',
      factAside: 'Faktaboks',
      table: 'Tabell',
      bodybox: 'Tekst i ramme',
      details: 'Ekspanderende boks',
      image: 'Bilde',
      video: 'Video',
      audio: 'Lyd',
      h5p: 'H5P',
      url: 'Ressurs fra lenke',
      related: 'Relatert artikkel',
      file: 'Fil',
    },
  },
  form: {
    metadataSection: 'Metadata',
    contentSection: 'Innhold',
    workflowSection: 'Arbeidsflyt',
    taxonomytSection: 'Taksonomi',
    copyrightSection: 'Lisens og bruker',
    save: 'Lagre',
    saveDraft: 'Lagre utkast',
    saveTax: 'Lagre taksonomi',
    choose: 'Velg',
    saving: 'Lagrer...',
    saved: 'Lagret ',
    preview: {
      button: 'Forhåndsvis',
    },
    previewProductionArticle: {
      button: 'Sammenlign utkast og artikkel',
      article: 'Artikkel',
      draft: 'Utkast',
    },
    previewLanguageArticle: {
      button: 'Sammenlign forskjellige språkversjoner',
      title: 'Utkast på {language}',
    },
    contributor: {
      add: 'Legg til',
    },
    abort: 'Avbryt',
    edit: 'Rediger',
    remove: 'Fjern',
    validate: 'Valider',
    publish: 'Publiser',
    savedOk: 'Lagret OK',
    publishedOk: 'Publisert OK',
    validationOk: 'Ingen valideringsfeil funnet',
    createdOk: 'Opprettet OK',
    addNewImage: 'Legg til nytt bilde',
    addNewAudio: 'Legg til ny lyd',
    notes: {
      heading: 'Merknader',
      add: 'Legg til merknad',
      remove: 'Ta bort',
      warning: 'En merknad må ha tekst',
      history: {
        heading: 'Merknadshistorikk',
        note: 'Merknad',
        empty: 'Ingen merknader',
      },
    },
    editImage: 'Endre bilde',
    editAudio: 'Endre lyd',
    resetToProd: {
      button: 'Tilbakestill til prod',
      modal: 'Vil du tilbakestille utkastet til slik det er på ndla forsiden?',
    },
    variant: {
      create: '+ Nytt språk',
    },
    remainingCharacters:
      'Maks {maxLength, number} tegn og du har {remaining, number} igjen.',
    title: {
      label: 'Tittel',
    },
    introduction: {
      label: 'Ingress',
    },
    visualElement: {
      title: 'Legg til visuelt element',
      label: 'Visuelt element',
      video: 'Videosøk',
      image: 'Bildesøk',
      imageUpload: 'Last opp bilde',
      h5p: 'H5P',
    },
    workflow: {
      title: 'Status',
      change: 'Endre status',
      qualityAssurance: 'Kvalitetssikring',
      deleteLanguageVersion: {
        button: 'Slett språkversjon',
        title: 'Slett språkversjon',
        modal: 'Er du sikker på at du vil slette denne språkversjonen?',
      },
    },
    status: {
      created: 'Opprettet',
      imported: 'Fra spoling',
      draft: 'Kladd',
      proposal: 'Utkast',
      user_test: 'Brukertest',
      awaiting_quality_assurance: 'Til kvalitetssikring',
      quality_assured: 'Kvalitetssikret',
      queued_for_publishing: 'Til publisering',
      published: 'Publisert',
      unpublished: 'Avpublisert',
      awaiting_unpublishing: 'Til avpublisering',
      archived: 'Arkivert',
      actions: {
        DRAFT: 'Kladd',
        PROPOSAL: 'Utkast',
        USER_TEST: 'Brukertest',
        AWAITING_QUALITY_ASSURANCE: 'Til kvalitetssikring',
        QUALITY_ASSURED: 'Kvalitetssikret',
        QUEUED_FOR_PUBLISHING: 'Til publisering',
        PUBLISHED: 'Publiser',
        AWAITING_UNPUBLISHING: 'Til avpublisering',
        UNPUBLISHED: 'Avpubliser',
        ARCHIVED: 'Arkiver',
      },
    },
    validDate: {
      label: 'Gyldighet',
      from: {
        label: 'Gyldig fra',
        placeholder: 'Fra og med dato',
      },
      to: {
        label: 'Gyldig til',
        placeholder: 'Til og med dato',
      },
    },
    content: {
      label: 'Innhold',
      placeholder: 'Innhold',
      figure: {
        notSupported: 'Mediatype {mediaType} er ikke støttet.',
        confirmDelete: 'Er du sikker på at du vil slette denne figuren?',
      },
      relatedArticle: {
        placeholder: 'Søk på tittel',
        urlPlaceholder: 'http://www.example.com',
        urlLocation: 'Nettside hos {domain}',
        titlePlaceholder: 'Tittel',
        emptyFilter: 'Ingen relaterte artikler funnet',
        emptyList: 'Det er ingen relaterte artikler i denne listen',
        invalidArticle: 'Ugyldig artikkel',
        addExternal: 'Legg til ekstern artikkel',
        searchExternal: 'Skriv inn url og tittel på ekstern artikkel',
      },
      link: {
        goTo: 'Gå til',
        insert: 'Sett inn lenke',
        update: 'Oppdater lenke',
        change: 'Endre',
        remove: 'Fjern lenke',
        href: 'Lenke',
        title: 'Tittel',
        newTab: 'Åpne lenke i ny fane',
        text: 'Tekst',
        addTitle: 'Legg til lenke',
        changeTitle: 'Endre lenke',
        required: 'Lenke er påkrevd',
        invalid: 'Ugyldig lenke',
        preview: 'Forhåndsvis lenke',
        unSupported: 'Innholdstypen i lenken er ikke støttet',
        newUrlResource: 'Ny ressurs',
        changeUrlResource: 'Rediger ressurs: {type}',
      },
      footnote: {
        title: 'Tittel',
        year: 'År',
        authors: {
          label: 'Forfatter',
          description: 'Obligatorisk med minst 1 forfatter.',
          createOption: 'Opprett ny forfatter',
          emptyFilter: ' ',
          emptyList: ' ',
        },
        edition: 'Utgave',
        publisher: 'Utgiver',
        addTitle: 'Legg til fotnote',
        editTitle: 'Rediger fotnote',
        removeFootnote: 'Fjern fotnote',
      },
      table: {
        'row-remove': 'Fjern rad',
        'row-add': 'Legg til rad',
        'column-add': 'Legg til kolonne',
        'column-remove': 'Fjern kolonne',
        'table-remove': 'Fjern tabell',
      },
    },
    tags: {
      label: 'Nøkkelord',
      helpLabel: 'Hva er nøkkelord?',
      description: 'Obligatorisk med 3 nøkkelord.',
      createOption: 'Opprett nytt nøkkelord',
      emptyFilter: 'Fant ingen passende nøkkelord',
      emptyList: 'Det er ingen tagger i denne listen',
    },
    resourceTypes: {
      label: 'Innholdstype og egenskaper',
      placeholder: 'Legg til egenskap',
      emptyFilter: 'Ingen egenskaper funnet',
      emptyList: 'Det er ingen egenskaper i denne listen',
    },
    subjects: {
      label: 'Emne',
      searchPlaceholder: 'Søk etter emne',
      placeholder: 'Legg til emne',
      emptyFilter: 'Ingen emner funnet',
      emptyList: 'Det er ingen emner i denne listen',
    },
    filter: {
      label: 'Filter',
      placeholder: 'Legg til filter',
      emptyFilter: 'Fant ingen passende filter',
      emptyList: 'Det er ingen filter i denne listen',
      core: 'Kjernestoff',
      supplementary: 'Tilleggsstoff',
      setRelevance: 'Velg relevans',
    },
    topics: {
      label: 'Emnetilknytning',
      placeholder: 'Legg til emnetilknytning',
      emptyFilter: 'Fant ingen passende emnetilknytninger',
      emptyList: 'Det er ingen emnetilknytning i denne listen',
      primaryTopic: 'Primærkobling',
      sharedTopic: 'Delt emne',
      setPrimaryTopic: 'Velg som primærkoblet emne',
    },
    metaDescription: {
      label: 'Metabeskrivelse',
      helpLabel: 'Hva er metabeskrivelse?',
      description: 'Beskrivelsen blir synlig i søk.',
    },
    agreement: {
      label: 'Koble til avtale',
      helpLabel: 'Hva er en avtale?',
      placeholder: 'Søk etter avtale',
      emptyFilter: 'Fant ingen passende avtaler',
      emptyList: 'Det er ingen avtaler i denne listen',
    },
    rightsholders: {
      label: 'Rettighetshaver',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv navn til rettighetshaver',
      createOption: 'Opprett ny rettighetshaver',
      emptyFilter: ' ',
      emptyList: ' ',
    },
    processors: {
      label: 'Bearbeider',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv navn til bearbeider',
      createOption: 'Opprett ny bearbeider',
      emptyFilter: ' ',
      emptyList: ' ',
    },
    creators: {
      label: 'Opphavsperson',
      labelRemove: 'Ta bort',
      placeholder: 'Skriv navn til opphavsperson',
      createOption: 'Opprett ny opphavsperson',
      description: 'Obligatorisk med minst 1 opphavsperson.',
      emptyFilter: ' ',
      emptyList: ' ',
    },
    license: {
      label: 'Lisens',
      helpLabel: 'Hva er lisenser?',
    },
    origin: {
      label: 'Opphav',
    },
    image: {
      file: 'Bilde',
      caption: {
        label: 'Bildetekst',
        placeholder: 'Bildetekst',
      },
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
    },
    video: {
      caption: {
        label: 'Videotekst',
        placeholder: 'Videotekst',
      },
    },
    audio: {
      file: 'Lydfil',
      title: {
        label: 'Lydtittel',
        placeholder: 'Lydtittel',
      },
      caption: {
        label: 'Lydtekst',
        placeholder: 'Lydtekst',
      },
      sound: 'Lyd',
      speech: 'Tale',
    },
    related: {
      title: 'Relaterte artikler',
      showMore: 'Vis flere relaterte artikler',
      showLess: 'Vis mindre',
    },
    file: {
      label: 'Filer',
      file: {
        label: 'Fil',
      },
      download: 'Last ned:',
      alt: {
        label: 'Alt-tekst',
        placeholder: 'Alt-tekst',
      },
      title: {
        label: 'Filtittel',
        placeholder: 'Filtittel',
      },
      addFile: 'Legg til fil',
      removeList: 'Fjern filliste',
    },
  },
  validation: {
    isRequired: '{label} er påkrevd.',
    bothFields: 'En {labelLowerCase} må inneholde alle felter.',
    isNumeric: '{label} må inneholde tall.',
    maxLength: '{label} kan ikke ha mer enn {maxLength, number} tegn.',
    minLength: '{label} må ha minst {minLength, number} tegn.',
    url: '{label} må inneholde en gyldig lenke.',
    dateBeforeInvalid: '{label} kan ikke være etter {afterLabel}.',
    dateAfterInvalid: '{label} kan ikke være før {beforeLabel}.',
    minItems:
      '{label} feltet må minst inneholde {minItems, plural, one{en} other{# ulike}} {labelLowerCase}.',
    noEmptyNote: 'En merknad kan ikke være tom',
  },
  footer: {
    aboutNDLA: 'Om NDLA',
    selectLanguage: 'Velg språk (language): ',
    footerInfo: 'Nettstedet er utarbeidet av NDLA som åpen kildekode.',
    footerEditiorInChief: 'Ansvarlig redaktør: ',
    footerManagingEditor: 'Utgaveansvarlig: ',
  },
  errorMessage: {
    title: 'Oops, noe gikk galt',
    description: 'Vi beklager, men en feil oppsto.',
    back: 'Tilbake',
    goToFrontPage: 'Gå til forsiden',
    invalidUrl: 'Ugyldig url',
    noArticleInProd: 'Ingen artikkel funnet i prod',
    taxonomy: 'Det var et problem ved lasting av taksonomi',
    auth0:
      'Autentiseringsfeil. Trykk avbryt for å ta vare på eventuelle endringer du har gjort før du logger inn på nytt. Følgende feilmelding kom fra auth0: {message}',
    statusCode: {
      409: 'Denne artikkelen har allerede blitt oppdatert. Ta vare på det du har endret og last siden på nytt for å kunne lagre.',
    },
  },
  notFound: {
    description: 'Denne siden finnes ikke.',
  },
  forbiddenPage: {
    description: 'Du har ikke tilgang til denne siden',
  },
  alertModal: {
    notSaved: 'Dokumentet er ikke lagret, ønsker du å fortsette?',
    continue: 'Fortsett',
    delete: 'Slett',
    confirm: 'Bekreft',
    loginAgain: 'Logg inn på nytt',
  },
  taxonomy: {
    editStructure: '  Rediger struktur',
    addSubject: 'Legg til nytt fag',
    addExistingTopic: 'Legg til eksisterende emne',
    newSubject: 'Nytt fag',
    existingTopic: 'Eksisterende emne',
    newTopic: 'Nytt emne',
    subjectSettings: 'Faginstillinger',
    topicSettings: 'Emneinstillinger',
    changeName: 'Endre navn',
    addTopic: 'Legg til nytt emne',
    errorMessage: 'En feil oppsto',
    emptyFilter: 'Ingen treff',
    editFilter: 'Rediger filter',
    addFilter: 'Nytt filter',
    connectFilters: 'Koble til filter',
    confirmDelete: 'Er du sikker på at du vil slette filteret?',
    confirmDeleteTopic:
      'Vil du slette dette emnet fra mappen? Dette påvirker ikke plasseringen andre steder',
    linkSettings: 'Link',
    setPrimary: 'Sett til primærkobling',
    addResource: 'Legg til ressurs',
    searchResource: 'Søk etter ressurs',
    searchArticle: 'Søk etter emneartikkel',
    or: 'Eller',
    urlPlaceholder: 'Lim inn lenke fra ndla.no',
    wrongType: 'Obs! Denne ressursen er en annen type',
    noResources: 'Ingen ressurser funnet',
    addTopicDescription: 'Endre emnebeskrivelse',
    confirmSetPrimary: 'Vil du gjøre dette til hovedplassering?',
    jumpToResources: 'Hopp til ressurser',
    resource: {
      confirmDelete:
        'Vil du fjerne ressursen fra denne mappen? Dette vil ikke påvirke plasseringen andre steder',
      chooseFilter: 'Koble til filter',
    },
    removeLink: 'Fjern link',
    resourceTypes: {
      title: 'Innholdstype',
      helpLabel: 'Hva er en Innholdstype?',
      subTitle: 'Hvilken innholdstype har denne ressursen?',
      placeholder: 'Velg innholdstype',
    },
    topics: {
      title: 'Emnetilknytninger',
      helpLabel: 'Hva er emnetilknytning?',
      subTitle: 'Hvor i taksonomien skal ressursen ligge?',
      filestructureButton: 'Opprett emnetilknytning',
      filestructureHeading: 'Velg emnetilknytning',
      filestructureClose: 'Lukk',
      addedTopic: 'Lagt til',
      filterTopic: 'Filtrer emner',
      disconnectedTaxonomyWarning: 'Ugyldig tilknytning',
    },
    filters: {
      title: 'Filter',
      subTitle: 'Hvilket fagfilter gjelder for denne ressursen?',
      helpLabel: 'Hva er et fagfilter?',
      additional: 'Tilleggsressurs',
      core: 'Kjerneressurs',
    },
  },
  contextTypes: {
    topic: 'Emne',
  },
};

export default phrases;
