/**
 * Copyright (c) 2019-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { ArticleDTO, RelatedContentLinkDTO } from "@ndla/types-backend/draft-api";
import {
  AudioEmbedData,
  BrightcoveEmbedData,
  H5pEmbedData,
  IframeEmbedData,
  ImageEmbedData,
  OembedEmbedData,
} from "@ndla/types-embed";

export interface FormikStatus {
  status?: string;
  warnings?: Record<string, string>;
}

export type NdlaError = {
  message?: string;
  severity: MessageSeverity;
  timeToLive: number;
};

// Should be a union of allowed status values generated by backend. Fix in the future.
export type DraftStatusType = string;
export type DraftStatusStateMachineType = Record<DraftStatusType, DraftStatusType[]>;

// Should be a union of allowed status values generated by backend. Fix in the future.
export type ConceptStatusType = string;
export type ConceptStatusStateMachineType = Record<ConceptStatusType, ConceptStatusType[]>;

export type LocaleType = "nb" | "nn" | "en" | "se" | "sma" | "ukr";

export interface CodeBlockType {
  code: string;
  title: string;
  format: string;
}

export interface Auth0UserData {
  app_metadata: {
    ndla_id: string;
  };
  name: string;
}

export type RelatedContent = RelatedContentLinkDTO | number;

export type ConvertedRelatedContent = RelatedContent | ArticleDTO;

export type MessageSeverity = "danger" | "info" | "success" | "warning";

export interface ErrorEmbed {
  resource: "error";
  message: string;
}

export type Embed =
  | ImageEmbedData
  | BrightcoveEmbedData
  | AudioEmbedData
  | H5pEmbedData
  | ErrorEmbed
  | OembedEmbedData
  | IframeEmbedData;

export interface FileFormat {
  url: string;
  fileType: string;
  tooltip: string;
}

export interface File {
  path: string;
  resource: string;
  title: string;
  type: string;
  url: string;
  display?: string;
  formats?: FileFormat[];
}

export interface UnsavedFile {
  path: string;
  title: string;
  type: string;
}

export interface BrightcoveAccessToken {
  access_token: string;
  token_type: string;
  expires_in: number;
}

export interface OembedResponse {
  height: number;
  width: number;
  html: string;
  type: string;
  providerName?: string;
  iframeSrc?: string;
  version: string;
  title: string;
}

export type SearchType = "content" | "audio" | "image" | "concept" | "podcast-series";

export interface WithTaxonomyVersion {
  taxonomyVersion: string;
}

export interface WhitelistProvider {
  name: string;
  url: string[];
  height?: string;
}

export interface GrepFormat {
  prefix: string;
  regexp: RegExp;
}

export type Dictionary<T> = Record<string, T>;

interface HtmlTranslateType {
  type: "html";
  content: string;
}

interface TextTranslateType {
  type: "text";
  content: string | string[];
}

export type ApiTranslateType = HtmlTranslateType | TextTranslateType;

export type PromptType = PromptVariables["type"];

export type PromptVariables =
  | SummaryVariables
  | AltTextVariables
  | AlternativePhrasingVariables
  | MetaDescriptionVariables
  | ReflectionVariables;

export interface SummaryVariables {
  type: "summary";
  content: string;
  title: string;
}

export interface AltTextVariables {
  type: "altText";
  image: {
    fileType: string;
    base64: string;
  };
}

export interface AlternativePhrasingVariables {
  type: "alternativePhrasing";
  selection: string;
  content: string;
}

export interface MetaDescriptionVariables {
  type: "metaDescription";
  content: string;
  title: string;
}

export interface ReflectionVariables {
  type: "reflection";
  content: string;
}

export type PromptPayload<T extends PromptVariables> = T & {
  language: string;
  role?: string;
  instructions?: string;
  max_tokens?: number;
};

export interface DefaultPrompts {
  role: string;
  instructions: string;
}

export interface LlmResponse {
  fullResponse: string;
  answer: string;
}

export type CamelToKebab<S extends string> = S extends `${infer T}${infer U}`
  ? U extends Uncapitalize<U>
    ? `${Uncapitalize<T>}${CamelToKebab<U>}`
    : `${Uncapitalize<T>}-${CamelToKebab<U>}`
  : "";

export interface ContentUriInfo {
  contentUri: string;
  id: number;
  type: string;
}

export type RevisionType = "revised" | "needs-revision";
