/**
 * Copyright (c) 2019-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { IAudioMetaInformation } from "@ndla/types-backend/audio-api";
import { IArticle, IRelatedContentLink } from "@ndla/types-backend/draft-api";
import { AudioEmbedData, BrightcoveEmbedData, H5pEmbedData, ImageEmbedData } from "@ndla/types-embed";
import { SearchTypeValues, LOCALE_VALUES } from "./constants";

export interface FormikStatus {
  status?: string;
  warnings?: Record<string, string>;
}

export type NdlaError = {
  message?: string;
  severity: MessageSeverity;
  timeToLive: number;
};

// Should be a union of allowed status values generated by backend. Fix in the future.
export type DraftStatusType = string;
export type DraftStatusStateMachineType = Record<DraftStatusType, DraftStatusType[]>;

// Should be a union of allowed status values generated by backend. Fix in the future.
export type ConceptStatusType = string;
export type ConceptStatusStateMachineType = Record<ConceptStatusType, ConceptStatusType[]>;

export type LocaleType = (typeof LOCALE_VALUES)[number];

export type PartialRecord<K extends keyof any, T> = {
  [P in K]?: T;
};

export interface SearchResultBase<T> {
  totalCount: number;
  page?: number;
  pageSize: number;
  language?: string;
  results: T[];
}

export interface CodeBlockType {
  code: string;
  title: string;
  format: string;
}

export interface FlattenedResourceType {
  id: string;
  name: string;
  typeId?: string;
  typeName?: string;
}

export interface Auth0UserData {
  app_metadata: {
    ndla_id: string;
  };
  name: string;
}

export interface ZendeskToken {
  token: string;
}

export type TypeOfPreview = "preview" | "previewLanguageArticle" | "previewVersion" | "previewProductionArticle";

export type RelatedContent = IRelatedContentLink | number;

export type ConvertedRelatedContent = RelatedContent | IArticle;

export type MessageSeverity = "danger" | "info" | "success" | "warning";

export interface H5pEmbed {
  resource: "h5p";
  path: string;
  url?: string;
  title?: string;
}

export interface ErrorEmbed {
  resource: "error";
  message: string;
}

export type Embed = ImageEmbedData | BrightcoveEmbedData | AudioEmbedData | H5pEmbedData | ErrorEmbed;

export interface FileFormat {
  url: string;
  fileType: string;
  tooltip: string;
}

export interface File {
  path: string;
  resource: string;
  title: string;
  type: string;
  url: string;
  display?: string;
  formats?: FileFormat[];
}

export interface UnsavedFile {
  path: string;
  title: string;
  type: string;
}

export interface SlateAudio extends Omit<IAudioMetaInformation, "title"> {
  title: string;
}

export interface BrightcoveAccessToken {
  access_token: string;
  token_type: string;
  expires_in: number;
}

export interface H5POembed {
  height: number;
  width: number;
  html: string;
  type: string;
  providerName?: string;
  version: string;
  title: string;
}

export type SearchType = (typeof SearchTypeValues)[number];

export interface ReturnType<TType, TReturnType> {
  type: TType;
  value: TReturnType;
}

export interface WithTaxonomyVersion {
  taxonomyVersion: string;
}

export interface WhitelistProvider {
  name: string;
  url: string[];
  height?: string;
}

export type Dictionary<T> = Record<string, T>;

interface BaseApiTranslateType {
  content: string | string[];
  type: "text" | "html";
  isArray: true | false;
}

interface ApiTranslateTypeSingle extends BaseApiTranslateType {
  content: string;
  isArray: false;
}

interface ApiTranslateTypeArray extends BaseApiTranslateType {
  content: string[];
  isArray: true;
}

export type ApiTranslateType = ApiTranslateTypeSingle | ApiTranslateTypeArray;
