export const statuses = {
  IMPORTED: ['DRAFT'],
  DRAFT: ['DRAFT', 'PROPOSAL', 'PUBLISHED'],
  PROPOSAL: [
    'USER_TEST',
    'QUEUED_FOR_PUBLISHING',
    'PUBLISHED',
    'AWAITING_QUALITY_ASSURANCE',
  ],
  USER_TEST: ['PROPOSAL', 'AWAITING_QUALITY_ASSURANCE', 'PUBLISHED'],
  AWAITING_QUALITY_ASSURANCE: ['USER_TEST', 'QUALITY_ASSURED', 'PUBLISHED'],
  QUALITY_ASSURED: ['QUEUED_FOR_PUBLISHING', 'PUBLISHED'],
  QUEUED_FOR_PUBLISHING: ['PUBLISHED'],
  PUBLISHED: ['DRAFT', 'AWAITING_UNPUBLISHING', 'UNPUBLISHED'],
  AWAITING_UNPUBLISHING: ['DRAFT', 'PUBLISHED', 'UNPUBLISHED'],
  UNPUBLISHED: ['PUBLISHED', 'DRAFT'],
  ARCHIEVED: [],
};
