name: CI
on: [push, pull_request]
env:
  GH_TOKEN: ${{ secrets.CI_NOW_GH_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  GH_PR_NUMBER: ${{ github.event.number }}
  GH_PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
  GH_PR_SHA: ${{ github.event.pull_request.head.sha }}
  NODE_OPTIONS: "--max-old-space-size=4096"
jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "22.15.0"
      - name: "Enable yarn v4"
        run: |
          corepack enable
          yarn set version 4.9.2
      - uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            .eslintcache
            .yarn/cache
            ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install"
        run: yarn install --immutable
      - name: "Check-all"
        run: yarn check-all
      - name: "Build"
        run: yarn build
      - name: "Deploy vercel build"
        run: yarn ndla-scripts vercel-github
        continue-on-error: true
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps chromium
      - name: "E2E"
        run: yarn e2e:headless
